### ISSUE TITLE
Export data use current filter & settings is not working

### ISSUE THREAD

**Issue by benjaminbours** [directus/directus#10025]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

![2021-11-24_13-40](https://user-images.githubusercontent.com/8804297/143240310-00362761-8a08-49fb-afc8-7676e0d97e76.png)
![2021-11-24_13-41](https://user-images.githubusercontent.com/8804297/143240419-3aefbf7a-b7fc-4ae6-b7c3-608790d69deb.png)

When exporting data from a collection, the export contain all the columns where previously it was only the selected fields.

### To Reproduce

- Create a collection with multiple fields
- Selected only a few of them in layout options
- Export data while having the option "Use current filter & settings" checked

### Errors Shown

No error logs.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.13.0 (inside the directus image)

### What database are you using?

Postgres 12.7

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
I can replicate this. Do you know the latest version where only selected fields were exported ? I went as far as `v9.0.0-rc.90` and this issue was already present.

**Comment by koksikus** [comment]
Since I remember it was in Directus, I didn't think it was a bug, because the columns cannot be selected either.  

It's will be great if I download csv, with data only from visible columns (not download too from hidden ones - like now) and only selected records. It would be great.  

At the moment, when downloading csv with the M2M field, it shows the reference id of the base and not the data from the second table, even though I have set the display of those data in directus.

**Comment by bcartier** [comment]
I was expecting this checkbox to export the columns chosen in the layout, and to export the content exactly as it's displayed in the layout, but all pages. I thought it would export human-readable values as opposed to what is actually stored  in the DB). So **User Updated** would export as someone's name rather than a UIID. 

Did it work this way at some point?

**Comment by azrikahar** [comment]
_Just adding extra reference here_

> Before being able to export the display's output, we'd have to add a "plaintext" output for each display. 

Reference: https://github.com/directus/directus/issues/9560#issuecomment-962507823

**Comment by azrikahar** [comment]
Closing this since #12201 should resolve this now as it overhauls the export feature and made it much more robust (filters, selecting nested relational fields, search, custom limit etc)
