### ISSUE TITLE
Create Extension for complete schema administration

### ISSUE THREAD

**Issue by ConnorGBrewster** [directus/directus#1011]
I don't know if this support is already there, but I can't seem to find it. It would be nice to be able to remove a table through the Directus interface rather than through Sequel Pro, this would also make sure of a clean removal of tables.

Edit: Looks like you can delete entries; however, tables and columns would be nice too.

**Comment by benhaynes** [comment]
Destructive table/field level deletes was something we didn't include in the API from the onset due to concerns about massive and irreversible data loss. If we're pushing Directus more as an DB Admin tool then we may need to reconsider this however. @WellingGuzman thoughts?

**Comment by ConnorGBrewster** [comment]
@benhaynes Hmmm I understand the thinking behind that, maybe when you delete a table via the online interface it removes the table from MySQL but also exports all the data into a file, that then if space is needed can be deleted from the server.

**Comment by WellingGuzman** [comment]
We can also "remove" it from Directus, by no giving permission to anyone to see it or interact with it.
It's also a dangerous features, but as we move forward into a DB Admin tool, we should implement it, so I'm thinking a user group capable of doing this, as we talked about @benhaynes, kind of a like "super admin" or something.

@ConnorGBrewster in your case exports all the table data into a file would be a great option to you? as for you, what would you rather prefer?

We can also alert the user like 2 times before this happen.

**Comment by ConnorGBrewster** [comment]
@WellingGuzman I was just thinking that a default export on delete setting would keep people from accidentally deleting a table and losing all their data. That would at least give them a way to retrieve any accidentally deleted data. I think the best middle ground would be having a checkbox on the delete modal that has an option to export the table and then remove it from MySQL.

**Comment by benhaynes** [comment]
I like the option of a file backup of the table before hard-delete, as well as a two-step confirmation. We could add a _database backup path_ to store table-delete dumps and any other database backups we offer. I'd say we auto-save any table dumps before delete... keep it safe!

**Comment by mickrip** [comment]
My $0.02. I think you should abandon this train of thought.

Lets take a step back and define what Directus is and what it's not. (in my opinion at least :)) - I'll take you through my logical flow..

* Database administration and Data Management are 2 different spaces.
* It is not a DB Admin tool - a DB Admin tool is something like phpmyadmin/SQLyog. 
* Do you really want to reinvent that wheel? It's not a space that Directus should ever be in and you'll only confuse people.
* In my opinion, Directus should only wrap around a DB schema using metadata, it should never interfere with the original schema, because: Your developers want to know that they can install Directus and not fear something bad is going to happen to their database. Especially if they are relying on an external app that makes assumptions about your schema!

**Comment by ConnorGBrewster** [comment]
@mickrip I agree with your points and I don't think Directus should try to be a DB Admin tool. But lets say you want to build your data system using just Directus. For example, lets say I want to do asset management with Directus and I install a fresh copy and add my tables for whatever assets I am tracking. If you were to make a typo or weren't thinking straight and added a column that is no longer needed, you have to go into something like Sequel Pro or phpmyadmin to fix it. I view this as frustrating and I think this feature should still be included in a Data Management system like Directus.

**Comment by mickrip** [comment]
@ConnorGBrewster - Yep, I see your point. But as a counterpoint, I have SQLyog always open - making a schema change is quick and easy. So your frustration can be fixed by improving your workflow.

In a real project, modifying schema impacts your models. I don't want Directus being able to change the source of truth. I don't want a client changing "totalPrice" to "price" and have my phone ring at 7am on a Sunday morning ;) It's a bit opinion based, but Directus is a drop-in client-facing "superadmin" and not a dev tool. (regardless of how you define your roles inside the admin) - as said above, you'll confuse the message. 

In my opinion, Directus should be focusing the time on improving the experience for clients and not developers. (Making the ecosystem extendable is what will make it more awesome)

Also, if Directus plan to abstract their DB to include other database ports, might be an idea to forget about this idea anyway.

**Comment by ConnorGBrewster** [comment]
@mickrip I see your point, and I definitely agree that users shouldn't have these permissions, but a superadmin I think should. One of the issues of doing it manually is making sure that you cleanly remove the table and any data that references that table is removed from the directus_* tables.

**Comment by WellingGuzman** [comment]
> I don't want a client changing "totalPrice" to "price" and have my phone ring at 7am on a Sunday morning ;)

Right! :100: 

Well I understand your point @ConnorGBrewster and it's something we can implement by just my opinion as well, now I believe in what @mickrip says about focusing on the experience for clients first, (without omitting altering scheme in a future) what do you think @benhaynes ?

I know we need to drop a table/column we don't want or created by mistake. But I'd see it as doing this in the development process using an Admin tool, and when are set, that where Directus comes in to play.

Thoughts?

**Comment by benhaynes** [comment]
@ConnorGBrewster @WellingGuzman @mickrip 
My thinking is that Directus is first-and-foremost a tool for managing database *content*. I personally have never used it to administer a database, and feel like it hasn't been designed with this in mind. What I would recommend is building out a Core Directus _Extension_ (*maybe* that even ships within the repo) with a more comprehensive set of DBA tools (including delete). 

This would give us a clean space to design/develop a proper set of DBA features without commingling them into the "content management system" codebase. Devs can then choose to use SequelPro, the Directus Extension, or anything else... but at least it's all decoupled and remains their choice. This direction is also nice since we can support several different DBA Extensions, and then formally adopt the one people feel is most successful.

Does that sound like an agreeable path forward?

**Comment by WellingGuzman** [comment]
@benhaynes :+1: Sounds good to me. I agreed with that.

**Comment by ConnorGBrewster** [comment]
@benhaynes @WellingGuzman if you decide to make it for purely managing content, it might seem that the ability to create tables and columns via the core Directus interface would be out of place.

**Comment by benhaynes** [comment]
@ConnorGBrewster I do agree with that mentality. If we go the route of a official extension for DBA tools then those features might also shift out of core and into the extension. Although there is a relationship between creating UIs/relationships and creating fields/columns... it will require some thinking but I think we can figure it out.

**Comment by benhaynes** [comment]
As an update, Directus now allows for the the deleting of tables/fields as follows:

User must be logged in as an admin, navigate to the Settings > Tables page, Click the delete button beside the table/field, click a confirm modal (`Are you sure? This table, its columns, and all of its content will be permanently removed from the system!`), and then type the exact name of the table/field into _another_ confirmation modal (`This cannot be undone. To confirm, please type the name of the table to delete: XXXXX`).

We believe this to be both safe and utilitarian. While our goal is not to become a database administration tool, we do want to make certain schema adjustments possible within the framework. 

Striking this balance will take time, and all input is welcome!

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+38)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
