### ISSUE TITLE
Tagging in comments error

### ISSUE THREAD

**Issue by nordcart** [directus/directus#10156]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Tagging in comments leads to error

### To Reproduce

![image](https://user-images.githubusercontent.com/12813484/144017341-61aedec7-c381-4acb-8291-c3e300b002a5.png)

### Errors Shown

![image](https://user-images.githubusercontent.com/12813484/144017308-cc661903-0f9c-4267-be3d-bb922793805d.png)

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

dont know

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Technically this is working as intended, where the user getting tagged (Toffe) has Email Notifications enabled[^1]. Since Directus is trying to send an email here, and I presume you have not configured/modified it via Docker env variables, it fails to send the email via Sendmail, thus it "errors". 

Just to be sure, if you have access or request that Toffe disables email notifications in their user profile, you should be able to mention them without any issue.

With that said, I'm not sure how many users _knowingly_ deploys Directus without configuring email (might be a valid scenario?)... perhaps this can be improved in various ways:

- make the error dialog for unconfigured email "friendlier". IIRC something similar will pop up for user invites
- add documentation for mentions requiring email setup to work properly

 @rijkvanzanten thoughts on this?

[^1]: Email notifications are enabled by default.

**Comment by nordcart** [comment]
Hi, email notifications are enabled for the user. Email has not been configured, haven´t found any documentation, so I didn´t know I needed to set this up. I thought these messages would show up in the new notification system? How are they showed there?

It would also be nice to use the notifications system as a chat, where you can send messages to other users?

**Comment by azrikahar** [comment]
> Hi, email notifications are enabled for the user. Email has not been configured, haven´t found any documentation, so I didn´t know I needed to set this up.

Can you try disabling the email notification setting for that user and test again? Just so we can be sure it's more of an email configuration issue, rather than a mentions issue.

It is indeed a _very_ new feature so any uncertainties on getting it working properly is understandable 👍 Definitely something we're looking to add to the docs.

>  I thought these messages would show up in the new notification system? How are they showed there?

If you have the chance to try the suggestion above, and provided it is working properly with email notification turned off, the user should receive the notifications (it'll have a red bubble indicator like a typical notification badge). They'll then be able to view it when they click on it and open up the notification drawer.

> It would also be nice to use the notifications system as a chat, where you can send messages to other users?

I believe this isn't technically meant for chatting per se, at least for now, but that's an interesting thought! Feel free to add a discussion if you want to gather more feedback for it.

**Comment by nordcart** [comment]
I disabled the Email notifications for all users, now the new notification system works 😄 . Thanks
