### ISSUE TITLE
Divider key name doesn't get transfered from simple to advanced mode

### ISSUE THREAD

**Issue by stefanfortuin** [directus/directus#10367]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When i name the divider in simple mode and then go to advanced mode the "key" field will replace with a randomly generated string instead of the string put in simple mode.

### To Reproduce

Get the error when trying to add a divider in translations.

1. Select divider field
2. Name the divider in simple mode
3. Go to advanced mode
4. See key name is regenarated

![image](https://user-images.githubusercontent.com/10186453/145021868-5570052c-2f32-4f23-87fe-8c67193dac19.png)
![image](https://user-images.githubusercontent.com/10186453/145021906-2f597417-4de5-430e-8ff5-b458ff3fdb4e.png)

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

Mysql 8.0+

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
The `title` is actually in the Interface tab of your second screenshot, which is not the same as `key`. That said, the advanced mode does allow you to modify the automatically generated `key` in case you want to, but that will not affect the `title` of the divider (Interface tab) which will be shown on the form. 

Technically the `key` for divider, button links etc won't really matter, hence their configuration is simplified in simple mode. Hope that clears things up.

I'll proceed to close this since this is a misunderstanding rather than an actual bug.

**Comment by azrikahar** [comment]
@stefanfortuin no worries! That's totally understandable. Honestly among all the ones that were "simplified", it does seems like divider is the only one which is more likely to cause this confusion as the first interface option coincidentally looked like key input. 

Let's see how it goes for now, and if this confusion proves to be more prominent than expected (more issues/questions about this from other users), we'll circle back and find a way to make it less likely to be confusing 👍
