### ISSUE TITLE
Minio UnknownEndpoint: Inaccessible host

### ISSUE THREAD

**Issue by xesjkeee** [directus/directus#10392]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have minio in k8s cluster, port-forwarding them to local port via

```bash
kubectl port-forward minio-0 9000:9000
```

Then if I open http://localhost:9000/ in my browser, I'll see the minio's login page

Trying to set up envs in directus app:

```env
STORAGE_LOCATIONS="S3"
STORAGE_S3_DRIVER="s3"
STORAGE_S3_KEY="AABBCCDD"
STORAGE_S3_SECRET="aabbccddeeffgghhii"
STORAGE_S3_BUCKET="blog-minio"
STORAGE_S3_ENDPOINT="http://localhost:9000/directus"
STORAGE_S3_REGION=""
```

And I see the error:
```
UnknownEndpoint: Inaccessible host: `blog-minio.localhost'. This service may not be available in the `us-east-1' region.
```

But it still works in k8s environment (when I ran it in k8s' contained pods)

---

After some minutes of researching, I found the issue in minio repo: https://github.com/minio/minio/issues/6071

One guy recommends to set config property: `s3ForcePathStyle: true`

Okay, let's do it

<img width="1017" alt="Снимок экрана 2021-12-08 в 15 08 42" src="https://user-images.githubusercontent.com/17751886/145206012-aa639fd5-983f-4c18-b786-bdd0bc583a09.png">

I restarted the server, and going to http://localhost:8055/admin/login, I still don't see images, but there are no errors about `UnknownEndpoint: Inaccessible host`

And for unexpected reasons, I get 403 Forbidden for images

<img width="928" alt="Снимок экрана 2021-12-08 в 15 13 14" src="https://user-images.githubusercontent.com/17751886/145206566-53f2b223-c1d1-4bb3-815c-1ae334084d62.png">

### To Reproduce

1. Run minio in docker/k8s
2. Make sure that you can open http://localhost:9000/minio/login in your browser
3. Try to run directus with the following config above
4. Upload some images or change logo
5. You'll get the errors

### Errors Shown

```
14:53:08 🚨 E_UNKNOWN: An unknown error happened with the file 52b66182-a303-4b51-8e39-fc4dc10b192a.jpeg.

Error code: UnknownEndpoint
Original stack:
UnknownEndpoint: Inaccessible host: `blog-minio.localhost'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/backend/node_modules/aws-sdk/lib/event_listeners.js:530:46)
    at Request.callListeners (/backend/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/backend/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/backend/node_modules/aws-sdk/lib/request.js:688:14)
    at error (/backend/node_modules/aws-sdk/lib/event_listeners.js:362:22)
    at ClientRequest.<anonymous> (/backend/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28) 
```

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

PostgreSQL 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Hi! Actually Directus does convert environment variables into camelCase provided they have the [same prefix as mentioned here](https://docs.directus.io/configuration/config-options/#type-casting-and-nesting) (the second half in that section), so you can do `STORAGE_S3_S3_FORCE_PATH_STYLE=true` instead of having to patching it in the node_modules 👍 Here's another reference: https://github.com/directus/directus/discussions/4632#discussioncomment-517865

That said, I'm also intrigued on how are you forming the `STORAGE_S3_ENDPOINT`here, especially the subpath `/directus`. It's likely wouldn't need to be added unless you have any other configurations we aren't aware of. You should also be able to skip the region declaration, so you should end up with:

```
STORAGE_LOCATIONS="S3"
STORAGE_S3_DRIVER="s3"
STORAGE_S3_KEY="AABBCCDD"
STORAGE_S3_SECRET="aabbccddeeffgghhii"
STORAGE_S3_BUCKET="blog-minio"
STORAGE_S3_ENDPOINT="http://localhost:9000"
STORAGE_S3_S3_FORCE_PATH_STYLE=true
```

provided Directus and Minio are in the same pod since you are using localhost here. 

Granted I'm not really familiar with Kubernetes myself, but I believe accessing minio via `localhost:9000` from your browser is different from Directus accessing minio via `localhost:9000`. Perhaps it would be better if you can expose Minio as a service rather than using port-forward, so you can set the endpoint as `http://minio:9000`.

**Comment by xesjkeee** [comment]
Hey @azrikahar 👋 
Thank you! I reconfigured it like this:
```bash
STORAGE_LOCATIONS="S3"
STORAGE_S3_DRIVER="s3"
STORAGE_S3_KEY="AABBCCDD"
STORAGE_S3_SECRET="aabbccddeeffgghhii"
STORAGE_S3_BUCKET="directus"
STORAGE_S3_ENDPOINT="http://localhost:9000"
STORAGE_S3_S3_FORCE_PATH_STYLE=true
```

And now I see images from remote minio ☺️

Also, it would be helpful to add `STORAGE_S3_S3_FORCE_PATH_STYLE` option to the docs, for example to «Guides > Using MinIO» page
