### ISSUE TITLE
Collection being created as a folder?

### ISSUE THREAD

**Issue by takuy** [directus/directus#10407]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm using the API functionality through an extensions module - trying to programmatically create a collection to store configuration options for the module:

Doing a fairly simple post (because I couldn't figure out how to use `useStores().useCollectionsStore().upsertCollection()` or whatever the proper method is)
```js

		api.post('/collections', {
			"collection": tableName, 
			"meta": {
				"hidden": false,
				"singleton": false,
			},
			"fields": [{
				"collection": tableName,
				"field": "LDAP Config Name",
				"type": "text"
			}]
		});

```

This seemingly creates...a folder?

![2021-12-08_22-48-20](https://user-images.githubusercontent.com/1631095/145331209-6f039f13-ffc5-4b1f-98d4-c8247dfa4841.gif)

### To Reproduce

Do a POST to the `/collections` endpoint (see example above)?

### Errors Shown

Looking at Chrome's dev console, this is the payload:
`{"collection":"LdapSyncConfig","meta":{"hidden":false,"singleton":false},"fields":[{"collection":"LdapSyncConfig","field":"LDAP Config Name","type":"text"}]}`

This is the response:

`{"data":{"collection":"LdapSyncConfig","meta":{"collection":"LdapSyncConfig","icon":null,"note":null,"display_template":null,"hidden":false,"singleton":false,"translations":null,"archive_field":null,"archive_app_filter":true,"archive_value":null,"unarchive_value":null,"sort_field":null,"accountability":"all","color":null,"item_duplication_fields":null,"sort":null,"group":null,"collapse":"open"},"schema":null}}`

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

v14.0.0

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally via NPM/X

**Comment by azrikahar** [comment]
Hi! Technically this is by design, since "folders" in this context are actually also collections in a sense, in order to facilitate things like nestings. But one major difference is folders will have no schema (null). In order to ensure you're creating a collection and not a folder, you can pass an empty object for schema, such as `schema: {}` in your POST request. Here's some further clarification from the codebase:

POST request in the App to create collection in data model:

https://github.com/directus/directus/blob/c5a9ce6e659aaaf19d97ef37f67e3f0b0c7760dd/app/src/modules/settings/routes/data-model/new-collection.vue#L236-L247

POST request in the App to create folder in data model:

https://github.com/directus/directus/blob/c5a9ce6e659aaaf19d97ef37f67e3f0b0c7760dd/app/src/modules/settings/routes/data-model/collections/components/collection-dialog.vue#L136-L139

We'll try to clarify this further in the docs. If you were referring to any section (like the API reference which seems like does not have any mentions of this yet) in the docs, do let us know as well.

**Comment by takuy** [comment]
Thanks for the clarification. I have not seen anything in the docs where `collections as folders` are discussed - the implication seems to always be `collections as a table`, kind of confusing with the idea of `folders` in the file sense.  I see the usefulness of this as a feature though, and it does make sense given that the UI allows you to do this. I'm not sure I agree with the approach of how the API handles this, but as long as the docs can make sense of it, it wouldn't be that bad. 

I was looking at these docs primarily, nothing is mentioned about using a `schema` field to create a table.
https://docs.directus.io/reference/system/collections/#create-a-collection

The `collection` object definition in the docs also doesn't discuss the difference between a collection with a `schema` or without:
https://docs.directus.io/reference/system/collections/#the-collection-object

The "glossary" entry for Collections also does not make reference to collection folders:
https://docs.directus.io/getting-started/glossary/#collections

**Comment by azrikahar** [comment]
Thank you for the detailed feedback! Really appreciate it. From what I've found, seems like it is (albeit can still be not super "visible") mentioned here: https://docs.directus.io/configuration/data-model/#sorting-grouping as `special "folder" collections`, but I've totally reached for the exact same sections you have outlined when finding for it. Definitely great places to add mentiones of it 👍
