### ISSUE TITLE
[UNKNOWN] Network Error when displaying a collection

### ISSUE THREAD

**Issue by desirelabs** [directus/directus#10439]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Creating a fresh collection and accessing it returns error `[UNKNOWN] Network Error`

### To Reproduce

Create a new collection named `impressions`
Add a new text field named `label`
Access the collection page

### Errors Shown

vendor.764dd834.js:70 GET http://localhost:8055/items/impressions?limit=25&fields[]=label&fields[]=id&sort[]=id&page=1&meta[]=filter_count&meta[]=total_count net::ERR_BLOCKED_BY_CLIENT

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome 96.0.4664.93

### What operating system are you using?

MacOS 12.0.1

### How are you deploying Directus?

running locally

**Comment by desirelabs** [comment]
Maybe this will help: extension AdNauseam is causing the issue. But not on every collection.

**Comment by Oreilles** [comment]
Do you face this issue at all when setting `TELEMETRY="false"` in your `.env` file ?

**Comment by azrikahar** [comment]
Hmm that's interesting. Can't say I'm familiar with it, but assuming you mean the _browser_ extension [AdNauseam](https://adnauseam.io/), I believe what's happening here is it's actively blocking said collection due to a false positive situation here. Here's what I've found from the privacy easylist that AdNauseam does use:

![chrome_ixTuIYzljC](https://user-images.githubusercontent.com/42867097/145595810-8837ca73-d5fe-4bbc-b761-188d9488af99.png)

Unfortunately this is effectively out of our control here, other than ensuring to avoid using the words like "impressions", or loosening/disabling the browser extension itself.

If you can confirm that this turns out to still be an issue with Directus rather than the browser extension, we'll reopen this 👍
