### ISSUE TITLE
M2M items empty display field when creating item

### ISSUE THREAD

**Issue by ilijaNL** [directus/directus#10476]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding a new item which has m2m relation, the label is not visible. The label becomes visible when item is saved and is editable.

New entry:
![image](https://user-images.githubusercontent.com/276772/145842447-7d276dda-f499-4d3e-a4ed-fb59367f6c60.png)

Edit entry: 
![image](https://user-images.githubusercontent.com/276772/145842520-d8308f96-235b-4e5c-b988-cc843dddd494.png)

Possible related to #9977 

### To Reproduce

Install v9.2.2. Create m2m relation. Add new item which has m2m relation.

### Errors Shown

Chrome logs `RangeError: Invalid time value` however not related (i think)

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

directus docker image

### What database are you using?

postgres

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying Directus?

docker

**Comment by joselcvarela** [comment]
Thank @ilijaNL the error on console and the issue you mentioned should not be related to this.
But, we also should take this into account #9990

**Comment by Antidote00** [comment]
Same issue:
![grafik](https://user-images.githubusercontent.com/4086468/149769365-9cc360be-776d-49aa-8589-3ff027e4546f.png)

Using v9.4.3 in Docker Container of this repo.

**Comment by AntoineBarroux** [comment]
Hi ! After some research, it looks like the m2m-list interface is emitting data like this as its value : 
{ 
junctionCollectionName.relationPrimaryKeyName: elment's id
}

To introduce this message, I'm working with a collection of articles, each one containing a list of thematics. My identifiers are generated uuids.

Problem is, when you're trying to add an inteface display template based on the element's name for example, this field is not present in the payload so when the render-template component is rendering this element, it does not know about this field and just renders "---".

![Failing case, trying to render the name of my related collection item](https://user-images.githubusercontent.com/22744488/153867595-390f649c-29f3-4dca-bfdb-6876520ceb81.png)
![Emitted value does not contain the name property](https://user-images.githubusercontent.com/22744488/153868011-6096ee39-6b09-48f2-887d-bbdb9dafa7c1.png)

I tried displaying the element's identifier instead of its name as an interface display, because this field is present in the payload and can be accessed by render-template, and it works correctly.
![Working case, rendering items by their identifiers](https://user-images.githubusercontent.com/22744488/153868390-7828d5da-28fe-41cf-855d-55c75821b56c.png)
![Emitted value contains the template field (identifier) so it works](https://user-images.githubusercontent.com/22744488/153868598-98f68617-e6c1-4ca7-9dcd-26e7e059bb86.png)

To confirm it, I tried to make the interface emit the name of my thematic, and it works again because the render-template component now finds my display field : 
![Adding my property with value "test" to the
![Now working with the display property in the payload](https://user-images.githubusercontent.com/22744488/153870289-19543789-ee5b-4c25-853a-b281aaaf08ad.png)
 payload](https://user-images.githubusercontent.com/22744488/153870159-defef183-f4e1-475f-8042-af4f44da3206.png)

I hope I was clear enough... I tried to find a solution but my knowledge of this system is quite limited... I think we would have to provide to the component that loads the list of elements a list of fields to retrieve (identifier + list of all fields used in the template expression) but I didn't find a way of doing it.
In case all of this was not clear, we can talk about it on Discord for further information
