### ISSUE TITLE
Admin password invalid after every server restart

### ISSUE THREAD

**Issue by stuartchris** [directus/directus#10780]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Running fresh install with just the one admin user, no changes to config/files, every time server is restarted the admin password doesn't work anymore, luckily the refresh token in browser enables access to the UI to reset the password, only discovered the issue when attempting to login from a different browser that hadn't previously connected to the server , after server restart login consistently failed, even through the API. Had I waited 7 days and let the refresh token expire I would've lost all access to login.

### To Reproduce

1. Install Directus
2. Login as admin with username/password
3. Stop the Node server and restart it
4. Clear all browser cache/cookies or use a different browser that hasn't previously connected to the server or attempt to login through the API
5. Attempt to login as admin with username/password, fails with error 'Wrong username or password'

### Errors Shown

Wrong username or password

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

14.15.4

### What database are you using?

Maria DB 10.6

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

npm install directus

**Comment by rijkvanzanten** [comment]
Seems to work as expected on my end. Are you running any custom logic on startup / shutdown? Any installed extensions? Any chance you might've accidentally changed the password in the app when using it the first time? 

https://user-images.githubusercontent.com/9141017/147797084-2a13fa79-d0ad-4d09-8aa6-85a2ea8832a3.mp4

The password hashing isn't relying on the current running process, so restarting the server wouldn't affect the stored hash in the DB unless something else is running / affecting it.

I'll close this for now, as I believe it to be a configuration / environment specific problem, rather than a bug in Directus. More than happy to keep discussing though 🙂
