### ISSUE TITLE
Next release prediction ?

### ISSUE THREAD

**Issue by alketii** [directus/directus#1094]
Hi, I know this isn't an issue, but do you have an ETA for the next release ?
Thanks.

**Comment by benhaynes** [comment]
Hey @alketii – the next full/major release (v7) is probably a ways off... we're moving to smaller, more  incremental updates now. 6.1 will be mostly bug fixes and optimizations – then we have a whole backlog of other features that will be added in. Is there a specific feature you're looking for or a reason for asking?

Things have been progressing a bit slower the past three months due to something new/big we're working on for Directus. More to come!
