### ISSUE TITLE
Make relational setup less confusing

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1102]
* Each UI parameter/option should have a clear title and description
* Look into better ways to visualize the relationships
* Show examples and placeholder text
* Ensure nothing is missing/broken (see other tickets)

**Comment by benhaynes** [comment]
First, I'm wondering why we're not using the actual "relationships" in MySQL to store these relationships?

### `directus_tables.is_junction_table`
Let's remove `directus_tables.is_junction_table` and all references to it in the framework. The only place it was used (I think) was when setting up a new relationship... it only showed junction tables. Now we can show all tables in this dropdown.

### `directus_columns.data_type`
For `directus_columns.data_type`, are we using this anywhere? It seems that most values are empty or in duplicate. We should change this field to be a boolean: `alias` with values of 0 or 1

### `directus_columns.relationship_type`
In `directus_columns.relationship_type` for consistency can we adjust `MANYTOONE` to be `many_to_one`? Also, should this be an `enum` so it only has three options:

* `many_to_one`
* `one_to_many`
* `many_to_many`

### Field Order
Let's move `system`, `master`, `hidden_input`, `hidden_list`, and `required` **right before** `sort` in the default schema field order

### Many-to-One & One-to-Many
Currently these require a value in `directus_columns.junction_key_right` – but this value always seems to match `directus_columns.column_name`. Would it ever not be the same? If not, can we change the logic so it doesn't require this value?

### Many-to-Many
Some thoughts around new naming for these fields:

* `related_table` (changed)
* `junction_table`
* `this_table_foreign_key` (changed)
* `related_table_foreign_key` (changed)

Thoughts @WellingGuzman ?

**Comment by WellingGuzman** [comment]
> * Each UI parameter/option should have a clear title and description
* **Look into better ways to visualize the relationships**
* Show examples and placeholder text
* Ensure nothing is missing/broken (see other tickets)

We have been working on all except a better visualization of the relationship, we can add that into the features.

----
> Why we're not using the actual "relationships" in MySQL to store these relationships?

Let's plan on adding this into future version.

> Let's remove directus_tables.is_junction_table and all references to it in the framework. 

Agreed, we have been removing its reference.

> directus_tables.table_name and directus_tables.field_name

You meant `directus_columns` right? 🐰 , I believe this was used as MySQL uses the same names, I like it that way, but we can discuss how confusing can it be. This will rise another question, are we naming it "Fields" or "Columns"? sometimes the names are interchangeable.

> directus_columns.master and directus_columns.system
>
> Where are these used? Could we find ways to simplify this... maybe remove them?

We can remove it, the use of `master` it was to indicate the main column/field of a table, the value that represents the table. System is a way to tell when a column/field name was a system field, such as `id`, `sort` and `status` (I think those are all).

> directus_columns.data_type

It's not sure the uses but it's mainly used for relational field, I think it will be best to store the column real data type, ex: `INT`, `VARCHAR` or `ALIAS`.

> directus_columns.relationship_type

I like all in uppercase altogether. wanna fight for it? ✌️  But I do love that it should be an enum.

> directus_columns.comment

What about SQLite? no love? As far as I know SQLite do not support field comment, or does it, can someone confirm?.

> Let's move system, master, hidden_input, hidden_list, and required right before sort in the default schema field order

Perfect!

> Some thoughts around new naming for these fields:
> 
> **related_table (changed)**

Agreed, it was giving anxiety.

> junction_table
> this_table_foreign_key (changed)
> related_table_foreign_key (changed)

On `many to one`, `junction_right_key` represents the current table key.
On `many to many` `junction_right_key` represents the `junction_table` key.

It can't be `this_table_foreign_key` because it not always the current table key.

Still analyzing what can be best regarding the column names, but while we are at it, we can discuss in labeling the way you say, depending on the relationship type, we label it in the form differently.

**Comment by benhaynes** [comment]
> Why we're not using the actual "relationships" in MySQL to store these relationships?
Let's plan on adding this into future version.

OK, I'll add a ticket!

> You meant directus_columns right? 🐰 , I believe this was used as MySQL uses the same names, I like it that way, but we can discuss how confusing can it be. This will rise another question, are we naming it "Fields" or "Columns"? sometimes the names are interchangeable.

OK, if that's what MySQL calls them then let's leave it as is. We do need to agree on fields/columns though. Is there a preference?

> We can remove it, the use of master it was to indicate the main column/field of a table, the value that represents the table. System is a way to tell when a column/field name was a system field, such as id, sort and status (I think those are all).

Cool – let's remove `master` (and any references), and let's remove `system` and just have a conditional for `id`, `sort`, and `status`.

> It's not sure the uses but it's mainly used for relational field, I think it will be best to store the column real data type, ex: INT, VARCHAR or ALIAS.

Is there a need to store the datatype? Don't we have that from the schema (no need for duplicate data). I like the idea of the `ALIAS` boolean. Datatype from the schema, relationship from `relationship_type`... 🙏

> I like all in uppercase altogether. wanna fight for it? ✌️ But I do love that it should be an enum.

Haha, 👊 ...  if you want to leave these as caps that's fine (though I still think they should be lowercase like everything else). But let's make that an `enum` for sure.

> What about SQLite? no love? As far as I know SQLite do not support field comment, or does it, can someone confirm?.

Good point! Let's keep this and manage comments in the system. But we should sync with the DB types that allow it.

> related_table (changed) – Agreed, it was giving anxiety.

Let's change it! We can leave the other left/right column names.

**Comment by WellingGuzman** [comment]
> OK, if that's what MySQL calls them then let's leave it as is. We do need to agree on fields/columns though. Is there a preference?

The only thing I have to say, it's that when I say column, I'm thinking about a table columns, but I say field Im thinking about that form field. (which is a column anyway).

**Field** seems like a more friendly name.

**Comment by benhaynes** [comment]
OK, much better. Most of these changes were made – some were not because they weren't as obviously beneficial. We need to continue to add optimizations here, including Docs and column notes in the GUI... but that will happen over time.
