### ISSUE TITLE
Readonly state doesn't match permissions config

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11058]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using permissions for a role with a custom permissions rule, only the field permissions are adhered in the readonly state. 

### To Reproduce

1. Setup a data model with a collection X with a couple fields 
2. Create a new role
3. Add full read permissions to collection X for role
4. Add Custom edit permissions
5. Set fields permissions to half of the available fields
6. Add a item rule for "field _neq value"
7. Try editing item where item rule permission matches
8. Notice how you can still edit half the fields and hit save, even though you don't have permissions to edit the current item

(You still can't save, as the API permissions correctly kick in, but the app check is missing that rule step from the looks of it)

### Errors Shown

n/a

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 13

### What browser are you using?

Safari 15.2

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
Since it needs to be fixed, I also have this bug, it is worth considering the type option depending on the field, let's say the "status" when there is "draft" can edit selected fields but when "publish" it is possible to edit other fields. I mean that depending on the met condition, other fields can be edited. In fact, you can do the same for creating and view...

**Comment by mslonina** [comment]
Hi, coming from #13774 - it looks like custom rule is not taken into account, I'd assume that all of fields should be disabled if the rule doesn't allow updating the item.

**Comment by mslonina** [comment]
It might be related - I have a content type, in which I allow users to see some of the properties, and only authors to see all of the properties (the same user role - authenticated; authors and users are the same role, they are both writers and readers):

- fields title, body - visible by anyone within the role
- fields title, body, state - visible by authors only

In the field Conditions section I set `User created doesn't equal $CURRENT_USER` and `Hide the field` - which works fine on the App side, but doesn't apply to the API (I get all the fields despite the settings). So it feels misleading:

- we have fields per role, which is the first level of permissions to check
- then we have field permissions within the model (another, yet powerful level) - but it doesn't work for the API (it is a bug or by design?)

**Comment by koksikus** [comment]
It is a pity that the basic directus function does not work yet 😉

**Comment by koksikus** [comment]
Fixing this bug will allow for better directus setup. At the moment, each field must have its own anti-editing conditions, which is tiring and easy to make mistakes

**Comment by rijkvanzanten** [comment]
Linear: [ENG-278](https://linear.app/directus/issue/ENG-278/readonly-state-doesnt-match-permissions-config)

**Comment by rijkvanzanten** [comment]
Permissions checking on the client side has since been rewritten so this should no longer be an issue
