### ISSUE TITLE
The char @ in the translation of a field name produces an Unknown error

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11056]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It the translation of a field name contains `@` the application will show a blank screen with an `Unknown error`

Specials chars of a translation should be filtered out.

### To Reproduce

As Admin [en-US], set the translation [xx-XX] of a field name with an `@` in it (I did it with  a field added to `Directus Users`)
Then try to connect as a user in the [xx-XX] language.

### Errors Shown

Blank screen with the following error

- Edge
```
{
  "stack": "SyntaxError: 9\n    at K5 (http://localhost:8034/admin/assets/vendor.1339fc9e.js:25:69)\n    at x (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:1046)\n    at Ir (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:6623)\n    at Nr (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:6776)\n    at Object._n [as nextToken] (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:7305)\n    at C (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:9080)\n    at L (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:10445)\n    at V (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:11000)\n    at Object.M [as parse] (http://localhost:8034/admin/assets/vendor.1339fc9e.js:26:11163)\n    at ej (http://localhost:8034/admin/assets/vendor.1339fc9e.js:27:466)",
  "message": "9",
  "code": 9,
  "location": {},
  "domain": "tokenizer"
}
```

- Firefox
```
{
  "fileName": "http://localhost:8034/admin/assets/vendor.1339fc9e.js",
  "lineNumber": 25,
  "columnNumber": 69,
  "message": "9",
  "code": 9,
  "location": {},
  "domain": "tokenizer"
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox and Edge

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by Pachat** [comment]
May I add this catastrophic scenario:
1. With Admin [en-US] add an @ in the translation of a field in another language [xx-XX]
2. In your User preferences, change your own language to [xx-XX]
3. Disconnect
4. You will not be able to connect anymore!
_Better have a backup before doing this_

**Comment by azrikahar** [comment]
@Pachat can confirm this on production. In the meantime, one workaround would be remove the `@` usages in field translations in your database directly to gain access to the admin app again.

---

Reference: This is only reproducible on production (tested on `v9.4.3` Docker image). It'll only show as console errors in development environment instead.

This seems to be caused by interpolation done by `vue-i18n`, as `@` is one of the [special characters](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters). 

We'll either have to disallow the entering of those special characters, or do [literal interpolation](https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation) automatically under the hood for these characters:

https://user-images.githubusercontent.com/42867097/149744708-dcd878d3-ce4d-4f4d-9c12-6897941ef244.mp4

**Comment by Pachat** [comment]
Thank you for your confirmation.
It looks like that only `@` is causing the bug. So just preventing to put `@` would be enough and still allow chars like `&` `$`, etc.
