### ISSUE TITLE
Header buttons don't always correctly check permissions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#11059]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The header action buttons should disable when you don't have permission to do the action (as is the case with Delete and Save on the item detail). However, this logic isn't always (correctly) applied:

- The _Archive_ header button on the item detail page doesn't check if you have update permissions to set the archive field to the (un)archive value
- The Batch operation actions on the layout (eg archive, edit, delete) don't correctly handle cases where you select both items you _can_ and _can't_ archive/edit/delete

(The API will still properly run all permissions, so any actions the app allows you to do don't actually go through)

### To Reproduce

Create a data model, set some creative permissions in a role, and check the above mentioned header buttons for messy behavior

### Errors Shown

n/a

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13

### What database are you using?

Postgres 13

### What browser are you using?

Safari 15.2

### What operating system are you using?

macOS Monterrey

### How are you deploying Directus?

locally

**Comment by log4shell** [comment]
I just want to add that this also applies the other way around, e.g., the buttons are sometimes disabled when the user in fact has permission to perform the operation. 

As an example, I have the following rule for "Delete" on a collection:
```
{
	"_and": [
		{
			"status": {
				"_in": [
					"draft"
				]
			}
		},
		{
			"user_created": {
				"id": {
					"_eq": "$CURRENT_USER"
				}
			}
		}
	]
}
```
When the user opens an item in this collection that they created, and still is in draft status, the delete button is disabled although the user should be authorized to delete the item. However, the user can delete the item as expected if they select it in the list view of all items in the collection and then invoke the delete button. It's just a UI bug when opening the specific item in question. 

It would be good if the fix takes this into account as well so that both enabling and disabling of buttons is done correctly according the configured permissions.

**Comment by azrikahar** [comment]
Just sharing an additional finding, seems like for `delete` permission specifically, we aren't able to select fields when granting said permission, which is 100% correct. However since there's no fields, the following logic always passes and return false for `delete` action:

https://github.com/directus/directus/blob/0a5ff6d12a77deb5cdc2d740cc9d643ee44c692e/app/src/utils/is-allowed.ts#L24

Which is why the delete button is always disabled even after allowing it with `$CURRENT_USER` checks. Changing `action !== 'share'` to something like `!['delete', 'share'].includes(action)` does seem to (partially) resolve this for delete permission, but then the user is also able to delete items that are _not_ `$CURRENT_USER`, so this definitely isn't the complete solution.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-277](https://linear.app/directus/issue/ENG-277/header-buttons-dont-always-correctly-check-permissions)

**Comment by paescuj** [comment]
Adding as a reference: https://github.com/directus/directus/issues/16498#issuecomment-1412239282

**Comment by rijkvanzanten** [comment]
I believe this was resolved in https://github.com/directus/directus/pull/21152 but can reopen if not
