### ISSUE TITLE
Server Error: Undefined index

### ISSUE THREAD

**Issue by TJProgrammer** [directus/directus#1111]
Hello!
When I tried save the table "Bookmarks" I got the error in the image bellow:

![image](https://cloud.githubusercontent.com/assets/7900361/12026124/dd5252c2-adad-11e5-9a25-9968231ed66d.png)

**Comment by WellingGuzman** [comment]
Hi @TJProgrammer thanks for letting us know, I'm going to take a look at this.

**Comment by benhaynes** [comment]
It seems like `directus_columns.relationship_type` for that table/column has a bad value... based on using the Single File UI it *should* be: `MANYTOONE`

@TJProgrammer – How did you create that `file` field? Directly in the DB or through Directus?

@WellingGuzman can we look at why this didn't save?

**Comment by WellingGuzman** [comment]
@benhaynes I believe the problem there it has to be with `Folder` field. I can't find it now, but I think I open a ticket about this, right now not all UIs have the relationship type set, but rather guessed on the server.

We need to implement this in a way that the UIs itself provide their relationship type, rather than the server to guess it.

**Comment by TJProgrammer** [comment]
I created the ```file``` field through Directus.

**Comment by WellingGuzman** [comment]
I couldn't replicate this before, so we went through a different fixes and hotfixes for relationship fields, so this might be fixed along the way.

I'm closing this one, but if @TJProgrammer still experience this issue, I will open this again and take care of that again.
