### ISSUE TITLE
Align `readMany` and `readByQuery` in SDK

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#11187]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The current javascript sdk documentation still refers to the `readByQuery` function on the ItemsService which judging from the code was merged into the `readMany` function.

**Comment by br41nslug** [comment]
I fully agree that thats the underlying issue. but the immediate issue here is that the docs and code are out of sync.

**Comment by rijkvanzanten** [comment]
@br41nslug Wanna shoot a quick PR to those docs? 🙂

**Comment by br41nslug** [comment]
Damnit i hate writing docs 🤣 but sure i'll give it a go

**Comment by joselcvarela** [comment]
> The real issue here is that the SDK isn't aligned with the internal services from Directus itself at the moment. We should split up `readMany` and `readByQuery` in the JS SDK as well, so it aligns with the `ItemService`'s `readMany` and `readByQuery` calls

I am not sure if this is the right approach.
SDK is just a thin wrapper around the REST API. Although `ItemsService` has a `readMany` which can read multiple items by primary keys, the same does not happen on the REST API, because we can only pass a single primary key on GET.
If  we would implement `readMany` on SDK, it was simply a `filter: { [primaryKey]: { _in: [keys] } }` on current `readMany`, so I am not sure if makes sense to create such method 🤔

**Comment by rijkvanzanten** [comment]
> If we would implement readMany on SDK, it was simply a filter: { [primaryKey]: { _in: [keys] } } on current readMany, so I am not sure if makes sense to create such method 

To me, that actually makes sense. If you have people that are writing both extensions, and use the SDK on their own projects, this consistent naming system with different type signatures is very confusing!
