### ISSUE TITLE
Token UI only visible by admins

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1124]
Using `directus_privileges.read_field_blacklist` to hide it by default for non-admin groups.

**Comment by WellingGuzman** [comment]
@benhaynes the issue here is that we are trying to select * (all) the fields most of the time (_to not say always_) and this violates the `read_field_blacklist`. same with updating violating the `write_field_blacklist`.

I recommends we just stripe out the blacklisted fields before perform an action. That will be the job of the API not letting this field to get into the selects or updates.

If `directus_users.token` is blacklisted on **read** every time a `select * from directus_users` is performed, the tablegateway will take care of taking this table from the select and convert it into `select id, email, password, etc from directus_users` but not token.

Making sure this can be warned on the admin panel, which will results in a Directus issue if they could've find a way to edit a blacklisted field, or they just add it directly to the api request, which either case we make sure the update or select won't happen on the server.

what do you think?

**Comment by benhaynes** [comment]
That works for me. As long as normal users don't see that field (only admins). I thought it would be nice to use the Directus feature to hide it... but I understand that might not work for this. Thanks!

**Comment by WellingGuzman** [comment]
All I said it was that it can work within Directus feature, but we need to update how we force to NOT Select blacklisted fields from a table. (a good behavior) So here is the question:

if we blacklisted `directus_users.token`, and a user request "all" fields from `directus_users`, should we a) remove the blacklisted field (what I'm proposing), or b) throw an error because you are requesting a blacklisted field (what currently happening).

OR

we keep doing what's currently being done, but we strip the columns first, on the server.

Am I clear? I'm being kind of confused here.

**Comment by benhaynes** [comment]
Yes, we would remove the field if they request all (*) fields. Perfect!

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/5db94e18d4003a6355b901abb4c5c96409d35458 and https://github.com/directus/directus/commit/ebff39aa992c433acaff3ee831e0f59e58b51481
