### ISSUE TITLE
enhancement: Column Name & Table Name should be lowercase only

### ISSUE THREAD

**Issue by webbakery** [directus/directus#1133]
the table or column name always has a capital in the application. I always want to start typing with a capital letter but that's gonna mess up my database. Also it's possible to add spaces which will break the application.
I think it will be better only allowing lowercase characters and underscore.

**Comment by WellingGuzman** [comment]
Didn't quite understand what you mean by capital letter. If you are talking about that Directus display the columns and table name with capital letter and underscore as spaces, it's kind of a "beautifier" if this is what you talking about we can have an option to display the actual name without "beautifying" the names.

And we can't stop the user from creating names with spaces, because the database engine allow it, what we can do it's work toward making those spaces  not break Directus.

Did I answer your concern?

**Comment by webbakery** [comment]
Yes, I think the easiest way would be not allowing a space (or auto change to "_" in the input field when creating a field within Directus (expanding database). And I would personally don't capitalize the field. So the overview within Directus has exactly the same name as the field within the database.

Example:
If I want to expand Directus and I see all the current fields have capital letters, I automatically want to type a capital letter if I add a field.
This results in having a database with and without capital letters. Afterwards it's hard to change this field and it's not quite clear within Directus which fields do and do not have a capital letter.


What do you think @WellingGuzman  ?

**Comment by benhaynes** [comment]
I agree, I think we add some simple input limits/formatting when adding columns/tables (only lower-case, spaces turn to underscores, no special chars). We can also add placeholder text to the inputs with: `eg: related_work`. If admins want to use a different naming convention that's not the Directus style, then they can do that directly in the database. That way all tables/columns made within directus are all "properly" formatted.

The other thing we could do it not prettify some of the tables/columns within the `Settings` area. This might help reinforce the naming conventions.

**Comment by WellingGuzman** [comment]
All tables and columns name are now being converted to lowercase and spaces and symbols to underscores.
