### ISSUE TITLE
Extension Routing not working

### ISSUE THREAD

**Issue by iamamused** [directus/directus#1139]
Trying to create a new extension and can't get it to load the page. To test i simply renamed the `_example` folder to `example` and had the same error. The extension shows in the navigation but when I tap it I get "You do not have permission to view that page or it doesn't exist". I'm logged in as admin and seem to have permissions to everything. 

Is there some additional configuration required? Or how exactly do you specify the routes for the module?

**Comment by WellingGuzman** [comment]
Hey @iamamused,

I see the problem here, is actually a issue with the routing path, right now there's a encode "/" at the end of the route, I'll take a look into this in a moment. If you go to `yourdirectus.com/example_extension` you should be seeing the extension.

The error `You do not have permission to view that page or it doesn't exist` has nothing to do with permission actually, but rather that a not found page.

Thanks for reporting this I will take a look at it.
