### ISSUE TITLE
Notice field removes target="_blank" attribute in <a> tags

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11477]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Is there a reason not to render `target="_blank"`

### To Reproduce

1. In a Notice field, set `<a href="my.pdf" target="_blank">Please click here</a>`
2. Save and show the item. The console shows: `<a href="my.pdf">Please click here</a>`

This is strange as the recorded content is `<a href=\"my.pdf\" target=\"_blank\">Please click here</a>`

### Errors Shown

Does not open in a new tab.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This seems to because notice interface passes the content via `v-md` directive:

https://github.com/directus/directus/blob/b8c4317cb1cd9a8ed0eeb1ad4db35f8771588624/app/src/interfaces/presentation-notice/presentation-notice.vue#L4

And the `target` attribute is still intact after processed by `marked`. However dompurify's sanitize function strips it out over here:

https://github.com/directus/directus/blob/b8c4317cb1cd9a8ed0eeb1ad4db35f8771588624/app/src/utils/md.ts#L1-L9

This is also a known issue in dompurify: https://github.com/cure53/DOMPurify/issues/317

As seen in the follow up comments in that thread, this can be resolved with dompurify's hooks, but this comment also does mention the security concern with this as well: https://github.com/cure53/DOMPurify/issues/317#issuecomment-670850160. @rijkvanzanten thoughts on this?

**Comment by Pachat** [comment]
About the security concern, the [Links to cross-origin destinations are unsafe](https://web.dev/external-anchors-use-rel-noopener/) gives the solution:
_Adding `rel="noopener"` or `rel="noreferrer"` to your `target="_blank"` links avoids these issues._

And this is exactly what Directus already does when we add a new external URL to the modules menu:
`<a class="button x-large align-center icon tile normal" type="button" disabled="false" href="http://localhost:8081/" target="_blank" rel="noopener noreferrer">
` 
which is fine there.

Unfortunately in a Notice, after sanitization, `target="_blank"` is removed and only `rel="noopener noreferrer"` is sent.

**Comment by azrikahar** [comment]
Thanks for the elaboration. Technically the `target` and `rel` attribute for external URL added to modules menu are "manually" added in the code as seen here, which is why it's fine:

https://github.com/directus/directus/blob/748ee976818fa86c27561710a3fb1fcf203d74ff/app/src/components/v-button/v-button.vue#L28-L29

but yea in the Notice interface case, dompurify ended up being the one sanitizing/removing `target` by default but not `rel` as seen in the existing issue in reported over there.
