### ISSUE TITLE
Rename, Move, Delete Folder in File Library do not work

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11633]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After right clicking on a folder in the list of File Library's folders, nothing happens

### To Reproduce

1. Open File Library
2. Right click on a folder
3. Choose Rename, Move or Delete

### Errors Shown

Nothing happens.

Move: I had one time the folders' tree where to move, but never could have it again

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by jaycammarano** [comment]
I was able to reproduce this. Nothing worked and then I was able to get rename to work once but then not again. I'm not seeing any errors anywhere.

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/directus/pull/11432

**Comment by azrikahar** [comment]
I believe this is an issue with the context menu directive, specifically the `focusout` event which turned out to be unreliable, similar to #11082. #11432 relates to Folders in Data Model rather than in File Library 👍

The proper fix will likely be doing something akin to the click outside directive: 

https://github.com/directus/directus/blob/40ec3229983f22ddf478d6bc191df4dd45ba4500/app/src/directives/click-outside/click-outside.ts#L116-L117

Where the context menu should close if the click is not within it or it's children.
