### ISSUE TITLE
Limit not apply on o2m

### ISSUE THREAD

**Issue by proceau** [directus/directus#11663]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When set fields=toto.*&limit=-1 the sub o2m toto it's limit to 100 item and not -1

### To Reproduce

create big collection, add o2m, query and see only first 100 sub item

### Errors Shown

no

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.0.0

### What database are you using?

mariadb 10.3

### What browser are you using?

opera

### What operating system are you using?

windows

### How are you deploying Directus?

vm

**Comment by azrikahar** [comment]
When we do `limit=-1` (or any other query parameters by themselves), it only applies to the queried collection itself and not the O2M collection. You should use the `deep` query param to apply it to the any nested relationships, and the first example also showcases the exact same use case: https://docs.directus.io/reference/query/#examples-7

To be more specific to your current query, `deep[toto][_limit]=-1` should do the trick rather than `limit=-1`. Hope that clears things up.

**Comment by proceau** [comment]
it is clearer for me, but not very practical, it would not be possible to define this value 100 in a global variable of the project to put 1000 or 10000 ? 
DIRECTUS_LIMIT=1000 in config

**Comment by azrikahar** [comment]
That is unfortunately not supported as of now, but do feel free to open a discussion about it so that other members of our community can share their thoughts such configuration 👍

**Comment by proceau** [comment]
it is a good practice to make parametric by variables, all arbitrary constants of a program. 
thx for your support
