### ISSUE TITLE
This query failed... after fresh install

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1168]
I am not sure if it makes sense to report bugs for the development branch. Is it stable enough to expect that cloning and installing it should work?

## Version Info
  - Directus version: e86379523e
  - PHP version: PHP 5.6.14-1+deb.sury.org~trusty+1 
  - MySQL version: 5.5.46-0ubuntu0.14.04.2
  - Web server: Apache/2.4.16 (Ubuntu)
  - OS name and version: Ubuntu 14.04.3 LTS

## Expected Behavior

After a fresh installation I expect the system to work.

## Actual Behavior

I get an exception after I log in.

## Steps to Reproduce
 1. clone git repo (development branch)
 2. run composer install
 3. run installation in the browser
 4. select "plain database" - do not use the example gallery data
 5. login

When using the example data everything works fine.
It looks like the access levels for the default user are not set correctly so that he does not have access to read any fields of the user table, resulting in an empty column list in the `SELECT` query.

## Logs or Screenshots

```
{
  "code":0,
  "class":"RuntimeException",
  "message":"This query failed: SELECT  FROM `directus_users` ORDER BY `id` ASC LIMIT 1000 OFFSET 0",
  "file":"\/var\/www\/public\/api\/core\/Directus\/Db\/TableGateway\/AclAwareTableGateway.php",
  "line":484,
  "trace":[
    {
      "file":"\/var\/www\/public\/api\/vendor\/zendframework\/zend-db\/src\/TableGateway\/AbstractTableGateway.php",
      "line":208,
      "function":"executeSelect",
      "class":"Directus\\Db\\TableGateway\\AclAwareTableGateway",
      "type":"->",
      "args":[
        {
          
        }
      ]
    },
    {
      "file":"\/var\/www\/public\/api\/core\/Directus\/Db\/TableGateway\/RelationalTableGateway.php",
      "line":686,
      "function":"selectWith",
      "class":"Zend\\Db\\TableGateway\\AbstractTableGateway",
      "type":"->",
      "args":[
        {
          
        }
      ]
    },
    {
      "file":"\/var\/www\/public\/index.php",
      "line":130,
      "function":"getEntries",
      "class":"Directus\\Db\\TableGateway\\RelationalTableGateway",
      "type":"->",
      "args":[
        {
          "table_name":"directus_users",
          "perPage":1000,
          "active":1,
          "columns_visible":[
            "active",
            "avatar",
            "first_name",
            "last_name",
            "group",
            "email",
            "position",
            "last_access"
          ]
        }
      ]
    },
    {
      "file":"\/var\/www\/public\/index.php",
      "line":315,
      "function":"getUsers",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 \/var\/www\/public\/api\/vendor\/zendframework\/zend-db\/src\/TableGateway\/AbstractTableGateway.php(208): Directus\\Db\\TableGateway\\AclAwareTableGateway->executeSelect(Object(Zend\\Db\\Sql\\Select))\n#1 \/var\/www\/public\/api\/core\/Directus\/Db\/TableGateway\/RelationalTableGateway.php(686): Zend\\Db\\TableGateway\\AbstractTableGateway->selectWith(Object(Zend\\Db\\Sql\\Select))\n#2 \/var\/www\/public\/index.php(130): Directus\\Db\\TableGateway\\RelationalTableGateway->getEntries(Array)\n#3 \/var\/www\/public\/index.php(315): getUsers()\n#4 {main}"
}
```

**Comment by WellingGuzman** [comment]
hey @laszlokorte, we are continuing working on `development` branch, it very possible everything has lots of unfinished works.

So Thanks for reporting this I will take a look later, but development branch is not meant to be ready right now.

**Comment by laszlokorte** [comment]
Ok, that's what I thought. I just wanted to try working on a PR regarding the SVG upload and thought it would be best to base it on the development branch.

**Comment by WellingGuzman** [comment]
@laszlokorte the best branch you could use is the master, as development branch is all crazy in there right now. I would leave it open until it's fixed on the development branch, so I can remember this is an actual issue before release it.

**Comment by laszlokorte** [comment]
Ok, slightly off topic question: Do you have some kind of public roadmap? Currently the documentation seems to be incomplete and there seems to be some dead code in both the php code and the db schema. 

For example this list of image formats in the AclAwareTableGateway:
https://github.com/directus/directus/blob/master/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php#L39 (https://github.com/directus/directus/commit/ea6e489eba18ad559dd07c00507e45f7d57ff925)

Or the `is_junction_table` column in the `directus_tables` table seems to be unused?

Or for commented code like this:
https://github.com/directus/directus/blob/master/api/core/Directus/Files/Thumbnail.php#L32-L34
the purpose is not quite obvious (?)

I am currently evaluating using Directus in a few of my projects. For doing so it would be great to get an idea in which direction the project is heading and what's the current state of development.

**Comment by WellingGuzman** [comment]
We are working hard on bringing an up to date and complete documentation, while we clean and make Directus and its code better.

The state of development is live and in continuing development, expect much more, we are not going anywhere yet.

About the "dead code" and "not quite obvious" comment, we have been working into that, so in couple of weeks this are going to be all fixed and well documented.

**Comment by benhaynes** [comment]
Thanks @laszlokorte – yeah, in the future we'll have these major updates on feature branches instead of `development`. Right now we have about 8 sprints getting wrapped up on dev and are waiting to merge them with `master` (in a few weeks). 

Dead code removal, performance/optimizations, UI/UX, SDK/API, example code, docs, vestigial schema names/columns, etc... are what we're focusing on now. We want to get everything cleaned up and working perfectly before introducing too many new features – through we do have some great new ones coming out such as multi-lingual support and more SQL DB type support.

Definitely submit any issues you see (master or dev) – and our Docs are in a repo too so feel free to submit PRs for that if you have time/interest. As you can imagine, this is a lot of work for such a small team – so any help from you or other devs is **greatly** appreciated.

I've sent you an invite to our Slack team in case you want to chat about anything more easily. We're working to make more things public (voting on feature requests, upcoming versions/sprints, roadmap, etc)... but until we have a good process for all that on GitHub Slack is good for getting more info.

**Comment by WellingGuzman** [comment]
hey @laszlokorte I think the issue here may be the composer/vendor packages.

Try this:

1. Remove the vendor directory (`api/vendor`)
2. Update the `development` branch with the latest (at least https://github.com/directus/directus/commit/bee32e3a3d9a31d233bfb37f856252a3c5d2cf23 when I pushed an update `composer.lock` file)
3. run `composer install` again

This step should fix this issue.

There's an old migrations package version that was causing troubles with permissions.

Let us know if it that fixed it for you.

**Comment by WellingGuzman** [comment]
I'm closing this. unless @laszlokorte reports that the previous comment didn't fix it for him.
