### ISSUE TITLE
Creating corresponding relational field for file fields breaks file feature

### ISSUE THREAD

**Issue by emrahnazif** [directus/directus#11719]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Relational fields fails if corresponded field created

https://user-images.githubusercontent.com/33692017/154761666-b2fb91de-fce8-44b2-b253-838e82f41591.mp4

Bug exist old versions of directus as well. 

Ubuntu 18 / PostgreSQL 12 / 9.5.2 and some older version of directus 
macos monterey / mysql 5.7 / 9.5.2 and some older version of directus 
macos monterey / mysql 8 / 9.5.2 and some older version of directus 

Error exist all above configurations.

Video shows a clean install directus v9.5.2 on ubuntu 18.04, nodejs 14, PostgreSQL 12

### To Reproduce

Clean install directus.
Create a new collection.
create a new field in the collection with relation (for example single file)
check create corresponding field.

Try to create an item in the newly created collection. 

### Errors Shown

Video display the error.
Even though in the error it says "directus_files.test does not exist".
It is in fact exist. 

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

14

### What database are you using?

PostgreSQL 12

### What browser are you using?

chrome

### What operating system are you using?

ubuntu 18.04

### How are you deploying Directus?

CLI

**Comment by licitdev** [comment]
This issue only affects the relational file fields.
 
With the automatically created alias field in `directus_files`, the API results in an error 500 with the column not found error, leading to inability to view files. Hence, impacting file uploads as well.

![Screenshot 2022-02-20 at 11 18 19 PM](https://user-images.githubusercontent.com/26413686/154849941-1e5fd1c6-f68c-41c1-91cf-ba2d86e82c8f.png)

**Comment by kuuroo3** [comment]
Still happens in 9.7.1
OS: Windows
Browser: Vivaldi
Deploying via Docker
Also using Postgres

I experienced the same with the files field. Uploading or viewing already existing files is no longer possible once the corresponding field was added to the files collection.

Got these errors:
### Uploading:
![image](https://user-images.githubusercontent.com/43739995/160067752-1a86cd0d-2ac7-4353-bf89-0865237d8517.png)
**In browser console:**
`{"errors":[{"message":"select \"directus_files\".\"id\", \"directus_files\".\"storage\", \"directus_files\".\"filename_disk\", \"directus_files\".\"filename_download\", \"directus_files\".\"title\", \"directus_files\".\"type\", \"directus_files\".\"folder\", \"directus_files\".\"uploaded_by\", \"directus_files\".\"uploaded_on\", \"directus_files\".\"modified_by\", \"directus_files\".\"modified_on\", \"directus_files\".\"charset\", \"directus_files\".\"filesize\", \"directus_files\".\"width\", \"directus_files\".\"height\", \"directus_files\".\"duration\", \"directus_files\".\"embed\", \"directus_files\".\"description\", \"directus_files\".\"location\", \"directus_files\".\"tags\", \"directus_files\".\"metadata\", \"directus_files\".\"applications\" from \"directus_files\" where \"directus_files\".\"id\" = $1 order by \"directus_files\".\"id\" asc limit $2 - column directus_files.applications does not exist","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`
**In docker console:**
`06:41:28 🚨 error select "directus_files"."id", "directus_files"."storage", "directus_files"."filename_disk", "directus_files"."filename_download", "directus_files"."title", "directus_files"."type", "directus_files"."folder", "directus_files"."uploaded_by", "directus_files"."uploaded_on", "directus_files"."modified_by", "directus_files"."modified_on", "directus_files"."charset", "directus_files"."filesize", "directus_files"."width", "directus_files"."height", "directus_files"."duration", "directus_files"."embed", "directus_files"."description", "directus_files"."location", "directus_files"."tags", "directus_files"."metadata", "directus_files"."applications" from "directus_files" where "directus_files"."id" = $1 order by "directus_files"."id" asc limit $2 - column directus_files.applications does not exist 
error: select "directus_files"."id", "directus_files"."storage", "directus_files"."filename_disk", "directus_files"."filename_download", "directus_files"."title", "directus_files"."type", "directus_files"."folder", "directus_files"."uploaded_by", "directus_files"."uploaded_on", "directus_files"."modified_by", "directus_files"."modified_on", "directus_files"."charset", "directus_files"."filesize", "directus_files"."width", "directus_files"."height", "directus_files"."duration", "directus_files"."embed", "directus_files"."description", "directus_files"."location", "directus_files"."tags", "directus_files"."metadata", "directus_files"."applications" from "directus_files" where "directus_files"."id" = $1 order by "directus_files"."id" asc limit $2 - column directus_files.applications does not exist
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

### Trying to view:
Since I already have files uploaded I can still see them, but once I want to open a single file the page just shows this:
![image](https://user-images.githubusercontent.com/43739995/160067932-e4c876da-8874-4781-8248-060e72b08752.png)
**In browser console:**
`{"errors":[{"message":"select \"directus_files\".\"id\", \"directus_files\".\"storage\", \"directus_files\".\"filename_disk\", \"directus_files\".\"filename_download\", \"directus_files\".\"title\", \"directus_files\".\"type\", \"directus_files\".\"folder\", \"directus_files\".\"uploaded_by\", \"directus_files\".\"uploaded_on\", \"directus_files\".\"modified_by\", \"directus_files\".\"modified_on\", \"directus_files\".\"charset\", \"directus_files\".\"filesize\", \"directus_files\".\"width\", \"directus_files\".\"height\", \"directus_files\".\"duration\", \"directus_files\".\"embed\", \"directus_files\".\"description\", \"directus_files\".\"location\", \"directus_files\".\"tags\", \"directus_files\".\"metadata\", \"directus_files\".\"applications\" from \"directus_files\" where \"directus_files\".\"id\" = $1 order by \"directus_files\".\"id\" asc limit $2 - column directus_files.applications does not exist","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`
**In Docker console:**
`06:40:28 🚨 error select "directus_files"."id", "directus_files"."storage", "directus_files"."filename_disk", "directus_files"."filename_download", "directus_files"."title", "directus_files"."type", "directus_files"."folder", "directus_files"."uploaded_by", "directus_files"."uploaded_on", "directus_files"."modified_by", "directus_files"."modified_on", "directus_files"."charset", "directus_files"."filesize", "directus_files"."width", "directus_files"."height", "directus_files"."duration", "directus_files"."embed", "directus_files"."description", "directus_files"."location", "directus_files"."tags", "directus_files"."metadata", "directus_files"."applications" from "directus_files" where "directus_files"."id" = $1 order by "directus_files"."id" asc limit $2 - column directus_files.applications does not exist 
error: select "directus_files"."id", "directus_files"."storage", "directus_files"."filename_disk", "directus_files"."filename_download", "directus_files"."title", "directus_files"."type", "directus_files"."folder", "directus_files"."uploaded_by", "directus_files"."uploaded_on", "directus_files"."modified_by", "directus_files"."modified_on", "directus_files"."charset", "directus_files"."filesize", "directus_files"."width", "directus_files"."height", "directus_files"."duration", "directus_files"."embed", "directus_files"."description", "directus_files"."location", "directus_files"."tags", "directus_files"."metadata", "directus_files"."applications" from "directus_files" where "directus_files"."id" = $1 order by "directus_files"."id" asc limit $2 - column directus_files.applications does not exist
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`
