### ISSUE TITLE
Sorting doesn't work on a field that is relational

### ISSUE THREAD

**Issue by alan-cleveston** [directus/directus#11743]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to sort a field that has a relationship, the sorting does not work, if the field is an input it works normally.

### To Reproduce

To reproduce the error just use a relational field in a content and try to sort

https://user-images.githubusercontent.com/82655156/154826431-8bd9ba2f-5e66-4315-b8ab-973580fa4a6d.mp4

![image](https://user-images.githubusercontent.com/82655156/154826502-94e7e411-aec0-4bfa-83dd-12f246141db9.png)

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13.4

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment]
The API correctly returns the sorted values of an M2O but the app overrides it.

https://user-images.githubusercontent.com/26413686/154886010-95119156-43f9-48da-9332-6aae50ee2d78.mov

**Comment by licitdev** [comment]
This issue ended up being more complex through testing as the sorting needs to be done on the rendered values. It affects displays such as `related-values`, `translations` and other custom displays for the following types: `['m2m', 'm2o', 'o2m', 'translations', 'm2a', 'file', 'files']`.

@rijkvanzanten Should sorting be disabled for the above listed types?

**Comment by rijkvanzanten** [comment]
@licitdev There is no way to sort on a o2m, as there is no value to sort on. M2O's are currently sorted on the actual saved value, which might be different from the displayed value.

The improvement here is to implement/finish https://github.com/directus/directus/discussions/4502, and then dynamically use that when sort is being used on a column that's relational and has a related-values display 👍🏻 

I'll close this for now in favor of https://github.com/directus/directus/discussions/4502, as it's a new feature request that already exists, rather than a bug
