### ISSUE TITLE
Public URL error

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#11800]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I set the `PUBLIC_URL` env to toe FQDN the app URL contains the URL twice

Example: `PUBLIC_URL="/"`
* App loads correctly on `example.com/admin`
* Reset-Password link does not contain a correct link (as expected)

Example: `PUBLIC_URL="https://example.com/"`
* App file path contains the url twice
* Example: `https://example.com/%22https:/example.com/%22%20%20/assets/vendor.62e5a05d.js`

### To Reproduce

Clean installation of Directus in Plesk, set env

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

MacOs

### How are you deploying Directus?

Plesk

**Comment by azrikahar** [comment]
Granted I could only test this on a VPS with Directus `v9.5.2`, seems to work on my end:

### Public URL set in env

![WindowsTerminal_NM5bialmZD](https://user-images.githubusercontent.com/42867097/155261667-fa091445-88b7-43fa-9b67-a2ada917504e.png)

### App file viewed in browser

![chrome_5wRNf8MxyB](https://user-images.githubusercontent.com/42867097/155261606-d6d31d37-d4a6-4248-b48c-9d74dfa70f65.png)

Can you verify there are no reverse proxy at play here which may rewrite the url?

**Comment by Dominic-Marcelino** [comment]
@azrikahar Found out that the error was produced by a comment in the same line as the variable:
`PUBLIC_URL="https://example.com/"  #TODO: set final URL`
After removing the comment everything works as expected

Btw: Is it recommended to put the env-variables in quotation marks or without?

**Comment by azrikahar** [comment]
> Found out that the error was produced by a comment in the same line as the variable

ohh that makes sense. THis is also why [the example.env file](https://github.com/directus/directus/blob/main/api/example.env) doesn't do inline comments as well. This is technically a "limitation" with dotenv rather than Directus though.

> Btw: Is it recommended to put the env-variables in quotation marks or without?

It can be hard to give a recommendation since different environments/setups parse/escape env variables slightly differently[^1], but quotation marks should be fine since [we do type cast the env variables](https://docs.directus.io/configuration/config-options/#type-casting-and-nesting) automatically. If you ever need to specify what the type is, you can also do it via [Environment Syntax Prefix](https://docs.directus.io/configuration/config-options/#environment-syntax-prefix).

I'll proceed to close this issue since it's not an inherent bug with Directus 👍

[^1]: I believe `docker-compose` and newer `docker compose` behaves differently from what I've briefly seen others mentioning (and a friend of mine quite recently), but I can't confirm it myself

**Comment by Dominic-Marcelino** [comment]
@azrikahar Thank's for the support & information! :)
