### ISSUE TITLE
Can't set default value for fields

### ISSUE THREAD

**Issue by rashidpathiyil** [directus/directus#11832]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Can't update default value for fields on a fresh 9.5.2 Directus with Cockroach DB.

### To Reproduce

https://user-images.githubusercontent.com/15140041/155476399-0048370f-0a0e-4ab2-8757-debda6b74c2d.mp4

### Errors Shown

![image](https://user-images.githubusercontent.com/15140041/155476572-dee230d6-2e6c-4bec-8108-f34aa013a3e7.png)

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

cockroachdb

### What browser are you using?

Edge

### What operating system are you using?

Windows 11

### How are you deploying Directus?

PaaS

**Comment by drnachio** [comment]
I'm having the same problem on Ubuntu

**Comment by licitdev** [comment]
I believe this has been be resolved since [v9.10.0](https://github.com/directus/directus/releases/tag/v9.10.0) through the update of Knex to `2.0.0` in https://github.com/directus/directus/pull/13051.

Knex [1.0.0](https://github.com/knex/knex/releases/tag/1.0.0) includes a workaround to enable the experimental use of alter column in https://github.com/knex/knex/pull/4874.

For more details on the experimental alter column, please refer to the PR in CockroachDB https://github.com/cockroachdb/cockroach/issues/49329.
