### ISSUE TITLE
MTO Typeahead settings not clear

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1189]
## Version Info
  - Directus version: bf52351

## Expected Behavior

It's not quite clear what the "Template" setting and the "Include inactive" settings for the Typeahead UI are supposed todo.

First I thought the template is for formatting the autocomplete dropdown of the input field but that's not the case. The autocomplete field just contains all "Visible Column"s concatenated.

As you can see in the screenshot the "Large" size option does not apply (?)

The "Include inactive" is probably for showing "Draw" items. But it's confusing that it's inconsistent with the "Visible Status IDs" settings of the simple MTO ui.

## Logs or Screenshots

![bildschirmfoto 2016-06-19 um 15 21 55](https://cloud.githubusercontent.com/assets/26493/16177562/ce82d584-3631-11e6-9d24-388d516cc69f.png)

![bildschirmfoto 2016-06-19 um 15 23 28](https://cloud.githubusercontent.com/assets/26493/16177563/cff4bf54-3631-11e6-8c36-f0f24c9ba877.png)

**Comment by laszlokorte** [comment]
You can also see on the screenshot above that the text of the input field is misaligned.

**Comment by benhaynes** [comment]
Hey @laszlokorte – here is what we're updated:

* We updated the notes for each field to be more specific.
* Small, Medium, Large adjusts the size of the input field and the dropdown width is auto.
* TODO: `Include Inactive` is going to be `visible_status_ids` (same as M2O proper) ... @WellingGuzman  is working on making this a set of checkboxes instead of a text input to reduce mistakes.
* The entire UI has been updated to resolve inconsistencies with styling

Let us know if you see any other issues with this UI – thanks for reporting on this!

**Comment by benhaynes** [comment]
Also, this is on the `development` branch still, not merged into `master` or `build` yet

**Comment by WellingGuzman** [comment]
> TODO: Include Inactive is going to be visible_status_ids (same as M2O proper) ... @WellingGuzman is working on making this a set of checkboxes instead of a text input to reduce mistakes.

This will be done in a new UI or Options right now will be done in a Text Input, so this can be closed, and focus on the Checkboxes in a new ticket. @laszlokorte @benhaynes agree?

**Comment by benhaynes** [comment]
Yeah, we can improve that UI option later... At least it's the same option interface now.

**Comment by benhaynes** [comment]
This is all working now... thanks @WellingGuzman!
