### ISSUE TITLE
Filters: Why does Input value sometimes default to true on string types?

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#11919]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When filtering radio buttons, if you set the operator to no-value-required operator like null, is not null, empty, is not empty, etc. then switch back to an operator that takes a value, it automatically sets the input value to `true`, however radio buttons appear to be stored as String type, not Boolean. This happens on the other string type Fields I have tested so far.

This seemed like a weird behavior so I'm adding it into bugs... but there are no console errors, so maybe it is just a silly question! 😄 

Why start with `--` as default Filter Value then switch to `true` even in cases where it seems like `true` can't even be filtered for?

### To Reproduce

https://user-images.githubusercontent.com/62306630/156444980-d4db7997-0ffd-4165-a570-14c50e83785f.mov

### Errors Shown

no.

### What version of Directus are you using?

9.5

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

safari

### What operating system are you using?

Mac

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
Agree that this is a point for UX improvement 👍

---

### Notes on what's happening here

When we switch to null/nnull/empty/nempty, the value is set to `true`:

https://github.com/directus/directus/blob/962af79dbcd773e4c00c2c6cd0b89a14155320b5/app/src/interfaces/_system/system-filter/nodes.vue#L264-L269

But since contains/ncontains etc doesn't have a switch case, it defaulted to using the original `value` which is `true` but casted into a string:

https://github.com/directus/directus/blob/962af79dbcd773e4c00c2c6cd0b89a14155320b5/app/src/interfaces/_system/system-filter/nodes.vue#L280-L282

**Comment by erondpowell** [comment]
Cool. Thanks!

**Comment by erondpowell** [comment]
> @erondpowell We'll leave this open as an improvement. We should clear the value when you switch operators to/from a type that's incompatible with that value 👍🏻

Got ya, jumped straight from email and didn't read Azzy's first line 👍
