### ISSUE TITLE
permission issues

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1192]
## Version Info
  - Directus version: bf5235156

**First:** when editing fields permissions it's not obvious when the changes are saved. When clicking on the "Edit field level permissions" button of a table and then clicking on another link (eg a table in the sidebar) you get a warning that the changes may get lost. (Even if you did not change anything)

The correct way to confirm all changes seems to be to click on the "back" arrow. But that's inconsistent with editing a record in a MTM field where the "back" arrow cancels the changes.

**Second:** revoking permissions for viewing or editing a required field is behaving weirdly. I will try this in more detail later but for now I noticed:

- Remove the write access of a required field but keep the read access:
when editing an existing record which has the field already set can not be saved because "error: field is required"

- Remove both read and write access: Now the record can be saved without the user seeing the field at all

- Give back read access but not write access: Now the field can even be edited even though the user should not have access to do so

**Comment by laszlokorte** [comment]
The "Draft only" status filter for tables when editing a permission group is confusing because the "draft" concept makes no sense for tables

**Comment by benhaynes** [comment]
@WellingGuzman Do you think we should have the Permissions update with a "Save" button instead of asynchronously saving? Is that a lot of work? It is currently inconsistent, but I don't think this is a priority.

@jel-massih did you work on the "Saving for specific statuses" (the dropdown at the top-right of the permissions page)? I want to make sure that's all working as expected.

@laszlokorte – Saving group permissions for table items of a specific "status" doesn't make sense? The thinking here is to allow for _workflows_...

eg: Intern Group can *edit* Draft items, but can only *view* Live items


Other notes:
> Remove the write access of a required field but keep the read access:
when editing an existing record which has the field already set can not be saved because "error: field is required"
This is logical, but we should probably not force the requirement if you can't edit it.

> Remove both read and write access: Now the record can be saved without the user seeing the field at all
This makes sense.

> Give back read access but not write access: Now the field can even be edited even though the user should not have access to do so
This is not good and needs to be fixed asap. Perhaps the permission value is being NULL'd somehow? @WellingGuzman can we look at this?

**Comment by WellingGuzman** [comment]
> > Remove the write access of a required field but keep the read access:
when editing an existing record which has the field already set can not be saved because "error: field is required"

> This is logical, but we should probably not force the requirement if you can't edit it.

I can't replicate this one, but maybe it was fixed along some fixes that was done today. did you get that error?

> > Give back read access but not write access: Now the field can even be edited even though the user should not have access to do so

> This is not good and needs to be fixed asap. Perhaps the permission value is being NULL'd somehow? @WellingGuzman can we look at this?

So, the catch here was that only blacklisted fields were enforce when the user do not have "big" edit permission. I'm working on it to be enforce no matter what.

> >Remove both read and write access: Now the record can be saved without the user seeing the field at all

> This makes sense.

Hmmm, what can be done here? it's what it should be expected, but what happen when the only field doesn't have read/write access? the problem is how it looks like an empty page that can lead to think it's hung.

**Comment by WellingGuzman** [comment]
Field permissions are saved when you click the switches, I made a fix to not ask _if you don't want to lose any data_.

**Comment by benhaynes** [comment]
@WellingGuzman – Did you turn off that message globally or only for this page?

**Comment by benhaynes** [comment]
@WellingGuzman I'm not getting this "are you sure you want to leave" message any more... can you confirm it's still in there?

**Comment by benhaynes** [comment]
1. Read and no write = working now, no issues with required fields
2. No read and no write = Still works as expected, but: You have to refresh the page after changing the permission when adjusting. I don't see this as an issue though since only admins can adjust permissions, and they wouldn't be adjusting for themselves. If they do, they don't even have access to the fields in Settings and need to reset in the DB. (I still think the admin group should ALWAYS see ALL fields/tables in the system, regardless of permissions).
3. I am not getting this. The only way to see the change in permissions (that I can find) is for the user affected to refresh the page... which fetches everything correctly.

@laszlokorte – if you have more insight into what you were experiencing we can re-open and discuss... but as of now this seems to be working correctly.

**Comment by WellingGuzman** [comment]
> @WellingGuzman – Did you turn off that message globally or only for this page?

I turned off for model that didn't actually have unchanged attributes. (Still a work in progress)

> @WellingGuzman I'm not getting this "are you sure you want to leave" message any more... can you confirm it's still in there?

It's not happening anymore as it's being saved after you click the switch.
