### ISSUE TITLE
CLI Schema import causes crash.

### ISSUE THREAD

**Issue by stefan1968** [directus/directus#12042]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm attempting to apply a schema to another clean instance of Directus, but it's throwing an error and crashing.

Screenshot attached.

### To Reproduce

Export a schema with a date/timestamp?

### Errors Shown

<img width="948" alt="Screenshot 2022-03-08 at 23 02 08" src="https://user-images.githubusercontent.com/5500038/157340512-cea59fe4-fd8a-44f5-bea8-2d7eb35d7d5d.png">

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Docker 

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
@stefan1968 Did the instance where you created the snapshot use the same database? (Postgres 13)

**Comment by stefan1968** [comment]
Yes, exactly the same. The only difference, the schema was  exported from a directus version 9.5.1 instance and attempted to import from a 9.6.0, the postgres versions are identical however. I can supply the schema if it helps?

**Comment by azrikahar** [comment]
A schema will be helpful indeed! Just so we can be on the same page when reproducing it 👍

With that said, I also just noticed and suspect that the quotation marks around `CURRENT_TIMESTAMP` is the culprit here. Just to sure, is the default value created directly in the database and not via the app? (I believe the app dictates "use current date/time" with a special value 'date-created' rather than the db function CURRENT_TIMESTAMP by default)

## Testing with SQL queries

### With quotes

![chrome_5xeRFHcqKW](https://user-images.githubusercontent.com/42867097/157393568-a8424d25-745c-4f8e-980c-765750c327ac.png)

### No quotes

![chrome_6Y1ooY5SvL](https://user-images.githubusercontent.com/42867097/157393588-688d3fd2-b234-48c8-ab44-7c118e8236af.png)

**Comment by stefan1968** [comment]
It's created via the APP/UI, when setting the default value. I use the expression now() when creating the field. Which then turns into CURRENT_TIMESTAMP 

Here is a link to the schema.

[https://drive.google.com/drive/folders/1qw_iPfCBhfm9JVvfUxYgmUtxf0TFo8xJ?usp=sharing](url)

**Comment by azrikahar** [comment]
Thanks for the snapshot and clarification. I've just tried it locally and I can reproduce the same issue:

![WindowsTerminal_1TGAp3SWvp](https://user-images.githubusercontent.com/42867097/158933626-6b272b1b-e3ed-432a-8dd5-d2084d3291a7.png)

This is because of the default value `CURRENT_TIMESTAMP` is being set as string as expected:

![Code_kizIs8pHP0](https://user-images.githubusercontent.com/42867097/158933902-28f1483f-61c1-42a3-a365-6ea08f50d3a2.png)

However, I did try to trace and see what's going wrong here and I've found this particular code where we are ensuring `now()` gets interpreted correctly:

https://github.com/directus/directus/blob/2419c2bbbf5d90ab88fb1ec622df88c08f3a84df/api/src/services/fields.ts#L541-L544

Using this knowledge, I was able to make your schema snapshot work by swapping `CURRENT_TIMESTAMP` to `now()` manually:

![WindowsTerminal_iS6EAUGvnG](https://user-images.githubusercontent.com/42867097/158933810-df8943d3-d2a6-4fb0-9da0-4e5462fbfae8.png)

So perhaps you can use this workaround for now while we find a better fix for it 👍
