### ISSUE TITLE
Two translation fields

### ISSUE THREAD

**Issue by adrianozappacosta** [directus/directus#1215]
## Version Info
  - Directus version: (Or commit hash)
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Expected Behavior
I added two translation fields on one table, as I do have the translated content distributed on two related tables. I expect to have one translation section in the backend that contains all fields of the two related tables or at least two translation sections containing the fields of the related table.

## Actual Behavior
The actual behavior shows just one translation section containing the fields of the related table, the second translation field isn't shown, however just the label ("teasers") of the second translation field is shown (see printscreen).

## Steps to Reproduce
 1. add two translation fields to two different related content tables
2. the related db-schema is attached.
[directus_2016-07-21.sql.zip](https://github.com/directus/directus/files/376159/directus_2016-07-21.sql.zip)

## Logs or Screenshots
![image](https://cloud.githubusercontent.com/assets/6317308/17025274/72969e52-4f5b-11e6-89d7-a644d3cb794f.png)

**Comment by benhaynes** [comment]
We've never thought about having two translation columns (for different related tables). We designed the UI to store all the data in a single table. That said, I don't know why there would be an issue with this... my guess is:

The Edit Page has some hardcoded Translation UI logic that is causing this. I believe that all translations are coded to show up at the end of the edit page... so the logic probably stops after it finds the first one.

Hopefully this is an easy adjustment, otherwise we'll need to move this into a later version (`6.5`) or FeatHub.

**Comment by benhaynes** [comment]
This UI is working really well now (two translation fields also work), thanks @WellingGuzman
