### ISSUE TITLE
Cross-Origin Request Blocked with CSV value in CORS_ORIGIN setting

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#12259]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since `9.7.0` CORS has been disabled by default, I need it though so I thought might as well re-enable it but this time restrict to only specific domains. The documentation says using a CSV of domains is permitted: https://docs.directus.io/configuration/config-options/#cors

Turns out it doesn't work, because it just sets the cors origin header to the CSV value instead of matching domains and then only setting the matched domain as the origin value. The CORS origin header can only contain one domain and it needs to be the same one as the one you are on, otherwise CORS requests are invalid. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

> `<origin>` Specifies an origin. Only a single origin can be specified. If the server supports clients from multiple origins, it must return the origin for the specific client making the request.

### To Reproduce

Set `CORS_ORIGIN` in `.env` file to a CSV of domains.

### Errors Shown

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.gastrodino.de/api/items/products (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match **‘http://localhost:4200,https://www.gastrodino.com’**

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

MariaDB 10.3.34

### What browser are you using?

Chrome Latest

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Ubuntu Server 20.04, npm installation with a systemd service running it

**Comment by riscie** [comment]
I am experiencing the same issue.

**Comment by jeremybradbury** [comment]
I can confirm CORS is broken in 9.7.0.

The issue I had: "method not allowed" on the preflight OPTIONS call for any post.

The Allow header only contains GET, POST.... 

So in this state CORS will never work for posts since OPTIONS are always sent prior when CORS is enabled.

**Comment by azrikahar** [comment]
@jeremybradbury I believe your issue is slightly different as in it should be technically `CORS_METHODS` in this case. Can you try setting `CORS_METHODS=GET,POST,PATCH,DELETE,OPTIONS` ([reference in docs](https://docs.directus.io/configuration/config-options/#cors)) to see does that solve your issue?

**Comment by jeremybradbury** [comment]
Yes you're right, i re-read the issue above. However, I can also confirm the docs suggest settings that no modern browser will respect.

I already had this in my config when I did the upgrade:  `CORS_METHODS=OPTIONS,POST`

Which is ideal for GraphQL only implementation and removing GET from the picture. the rest are, well for REST but missing PUT and some others if the standard is actually followed (and it rarely is).

The Allow header is new and doesn't show on earlier versions when the setting is omitted.

Allow still shows GET, POST even after adding DELETE, GET & PATCH to POST & OPTIONS.

Perhaps I should make a new issue?

**Comment by azrikahar** [comment]
@jeremybradbury although docs suggests comma separated list, it is _supposedly_ turn it into an array and pass it to the [cors](https://expressjs.com/en/resources/middleware/cors.html) middleware here:

https://github.com/directus/directus/blob/3d795236da51f642ddf2883f13286ddaa0ec534c/api/src/middleware/cors.ts#L9

but it is indeed currently not working as intended. The PR #12265 linked above aims to address this, which should then work like the dynamic headers you described!

As for the `Access-Control-Allow-Methods`, we are also passing it as-is to the cors middleware here:

https://github.com/directus/directus/blob/3d795236da51f642ddf2883f13286ddaa0ec534c/api/src/middleware/cors.ts#L10

and the Express docs for [cors configuration](https://expressjs.com/en/resources/middleware/cors.html#configuration-options) does say they can accept comma-delimited string. I also did a test and it seems to work:

![chrome_5pgUxFIitx](https://user-images.githubusercontent.com/42867097/159618972-d61370c9-957f-40bc-987e-64368981a748.png)

Perhaps you can try the following (which was another test I conducted):

- Navigate to https://hoppscotch.io
- Go to Settings tab: https://hoppscotch.io/settings
- Turn on "Use the proxy middleware to send requests"
- Go to REST tab: https://hoppscotch.io
- Set the method as `OPTIONS`, and url as the base url of your staging instance (eg. `https://directus.example.com`), hit Send
- You should receive status 204 no content, but you can click on the Headers tab and see whether the allow methods header is shown with what you had configured, such as:

   (here I set it as `CORS_METHODS=OPTIONS,POST` like your staging server)
   
   ![chrome_qbkXlGUvE6](https://user-images.githubusercontent.com/42867097/159620783-af9258ff-5c73-4c8a-a3d7-2fa677a76864.png)

If the issue still persists for you, then you can make a new issue with info on your setup so that we may investigate further 👍

**Comment by rijkvanzanten** [comment]
> Turns out it doesn't work, because it just sets the cors origin header to the CSV value instead of matching domains and then only setting the matched domain as the origin value. 

This turned out to be a bug in the .env parsing of CSV like values. If you tell it explicitly to use the value as an array, everything still works as expected:

```
CORS_ORIGIN="array:http://localhost:4200,https://www.gastrodino.com"
```

**Comment by jeremybradbury** [comment]
yeah here's what I get in 9.7.0

`Allow: GET, POST`

downgrade to 9.6 and reboot with no config changes:

`Access-Control-Allow-Methods: POST,OPTIONS`

Here I specified them in the config.

But again in 9.6 only, when I remove the setting, it removes the header allowing all http request verbs.

Again the `Allow` header doesn't show outside of 9.7 and in 9.7 the other headers like `Access-Control-Allow-Methods` are missing because it only sends a 405 about the OPTIONS call.

For now I will continue using 9.6 until this can be resolved. 

If you want to make a new issue or wait until others do, just mention me, I'll be happy to help as much as I can.

**Comment by jeremybradbury** [comment]
@rijkvanzanten this is still broken likely related to env parsing issues 

https://github.com/directus/directus/issues/12365

https://github.com/directus/directus/issues/12403

**Comment by holyris** [comment]
@jeremybradbury Did you find a solution ? It's still happening to me with directus 9.13

**Comment by iamsellek** [comment]
This seems to have maybe broken again since March? If I try to use CSV list of domains, whether it's prepended by `array:` or not, there is no CORS Origins allowed at all in the responses coming from my Directus server.

**Comment by n0script22** [comment]
https://github.com/n0script22/directus/commit/27590add31ec6b6789df89b5161d405bd71964aa works out for me. make sure to enable cors in .env and set origin like:

```
CORS_ENABLED="true"
CORS_ORIGIN="http://localhost:3000,http://localhost:3001"
```
