### ISSUE TITLE
numeric allow null list view

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#1226]
If a numeric column is allowed to be null and a record is created with no value entered for that column the in the list view the value `0` gets displayed.

I would expect the column in the list view to be empty if the record has no value at all.

**Comment by WellingGuzman** [comment]
Good point, thanks.

**Comment by benhaynes** [comment]
@WellingGuzman Does this take `allow null` into consideration?

If the INT has `allow_null = false` and we set it to `NULL`, will it convert to `0` or throw an error?

**Comment by WellingGuzman** [comment]
@benhaynes it will throw an error if you do it through the API, but the UI will enforce validation.

So this got me thinking we need an output and input formatting, because if we want to avoid the issue we will have to convert it to 0, but that wouldn't work for an API response, because the actual value is `null`. makes sense?

**Comment by benhaynes** [comment]
Hmm, I think it's OK for the API to throw an error if you send `NULL` to an INT column that doesn't support NULL. But it needs to respond with an error that makes sense:

`The column "xxxxx" does not support the value "NULL"`

**Comment by WellingGuzman** [comment]
You are right, we talked about making the "Internals error" friendly. so I will think about this when we are organizing the API (#1105). what do you think?

**Comment by benhaynes** [comment]
Perfect... I added a note to that other ticket.
