### ISSUE TITLE
Improve O2M rendering on tabular layout

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#12271]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The new Table Layout improvements we've got in the release of 9.7.0 are great ✨ One of the new features is the possibility to add relational values as table columns - a highly anticipated improvement of the Table Layout! This particular feature is especially necessary for adding translated fields. Me myself often got a lot of translated fields in my collections. If there is a title field, or something alike, you've probably need to have it translatable in a multi lang setup - and that title you most likely want to have in the table layout.

However the output of the relational (translated) fields isn't working that well. You'll end up with a concatenated string including ALL of the languages... You should only get the current user language in my opinion. 

Example below.

### To Reproduce

Basic setup with a Pages collections and a Page Translations collection:

<img width="766" alt="1" src="https://user-images.githubusercontent.com/20950568/159240799-64ec7c12-2526-4461-a57c-38792fa0f527.png">
<img width="868" alt="2" src="https://user-images.githubusercontent.com/20950568/159240803-0fd1b365-3fdd-461e-b287-d11c4fd02d97.png">
<img width="1063" alt="3" src="https://user-images.githubusercontent.com/20950568/159240806-d7e3edcb-94d3-450e-8daf-abdd2164b7de.png">
<img width="864" alt="4" src="https://user-images.githubusercontent.com/20950568/159240809-016cbe56-5b10-4319-b480-b170d6d37294.png">
<img width="535" alt="5" src="https://user-images.githubusercontent.com/20950568/159240811-44e86d7c-0498-44f6-abe2-17ef026ce012.png">

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16 / 17

### What database are you using?

PG 12-14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally / NPM

**Comment by rijkvanzanten** [comment]
This is a very interesting point. Technically speaking, the relational path to the translations results in an array of titles, rather than a single value (which is also what's currently displayed). However, for translations specifically, you're looking to then only show one of those, which is translated into your own language. That can be done by using the translations display on the main translations field (so rather than using `translations->title`, you'd show `translations` with that display configured). 

I'll leave this issue open as I think the bug here is that O2M values should be treated rendered as a "preview list" style (where it maybe shows the first X, and then renders the rest in a popover).

**Comment by danieljwestman** [comment]
@rijkvanzanten 

Yes, this should be handled the same way as the Tranlations display (rendered as a "popover list"). 

If we are using the main translation field, as you suggest, we are limited to add only one field column in the table. And also, the column header will be "Translations..." and not the specific field name which isn't what we want...

**Comment by rijkvanzanten** [comment]
Ahh gotcha, yeah that's a good one. Didn't think about that restriction 👍🏻

**Comment by wc-matteo** [comment]
yep, same issues here with translations.

I think it would be great to have a generic filtering capability on relational items in the table layout (at the preset level) plus have a global setting (or per collection, I'm not sure), where you can specify how (and if) you want translations fields to be displayed:
- show all translations (like it is now)
- show specific language/s
- show current user language
and this way you configure it once and it works everywhere a translation relation is in a `display`

**Comment by danieljwestman** [comment]
Would be awesome if this new "nested relational fields to the parent table" where treating translations the same way as the main translation field display: show one language in the table column and a provide the "popover list" with all languages 🙏🏼

Copy-paste translations display? 😬

**Comment by rijkvanzanten** [comment]
We'll have to think through how that configuration would look like 🤔 

Right now, you could have another display for the "title" field in your translations for example (maybe to make it Serif, or do some other logic. You could even have an "image" field+display in your translations that you wanna render inline). I don't think we'd want to just force-override the actual display used. This might have to be some core magic in the table layout itself to render the `translations->title` field using the display from `translations->title`, but then still render it as the popover list style because we know it's a list of values (as it's a o2m relationship) 

The only question then becomes: where/how do you configure the parameters for that list style display on the table layout. For translations, you might want to set what language to use (if not your own) or what language to default too. For other "regular" o2m lists, you might want to control how many items to preview inline (short tags vs long sentences), and which one to preview first (nested sort/filters f.e.) 🤔

**Comment by rijkvanzanten** [comment]
Linear: [ENG-266](https://linear.app/directus/issue/ENG-266/improve-o2m-rendering-on-tabular-layout)

**Comment by dammafra** [comment]
Hello @azrikahar, can we add this fix in the Next Release?
