### ISSUE TITLE
Files don't get deleted

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#12350]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a collection which contains a files field.
![image](https://user-images.githubusercontent.com/43739995/159885257-4436887e-1748-42a5-96e4-4d384a051066.png)
The junction collection fields are also set to "delete cascade".

But when I delete an item only the junction element gets deleted. The files still exist.
I expected the files to be deleted too.

### To Reproduce

1. Create a collection with a files field, set all relationship options to "delete (cascade)"
2. Create an item
3. Delete that item
4. Check Files

### Errors Shown

None

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

inside Docker: 16.14.2

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by Pachat** [comment]
May be related:
When deleting a Parent collection and its' M2M related collection, the junction table is not deleted.

**Comment by rijkvanzanten** [comment]
> But when I delete an item only the junction element gets deleted. The files still exist.
> I expected the files to be deleted too.

In the configuration you shared, the cascade is configured to delete the junction row whenever the parent `applications` or `directus_files` item is deleted. There's currently no way to configure Directus to auto-delete related items when the item that holds the m2o is deleted[^1] 👍🏻 

[^1]: Because that's not how database cascades work. If you delete the related item, the primary key disappears, and the current item has to be updated to resolve for that. This is either done by preventing the original deletion, setting the value to `null`, or deleting the whole row. However, when you delete the current item, the related item isn't affected in any way, as there's no relationship from the related item to the current item and therefore no relational constraints on the item.

**Comment by kuuroo3** [comment]
Is there another way in which I can make sure that the related files get deleted? 

I was thinking about using hooks but when I'm using the `<collection>.items.delete` hook the item is no longer accessible.

**Comment by rijkvanzanten** [comment]
> Is there another way in which I can make sure that the related files get deleted?
> 
> I was thinking about using hooks but when I'm using the `<collection>.items.delete` hook the item is no longer accessible.

If you use the filter hook for the delete, you should still be able to read the to be deleted item, as the hook fires before the delete is committed 👍🏻
