### ISSUE TITLE
custom REFRESH_TOKEN_COOKIE_NAME prevent to logout in cookie mode with SDK

### ISSUE THREAD

**Issue by Silbad** [directus/directus#12458]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello, the logout sdk method wait a refresh token in cookie mode.

### To Reproduce

- Set a custom name to REFRESH_TOKEN_COOKIE_NAME
- log in with cookie mode 
- log out without refresh token ('cause doc says that)
=>Error

With defaut cookie name, it's ok.
Thanks

### Errors Shown

![image](https://user-images.githubusercontent.com/31576982/160604594-d3b350a5-94f3-475a-b5b5-162d57b3e7b1.png)

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

14.17.4

### What database are you using?

MySQL 8

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Plesk

**Comment by azrikahar** [comment]
Hi, I tried to set a custom cookie name via `REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token_custom"` (note the `_custom` at the end) and logout via the SDK, it seems to work on my end:

https://user-images.githubusercontent.com/42867097/161493127-69f80531-cbce-4afd-8072-b7b9826cd777.mp4

Based on the API code here:

https://github.com/directus/directus/blob/703fb8426f59619a4f21e80f670ed4347d01666c/api/src/controllers/auth.ts#L118-L122

I can only assume the cookie is not being sent in your request? It is sent in the request header in my case:

![chrome_16BPqU9C4e](https://user-images.githubusercontent.com/42867097/161493477-7aaf890c-67f2-43ce-839d-0d74d544294e.png)

**Comment by azrikahar** [comment]
Would you mind clarifying what is the "trick" or potential addition to the docs here? I used the value `directus_refresh_token_custom`, but it could also be anything such as `special_ref_token_here`. In any case, the env variable will still remain the same as `REFRESH_TOKEN_COOKIE_NAME` 👍

If you meant it worked after adding `_custom` to your own custom refresh token naming, would you mind sharing what was the previous name you were using? Perhaps there was a collision with other cookies you may have that is not related to Directus 🤔

With that said, I assume you are answering on behalf of OP here in the same organization? Since I've just noticed both of your locations are the same and the sudden reply from you instead of OP. If that is the case, I'll proceed to close this issue since it seems to be a configuration misunderstanding here rather than a bug with Directus.
