### ISSUE TITLE
Docs: Link to Field Tranforms on System/Fields is broken

### ISSUE THREAD

**Issue by m0rtis0** [directus/directus#12491]
On the page https://docs.directus.io/reference/system/fields/
the link to field tranforms yields a 404. Does this doc page even exist?
![image](https://user-images.githubusercontent.com/65440078/160926260-f105f72a-81db-4382-a710-3dad07ab2d3f.png)

**Comment by azrikahar** [comment]
It does used to exist, just unfortunately got lost during the major docs rework in #9071. Linking the old file here so that we can lift it off from there later: https://github.com/directus/directus/blob/a257f324c0b2b2befae3ffe4df50ce2949412067/docs/reference/field-transforms.md

As there has been some changes to the naming of the transforms recently, in case you're wondering what are the latest ones, you can view them over here: 

https://github.com/directus/directus/blob/2dce9440e321e1ff82eed2a346ad8cf1f3eb67ce/api/src/services/payload.ts#L50-L136

**Comment by rijkvanzanten** [comment]
cc @erondpowell

**Comment by erondpowell** [comment]
> cc @erondpowell

Noted

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/directus/commit/5cce44fa0547a7e4e6b04e479da245457b238647. We're tracking the additional information in a different issue 👍🏻
