### ISSUE TITLE
Duplication on relational field doesn't work

### ISSUE THREAD

**Issue by Mario-Amos** [directus/directus#12555]
### Describe the Bug

Duplication is not working anymore on relational field
Duplication checkboxes are not checked anymore
If I want to check relation field duplication, I have to check a "normal" field first, and then check the relation one
Duplication doesn't duplicate selected fields

### To Reproduce

- Create two collections, A and B
- Create a M2M relation between A and B
- Check M2M field in duplication section

### What version of Directus are you using?

9.7.1 - 9.8.0

### What version of Node.js are you using?

14.18.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### How are you deploying Directus?

Deployed on Infomaniak's cloud server

**Comment by HitomiTenshi** [comment]
@rijkvanzanten Same here, only that duplication doesn't work at all anymore. I can't even set non-relational fields to be duplicated.

I can confirm @Mario-Amos error though. If you first click on a relational field to be duplicated an error is thrown:

![chrome_2022-04-06_11-53-49](https://user-images.githubusercontent.com/7304212/161949405-df166b55-48e0-439d-ad3c-38e6ad4bc1e7.png)

Saving after setting the checkboxes for what needs to be duplicated doesn't work, the fields all get reset to not being checked.

When trying to "save as copy" anything, it seems to complain that **required** values are not filled even though they have a value. If I change them a bit the complaining stops, but after duplication only the **required** fields have been duplicated (that I previously touched because of the required errors). Any other fields never get duplicated anymore.

Error is in both `9.7.1` and `9.8.0`.

**Comment by azrikahar** [comment]
@HitomiTenshi just to confirm, is there any discrepancies in my steps here? Can't seem to reproduce any error on my end but just want to be sure I understood correctly:
 
https://user-images.githubusercontent.com/42867097/161953167-5f049524-9ad1-418c-8275-8053374f9ad4.mp4

**Comment by HitomiTenshi** [comment]
@azrikahar I never open the related fields on the copy checkboxes, I always just click on the top-most checkbox.

Marking fields to copy:
https://user-images.githubusercontent.com/7304212/161953996-7c8d7c5b-02d2-4f60-87b3-a269f866de52.mp4

After saving it does not show them checked anymore **BUT** in the database table "directus_collections" the selected copy fields are saved correctly.

Trying to duplicate:
https://user-images.githubusercontent.com/7304212/161954549-3429194d-af87-4540-b4ac-3c1bc4459ea5.mp4

Even with the fields being saved correctly it does not copy them. In the video I used a table that did not have required fields, but if it had any it would've complained that they have no value, even though they have one.

Here, another video, I changed the name field to be required:
https://user-images.githubusercontent.com/7304212/161955075-de9b0152-468b-481f-94b2-455bd6a2b0df.mp4

It only saves the fields that I changed something on.

**Comment by HitomiTenshi** [comment]
@azrikahar I think this issue title is wrong, duplication doesn't work on any field in any collection right now. I tested it with version `9.9.0` and it's still there.

Here is how to reproduce it.

# Reproduction:

## Setup
1. Create a new collection "test"
2. Add 3 string fields: first, second, third
3. Make sure field "first" is `NOT NULL` and has "Require value to be set" checked. (Leave the other 2 fields as `NULL`-able with default settings)
4. After adding the 3 fields refresh the data model page, because the duplication fields at the bottom do not get updated while adding new fields.
5. Now scroll down to duplication fields and check the fields "first", "second" and "third" and hit save.
6. Go to the collection and create a new entry that has a value in all 3 fields.

## Reproduce Error: "Value is required"
7. Open the item you have created and change the value in field "third".
8. Click on "Save as copy", you will get the error "First: Value is required".

## Reproduce Error: Only changed fields are saved 1
7. Open the item you have created and change the value in field "first" and in field "second".
8. Click on "Save as copy", the item will be saved but the value of field "third" is not copied.

## Reproduce Error: Only changed fields are saved 2
7. Open the item you have created and change the value in field "first".
8. Click on "Save as copy", the item will be saved but the value of field "second" and "third" is not copied.

**Comment by HitomiTenshi** [comment]
# Reproduction for the M2M / M2O / O2M duplication field error:

## Steps
1. Create a new collection "test".
2. Add M2M or M2O or O2M fields.
3. No need to configure them extensively, just fill out the related collection names and save.
4. After adding the relation fields refresh the data model page, because the duplication fields at the bottom do not get updated while adding new fields.
5. Now scroll down to duplication fields and try to check the relation fields you created.
6. You will see this error for all relation fields when trying to check them for duplication:

![chrome_2022-04-06_11-53-49](https://user-images.githubusercontent.com/7304212/161949405-df166b55-48e0-439d-ad3c-38e6ad4bc1e7.png)

This error happens no matter what type of relation field you create and only if the first click is on a relation field. If you first click on a non-relation field and after that on one of the relation fields, it will check them normally without throwing the above error.

**Comment by azrikahar** [comment]
@HitomiTenshi thank you for the detailed reproduction steps! Really wish more issues have this level of detail 😄

Turns out it may just be a single line of code change, which is `json` should be updated to `cast-json` here:

https://github.com/directus/directus/blob/69d40af5b3198cab4946b3c6be43eb7ddb5c037d/api/src/database/system-data/fields/collections.yaml#L196

(because we updated it to `cast-json` on a recent version)

As it was not casting in json properly, saving as copy was fetching the field as a whole string, so it actually ended up fetching _no data_ to be combined with the edits:

![chrome_8LfG9BEMsB](https://user-images.githubusercontent.com/42867097/163795527-67ee8632-89c6-4905-8217-c284413a2201.png)

![chrome_D1HHNhXcwF](https://user-images.githubusercontent.com/42867097/163795539-0641b737-8e96-4984-9f00-83b187898741.png)

That seems to resolves it for me. Would it be possible for you to test this change out (by changing the same line in that yaml file and restarting Directus) just to be sure? Once again really appreciate the tremendous help!

**Comment by HitomiTenshi** [comment]
@azrikahar Hi, sorry for the late response, I changed the line you suggested and it does seem to fix everything, but that is only an illusion. It does fix duplication on simple fields but problems with M2M and O2M fields remain, M2O fields are fine though.

**Only fields that cause items to be duplicated in another collection are failing now.**

You can reproduce it very easily by doing the following:

# Reproduction:

1. Create a new collection "test"
2. Add 1 string field called "name"
3. Add 1 translation field
4. In the "test_translations" collection also add a string field called "name"
5. Go to the "test" collection and scroll down to duplication fields and check both the "name" field and the "translations" field
6. Create an entry without a translation.
7. Try to duplicate it.

This error then occurs:

Request URL: /api/items/products_translations?fields[]=id&fields[]=&filter[id][_in]=15
Request Method: GET
Status Code: 400 **BAD_REQUEST**

```json
{
    "errors": [
        {
            "message": "\"fields[1]\" is not allowed to be empty",
            "extensions": {
                "code": "INVALID_QUERY"
            }
        }
    ]
}
```

**Comment by HitomiTenshi** [comment]
There's also another bug when trying to check field-groups for duplication.

When selecting a field-group for duplication, all field-groups get checked at the same time but the check mark does nothing. It does not check any fields inside the field-group.

This is only a minor usability bug as you can open the field-group and check all the fields inside it manually.

# Reproduction for Field-Groups:

1. Create a collection "test"
2. Add 2 string fields
3. Add 2 field groups
4. Move 1 string field inside each group
5. Refresh the data model page
6. Scroll down to the duplication fields and try checking the field groups.
7. You will see it is kind of buggy and selecting one field group also selects the other _visually_, but without any actual effect.

**Comment by azrikahar** [comment]
Currently it is using value-combining `exclusive`:

https://github.com/directus/directus/blob/5cce44fa0547a7e4e6b04e479da245457b238647/app/src/interfaces/_system/system-field-tree/system-field-tree.vue#L15

and maybe changing it to `leaf` will feel more "natural":

https://user-images.githubusercontent.com/42867097/164007838-3a4211c9-36d4-4287-a48c-8c2d45e35723.mp4

but will need to confirm what are the potential implications of this change first.

---

Regarding the field groups, interestingly the issue is they do not really have a value (empty string), so when you check one of them, the reason why both gets checked because they are both of the same value `""`:

Uploading chrome_sxLU5cMhCx.mp4…

Definitely counts as a bug 👍 Thanks again for the concise reproduction steps!
