### ISSUE TITLE
Filter functions do not work on relationships

### ISSUE THREAD

**Issue by u12206050** [directus/directus#12725]
### Describe the Bug

Any functions applied in the filter on relationships fail to execute correctly.
This is seems to be both an app issue and api issue.

In the app it needs to change from `{"_and":[{"year(topic":{"some_date)":{"_lt":"2000"}}}]}` to `{"_and":[{"year(topic.some_date)":{"_lt":"2000"}}}]}` or `{"_and":[{"topic": { "year(some_date)":{"_lt":"2000"}}}]}`

In the api this needs to be parsed correctly as well as it doesn't work on relationships.

![FunctionsFilterIssue](https://user-images.githubusercontent.com/6641242/163157764-d1dec5c5-6a02-4367-84c8-00433e3a056f.gif)

### To Reproduce

Try filtering using a function on a relationship

### Errors Shown

\"things.year(topic\" is not a relational field

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

GCP

**Comment by licitdev** [comment]
Thank you for your report.
The filter output in the app is definitely invalid.
Tested the API works with `{"_and":[{"topic": { "year(some_date)":{"_lt":"2000"}}}]}`.
However, there seems to be an issue with deeply nested fields with filter functions.

**Comment by azrikahar** [comment]
Just to detail my findings as I'm not sure what are the optimal solutions, particularly for API:

## App side

It's due to when we're adding a node here:

https://github.com/directus/directus/blob/efdf7bbc0c05c8b46b54b56c888d6bf48bd1e852/app/src/interfaces/_system/system-filter/system-filter.vue#L128-L146

The lodash `set()` in line 143 is setting something like `year(related_collection.date_created)` as it's path. Since lodash `set()` uses dots as paths, it's being misinterpreted as `year(related_collection` wrapping `date_created)`.

Making the following changes seems to resolve this App side issue by making sure `year(related_collection.date_created)` gets turned into `related_collection.year(date_created)` instead:

```diff
function addNode(key: string) {
                innerValue.value = innerValue.value.concat({ _and: [] });
        } else {
                let type: Type;
+               let resultingKey = key;
                const field = fieldsStore.getField(collection.value, key);

                if (key.includes('(') && key.includes(')')) {
                        const functionName = key.split('(')[0] as FieldFunction;
                        type = getOutputTypeForFunction(functionName);
+
+                       const { field: fieldInFunction } = extractFieldFromFunction(key); // import this from '@/utils'
+                       const indexOfLastDot = fieldInFunction.lastIndexOf('.');
+                       resultingKey = `${fieldInFunction.slice(0, indexOfLastDot)}.${functionName}(${fieldInFunction.slice(
+                               indexOfLastDot + 1
+                       )})`;
                } else {
                        type = field?.type || 'unknown';
                }
                let filterOperators = getFilterOperatorsForType(type);
                const operator = field?.meta?.options?.choices && filterOperators.includes('eq') ? 'eq' : filterOperators[0];
-               const node = set({}, key, { ['_' + operator]: null });
+               const node = set({}, resultingKey, { ['_' + operator]: null });
+
                innerValue.value = innerValue.value.concat(node);
        }
 }
```

## Api side

For nested joins, the collection/table name is aliased as mentioned by this comment:

https://github.com/directus/directus/blob/efdf7bbc0c05c8b46b54b56c888d6bf48bd1e852/api/src/utils/apply-query.ts#L102-L105

When the `columnName` is retrieved here with `collection` = "related_collection" for example:

https://github.com/directus/directus/blob/efdf7bbc0c05c8b46b54b56c888d6bf48bd1e852/api/src/utils/apply-query.ts#L353-L355

it become something like `abcde.year(date_created)` instead of `related_collection.year(date_created)`. Afterwards when `abcde.year(date_created)` gets passed to `applyFilterToQuery`, it is split as `table` and `column` here:

https://github.com/directus/directus/blob/efdf7bbc0c05c8b46b54b56c888d6bf48bd1e852/api/src/utils/apply-query.ts#L393

Recalling that our `table` is `abcde` instead of the actual collection name, when it's passed to getColumn here:

https://github.com/directus/directus/blob/efdf7bbc0c05c8b46b54b56c888d6bf48bd1e852/api/src/utils/apply-query.ts#L396

It will try to infer the type by looking up `schema.collection['abcde']` _instead of_ `schema.collection['related_collection']` here:

https://github.com/directus/directus/blob/efdf7bbc0c05c8b46b54b56c888d6bf48bd1e852/api/src/utils/get-column.ts#L33

and since `abcde` is not an actual collection in the schema, the type ends up being 'unknown' and any functions will cease to work.

**Comment by azrikahar** [comment]
Although there aren't any visible updates to this specific issue, it wouldn't mean we're ignoring open issues in any way 👍 Understandably this issue isn't exactly minor (hence it is actually somewhat far up the current list of action items), but the general consideration described here still applies: https://docs.directus.io/getting-started/support/#can-you-give-an-eta-for-this-feature-fix. Hope that's understandable!

**Comment by nodeworks** [comment]
I have a PR in for this:

https://github.com/directus/directus/pull/15991

**Comment by rijkvanzanten** [comment]
Linear: [ENG-259](https://linear.app/directus/issue/ENG-259/filter-functions-do-not-work-on-relationships)
