### ISSUE TITLE
In app documentation navigation anchor link bad target

### ISSUE THREAD

**Issue by laekem34** [directus/directus#12752]
### Describe the Bug

The link in application documentation not refer to the same page anchor
So clicking the link redirect to another page and app ask login confirmation

![image](https://user-images.githubusercontent.com/21008981/163342346-1a963474-6b1a-461c-b2f7-f05361a4a4a6.png)

### To Reproduce

Go to the app documentation et click on top summary link

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

sqlite3@5.0.2

### What browser are you using?

chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This seems to be the same as #11736, but that issue was closed without being resolved since it was not reproducible.

Turns out yes it is not reproducible in dev, but  it is actually 100% reproducible _only_ when we run a local installation.

## Local installation (bugged)

https://user-images.githubusercontent.com/42867097/163352464-5f8e4ca1-843d-4877-bce1-c9c98579cb73.mp4

## Dev (working)

https://user-images.githubusercontent.com/42867097/163353233-cdf1b731-7874-49a4-ba6d-1a778829d202.mp4

**Comment by rijkvanzanten** [comment]
Prod vs dev issue? Lovely!

**Comment by nickrum** [comment]
@rijkvanzanten This was introduced when we added the `<base>`-tag to `index.html`. I think we have to use `<router-link>`s instead of `<a>`s for links to anchors and then somehow instruct vue-router to scroll to those anchors once the page has loaded.
I tried to fix this when I refactored the docs generation to be done at build time, but I haven't had the time to investigate further.
