### ISSUE TITLE
Can not upload a pdf to files

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1279]
## Version Info
- Directus version and branch: Version 6.3.4
- PHP version: 7.0.8
- MySQL version: Ver 14.14 Distrib 5.7.15,
- Web server: Apache 2
- OS name and version: Ubuntu Server 16.04.3
- Safari 10 on macOS 10.12.0 (Sierra)
## Expected Behavior

I can upload a simple, small pdf file
## Actual Behavior

I drag and drop a pdf file to Item field in files upload, Error Toast/Notification appears.
## Note

Upload of images works! 
## Logs or Screenshots

Log in Safari Dev Console: 

> https://server/directus/api/1/files Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by WellingGuzman** [comment]
Thanks for the report @RabbitMC, Working on a fix.

**Comment by WellingGuzman** [comment]
Hey @RabbitMC this commit https://github.com/directus/directus/commit/927616443b518ea3059289a9b53ecc9f2d66dc9e should fix the issue.

Thanks again for reporting this.

**Comment by RabbitMC** [comment]
Yeah! Checked it! works! awesome! 🤘

**Comment by KingKarrow** [comment]
Hi! I'm seeing the same thing on 6.3.6.

**Comment by WellingGuzman** [comment]
@KingKarrow any specific error? any logs in `api/logs`?

**Comment by KingKarrow** [comment]
This one looked relevant:
```
ERROR - 2017-03-03T15:54:02-05:00 - ImagickException: Unable to read image blob in /var/www/html/api/core/Directus/Files/Thumbnail.php:31
Stack trace:
#0 /var/www/html/api/core/Directus/Files/Thumbnail.php(31): Imagick->readimageblob('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...')
#1 /var/www/html/api/core/Directus/Files/Files.php(401): Directus\Files\Thumbnail::generateThumbnail('%PDF-1.5\r%\xE2\xE3\xCF\xD3\r...', 'pdf', '200', '1')
#2 /var/www/html/api/core/Directus/Files/Files.php(89): Directus\Files\Files->createThumbnails('E7.HorizontalLo...')
#3 /var/www/html/api/api.php(1338): Directus\Files\Files->upload(Array)
#4 [internal function]: {closure}()
#5 /var/www/html/vendor/slim/slim/Slim/Route.php(436): call_user_func_array(Object(Closure), Array)
#6 /var/www/html/vendor/slim/slim/Slim/Slim.php(1305): Slim\Route->dispatch()
#7 /var/www/html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#8 /var/www/html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 /var/www/html/vendor/slim/slim/Slim/Slim.php(1254): Slim\Middleware\MethodOverride->call()
#10 /var/www/html/api/api.php(1696): Slim\Slim->run()
#11 {main}
```

**Comment by WellingGuzman** [comment]
@KingKarrow can you send me a pdf that I can use to reproduce this error, I tried couple of PDFs without any problem.

It seems you have `Imagick` already installed, so we can take that out of the way.

**Comment by KingKarrow** [comment]
I should point out that we used directus-docker to set this up. Don't know if that is relevant.
Here's a simple test PDF that threw the error:
[Output-Management-as-a-hub_Compart.pdf](https://github.com/directus/directus/files/821518/Output-Management-as-a-hub_Compart.pdf)

**Comment by KingKarrow** [comment]
Update: I've been working on my local running Docker as noted. Just tested on our development server, and it works. Though the thumbnail is just "PDF"... doesn't that mean Imagick shouldn't care about the PDF?

**Comment by WellingGuzman** [comment]
Hey @KingKarrow, so it happens to be the other way around it was an issue creating the pdf thumbnail, so it was about having `Imagick` installed.

I'm working on a fix, get back to you when it's done.

**Comment by WellingGuzman** [comment]
Note: I have experienced another issue, apparently on Mac OS X, `Imagick` is having issue reading files binary data, while on ubuntu there's not issue at all.

**Comment by kjj77** [comment]
Hi, I have the same error on 6.4.9. Just to be sure : is this related to imagick NOT being installed ? 
Thanks 

## Version Info
  - Directus version and branch (Or commit hash): 6.4.9
  - PHP version: 7.0.27-0+deb9u1 
  - MySQL version: 10.1.26-MariaDB-0+deb9u1
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Debian 9

## Expected Behavior

Correctly upload a PDF file.

## Actual Behavior

This is the last part of api/logs log file :

**ERROR - 2018-04-25T10:18:49-04:00 - ImagickException: Unable to read image blob in /var/www/clients/client0/web1/web/api/core/Directus/Filesystem/Thumbnail.php:120**

Stack trace:
#0 /var/www/clients/client0/web1/web/api/core/Directus/Filesystem/Thumbnail.php(120): Imagick->readimageblob('%PDF-1.7\n%\xE2\xE3\xCF\xD3\n...')
#1 /var/www/clients/client0/web1/web/api/core/Directus/Filesystem/Thumbnail.php(38): Directus\Filesystem\Thumbnail::createImageFromNonImage('%PDF-1.7\n%\xE2\xE3\xCF\xD3\n...', 'jpeg')
#2 /var/www/clients/client0/web1/web/api/core/Directus/Filesystem/Files.php(466): Directus\Filesystem\Thumbnail::generateThumbnail('%PDF-1.7\n%\xE2\xE3\xCF\xD3\n...', 'jpeg', '200', '1')
#3 /var/www/clients/client0/web1/web/api/core/Directus/Filesystem/Files.php(271): Directus\Filesystem\Files->createThumbnails('MK2_Confirmatio...')
#4 /var/www/clients/client0/web1/web/api/routes/A1/Files.php(87): Directus\Filesystem\Files->saveData(NULL, 'MK2_Confirmatio...')
#5 [internal function]: Directus\API\Routes\A1\Files->files()
#6 /var/www/clients/client0/web1/web/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Array, Array)
#7 /var/www/clients/client0/web1/web/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#8 /var/www/clients/client0/web1/web/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /var/www/clients/client0/web1/web/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /var/www/clients/client0/web1/web/api/core/Directus/Slim/CorsMiddleware.php(19): Slim\Middleware\MethodOverride->call()
#11 /var/www/clients/client0/web1/web/api/core/Directus/Slim/HttpCacheMiddleware.php(18): Directus\Slim\CorsMiddleware->call()
#12 /var/www/clients/client0/web1/web/api/core/Directus/Slim/ResponseCacheMiddleware.php(37): Directus\Slim\HttpCacheMiddleware->call()
#13 /var/www/clients/client0/web1/web/vendor/slim/slim/Slim/Slim.php(1302): Directus\Slim\ResponseCacheMiddleware->call()
#14 /var/www/clients/client0/web1/web/api/core/Directus/Application/Application.php(103): Slim\Slim->run()
#15 /var/www/clients/client0/web1/web/api/api.php(533): Directus\Application\Application->run()
#16 {main}

**Comment by konradwww** [comment]
@kjj77 it is imagick issue, you need to install ghostscript and libjpeg-dev packages.

**Comment by kjj77** [comment]
@konradwww Thanks it worked, for those who don't know on Debian it's just 

sudo apt-get update
sudo apt-get install ghostscript
sudo apt-get install libjpeg-dev

and then restart Apache.

**Comment by rijkvanzanten** [comment]
Perfect! Thanks @konradwww
