### ISSUE TITLE
Pasting value in field names should not be allowed to end in "?"

### ISSUE THREAD

**Issue by lucasshipsides** [directus/directus#12943]
### Describe the Bug

Directus allows field names to end with "?". It will save the field initially and appear normal.
However this wreaks havoc in editing and submitting a form. The API / web method for posting doesn't interpret the "?" as %3F, so the field can't be edited in the GUI without manually changing the URL. The form cannot be submitted to a collection if the question was set as compulsory, and the built in functions like "delete field" appear to work but don't do anything at the POST that runs in the background returns a 204 no data, and on refresh the field remains.

### To Reproduce

1. Create a field with "?" as the last character.
2. Try to edit this field past the initial completion

### Errors Shown

Responses from fiddler come back with 204 no content

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

Chrome, Powershell

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
Can you share a short clip for step 1? I believe field names by default already disallow characters like question mark, as seen in the code below:

`dbSafeCharacters` lists the characters we _can_ use, with "space" being the outlier since we still need to allow that to work, but it will automatically get turned to underscore afterwards.

https://github.com/directus/directus/blob/81483a80122d5ee03a895c9c5d2e7414fd231b4f/app/src/components/v-input/v-input.vue#L172-L180

**Comment by lucasshipsides** [comment]
hi @azrikahar, good pick up!
it turns out the reason i was able to insert the invalid character is because i copy and pasted a field name that contained "?" into the field. so there is a difference between entering a "?" and copy/pasting something that contains a "?"
