### ISSUE TITLE
delta stored but not displayed

### ISSUE THREAD

**Issue by frankvolkel** [directus/directus#1301]
I noticed that the delta for changes are stored in the directus_activity table, but isn't displayed on the interface itself. It's also advertised on directus.com that "(a)ll activity within Directus is tracked giving system-wide accountability. With revision roll-backs". 

Am I missing something?

**Comment by benhaynes** [comment]
Hey @frankvolkel – you're correct, we're storing the full item at each change, as well as the delta (with user for accountability). Activity is shown inline with comments at the bottom of the Item Detail page. And while we used to have an interface for "rolling back" we've disabled it due to unintended and far-reaching consequences of relational data.

The thinking (for now) is that the data is there and admins can roll items back to previous states using what's in the `directus_activity` table. We're actually in the middle of a design refresh that addresses this issue which will be rolling out in v`6.5`! Thanks for keeping us honest, and sorry for any confusion!
