### ISSUE TITLE
extension auto reload only works if NODE_ENV !== 'development'

### ISSUE THREAD

**Issue by meytin1337** [directus/directus#13025]
### Describe the Bug

I was wondering why the extension auto reloading didn't work for me. I dug into the codebase and found this line of code in directus/api/src/:
```
const defaultOptions: Options = {
	schedule: true,
	watch: env.EXTENSIONS_AUTO_RELOAD && env.NODE_ENV !== 'development',
};
```
I don't think this is what the code is supposed to be since the primary use case for the extension auto reloading should be a development environment.

### To Reproduce

In the environment where you run your directus instance set the environment variables
```
EXTENSIONS_AUTO_RELOAD=true
NODE_ENV=development
```

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

postgres

### What browser are you using?

firefox

### How are you deploying Directus?

docker

**Comment by meytin1337** [comment]
I have create a PR here: **https://github.com/directus/directus/pull/13027**

**Comment by rijkvanzanten** [comment]
This is correct, as we don't want the auto reload to kick in when running Directus from source through `npm run dev` as that is already handled by `ts-node-dev` 👍🏻

**Comment by Anoesj** [comment]
@rijkvanzanten Would be nice to see whenever extensions are reloaded in the logs when `NODE_ENV=development`. I found this issue because I was confused why my extensions weren't reloading. In fact, you're saying the reload mechanism should still work? Because that doesn't seem to work right now (latest version of Directus as of writing).

**Comment by rijkvanzanten** [comment]
I believe the original intention for the reliance on NODE_ENV=development was to make sure that extensions weren't "double reloaded" when using the `ts-node-dev` based dev mode in the source code. Feels like it might be better to decouple that from NODE_ENV completely to remove any confusion as to wth is going on here 😁

**Comment by Anoesj** [comment]
I agree! Less exceptions = less confusion :smile:

**Comment by nickrum** [comment]
> I believe the original intention for the reliance on NODE_ENV=development was to make sure that extensions weren't "double reloaded" when using the `ts-node-dev` based dev mode in the source code.

That was exactly the original intention 👍

The root of the problem is that `NODE_ENV == development` could either mean that you are running Directus in dev mode to work on Directus itself or it could mean that you are running your own software that relies on Directus in dev mode. I think at some point we had a `DIRECTUS_DEV` env var. Maybe we should reintroduze that 🤔
