### ISSUE TITLE
Permissions till show 403 even after setting it to allow public view access

### ISSUE THREAD

**Issue by Aliemeka** [directus/directus#13092]
### Describe the Bug

Anytime I try to read the data in my directus database, I get a 403 error even though I have enabled public read access permissions to all fields.

### To Reproduce

- Install directus
- Create a collection
- Enable public read access to collection
- Try calling the api

### Errors Shown

```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.13.1

### What database are you using?

SQLite

### What browser are you using?

Chrome, Brave

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Hi, would you mind providing more detail such as what is the exact collection name and URL you are requesting? In case you created the collection with capital letter(s), for example `Articles`, do make sure to request `/items/Articles` instead of `/items/articles`.

Here's a test I just did and it seems to work as expected:

https://user-images.githubusercontent.com/42867097/166428353-4e70dc19-47d6-4fc7-b2d6-bf24195bbc91.mp4

I'll close this for now as this may be similar to the confusion in #13030, but happy to debug further once you share more detail and if it still persists for you.

**Comment by Aliemeka** [comment]
You clearly didn't read through properly before closing this issue. I've already done this. I still have the problem

<img width="1726" alt="Screenshot 2022-05-03 at 10 24 26" src="https://user-images.githubusercontent.com/24621519/166430949-d90382ea-228d-446b-9234-c04676ad4f79.png">

<img width="1722" alt="Screenshot 2022-05-03 at 10 26 37" src="https://user-images.githubusercontent.com/24621519/166431229-f73a39b4-8c81-46b3-b7ef-d46d4b59f906.png">

**Comment by azrikahar** [comment]
Glad it's resolved 🙂 Can you share what was the resolution? Was it the capitalization of collection name? We're planning to lessen the confusion with this so it'd be very helpful if you can confirm whether this was the case. Thanks!

**Comment by Aliemeka** [comment]
Capitalisation of the collection name
