### ISSUE TITLE
Creating File (Uploading Image) with request doesnt Work.

### ISSUE THREAD

**Issue by ValonK** [directus/directus#1316]
Hello, 

im not sure if this is the right place to post my Problem, because i think that this could be a Directus bug.
I asked the on StackOverflow http://stackoverflow.com/questions/41270038/c-sharp-get-request-directus.

Basicly what im tring to do is to create a File (Base64 Image)  using a simple GET Request exactly like described in the Api Docs https://api.getdirectus.com/1.0/#Create_File. But no matter what i do it never works.
If i switch to Postman and make a POST instead of a GET it creates an Empty File,
Am i missing something ? 

## Version Info
  - Directus: Api Version 1.0
  - PHP version: PHP 7.0.14-1+deb.sury.org~xenial+1 
  - MySQL version: Ver 14.14 Distrib 5.7.16, 
  - Web server: Apache
  - OS: Ubuntu 16.04.1

**Comment by benhaynes** [comment]
Thanks @ValonK – we'll look into this today!

**Comment by ValonK** [comment]
Thanks!! I love Directus !! keep up the great Work!

**Comment by WellingGuzman** [comment]
Hey @ValonK,

I'm working on this.

The docs is incorrect it's actually a `POST` request. thanks for pointing that out.

To upload a new file you need three provide three values:

```json
{
	"name": "image.png",
	"type": "image/png",
        "data": "base64content"
}
```

The data content has to be in this format `data:<mime-type>;base64,<data-content>` so it will look  something like this: `data:image/png;base64,ThisIsABase64Content`

I'm working to allow just the base64 content, because the mime type must has been already provided.


Hope this works for you.

I added a [response to stackoverflow](http://stackoverflow.com/questions/41270038/c-sharp-get-request-directus/41290752#41290752) as well

**Comment by ValonK** [comment]
First let me thank you for your Time ! 
Ive tried your approach like this 
```
  public static async void UploadUserImage() {
            var uri = "http://IP/Directus/api/1/files?access_token=TO
OKEN";

            using (var client = new HttpClient())
            {
                var values = new Dictionary<string, string>
                {
                   { "name", "neuesBild.jpg" },
                   { "type", "image/jpg" },
                   { "data", GetBaseImageData() }
                };

                var content = new FormUrlEncodedContent(values);
                var response = await client.PostAsync("http://IP/Directus/api/1/files?access_token=TO
OKEN", content);
                var responseString = await response.Content.ReadAsStringAsync();
                Console.WriteLine(responseString);
            }
        }

```
Im getting a Exception Response Message http://pastebin.com/6JZV8BxB. I hope im doing something wrong and its not a bug on the Directus Side.

**Comment by WellingGuzman** [comment]
Yeah, that's a bug on our side, I'm about to push a fix for it on `development` branch.

But you can solve it by prefixing `data:image/jpg;base64,` to `GetBaseImageData()`

Like this: `"data", "data:image/jpg;base64," + GetBaseImageData()` (If that doesn't work on C# at least you get the idea 😄 )

**Comment by ValonK** [comment]
Allright thanks for your help! That resolved my issue ! :)

**Comment by WellingGuzman** [comment]
Great to hear! In the next version you would've to add that, but still will work if you add it. 👍

**Comment by john-kurkowski** [comment]
Looks like the fix was undone? Still need the workaround? [This `$type`](https://github.com/directus/directus/blob/6.4.5/api/core/Directus/Filesystem/Files.php#L239) is never initialized, unless I use the workaround format from [the previous comment](https://github.com/directus/directus/issues/1316#issuecomment-268882052).

**Comment by WellingGuzman** [comment]
Hey @john-kurkowski, would you care to share the code you are using to trigger this issue/bug?

**Comment by john-kurkowski** [comment]
Sure.

```sh
$ curl -X POST -H 'Authorization: Bearer xxxxxx' -H 'Content-Type: application/json' -d '{"data": "somethingbase64here", "name": "some file name", "type": "image/png"}' https://yyyyyy/api/1.1/files
{"error":{"message":"Missing [type] parameter. Must provide file mime type."},"success":false}
```

**Comment by WellingGuzman** [comment]
Thanks for the snippet @john-kurkowski, I will be working on it, some time today.

**Comment by WellingGuzman** [comment]
This has been fixed by https://github.com/directus/directus/commit/f139bf3110b7d61a5e3574373a523122d86d6064
