### ISSUE TITLE
Notification coming late

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [directus/directus#13219]
### Describe the Bug

When we trigger the notification through API. it reach the recipient very late

POST /notifications

{
	"recipient": "410b5772-e63f-4ae6-9ea2-39c3a31bd6ca",
	"subject": "Hi there!"
}

### To Reproduce

- Send the notification through api
- check on the recipient side

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloudron

**Comment by azrikahar** [comment]
I can't seem to reproduce this as seen here:

https://user-images.githubusercontent.com/42867097/167770876-46e0f575-8ae7-4203-a968-a8e577a78949.mp4

Also had to add the "sender" the property for it to work properly, so it'd be rather odd if it's working for you without it (could be related to old version though!).

I'm not sure how "late" it is in terms of seconds/minutes or even hours, but I believe this is not something to do with Directus itself. This may be something related to Cloudron, so you should raise this out with them instead 👍 If you can replicate this odd delay with a local installation or with Directus cloud, do let us know so that we can investigate further.

**Comment by Jeyakumarrathnaselvi** [comment]
This issue exisit even in Directus cloud deployment.

https://user-images.githubusercontent.com/36895131/188178789-fd1d2532-5efb-4634-a61b-6c1d9b2522cf.mp4

**Comment by rijkvanzanten** [comment]
The app only loads notifications on navigation currently, so that's expected 👍🏻 

Once #14737 becomes a thing, we can start pushing those things live 🙂
