### ISSUE TITLE
Map creation Error

### ISSUE THREAD

**Issue by mape09** [directus/directus#13251]
### Describe the Bug

I can't add a map on my data

### To Reproduce

Create a table 
Add map
Validate

### Errors Shown

![image](https://user-images.githubusercontent.com/103728185/168050908-817ffc29-8cb0-4ea3-a0a1-0403be18df64.png)

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

Don't Know

### What database are you using?

mySQL

### What browser are you using?

FireFox

### How are you deploying Directus?

DigitalOcean

**Comment by azrikahar** [comment]
This should be https://github.com/directus/directus/discussions/12927#discussioncomment-2608768, which seems like you have yet to actually respond to (regarding the database vendor in use). Would you mind replying and share your environment variables configuration over there so that we can investigate further? Thanks!
