### ISSUE TITLE
Versioning the API vs. versioning the API endpoints

### ISSUE THREAD

**Issue by mkleywegt** [directus/directus#1345]
Configuring the API version through `config.php` currently does not work as intended.

It seems the old (v1) and the new (v1.1) sets of API endpoints are both supposed to work simultaneously, but the API_VERSION constant confuses and breaks things.

Consider:
- API_VERSION set to **1**: `/api/1/<endpoint>` works (with all the new endpoints introduced in [v1.1 of the API](https://api.getdirectus.com/1.1/#API_Endpoints)), `/api/1.1/<endpoint>` works as well, but does not return related items (referenced on many to many fields)
- API_VERSION set to **2** (or other INT): `/api/2/<endpoint>` works (with all the new endpoints), `/api/1.1/<endpoint>` still works, but does not return related items (referenced on many to many fields)
- API_VERSION set to **1.1**: `/api/1.1/<endpoint>` works (with all the new endpoints), but does not return related items (referenced on many to many fields), `/api/1/<endpoint>` does not work at all.
- API_VERSION set to **1.2 (or other decimal other than .1)**: `/api/1.2/<endpoint>` works (with all the new endpoints introduced),  `/api/1.1/<endpoint>` works (with all the new endpoints introduced in [v1.1 of the api](https://api.getdirectus.com/1.1/#API_Endpoints)), but does not return related items (referenced on many to many fields), `/api/1/<endpoint>` does not work at all.

Long story short, it works correctly in two cases:
- leave API_VERSION set to **1**, use both API versions (but be mindful of the omission of fields on `/api/1.1` endpoints)
- set API_VERSION to anything other than **1.1**, use that API version with endpoints of v1

So I guess the confusion is between giving the user the ability version their api, whilst privately versioning the sets of endpoints at the same time.

As to why the response would differ specifically in the case of M2M items, that is another question.

## Version Info
  - Directus version and branch: 6.3.6 / master @ [2b333d5](https://github.com/directus/directus/commit/2b333d50714c57a6cc769324847fca6ae34408b1)
  - PHP version:  5.6.30
  - MySQL version: 5.7.12 
  - Web server: nginx
  - OS name and version:  Ubuntu 16.04 LTS

## Expected Behavior
When the API_VERSION constant is set to **1**, the API should respond on the `/api/1.1/<endpoint>` routes, as [described in the documentation](https://api.getdirectus.com/1.1/#API_Endpoints), and return all fields on the data key, including recursive / related items.

## Actual Behavior
The api does respond on the `/api/1.1/<endpoint>`, however M2M fields are omitted from the response.

## Steps to Reproduce
 1. Set API_VERSION to **1** in [api/config.php](https://github.com/directus/directus/blob/master/api/config_sample.php)
 2. Create a database schema with M2M relation
 3. Query the API on a `/api/1.1` endpoint which is supposed to include up the M2M relations

**Comment by mkleywegt** [comment]
Some more information:

- Whatever the API version, the admin client needs version **1** to function properly.
- Also, using any API version other than **1.1** gives you API responses from v1 (i.e. no filters are available).

**Comment by WellingGuzman** [comment]
Hey @mkleywegt, sorry for the confusion, the API versions are not intended to work together interchangeable **_YET_**, they work together.

We created the API 1.1 to improve the version 1, but we change all the responses to have the same output format, so that means it won't work changing **1** to **1.1** yet, also won't work because it will change all the current endpoints version, which in the end, you may be using the same version **1.1**

Filters were added in 1.1 for the first time.

**Conclusion:**
- it doesn't work yet, we will try to make API **1.1** and **1** interchangeable, otherwise we will deprecate API **1**
- Keep the API_VERSION on `config.php` be **1**
- Use **1.1** when possible as standalone endpoint, we recommend using this instead of **1**, it is faster than **1**

I will close this as this is a information confusion we create and will be resolve in a future release, thanks for reporting this and again we apologies for any confusion.
