### ISSUE TITLE
Funny little glitch in Display templates

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#13495]
### Describe the Bug

When I add spaces immediately after a Field, a `.` will be generated.

https://user-images.githubusercontent.com/62306630/169913611-8472cc40-26f8-4559-90dd-2a55e156001a.mov

### To Reproduce

As seen in the video.

### Errors Shown

Not 100% sure if related to this

<img width="802" alt="Screen Shot 2022-05-23 at 5 12 17 PM" src="https://user-images.githubusercontent.com/62306630/169913514-3fd700f6-b476-4a85-a2dd-9fa2f7cb24d6.png">

### What version of Directus are you using?

cloud

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
I can't seem to reproduce this locally with 9.11.0 on Windows, but this does remind me of a particular interaction on certain keyboards for mobile which turns "double spaces" into periods, as a form of shortcut. 

With that in mind, seems like [it is also a thing on MacOS as well](https://support.apple.com/lv-lv/guide/mac-help/mh35735/mac#:~:text=Note%3A%20You%20don't%20have,Text%20pane%20of%20Keyboard%20preferences.)! Could this be the cause here?

**Comment by erondpowell** [comment]
> I can't seem to reproduce this locally with 9.11.0 on Windows, but this does remind me of a particular interaction on certain keyboards for mobile which turns "double spaces" into periods, as a form of shortcut.
> 
> With that in mind, seems like [it is also a thing on MacOS as well](https://support.apple.com/lv-lv/guide/mac-help/mh35735/mac#:~:text=Note%3A%20You%20don't%20have,Text%20pane%20of%20Keyboard%20preferences.)! Could this be the cause here?

Maybe, but I have never seen this in any context in 8 yrs of owning a mac.
Also, if you notice, I rapidly put spaces after an existing space (instead of the field button) and this does not happen.
