### ISSUE TITLE
When create tables , I can't input Chinese in fields.

### ISSUE THREAD

**Issue by GodofOrange** [directus/directus#13504]
### Describe the Bug

![image](https://user-images.githubusercontent.com/38205098/169978682-6c638d34-76cb-4218-a0a5-1b842924ba09.png)
When create tables , I can't input Chinese in fields. 
I think it is because of the vue watch hook.

### To Reproduce

![tm](https://user-images.githubusercontent.com/38205098/169979266-273ff2ff-c490-4eff-b55b-2594fdde44e3.gif)

### What version of Directus are you using?

9.11

### What version of Node.js are you using?

14.0.0

### What database are you using?

Mysql 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
It is because this will be the column name in the table within the database, so a `dbSafe` prop is enabled on the input to only allow alphanumeric and/or underscore characters 👍

https://github.com/directus/directus/blob/fd62fa29542f0f93da1e26596dfcd073079f9955/app/src/interfaces/input/input.vue#L89-L92

In case you were looking to name the field with Chinese characters, you can do so by using field translations (configurable after you have created this field):

![chrome_zg21AmszQr](https://user-images.githubusercontent.com/42867097/169981523-58d9fc79-f10a-465b-864e-f6f368b417a8.png)

I'll close this for now as it's not an actual bug, but would also love to hear from you if you have any suggestions to improve this if it's not as clear as it can be!

**Comment by GodofOrange** [comment]
Thank you, I get it. :)
