### ISSUE TITLE
Unable to revert the value by typing for an edited but unsaved O2M item

### ISSUE THREAD

**Issue by koksikus** [directus/directus#13543]
### Describe the Bug

In an O2M field, when I want to change the text in the field (Input) of item in other collection, the letter in the second place I "shift with i" sends me to the end of the text ...

### To Reproduce

Click on the O2M to edit field then confirm and not closing the main record but opening it once more, try to enter in the second place I "shift with i" will send you to the end of the text..

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
I can't seem to reproduce this, but just so we can be on the same page here, would you mind sharing a quick clip on this particular interaction?

In the spirit of cases such as #13495 which turned out to be user's machine-dependent, it would also be helpful if you can try it with another device and/or browser as well as an attempt to rule out more possibilities here.

**Comment by koksikus** [comment]
I noticed one more thing that after the update, the conditions do not work properly ...

https://user-images.githubusercontent.com/90528895/170298543-e9c3462d-7ebf-4ef1-9d48-1ca61ea98f6c.mp4

I included the second case in # 13451

**Comment by koksikus** [comment]
I noticed one more thing that after the update, the conditions do not work properly ...

https://user-images.githubusercontent.com/90528895/170299153-215992ad-a778-42ed-a614-1ba76fde0375.mp4



I included the second case in # 13451

**Comment by azrikahar** [comment]
> Where the cursor jumps to the end, I try to press "I"

Thanks for the video! I believe the actual issue here is when we are making the value become the _original_ value, there's a weird "reset" behavior which causes the cursor go to the end of the input. Will update this issue's title to reflect this clearer.

https://user-images.githubusercontent.com/42867097/170447419-724f0e6d-26e2-49ba-bd19-7ac057f8fafd.mp4

> I noticed one more thing that after the update, the conditions do not work properly

Answered your comment in https://github.com/directus/directus/issues/13451#issuecomment-1137386506, but mentioning it here again just to link them together: This should be fixed in #13563.

**Comment by koksikus** [comment]
I have the same thing. It seems to me that it all depends where you remove the letter ... The same is true of searching in a table that has a relationship. When I enter the numbers, they disappear by themselves, and when I try to delete, they reappear and I have to delete it myself - it looks like something in the background is refreshing ...

**Comment by br41nslug** [comment]
Running into the same issue on M2M junction tables where explicitly typing/selecting the default value for the field will unset it back to the initial value.
![firefox_wDIPszAXdt](https://user-images.githubusercontent.com/9389634/187396818-53496c08-9dfd-40b3-ae07-97075884e09d.gif)

**Comment by rijkvanzanten** [comment]
Linear: [ENG-253](https://linear.app/directus/issue/ENG-253/unable-to-revert-the-value-by-typing-for-an-edited-but-unsaved-o2m)
