### ISSUE TITLE
conditions in "Detail Group" is broken

### ISSUE THREAD

**Issue by ludi81** [directus/directus#13621]
### Describe the Bug

I created a collection called Test with a dropdown element (Type with two entries: Type 1 und Type 2).
Additionally I added a condition for the "Detail Group" element to be shown only if type is not Type 1.

I set the condition as follows:
<img width="838" alt="2022-05-30_16-58-21" src="https://user-images.githubusercontent.com/25344341/171018432-14734bf6-5188-44cd-94d2-7b54fe53e7b5.png">

During the saving process I receive the following error and the above dialog is still shown:
<img width="754" alt="2022-05-30_16-59-07" src="https://user-images.githubusercontent.com/25344341/171018670-8a934938-cba6-4e91-a034-bd14c7afadc0.png">

### To Reproduce

To reproduce the above error just use the database dump in the bug report: https://github.com/directus/directus/issues/13620

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

mysql

### What browser are you using?

chrome and safari

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
> Additionally I added a condition for the "Detail Group" element to be shown only if type is not Type 1.

I'm not sure if this is a typo, but this statement seems to contradict with your config in the screenshot, since you are hiding it instead of showing it when type is not Type 1.

With that said, I was not able to reproduce this error:

https://user-images.githubusercontent.com/42867097/171114343-64eb38b8-a7b3-493e-ae8c-9fe5b1ab9b2e.mp4

Can you share what were the exact steps (and which fields) you were configuring which led to the reported error? We'll re-open this when more info is available 👍

P/S: It seems like you forgot to share the credentials (particularly password) of the db dump. I've regenerated the argon2 hash to circumvent it, but just want to point it out as a future reminder, no worries 😄

**Comment by azrikahar** [comment]
Ah that makes more sense now. I was testing on the latest main branch. This conditions options bug was fixed in #13563 recently and not released yet 👍

**Comment by ludi81** [comment]
That's great, in this case I will wait until the next release will be published.
