### ISSUE TITLE
Deleted language creates translation record on translated_table

### ISSUE THREAD

**Issue by nmpribeiro** [directus/directus#1365]
Just figured out how to create translations (using the projects and projects_translations from O2M relationship manual on Directs Docs), but upon testing it became obvious that my first (ID=1) deleted language was being used to create a translation record. After cycling through the translations through the drop down menu on my 'projects' it seams my first language was being fetched from 'default language' selected on the UI for the translation field on my projects table. I've inserted ID = 1 (my deleted language) on "Default language ID in language table".

## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: PHP 5.6.30 (cli)
  - MySQL version: mysql  Ver 15.1 Distrib 10.0.29-MariaDB
  - Web server: Server version: Apache/2.2.15 (Unix)
  - OS name and version: centos-release-6-8.el6.centos.12.3.x86_64

## Expected Behavior
Although I've selected on "Default language ID in language table" the ID of the deleted language record, it should be selected the first active one after.

## Actual Behavior
Translation record presented on form upon edition of 'project' record was from the deleted language record.

## Steps to Reproduce
 1. Create 3 languages
 2. Delete first
 3. Do products table and products_translation table as in O2M docs: https://docs.getdirectus.com/6.3.6/#Translation_(O2M)
 4. In the translation UI insert 'default language' ID 1 (the first language you've deleted)

**Comment by WellingGuzman** [comment]
@nmpribeiro I believe this is a good behavior, It can be confusing or seem like a bug, but I'm open to discuss this further.

**Comment by benhaynes** [comment]
Hey @nmpribeiro – I think I understand this issue. You're saying that you have multiple language options – and even though you have the first (id=1) set as the default, you think it should bypass that one because you've deleted it? Instead showing the next active item?

I actually agree with Welling here. Directus makes no assumptions about your architecture – including status/workflow. If you set the default to `1` – that is the default. Since the status (workflow) is completely customizable, "deleted" (actually "soft-deleted") is just a state. You can imagine if this were "draft" instead, then it could be useful to have the draft language be the default until it's ready to publish.

As Welling said, certainly open to discuss – but that's my take. I'll close this in the meantime unless this becomes an _actionable_ ticket. Either way, thank you for thinking this through! :)
