### ISSUE TITLE
Notifications go to page not found null/null

### ISSUE THREAD

**Issue by sfarrowGR** [directus/directus#13727]
### Describe the Bug

I have created a "Flow" (admin/settings/flows).  As the result of a the flow a user notification is created.

The notification generates and I see it in the side panel.  However, when I click the title of the notification is takes me to a page not found with an address of http://localhost:8055/admin/content/null/null.

This is a clean project.  The only thing I have done is create it, and add this flow.

### To Reproduce

1. Create a flow.
2. trigger with server start
3. Set operation to Send Notification
4. Add a user id etc.
5. Add a title and message.
6. Save flow.
7. In this case restart server.

The notice bell has a red indicator.  When clicked the side panel opens and shows the notification.  When the notification is clicked I get the error page.

### Errors Shown

none

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

SQLite

### What browser are you using?

Safari/Chrome/Fire Fox

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
Ref: https://github.com/directus/directus/pull/12522#issuecomment-1133015680

**Comment by azrikahar** [comment]
> Any progress with this "null/null-problem"? All notification links generated with Flows are broken...
> 
> Is there any open issue/PR/discussion about notifications optimization? Think I've seen something a while ago but can't find now...

No progress that I'm aware of yet, but it is one of the higher priority item on the list 👍

It does feel like this were brought up before, but I can't seem to find it as well, other than the original report & subsequent discussion in the Flows PR linked in my other comment above.

**Comment by ConnorSimply** [comment]
Has there been any forward movement on this? Would like to implement custom notifications and such with flows instead of just sending emails, but currently, the notification operation in the flows is not viable. Even if there were UI for notifications without a related item/comment, there isn't a way to set it in the operation, so it doesn't go to /null/null.

If there aren't any current plans for this, is there a way to expedite it?

@rijkvanzanten @azrikahar

**Comment by rijkvanzanten** [comment]
@ConnorSimply It's on our radar as something to do (which is why it's an open issue), but we have to prioritize based on community feedback and [sponsored work](https://docs.directus.io/getting-started/support.html#sponsored-work) first. Wanna open a PR to address the problem? That would be the very fastest way to get that resolved 🙂

**Comment by rijkvanzanten** [comment]
> I was going to make a PR for this, but right now there, it seems, there are 2 separate definitions of "notifications"—one on the front end, that show up as little dialog popups on the bottom right side, and are stored in the NotificationsStore. You can use the notify util to send one. The other kind are from the backend, and are stored in the database. They appear on the bottom left, and are what's sent from operations/flows, and mentions. Is that about right?

That's correct! The verbiage is a little confusing. That being said, the NotificationsStore holds both. The "full" messages in the bottom left are "Notifications", the little popup messages in the bottom right are "Snackbars" in terms of typing and internal naming

> These notifications have a subject and message, but there's no way to see the message, nor is there a way to mark as read, except for archiving. They don't get marked as read when you click on them. I was going to make a way to view the message part of the notification, but because there are already components named like "notification-group" and such, I'm....not really sure how to go about naming any new components.

True! The setup was originally only designed for mentions in comments, which in turn means they're only redirecting to the item you were mentioned in at the moment. We should indeed make it a more "full fledged" inbox type of interface. In terms of naming conventions, I think we should double down on the "snackbar" vs "notification" verbiage and refactor the current notification naming to snackbar equivalents to ensure we don't confuse the two even more

**Comment by rijkvanzanten** [comment]
Linear: [ENG-249](https://linear.app/directus/issue/ENG-249/notifications-go-to-page-not-found-nullnull)

**Comment by donni106** [comment]
any updates or roadmap on this?

**Comment by Anoesj** [comment]
> Linear: [ENG-249](https://linear.app/directus/issue/ENG-249/notifications-go-to-page-not-found-nullnull)

I cannot access this as an outsider. Was this comment meant for me or for internal use?

**Comment by donni106** [comment]
I was able to add a Flow after sending a notification that updates the notification with the missing `collection` and `item`. this way a click on the notification results in `admin/content/blog_posts/22` instead of `admin/content/null/null`!
anyone interest on how to do that?

**Comment by josephdpurcell** [comment]
@donni106 That's a fascinating approach. I didn't understand the underlying issue.

I would be very interested in how you accomplished that!

**Comment by rijkvanzanten** [comment]
> I was able to add a Flow after sending a notification that updates the notification with the missing `collection` and `item`. this way a click on the notification results in `admin/content/blog_posts/22` instead of `admin/content/null/null`! anyone interest on how to do that?

Very clever

**Comment by rijkvanzanten** [comment]
> > Linear: [ENG-249](https://linear.app/directus/issue/ENG-249/notifications-go-to-page-not-found-nullnull)
> 
> I cannot access this as an outsider. Was this comment meant for me or for internal use?

Linear is internal private notes / priority tracking 👍🏻

**Comment by donni106** [comment]
> @donni106 That's a fascinating approach. I didn't understand the underlying issue.
> 
> I would be very interested in how you accomplished that!

sure, I have created an additional step ("Daten aktualisieren") to my flow after sending a push notification ("Push senden").
in the step to send a push notification the name of the key is important. this is used as reference in the step to update the data. in my case this is `notification_c66o5` (you can rename it if you want). to update a push notification I needed to configure a "updater" with the collection "directus_notifications" and a specific id. this id is contained in the payload of the previous step under the mentioned key `notification_c66o5`, which is passed as an array. so the specific id our push notification can be retrieved per `{{notification_c66o5[0]}}`. now the data need to be passed to the collection in order to update it. in my case I set the `collection` and `item` from the values in the `$trigger` variable.

```
{
  "collection": "{{ $trigger.collection }}",
  "item": "{{ $trigger.key }}"
}
```

this way push notifications with `collection: null` and `item: null` get necessary values, that will be used by navigating when clicking in the overview of notifications.

|flow steps|key to use in update|update push notification|
|---|---|---|
|![image](https://user-images.githubusercontent.com/1942953/214267945-7001cd2e-1d64-4aa8-ba81-67ef98e680a0.png)|![image](https://user-images.githubusercontent.com/1942953/214279295-a7853bad-7e0d-4afb-96f3-0fe9f746fbd4.png)|![image](https://user-images.githubusercontent.com/1942953/214279320-452c2464-0879-4eed-8caa-0fdfb5186c78.png)|

any questions or parts I could elaborate a bit more precisely?

**Comment by Rifqi-Irfansyah** [comment]
> > @donni106 That's a fascinating approach. I didn't understand the underlying issue.
> > I would be very interested in how you accomplished that!
> 
> sure, I have created an additional step ("Daten aktualisieren") to my flow after sending a push notification ("Push senden"). in the step to send a push notification the name of the key is important. this is used as reference in the step to update the data. in my case this is `notification_c66o5` (you can rename it if you want). to update a push notification I needed to configure a "updater" with the collection "directus_notifications" and a specific id. this id is contained in the payload of the previous step under the mentioned key `notification_c66o5`, which is passed as an array. so the specific id our push notification can be retrieved per `{{notification_c66o5[0]}}`. now the data need to be passed to the collection in order to update it. in my case I set the `collection` and `item` from the values in the `$trigger` variable.
> 
> ```
> {
>   "collection": "{{ $trigger.collection }}",
>   "item": "{{ $trigger.key }}"
> }
> ```
> 
> this way push notifications with `collection: null` and `item: null` get necessary values, that will be used by navigating when clicking in the overview of notifications.
> 
> flow steps	key to use in update	update push notification
> ![image](https://user-images.githubusercontent.com/1942953/214267945-7001cd2e-1d64-4aa8-ba81-67ef98e680a0.png)	![image](https://user-images.githubusercontent.com/1942953/214279295-a7853bad-7e0d-4afb-96f3-0fe9f746fbd4.png)	![image](https://user-images.githubusercontent.com/1942953/214279320-452c2464-0879-4eed-8caa-0fdfb5186c78.png)
> any questions or parts I could elaborate a bit more precisely?

thanks for the code, the tutorial is fix for my project, but i cannot display the message of the notification

**Comment by Rifqi-Irfansyah** [comment]
@donni106 thanks i can fix my problem, but now i can not display message of the notification

**Comment by donni106** [comment]
> @donni106 thanks i can fix my problem, but now i can not display message of the notification

where do you mean is you notification message not displayed? and what was the case before you changed something? what have you changed?

**Comment by Rifqi-Irfansyah** [comment]
on the user account displays the notification, but only the title and timestamp, I'm confused where I can see the notification message

**Comment by paescuj** [comment]
> on the user account displays the notification, but only the title and timestamp, I'm confused where I can see the notification message

This has already been mentioned in https://github.com/directus/directus/issues/13727#issuecomment-1236230944 and got a response in https://github.com/directus/directus/issues/13727#issuecomment-1236345821.

**Comment by donni106** [comment]
> My goal is to inform the user if a hook has an error, so there is most likely no collection/item

@skuhnow and does this happen? is the user receiving you notification or not? if yes, what else would you like to achieve?

**Comment by skuhnow** [comment]
Yes, the user is receiving the notification (I need to refresh the page) but I can't see the message and if I click on it, I also get the null/null page. In the meantime I added a an Item, but I still don't see the message. 

Also, the notification is very subtle. I was hoping for a more prominent way like a dialog, toast or shoutout

I understand why, I've read https://github.com/directus/directus/issues/13727#issuecomment-1236345821
