### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by tmikaeld** [directus/directus#1373]
"The framework is void of any fixed Directus branding or styling"

But there is still some branding in the system:

Here: 
![screenshot_2017-03-17_01-09-27_pm](https://cloud.githubusercontent.com/assets/907195/24042607/08cd29fe-0b13-11e7-88be-05ad5b9c31f7.png)

And on a lot of files and comments in the source.

![screenshot_2017-03-17_01-12-40_pm](https://cloud.githubusercontent.com/assets/907195/24042721/894b9b88-0b13-11e7-929d-336c10a687cc.png)

![screenshot_2017-03-17_01-12-54_pm](https://cloud.githubusercontent.com/assets/907195/24042727/8c6b7a54-0b13-11e7-90b1-6417014e13e2.png)

![screenshot_2017-03-17_01-13-07_pm](https://cloud.githubusercontent.com/assets/907195/24042730/8f135d4e-0b13-11e7-9c21-a00800e0e409.png)

![screenshot_2017-03-17_01-13-27_pm](https://cloud.githubusercontent.com/assets/907195/24042733/918a517c-0b13-11e7-8d6e-0b7c7cbe5bf4.png)

**Comment by benhaynes** [comment]
Thank you for submitting this @tmikaeld. We'll update the "Directus Files" button to be brand agnostic asap.

As we discussed before, the code (classes and resource names) may not happen so quickly. Our goal is to create a CMS that can easily be branded to match any organization or corporate branding at the admin webapp level. At the developer level we still want to grow awareness for our platform and the best way to do this is to have some way for developers to know where it came from and to learn more about our framework. Since our codebase is open-source you always have the option to fork/change things – but we would hope that in most circumstances you would still give credit to our team/organization.

**Comment by tmikaeld** [comment]
Hello Ben,

It's ok if files and code take time.

Like with all OSS software we work with, we donate a lot and report a lot of issues and request features every day, that is what we hope to do with Directus as well. I hope you understand the issue with branding.

Midsized E-Commerce companies that we work with usually have employees that knows how to code basic stuff and check the source of a site. When they see the Directus branding, they will check up on it and they will determine that it's open source and that they can run it themselves or turn to you for setting up their custom solution (Since you are more qualified). Thus they don't need us as a third party and that can cost us a lot of money in lost prospecting effort.

**Comment by Zilus** [comment]
You can change the "Directs Files" under "api/locales/yourlocale.json"

**Comment by benhaynes** [comment]
I understand the concern here, some responses/thoughts:

1. "No fixed branding or styling" – this means that the Directus framework is not heavily styled with a proprietary design. It is minimal and brand agnostic, using desaturated colors except for color callouts as needed (red = serious, yellow = important, blue = CTA, etc). Other than a very small "Powered by Directus" on the login page (that can be removed, but we'd appreciate it staying) there is only a Directus logo that can be overridden with a company logo. This is a "best effort" to minimize our brand/impact so that others can apply their own style – not to "hide" the framework.

2. This is open-source software. You can always adjust the SCSS/CSS files to suit your style needs – especially easy with the SASS variables. You can also change most text through the translation file (or in the codebase) – allowing you to remove "Directus" if needed.

3. We won't take this to the 100% extreme because that is less clear for developers. For instance, removing the term "Directus" from the code. At a certain point it is useful to know if a table/feature/etc belongs to Directus... and so those things will be/remain appropriately named. Alternate, more agnostic, terms such as "system" would be more confusing.

4. We are free and open-source. Use the software as you will, but we invest a lot of time and energy into building this platform and don't have the "enterprise" dollars to market/advertise. So word of mouth, and direct exposure to our free (yet premium) product are our best options. In the end, if clients have tech savvy people that find out the platform is Directus – then they should still be able to see the value/need for the team that is setting up and extending Directus. Essentially this all boils down to one point:

*Open-source Directus is unbranded, not white-labeled.*

Happy to discuss further if needed. If anyone comes across a blatant button or component that says "Directus" please let us know and we'll try to resolve that.

**Comment by tmikaeld** [comment]
@benhaynes Thanks for the clarification, I understand that white-label is quite different and usually companies offer sub-licensing for such things and charge a fee to use it. But that is not allowed in this case due to GNU 3 licensing.
