### ISSUE TITLE
API: `_eq: null` does not return results

### ISSUE THREAD

**Issue by madc** [directus/directus#13778]
### Describe the Bug

I'm seeing a similar issue as described in #4386.

This request returns an empty array:

```gql
query ($locale: String, $slug: String) {
  page(filter: { translations: { slug: { _eq: null } } }) {
    translations(
      filter: { languages_id: { code: { _eq: 'en-US' } } }
      limit: 1
    ) {
      slug
      meta_title
      meta_description
      languages_id {
        code
      }
    }
  }
}
```

This request returns my page content:

```gql
query ($locale: String) {
  page(filter: { translations: { slug: { _null: true } } }) {
    translations(
      filter: { languages_id: { code: { _eq: 'en-US' } } }
      limit: 1
    ) {
      slug
      meta_title
      meta_description
      languages_id {
        code
      }
    }
  }
}
```

I'm not sure, if this is expected behavior, but I feel that `_eq: null` should be allowed. Otherwise a separate query is necessary to fetch data for a page without slug (i.e. startpage).

### To Reproduce

Request made with Insomina.

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

12.22.5

### What database are you using?

MySQL

### What browser are you using?

None

### How are you deploying Directus?

Running locally.

**Comment by azrikahar** [comment]
Note: this seems to be happening for REST as well. Was able to "patch" REST by adding an additional `|| (operator === '_eq' && compareValue === null)` over here:

https://github.com/directus/directus/blob/8f131b51565ebcf9f10427fd2577e742e619fd8c/api/src/utils/apply-query.ts#L407-L410

and adding `&& comparevalue !== null` here:

https://github.com/directus/directus/blob/8f131b51565ebcf9f10427fd2577e742e619fd8c/api/src/utils/apply-query.ts#L472-L474

but it might not be an ideal solution. 

For GraphQL, seems like passing `_eq: null` will always yield `undefined` instead of `null`. hence it'll skip over the `value === null` IF condition and throw the `InvalidQueryException` on line 107:

https://github.com/directus/directus/blob/8f131b51565ebcf9f10427fd2577e742e619fd8c/api/src/utils/validate-query.ts#L100-L108

**Comment by breuxi** [comment]
Confirming this!

**Comment by rijkvanzanten** [comment]
Use `_null: true` instead 👍🏻

**Comment by madc** [comment]
We have the exact same usecase using Nuxt as a framework. Our current workaround is a seperate GraphQL-query for the homepage, which works but is not very elegant.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-247](https://linear.app/directus/issue/ENG-247/api-eq-null-does-not-return-results)

**Comment by alex-cailler** [comment]
can fix this problem now ?

**Comment by rijkvanzanten** [comment]
> can fix this problem now ?

This is an open issue so PRs are more than welcome 🙂
