### ISSUE TITLE
Permission Field Preset with Dynamic Variable

### ISSUE THREAD

**Issue by piotr-cz** [directus/directus#13806]
### Describe the Bug

I'm not able to use *Dynamic Variable* as default field value with *Custom Role > Collection > Read > Field Preset*

Suspect commit: https://github.com/directus/directus/pull/10576#issuecomment-1003481572

According to Docs > Filter Rules > [Dynamic Variables](https://docs.directus.io/configuration/filter-rules/#dynamic-variables) it should work:
> Note: This feature is only available for permissions, validation, and **presets**. Regular filters and conditional fields currently only support the root ID.

Use case
I'm setting up Directus for multi-tenancy with single database where every user and content item has a field Organisation.
For new content Items I'd like to prefill Organisation's field value to Users' Organisation (and even hide if it's possible).

Extensive description is available here: https://github.com/directus/directus/discussions/9682#discussioncomment-2911547

### To Reproduce

1. Create new Data model (*News*) with field *my_email* as string
1. Create new Role (*Manager*) with App Access: *Enabled*, Admin Access: *Disabled*
1. Set Create Permission for News to *Use Custom*
1. Set Field Presets to
   ```json
   {
     "my_email": "$CURRENT_USER.email"
   }
   ```
1. Create new User with *Manager* role and log in
1. Go to Content > News > Create Item
1. See Dynamic variable key used instead of value

### Errors Shown

Value filled in as `$CURRENT_USER.email` instead

When field has type M2O (as described in Use case), an error pops up: `[Forbidden] You don't have permission to access this.` however I believe the root cause is in Dynamic Variables replacement issue.

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by piotr-cz** [comment]
Perhaps simpler reproduction is to
1. Create collection with type *DateTime*: `date_published`
1. Set *Field Presets* to
   ```json
   {
     "date_published": "$NOW"
   }

Dynamic Variable is not expanded - field value is `$NOW`

**Comment by azrikahar** [comment]
This turns out to be an App-only bug, but the API does work as usual since the referenced PR #10576 was only dealing with the App.

> When field has type M2O (as described in Use case), an error pops up: [Forbidden] You don't have permission to access this. however I believe the root cause is in Dynamic Variables replacement issue.

I believe this may indeed be a permission issue, since Dynamic Variables are working API side. Here's an example:

https://user-images.githubusercontent.com/42867097/173030989-d1a4de0b-457f-41e9-9bcc-28d77948f10f.mp4

Notice that even though the App does indeed show the "unparsed" dynamic variable `$CURRENT_USER.email`, it is _never_ sent to the API (since that's how default value in the App currently works), then the `$CURRENT_USER.email` is correctly parsed API side and show that the resulting item has the current user's email.

The same is happening for the DateTime reproduction 👍 so I'd recommend double checking your permissions settings (when it comes to relational fields) for this scenario if possible.

> Extensive description is available here: https://github.com/directus/directus/discussions/9682#discussioncomment-2911547

For the issue described here, the App is now truly affecting this use case since you need the organisation ID for the URL to be formed properly!

With that said, will get a PR up to fix this App side. Thanks again for the additional reproduction steps and elaborate descriptions.

**Comment by piotr-cz** [comment]
Thanks for looking into this and preparing a PR!

As I mentioned in https://github.com/directus/directus/discussions/9682#discussioncomment-2911547, I believe the *Forbidden* error comes up as an effect of having raw Dynamic Variable in a M2O type field at the time when form/ Item detail is opened.

As you mentioned, the Dynamic Variable might be expanded/ replaced when form is being saved, however at the time the error popup is shown, value is cleared just after this request:

```http
GET 403 /items/organisations/%24CURRENT_USER.organisation_id?fields[]=name&fields[]=id

Content-Type: application/json; charset=utf-8
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

Anyway I believe Your pull request will fix this case.
