### ISSUE TITLE
O2M relation does not display correctly

### ISSUE THREAD

**Issue by koksikus** [directus/directus#13836]
### Describe the Bug

After upgrading from 9.12.1 to the latest version, the O2M relationship does not display correctly. In the table view, you can not see the data only after entering a specific record, you can see the data with the ability to display a number of data (according to the new option). In the case of M2O, it displays all records even when there is no data, so it shows -- -- --
Also photos display badly, i.e. the icon of no photo even though the photos have never been there before.

### To Reproduce

install the latest version when you have this type of relationship... you will immediately see in the fields of these relationships

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by koksikus** [comment]
this solution #13772 looks great and it works, but I think because of this you can not see the data in the table view. One more thing - if we have an O2M relation and another relationship in it, the data from relations is visible only after saving, other fields are immediately visible.

**Comment by koksikus** [comment]
In the M2M relation is the same in the table view you can not see the data only after entering the record.

**Comment by rowild** [comment]
I can confirm a problem with m:m relationships: In a classic post - post_categories setup the category is not shown in the backend nor in the post's relational field not in the restAPI call. But creating the same category again throws an error (given the slug field was defined as unique). The category still exists within the DB (SQLite). 

![1](https://user-images.githubusercontent.com/213803/173197067-5502c1f1-de72-4516-967a-56ac6bff803a.jpg)
![2](https://user-images.githubusercontent.com/213803/173197068-b9ccb635-babf-45f0-88d8-223d474a3fd2.jpg)
![3](https://user-images.githubusercontent.com/213803/173197069-cd0a457f-4f86-4943-ac8a-70143917a962.jpg)
![4](https://user-images.githubusercontent.com/213803/173197070-e2b16e6d-6867-4ca6-9380-f4558713f74a.jpg)
![5](https://user-images.githubusercontent.com/213803/173197071-1157d907-decb-40de-be61-8202a8044d5f.jpg)

Same thing with another m:m table "tags".

Mac 10.15.6
Directus 9.1.12
Node 16.4.2
npm 8.5.0
yarn 1.22.18

**Comment by rowild** [comment]
I think at least my problem has to do with the fact that `posts` as well as `post_categories` have a field called `title` as their "main field". If this field is not shown in the list of data items, all categories are shown. Please have a look at the short video. I think a solution would be to rename the fields. But that would mean a lot of refactoring or even recreation of data, since the key cannot be renamed anymore

https://user-images.githubusercontent.com/213803/173197391-d302ffac-2e34-4fc0-b413-e3aa35a3c876.mp4


UPDATE

My problems disappeared after I removed the "Display Template" option in "Collection setup" (sorry, I am new and I still don't now, which "Display Template" is working for which field... anyway, I leave my comments just in case it helps somehow; please feel free to remove them again if you think this would be preferable. Thank you!)

![Bildschirmfoto 2022-06-11 um 19 13 16](https://user-images.githubusercontent.com/213803/173197920-6209d6ff-1509-4079-b15b-a27b7f1cbe5f.png)
