### ISSUE TITLE
(Minor) "Not visible" field in of accordion still shows accordion

### ISSUE THREAD

**Issue by aliemba** [directus/directus#13831]
### Describe the Bug

This scenario
![image](https://user-images.githubusercontent.com/44196248/173053692-3271dca7-7ba2-4935-b5db-9ecb2c475708.png)

Will show this
![image](https://user-images.githubusercontent.com/44196248/173053708-f36f38a6-048e-48ea-8c75-22c127841887.png)

It should not show the part of the accordion (although it does correctly not show the field)

### To Reproduce

Create an accordion. Add field. Hide field.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

v14.19.1

### What database are you using?

mysql  Ver 15.1 Distrib 10.5.13-MariaDB

### What browser are you using?

Chrome latest

### How are you deploying Directus?

local

**Comment by br41nslug** [comment]
As the accordion wraps around the input i think this is working as intended although it would be a nice-to-have improvement. To achieve the desired result here you'd need to hide the accordion itself instead of its content.
![image](https://user-images.githubusercontent.com/9389634/173058064-db414ad7-2c6a-4cdb-b14a-6da57bd3f691.png)
