### ISSUE TITLE
Can't select with autocomplete field

### ISSUE THREAD

**Issue by ansutung** [directus/directus#13860]
### Describe the Bug

I selected item but not effect.

https://user-images.githubusercontent.com/26163387/173274073-033e7647-b01a-4f9c-883a-863d67d91f7d.mp4

It's work well on version 9.10.x, but issues after upgrade.

### To Reproduce

Issue when click on item

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

12.18.3

### What database are you using?

MSSQL 14.0

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Seems like the `@blur="deactivate"` event for v-input (right when we select an option) is firing "earlier" thus causing any selection to not really register.

Note: as there was no code change to this interface since last year, went and confirmed that this used to work in 9.12.0 (specifically tested on `2f8c9aca`), so this is likely linked to the `vue` update in #13713.
