### ISSUE TITLE
incomplete database install: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list' after  database install

### ISSUE THREAD

**Issue by terion-name** [directus/directus#13914]
### Describe the Bug

Running directus in docker with migrations to setup some basic data. As by migrations docs set the cmd like this:
```
CMD npx directus database install ; npx directus schema apply ./schema.yml -y && npx directus database migrate:latest && npx directus start
```

Getting error at schema apply stage:
```
2022-06-15T20:26:48.140612681Z 20:26:48 🚨 select `collection`, `singleton`, `note`, `sort_field`, `accountability` from `directus_collections` - ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
2022-06-15T20:26:48.140643384Z Error: ER_BAD_FIELD_ERROR: Unknown column 'accountability' in 'field list'
```

Database after install has 15 directus tables, which is less then should be:
```
directus_activity
directus_collections
directus_fields
directus_files
directus_folders
directus_migrations
directus_permissions
directus_presets
directus_relations
directus_revisions
directus_roles
directus_sessions
directus_settings
directus_users
directus_webhooks
```

### To Reproduce

see description

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16

### What database are you using?

mysql

### What browser are you using?

brave

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
> As by migrations docs set the cmd like this:

What migration docs? If you're referring to https://docs.directus.io/extensions/migrations/#custom-migrations, that's for custom migration files (using knex migrations in JS), not schema migrations using the schema files. 

In this particular case, the error is thrown because the initial install of the database doesn't contain any of the migrations (and therefore reflects the database of v9.0.0 effectively). In this particular case, you're probably looking to set the command to 

`CMD npx directus bootstrap ; npx directus schema apply ./schema.yml -y && npx directus start`
