### ISSUE TITLE
UX issue: Import with auto increment (identity) PK

### ISSUE THREAD

**Issue by aaron-manning** [directus/directus#13983]
### Describe the Bug

The current UX is bad for importing data with auto-incrementing primary keys.
It's practically unusable for a non-technical user to maintain data after an import has been made because directus isn't setting the auto increment to reflect the highest PK value in any imported data.

### To Reproduce

Create some test data, eg a simple csv with one column for ID and the rows 1,2,3

Create a new table with an auto increment PK. It doesn't need any fields.
Import the data into the new table, which will succeed.
Now try add a new record for this table using the admin dash. it will fail with the error

```
The following fields have invalid values:

ID: Value has to be unique
```

This occurs because the auto increment has NOT been updated to reflect the imported data. Every attempt to insert a new record would fail until the system has incremented the sequence enough to exceed the id's found in the imported data.

The typical usecase for an auto-increment would be for the user to NOT need to go look through existing id's and manually set the ID of the new record, this is surely why the behaviour in directus for auto-increment fields is to be hidden / readonly by default.

Can we please get the importing logic enhanced to reset the auto increment (identity) to the highest value found in the collection once the import has succeeded?

The only other workarounds would be
1. Require dev intervention to create a migration to set the auto increment higher (or lower, using the negative number space) than the user would ever use in an import. This is the best option currently but is non-ideal.
2. Enforce a bad UX by forcing users to pick a PK value themselves, removing the benefit of auto-increment.
3. Disable the importing feature.

Thanks

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

14.18.1

### What database are you using?

postgres 14.3.2

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Should be the same as #6321 👍

**Comment by aaron-manning** [comment]
Directus should handle real use cases, not tick feature boxes to lure developers into adopting it, with no "planned" desire to make it usable.

I can understand this not being any priority (without funding), or not being feasible given the use of Knex, but not having a plan for a usable import feature for auto incrementing PK tables is concerning.

**Comment by aaron-manning** [comment]
@benhaynes are things like this really not planned for directus, or just need funding?

**Comment by benhaynes** [comment]
> @benhaynes are things like this really not planned for directus, or just need funding?

That ticket needs funding (to be sponsored), time (there are other tickets we need to handle first), or a PR (we welcome coordinated contributions to the open source project).

> Directus should handle real use cases, not tick feature boxes to lure developers into adopting it, with no "planned" desire to make it usable.

We're doing what we can to move the platform forward, with a very small and under-funded team maintaining an enormously complex project. Every fix (and feature that passes our 80/20 rule) is "planned" but the timelines are longer than we (or you) would like due to the above reasons.

I personally think your statement is a bit unfair. Unlike other commercial vendors, we pride ourselves in being product first (not marketing or sales) and give away both our core product and base cloud service for free (no sneaky corporate agenda). The bug of resetting pk auto increment was not intentional, and will be fixed based on our triage... but unless more people vote for that ticket it is just a little lower on the list. I hope all of this clears up our intentions/goals. ❤️

**Comment by aaron-manning** [comment]
@benhaynes thanks for clearing that up.

My concern was that these issues were being swept under the rug.
