### ISSUE TITLE
Getting '[RECORD_NOT_UNIQUE] Field "id" has to be unique.' when trying to create a new collection or add to an existing one

### ISSUE THREAD

**Issue by tjsheppard** [directus/directus#14009]
### Describe the Bug

On Directus Cloud, creating a new collection or a new field in a collection is responding with `"id" has to be unique` even though the id is unique.

### To Reproduce

I deleted a collection with the name and then tried to re-create it. It might be because of the names being the same but when I tried to reproduce it didn't work - Sorry I'm not entire why it is doing this!

### Errors Shown

`[RECORD_NOT_UNIQUE] Field "id" has to be unique.`

<img width="604" alt="Screenshot 2022-06-20 at 19 13 38" src="https://user-images.githubusercontent.com/18311489/174658431-eec77b19-2384-4867-8f1c-b2b55474e19f.png">

### What version of Directus are you using?

Directus Cloud

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

Brave browser and Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment]
This seems identical to #13850, so it should likely be a Directus Cloud specific occurrence instead of Directus itself.

For issues specific to Directus Cloud projects, please do reach out via the Live Chat so that our Cloud engineers can help look into this on their side. Alternatively, you can also email to [support@directus.io](mailto:support@directus.io) if that's preferred. Thanks! 👍
