### ISSUE TITLE
Flow filter does not work

### ISSUE THREAD

**Issue by zhex900** [directus/directus#14084]
### Describe the Bug

I am trying to read a collection by a query. Read by id returns a value. But query only returns `[]`. The query is correct. It works in graphql. 

````
{
  "filter": {
    "key": {
      "_neq": "netlify-site-name"
    }
  }
}
````

````
{
  "collection": "settings",
  "key": [],
  "query": "{\n  \"filter\": {\n    \"key\": {\n      \"_neq\": \"netlify-site-name\"\n    }\n  }\n}",
  "permissions": "$full"
}
````

### To Reproduce

Try to run the query for any collection.

I am using the hosted cloud. 

https://hyjo51vx.directus.app

### What version of Directus are you using?

v9.12.2

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

firebox

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
Hi, can you try the following steps and let us know does it work afterwards?

1. Go to the read operation
2. Click on the `Clear Value` for "IDs":

   
![image](https://user-images.githubusercontent.com/42867097/175520316-1b181d44-b289-4205-ad53-6c32c4340828.png)
3. Save
4. Try again and see does the query return items correctly

**Comment by zhex900** [comment]
All is good now. Thank you!

**Comment by azrikahar** [comment]
Thanks for confirming!

That said, the confusion caused here is because when we set a value to IDs and unset it, it turns in an empty array `[]` rather than actually undefined. 

This causes `!key` to be false, and it attempts to pass an empty array to readMany and return empty array:

https://github.com/directus/directus/blob/7a21f701ebb4a91c4ad8c25743f7d8a2ea7b355c/api/src/operations/item-read/index.ts#L45-L55

@rijkvanzanten thoughts on potentially mitigating this? perhaps flipping it to `if(sanitizedQueryObject)` then do read by query regardless of value of key? 🤔 

but then empty array is still a possibility. Or perhaps making tags turns to null when empty like how it does now?

https://github.com/directus/directus/blob/7a21f701ebb4a91c4ad8c25743f7d8a2ea7b355c/app/src/interfaces/list/list.vue#L302-L305

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten thoughts on potentially mitigating this? perhaps flipping it to if(sanitizedQueryObject) then do read by query regardless of value of key? 🤔

That'd work, or changing `if (!key)` to `if (!key || (Array.isArray(key) && key.length === 0))`
