### ISSUE TITLE
Flow doesn't trigger if it listen to a Directus_Collection event

### ISSUE THREAD

**Issue by nicolaschapeau** [directus/directus#14104]
### Describe the Bug

Hi,

I am trying to implement flows with my directus application.
I need them to trigger on user creation or files creation.
Nothing is logged on the directus interface, like if the trigger event was not happening.
I tried with custom collections and it worked.

### To Reproduce

Create a flow with an event trigger (items.create) on Directus_Files or Directus_Users.
Try to do an operation afterwards like console logging.

Nothing gets triggered when the event occurs. (+ No logs on directus interface right sidebar)

### Errors Shown

No error shown, like nothing happened 

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.13.2

### What database are you using?

postgre

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
Granted I'm not sure what's the difference in setup here, but I was not able to replicate this issue  (except `directus_files`, but reasoning is explained below):

https://user-images.githubusercontent.com/42867097/175841062-c4e249de-3f29-4503-a3e4-c1b41ce35583.mp4

Regarding  `directus_files`, the docs had actually pointed out that it does not currently emits `create` or `update` hooks: https://docs.directus.io/extensions/hooks/#action-events, so it's technically by design. The closest alternative for file creation events could be `files.upload` instead.

---

Questions:

- Are you using a filter or action hook?
- If you are using action hook, did you see similar error logs when "nothing happens" on your end?

   ```
   00:48:28 ✨ {"payload":{"role":"4727cce4-cb20-4377-beb8-20df9fb0cd56","email":"newuser@example.com","password":"password"},"key":"37600fc0-610e-4d4a-ba31-753751610d5e","collection":"directus_users"}
   00:48:28 ⚠️  An error was thrown while executing action "users.create"
   00:48:28 ⚠️  Transaction query already complete, run with DEBUG=knex:tx for more info
   ```

   FWIW I did saw this when testing 9.12.2 docker image, but the console log should still go through as seen in my logs above. This issue was tracked in #13747 and has been resolved for the next upcoming release.

   > Nothing gets triggered when the event occurs. (+ No logs on directus interface right sidebar)
   
   This should also be one of the symptom of #13747.

- Can you try using filter hook instead?  
- Have you tried restarting the Directus instance?
- Was this a fresh installation or upgraded from older existing Directus instance?

**Comment by nicolaschapeau** [comment]
Hi, thanks for replying.

I can confirm it's the same error as you mentioned.

![image](https://user-images.githubusercontent.com/32775238/176016500-857a5cb3-fd0a-4add-93a0-1e2a35b81017.png)

I am currently using an action hook, i don't really know what you mean by filter hook ? 
Do i need to create a webhook and see if it behaves to an user creation ?

**Comment by nicolaschapeau** [comment]
Yes it is ! Thanks.

It was an action event.
