### ISSUE TITLE
Deleted Items from one table of a M2M table set are still visible

### ISSUE THREAD

**Issue by krupper** [directus/directus#1413]
## Version Info
  - Directus version and branch: 6.3.8 master
  - PHP version: 7.1.4
  - MySQL version: 5.5.52-MariaDB
  - Web server: Apache

## Expected Behavior
The deleted items should be hidden.

## Actual Behavior
The deleted items are visible.

## Steps to Reproduce
 1. create a M2M table set via the ui (example: offers and categories with a bridge table) 
 2. delete an item from one table (example: from categories)
 3. get the api request 

Is this a bug or a feature? ;)

**Comment by WellingGuzman** [comment]
Hey @krupper does your table has `active` field? does the record has `active=0`?

Either way it's a bug ;)

**Comment by krupper** [comment]
Hi @WellingGuzman,  yes the m2m, offers and categories table have an active field. Something else catch my attention: all entries in the m2m table are automatically set to draft.

Thank you for your great software. I really like it! :)

**Comment by WellingGuzman** [comment]
Hey @krupper, it seems to be deleting when has `active` column, did you update the status value in your configuration?

About the draft as default, it's because it uses the column default value, which is 2 by default.

**Comment by benhaynes** [comment]
Hey @krupper – we've recently released version `6.4` where we resolved a similar issue. Could you test on the new version?

Unfortunately, because of our small team (and no real funding) we can only support our most recent version, so we won't be hotfixing 6.3.x any more. Instead we recommend that users upgrade to the newest version.

I'll close this because the API seems to be returning the correct values on 6.4... let us know if you still see the issue and we'll re-open.
