### ISSUE TITLE
Allow array of IDs passed to Notify operation in Flows

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#14273]
### Describe the Bug

I'm trying to send `Notifications` to users that are subscribers.

In my test I have two simple collections; `Pages` and `Subscriptions`. The second collection has one column named `user_id`. 

In my Flow I (1) trigger on created pages, (2) get all subscribing users and (3) send notifications. If I hard code a single user id in the user field it works, but if I use the Flow object it doens't create any notification at all.

Maybe it's because that object is an array with multiple user id's? But in the docs example it seems to be possible with emails... What is the correct syntax?

<img width="1063" alt="Skärmavbild 2022-07-04 kl  14 11 28" src="https://user-images.githubusercontent.com/20950568/177153148-97888a3f-1e55-41b8-adae-f1ab9740a029.png">
<img width="994" alt="Skärmavbild 2022-07-04 kl  14 11 41" src="https://user-images.githubusercontent.com/20950568/177153155-8a729f07-b5dd-41dc-afea-d016737b7296.png">

### To Reproduce

Se above

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

17.4.0

### What database are you using?

PG 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally with npm

**Comment by azrikahar** [comment]
Just as a heads up, the linked PR technically only brings the same capability of `To` in Email operation to the user IDs in Notify operation as an MVP.

Since "Read Data" operation returns an array of objects instead of an array of IDs, we will need something like #14391 (and to a certain extent, #13944) to make the original reported use case in this issue possible.

Another potential great improvement would be to sort of extract out the comment mentions logic as a more general interface (or shared logic) so that we can type username/email for Notify operation, and autocomplete emails for Email operation.
