### ISSUE TITLE
Time series panels automatically change their height

### ISSUE THREAD

**Issue by ravi-2912** [directus/directus#14281]
### Describe the Bug

In Insights in draw mode I have created panels like this

![image](https://user-images.githubusercontent.com/25941167/177197213-06f09dca-36b6-49ed-89e4-aed80aa982aa.png)

However on saving this, the time series panel automatically adjust its height, see image below.
![image](https://user-images.githubusercontent.com/25941167/177197272-338520a7-6317-4a84-8668-1298e1136887.png)

### To Reproduce

Create Panels in Insights.

### Errors Shown

None

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14.3.2

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
I can't seem to reproduce this locally, but can you share what was the step you were doing before saving? Since it seems like the save button is not enabled yet in your first screenshot. Seems very similar to what was reported in #13480, so it does feel like there might be a detail that we are missing here to reproduce this reliably.

Just to narrow down potential causes here, can you try clearing the cache _after_ you resize but _before_ you hit save? You can do so by using the `/utils/cache/clear` endpoint as an admin user: https://docs.directus.io/reference/system/utilities/#clear-the-internal-cache 👍 Thanks!

**Comment by ravi-2912** [comment]
Hi I ran this on local and had the same issue. The time series panel's bottom snaps to the bottom of right side panels. See this vide0 that shows the issue. Its a minor one, but I thought to report it. It might be feature you never know :). 

![Insights - Google Chrome 2022-07-05 11-38-51](https://user-images.githubusercontent.com/25941167/177310977-e7ffb939-4c8c-4bca-9f43-20e8e4df507d.gif)

**Comment by azrikahar** [comment]
Seems like a reliable way to reproduce this error is to ensure creating 1 higher/wider panel first, then create 1 shorter/narrower panel afterwards, so now the shorter/narrower panel is (wrongly) recognized as the furthest X/Y point of reference.

However since edit mode tries to add additional width/height to the workspace to give more space for new tiles, it "fixes" the workspace size for the panels to resize to their actual height/width.

## Height

https://user-images.githubusercontent.com/42867097/190962889-8640e92f-1874-44e3-9db3-17d5243bb4f5.mp4

## Width

https://user-images.githubusercontent.com/42867097/190962913-ed9ab00b-b101-4928-9150-02c2b0f82260.mp4
