### ISSUE TITLE
transform operator can not working if value is undefined.

### ISSUE THREAD

**Issue by imiskolee** [directus/directus#14330]
### Describe the Bug

transform operator can not working if value is undefined.

### To Reproduce

1. create a read data operator.
2. create a transform operator connect to this read data operator for convert single element array to object
transform rule is

```json
{
 "payload" : {{ $last[0] }}
}

```

### Errors Shown

I already debug from locally, the transform rule will be parsed to `{"payload" : undefined}` if empty result from read data. 
but `{"payload" : undefined}`  is not a JSON string, so got a exception. 

how can we change `undefined` to `null` ? 

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by br41nslug** [comment]
You're missing the quotes around the dynamic variable there:
```
{
 "payload" : "{{ $last[0] }}"
}
```
We can re-open the ticket if the issue persists with the updated rule 😄

**Comment by br41nslug** [comment]
Ah my bad sorry the payload template needed to be valid JSON at some point 😬 the transform operation is giving me a lot of trouble in testing this so re-opening this

**Comment by imiskolee** [comment]
> Ah my bad sorry the payload template needed to be valid JSON at some point 😬 the transform operation is giving me a lot of trouble in testing this so re-opening this

also take a look this https://github.com/directus/directus/discussions/14334 please.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-234](https://linear.app/directus/issue/ENG-234/transform-operator-can-not-working-if-value-is-undefined)

**Comment by paescuj** [comment]
Hey @imiskolee, just tested this and noticed that it can be fixed by putting quotes around the variable:
```json
{
 "payload" : "{{ $last[0] }}"
}
```

If an object is passed through, it will still remain an object (not sure if this has changed since you opened this report):
```json

{
  "payload": {
    "id": 1,
    "test": "1"
  }
}
```

If the object doesn't exist, you'll get the following (valid JSON):
```json
{
  "payload": "undefined"
}
```

You might also be interested in the ["Run Script" operation](https://docs.directus.io/configuration/flows/operations.html#run-script) which has been introduced in [v9.16.0](https://github.com/directus/directus/releases/tag/v9.16.0). In this specific case you could use it, for example, to throw an error if the object doesn't exist or to fallback to another value.
