### ISSUE TITLE
Markdown Custom Block renders 'null' value

### ISSUE THREAD

**Issue by herrowna** [directus/directus#14383]
### Describe the Bug

I wish to create custom blocks in my Markdown field, and found that the 'null' value is rendered in the suffix, even though I intentionally left it blank:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/6374909/178406380-38c0a836-ca3c-4aeb-98c9-27ad1b19c26e.png">

'Suffix' field intentionally left blank above.

https://user-images.githubusercontent.com/6374909/178406481-612a02b1-13a2-4fc2-ba0a-82e3fb71af2a.mp4

Upon rendering the 'Excerpt' custom block, the unwanted 'null' text appears in the Markdown field.

### To Reproduce

1. Create a Markdown field
2. Go to 'Interface' and scroll down to 'Custom Blocks'
3. Click 'Add custom syntax'
4. Name your custom block, and intentionally leave prefix or suffix blank.
5. Save the data model
6. Create a new instance of this data model, then insert the custom block in your Markdown editor.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

14.15.4

### What database are you using?

Postgres 12

### What browser are you using?

Firefox

### How are you deploying Directus?

PaaS (Digital Ocean, Ubuntu)

**Comment by azrikahar** [comment]
Can confirm this is happening on 9.14.1, albeit it shows `undefined` since I didn't set it when creating the custom block. Pretty sure OP's case is they remove it, hence `null`:

![chrome_iYDPAd8cnN](https://user-images.githubusercontent.com/42867097/178428100-8de7af7d-13bb-49ad-a292-05f42080cae4.png)

---

We'll likely need to modify these 2 lines here:

https://github.com/directus/directus/blob/9e387fe4b08b420fa1821a833c61db48c9926b65/app/src/interfaces/input-rich-text-md/edits.ts#L239

https://github.com/directus/directus/blob/9e387fe4b08b420fa1821a833c61db48c9926b65/app/src/interfaces/input-rich-text-md/edits.ts#L252

and prevent it from constructing the template literal string with null/undefined prefix/suffix.

**Comment by rijkvanzanten** [comment]
@herrowna I'd recommend configuring it as follows:

<img width="847" alt="CleanShot 2022-07-20 at 16 36 39@2x" src="https://user-images.githubusercontent.com/9141017/180077092-cb392e07-7108-4e7e-a784-df3cfbff8002.png">

That way, you can select existing text and auto-wrap it in the custom tag, for example:

https://user-images.githubusercontent.com/9141017/180077196-97656aa0-9343-4725-92d6-0a25736ed9c8.mp4

**Comment by herrowna** [comment]
@rijkvanzanten What a handy trick! Thank you for that
