### ISSUE TITLE
insights panel strange behaviour 

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#14397]
### Describe the Bug

After submitting an insight panel, the panels are rotating endlessly

![image](https://user-images.githubusercontent.com/102175921/178478332-454666d7-554b-428a-8c23-884bf449fe31.png)

many errors on the console

![image](https://user-images.githubusercontent.com/102175921/178478762-38285f28-f77c-4be4-9941-7fc637f52db7.png)

### To Reproduce

Insert a new panel into an existing or new dashboard.
Save the panel
Edit panels 
Save

![image](https://user-images.githubusercontent.com/102175921/178478332-454666d7-554b-428a-8c23-884bf449fe31.png)

### Errors Shown

none

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

directus cloud

### What database are you using?

directus cloud

### What browser are you using?

chrome and firefox

### How are you deploying Directus?

Directus Cloud

**Comment by rijkvanzanten** [comment]
@br41nslug This happens when a collection is used in some of these interface options that doesn't exist (anymore). The app expects the primary key to exist here, but that shouldn't be the case:

https://github.com/directus/directus/blob/06014b85dd063e7704506dfc09b8dd590f762baf/app/src/utils/query-to-gql-string.ts#L31

The solution here is to make sure that the insights engine strips out query items to collections that don't exist for the current user, and then show an error on those panels

**Comment by joselcvarela** [comment]
> @br41nslug This happens when a collection is used in some of these interface options that doesn't exist (anymore). The app expects the primary key to exist here, but that shouldn't be the case:
> 
> https://github.com/directus/directus/blob/06014b85dd063e7704506dfc09b8dd590f762baf/app/src/utils/query-to-gql-string.ts#L31
> 
> The solution here is to make sure that the insights engine strips out query items to collections that don't exist for the current user, and then show an error on those panels

This happens when we use "Metric" option with any `directus` table.
