### ISSUE TITLE
Permissions error on create_collections_item

### ISSUE THREAD

**Issue by mccombs** [directus/directus#14406]
### Describe the Bug

Creating collection via graphQL as an admin returns `You don't have permission to access this`

How can I not have access if I'm creating a new collection?

### To Reproduce

Auth in as an admin user and then run the following graphql query

```
mutation x {
    create_collections_item(data: {
        collection: "testimonials",
    }) {
        collection
    }
}
```

### Errors Shown

```
{
	"errors": [
		{
			"message": "You don't have permission to access this.",
			"locations": [
				{
					"line": 28,
					"column": 3
				}
			],
			"path": [
				"create_collections_item"
			]
		}
	],
	"data": {
		"create_collections_item": null
	}
}
```

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

18.4.0

### What database are you using?

SQLite

### What browser are you using?

Brave / Using Insomnia

### How are you deploying Directus?

locally

**Comment by mccombs** [comment]
And if there is any question about my role:
```
query me {
	users_me {
		id
		role {
			name			
		}
	}
}
```

This returns:
```
{
	"data": {
		"users_me": {
			"id": "a3d184f1-07dc-4492-9f31-43a361aad1fa",
			"role": {
				"name": "Administrator"
			}
		}
	}
}
```

**Comment by azrikahar** [comment]
Make sure to pass `meta` and/or `schema`, as described in the docs here: https://docs.directus.io/reference/system/collections/#create-a-collection

> TIP
>
> Make sure to pass an empty object for schema (`schema: {}`) when creating collections. Alternatively, you can omit it entirely or use `schema: null` to create ["folder" collections](https://docs.directus.io/configuration/data-model/#sorting-grouping).

The `You don't have permission to access this` error is technically due to collection not existing when it's reading the value to return as the response for the mutation request. Understandably that's too generic for situations like this even if it's for safety reasons. Improvements for error messages is discussed in #4368. 👍

With that said, #4368 will only clarify the collection was not created, but not exactly why. @rijkvanzanten currently the collections service does throw InvalidPayloadException when `collection` is not passed, but perhaps we can add an additional check to make sure at least one of `meta/schema` is passed? 🤔
