### ISSUE TITLE
429 Too Many Requests error on Cloud App

### ISSUE THREAD

**Issue by nonlinearcom** [directus/directus#14513]
### Describe the Bug

Hi, I've noticed on directus.cloud that if a collection has multiple images then the app fires lots of 429 errors. 
As @joselcvarela suggested, adding the loading="lazy" attribute to images could potentialy fix this issue.

### To Reproduce

<img width="523" alt="Screenshot 2022-07-19 at 16 47 14" src="https://user-images.githubusercontent.com/7942973/179782106-11a35940-5a1e-4dac-ba19-95b65a01fb3f.png">

### Errors Shown

<img width="586" alt="Screenshot 2022-07-19 at 16 47 39" src="https://user-images.githubusercontent.com/7942973/179782144-ea0b6447-3ede-41e8-b772-1021f6c2e65e.png">

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

12?

### What database are you using?

Postgres

### What browser are you using?

firefox

### How are you deploying Directus?

directus.cloud

**Comment by rijkvanzanten** [comment]
This is being resolved in https://github.com/directus/directus/pull/10592

**Comment by rijkvanzanten** [comment]
For reference: the problem here is that the `<img>` tags of the previews in the rows all render simultaneously, firing 12*3 = 36 simultaneous requests in this screenshot alone. This causes the images to run into the rate limiter of the api. By default, all API communication from the app goes through the single `api` axios instance that has a throttler enabled that ensures that the app never exceeds 10req/sec. The linked PR updates the `<img>` tag usage with a new `<image>` component that downloads / renders the images through the same `api` instance, ensuring that the rate limiter isn't hit
