### ISSUE TITLE
Current admin locale changes when updating project default language even when admin has a configured language preference

### ISSUE THREAD

**Issue by giovanni-ciccia** [directus/directus#14522]
### Describe the Bug

I added translations to Spanish(Latin America) for field names in my project. When I go to edit a collection and see if the field names are translated, they correctly show the translation in Spanish. However, if I leave the editor and then go back, the field names siwtch back to English. It is only after I refresh the page that the field names are shown correctly translated.

### To Reproduce

1. Go to Project Settings and change Default Language to Spanish (Latin America)
2.  Go to Data Model and click on the plus icon to create a new collection named Test
3. Create a new input called "field_name" on the newly created Test collection.
4. Click on the "field_name" field on the Test collection to edit it.
5. Click on "Field" on the side menu.
6. Click on "Create New" button under "Field Name Translations"
7. Select Spanish (Latin America) on the language drop-down menu
8. Enter the word "translation" in the translation input
9. Click on the save button to save the translation, then to save the changes made to the field
10. Click on "Content" on the side menu, then click on the "Test" Collection
11. Click on "Create Item"
12. You should see the input is called "Field Name" (the original name) instead of "translation" (the translation we gave it)
13. If you refresh the page, the translation appears correctly
14.  Go back to "Data Model" and click on the "Test" collection as if you were to edit it again
15. Now go back to "Collection" and try to create a new "Test" item
16. You should see that the field name changed back to English

### Errors Shown

No errors

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 13.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker container on Azure Kubernetes Service

**Comment by azrikahar** [comment]
> 11. You should see the input is called "Field Name" (the original name) instead of "translation" (the translation we gave it)

I wasn't able to reproduce this as it still shows "translation", but for step 14-16 _after_ doing a refresh (at the `1:09` timestamp of the video below), I can confirm this does happen 👍

https://user-images.githubusercontent.com/42867097/179896759-ee3d802a-8ba7-4592-8354-fa21b53a3e63.mp4

Very likely this is also what was reported in #13795 but now the reproduction steps are much clearer. Thanks!

**Comment by giovanni-ciccia** [comment]
I also just realized, it´s not only the field names that change back to English, the whole interface does too (You can see it in the video at around 1:21, the side menu is in English)

**Comment by giovanni-ciccia** [comment]
It looks like the bug disappers if you also change the language under User Preferences (besides changing the default language in Project Settings).

**Comment by azrikahar** [comment]
@giovanni-ciccia before doing step 1 in the reproduction steps, what was the configured language for the user? Was it **English (United States)** (`en-US` raw value) or **Default Language** (empty/null raw value)?

I'm now wondering if the "bug" is that when changing the project default language, it _should not_ switch the language if the user already has configured their language.

The reason why it's always changing to English _after refresh_ should likely be due to the admin has `en-US` configured, which technically behaves correctly to override the default Spanish with English.

Here I tested the same reproduction steps again but ensuring the user has no language set (it should show "Default Language"), and now it stays as **Spanish (Latin America)** even after refreshing:

https://user-images.githubusercontent.com/42867097/180952537-ea57fc7a-7992-4561-a78a-945de36a47e2.mp4

**Comment by giovanni-ciccia** [comment]
Yes, it looks like that was the problem, my bad. Thanks for the support!
