### ISSUE TITLE
Flows - Webhook / Request URL - weird content-type 

### ISSUE THREAD

**Issue by stefanovalentegva** [directus/directus#14547]
### Describe the Bug

I've got a bizarre behavior using **Flows** and **Webhook / Request URL** operation (https://docs.directus.io/configuration/flows/operations/#webhook-request-url)

If  I put in the **Request body** `{{ $trigger}}`
![image](https://user-images.githubusercontent.com/92720697/180156227-c7227505-964d-4d0d-a56c-4b4e8eb913cf.png)

the content-type of the request is **application/json** but if I put another json as for example `{ "a": 1 }` (or even something else more complicated) 
![image](https://user-images.githubusercontent.com/92720697/180156475-4f7be645-7249-4a7f-a3c2-81ef95124f4a.png)

the content-type is **application/x-www-form-urlencoded** and not the expected **application/json**.

### To Reproduce

Create a non blocking Flow triggered on item.create and item.update scope.
![image](https://user-images.githubusercontent.com/92720697/180157559-a723bb7f-6fea-42bd-b8eb-8e4f8ea8add4.png)

As first operation use a **Webhook / Request URL** (https://docs.directus.io/configuration/flows/operations/#webhook-request-url) with method POST. As URL you can use https://webhook.site/. 

![image](https://user-images.githubusercontent.com/92720697/180158724-b6617599-9121-496a-b987-56ca53f06d41.png)

![image](https://user-images.githubusercontent.com/92720697/180159074-e04f1ab8-c10c-4855-9c5a-0d9576d41691.png)

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

v16.15.1

### What database are you using?

mysql:8 or 5.7.mysql_aurora.2.07.2

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
I believe what's happening here is when you were using `{{$trigger}}` as the request body, Axios sets it as `application/json` by inspecting the payload:

> Setting the Content-Type header is not required as Axios guesses it based on the payload type.
> Link: https://github.com/axios/axios#formdata

However when you typed `{"a": 1}`, it is technically sent as a string to the Webhook/Request URL operation hence the default `application/x-www-form-urlencoded` content type is sent: https://github.com/axios/axios/blob/64dcec5e41b834b74ac8cda47b4eefa69ff25c83/lib/defaults/index.js#L12-L14. You can confirm this by sending `"{{$trigger}}"` which forces it to become a string instead.

If you'd like to send it as a JSON fully knowing you are sending a proper JSON payload, you can add the header manually:

![chrome_C7Cu11G1A1](https://user-images.githubusercontent.com/42867097/180183496-2ed73bc8-daba-4504-a2c2-c8fbbcce8dbe.png)

That said, one possibility is we can do the additional "attempt to parse as json" in the operation so that it will automatically send it as `application/json`, but once again the payload is intentionally allowed to be arbitrary (Ref: https://github.com/directus/directus/pull/12522/commits/2245a5675937d511e645e9250a7402353aa6c9e5). Or perhaps alternatively this can be noted in the docs.

**Comment by stefanovalentegva** [comment]
Thank's @azrikahar it's all clear. I can confirm that with forcing the header it works as expected.

I think the problem here is the the docs.
In "[Webhook / Request URL](https://docs.directus.io/configuration/flows/operations/#webhook-request-url)"  it says:

> Request Body — Set the request body data, using any string or JSON.

and since it says JSON the content-type is expected to be **application/json**.

Maybe could be an option add a checkbox "sand as json" and if checked force the JSON parsing.
