### ISSUE TITLE
Related data not fetched correct

### ISSUE THREAD

**Issue by studiovlijmscherp** [directus/directus#1458]
## Version Info
  - Directus version and branch: 6.3
  - PHP version: 7.1.0
  - MySQL version: 5.6.34
  - Web server: MAMP / Apache 
  - OS name and version: macOS 10.12.4

## Expected Behavior
Fetch or display all related (table) data like the first node in the JSON output

## Actual Behavior
Only the first node of the JSON output contains als related (table) data

## Steps to Reproduce
I have 4 tables (and pivots for M2M):
1. place -> fields: name, label, M2M properties (pool, parking, etc)
2. property_groups ->  fields: name, M2M properties  (pool, parking, etc)
3. properties ->  fields: name, label, M2M property_groups
4. category (hotel, camping, etc) -> fields: M2M property_groups

Each place has multiple properties (pool, parking, etc.). Each property belongs to one or more property_groups.
Each place belongs to a category (hotel, camping, etc.). And each category has one or more property_groups.

When I fetch a place, not all related data is returned, only related data for the first node. The properties node for example, does only return the property_groups it belongs to - for the first node/property.

place -> property -> pool -> property_group [data]
place -> property -> parking -> ... no [data], but property_id (it seems)
place -> property -> terras -> ... no [data], but property_id (it seems)

I have attached JSON output for 1 'place':
[place.json.zip](https://github.com/directus/directus/files/986588/place.json.zip)

**Comment by WellingGuzman** [comment]
Hey @studiovlijmscherp, I will be working on this, sorry it took me weeks to reply, but I wonder were you using API 1.1 or 1.0?

A minimal schema to replicate this issue would be helpful.

**Comment by studiovlijmscherp** [comment]
Hi, no problem. Using api v1.1

This more usefull? 
![schermafbeelding-2017-05-24-om-09 23 14](https://cloud.githubusercontent.com/assets/3353713/26391510/5c3f567c-4063-11e7-8291-857d071220ea.jpg)

**Comment by WellingGuzman** [comment]
@studiovlijmscherp Yeah, that would do. I want to ask you this; did you change the `depth` level param? that's the way we pick how many level deep to fetch more data.

**Comment by benhaynes** [comment]
Hey @studiovlijmscherp – apologies for the late response here. We have been _very_ busy getting ready for the release of 6.4.

Your schema printout is helpful, but could you please send the SQL you're using to help us save time? That also helps because it ensures we're seeing the same thing (no slight differences in column/interface setup).

More importantly, could you please try this same schema/issue on version 6.4 to see if the problem persists? There are _many_ differences in the codebases and this issue might have already been solved in the newer version.

Thank you!

**Comment by benhaynes** [comment]
Hey @studiovlijmscherp – we're released 6.4 and the API seems to be returning values correctly now. We're seeing complete relational objects nested within the returned JSON. The depth parameter does seem to have an issue though, so I'll open a new ticket for that now.

I'll close this ticket, please upgrade to `6.4` and let us know if your issue is now resolved.
