### ISSUE TITLE
Comments/revisions/shares uses ID `+`  initially for content items

### ISSUE THREAD

**Issue by khunsatant** [directus/directus#14608]
### Describe the Bug

Comment not shown after post comment succeed.  I found that the api request is wrong.
in my case the item should be 21 (primary key) but app just sent value “+” instead.

`http://localhost:8055/activity?filter[collection][_eq]=employee&filter[item][_eq]=%2B&filter[action][_eq]=comment&sort=-id&fields[]=id&fields[]=action&fields[]=timestamp&fields[]=user.id&fields[]=user.email&fields[]=user.first_name&fields[]=user.last_name&fields[]=user.avatar.id&fields[]=revisions.id&fields[]=comment`

<img width="1679" alt="Screen Shot 2022-07-24 at 22 47 10" src="https://user-images.githubusercontent.com/18061895/180655447-42f93e08-3836-477f-af3b-339266c53e8b.png">

### To Reproduce

1. just go to item page and post some comment.
2. after post succeed, comment not show.

### Errors Shown

no error, just no data (comment data not found)

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

v16.15.1

### What database are you using?

Mysql 8.0.29

### What browser are you using?

Brave

### How are you deploying Directus?

running Locally

**Comment by azrikahar** [comment]
Seems to be related to the fix for singletons in #14542. Removing `if (unref(loading)) return '+';` does resolve this, because the `collection` and `primaryKey` prop in `<comments-sidebar-detail>` component is not reactive (hence it will only load id `+` one time):

https://github.com/directus/directus/blob/16fbe743fe68093f6931ede4aebce487e9b3aa3e/app/src/modules/content/routes/item.vue#L345-L352

However removing that line may undo the original singleton fix. 

Technically can be resolved by using `toRefs(props)` in `<comments-sidebar-detail>`, however for revisions (and comments + shares if we do use reactive fix) for example, they do now load and filter by `+` first, before reloading again for the actual ID. So we may need to revisit the fix used.
