### ISSUE TITLE
Validation of relational field fails

### ISSUE THREAD

**Issue by tb-lbi** [directus/directus#14680]
### Describe the Bug

When a field on a collection "A" has a field with many-to-one relationship with a collection "B" and the field on collection "A" has a validation filter that references any of the sub fields on collection "B", the validation fails.

### To Reproduce

Create a collection collection_b with field b_field. Create an item in collection_b where b_field is set to "value". Create a collection collection_a with field a_field where a_field has a many-to-one relationship with collection_b. Go the the validation tab for a_field and add the filter a_field -> b_field equals value. If you try to add an item to collection_a where a_field is set to reference the item in collection_b, validation will fail.

### Errors Shown

{
	"errors": [
		{
			"message": "\"a_field\" must be of type object",
			"extensions": {
				"code": "FAILED_VALIDATION",
				"field": "a_field"
			}
		}
	]
}

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud instance

**Comment by rijkvanzanten** [comment]
This is caused by the fact that the validation only runs against the _submitted_ values, not the whole stored item, and that relational IDs aren't automatically expanded to its nested values. For example, if you submit `author_id: 1` to the API, it will fail validation `{ name: { _eq: 'Rijk' }}` as the literal value `1` isn't an object with a field `name`. 

This is currently working as intended, though it's (obv) causing quite a bit of confusion. There's a lot of other open issues and discussions around this topic, and it's something that we're aiming to improve in the short term 🙂 

(cc @br41nslug look another one!)

**Comment by azrikahar** [comment]
Related issue regarding the validation for relational fields: #8228 👍
