### ISSUE TITLE
Warn users when leaving page with unsaved changes

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1476]
This used to work, but has been disabled/broken in 6.4

Should work on all edit pages, including modals

**Comment by WellingGuzman** [comment]
Another thing to discuss here is, what happens if there unsaved changes and the user goes inactive for x minutes and the cms tries to log it out? should stay or force the log out?

**Comment by benhaynes** [comment]
Force logout. There used to be a notification that came up with 1 minute remaining... Let's make sure we have that still. 

Eventually this issue will be solved by the "save progress" feature...

**Comment by WellingGuzman** [comment]
This has been implemented now, the issue now is that some interfaces mark changes incorrectly or set values by default which make it weird when you just enter into a new item and just leave the page right after.

Ex: Creating new users, the first option is set by default because it can set any null values.

Which bring to another question, should we let the user group be default to null? and let the admin pick the group whenever they want, this prevent the unsaved changes and creating an user in a unwanted group by mistake.

**Comment by benhaynes** [comment]
There are a few interfaces (or pages) where I *always* get this message – even with no changes made. Let's come up with a solution to avoid this so we can mark this as complete.

ATTN @WellingGuzman @rijkvanzanten

**Comment by WellingGuzman** [comment]
The interfaces having problem with unsaved changes were fixed by https://github.com/directus/directus/commit/6d39af7acfe02413ade3c5141cc11e3dc2d0d254

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/2bf7fced7537a103c4c432ba4efcb160803aa95a

We still need to keep an eye on updated/new interfaces to make sure we make unsaved changes in the correct way.
