### ISSUE TITLE
Custom Endpoint Error when trying to order by Datetime field

### ISSUE THREAD

**Issue by TomSmedley** [directus/directus#14772]
### Describe the Bug

Ordering by a datetime field in my custom endpoint is giving the response:
```
{
    "errors": [
        {
            "message": "rootSort.map is not a function",
            "extensions": {
                "code": "SERVICE_UNAVAILABLE"
            }
        }
    ]
}
```
This is the code for the API:
```
const query = {
      fields: ['*', 'layers.*'],
      filter: {
        ...(id && {
          id: { _eq: id },
        }),
        ...(createdBy && {
          createdBy: { _eq: createdBy },
        }),
      },
      page: +page || 1,
      limit: +limit || 100,
      sort: 'createdTimestamp',
    }

    flowersService
      .readByQuery(query)
```
Removing `sort: 'createdTimestamp'` returns the results adding it returns the error. This is the field in the CMS:
![image](https://user-images.githubusercontent.com/95056193/182119478-cbd51642-a91e-40d4-831a-163f98adebe6.png)

### To Reproduce

Create a datetime field in a custom endpoint and try to sort by it.

### Errors Shown

```
{
    "errors": [
        {
            "message": "rootSort.map is not a function",
            "extensions": {
                "code": "SERVICE_UNAVAILABLE"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by TomSmedley** [comment]
With `ItemsService` and unlike the RestAPI the sort needs to be passed as an array.

**Comment by azrikahar** [comment]
Although an array is indeed expected, I'm wondering can we perhaps make it more consistent.

The error stems from the `.map()` in `applySort()` here:

https://github.com/directus/directus/blob/9e2ffb9bc9a52622a8bdfcb7b64fde711eaddfb7/api/src/utils/apply-query.ts#L222

as it's trying to map on a string rather a string array. The reason why it worked via the API is likely due to `sanitizeSort()` here:

https://github.com/directus/directus/blob/173069ac5f113df98aa27e48258178b824a057eb/api/src/utils/sanitize-query.ts#L90

where the `.split(',')` (sort of indirectly) turns `'myfieldtosort'` to `['myfieldtosort']`.

Perhaps wrapping [`toArray()` util](https://github.com/directus/directus/blob/main/packages/shared/src/utils/to-array.ts) on `query.sort` before it's passed to `applySort()` will resolve this issue? @rijkvanzanten thoughts on this?

**Comment by rijkvanzanten** [comment]
@azrikahar I'd rather keep the internal services strongly typed. The REST API has to accept all sorts of "garbage", as everything is technically coming in as a string. That makes it a little more open than the other interfaces like GraphQL or the SDK. That being said, we could consider running the query validator inside the items service, instead of right before it's being used (like we're doing right now), so you get better error messages
