### ISSUE TITLE
When searching for a related collection to filter by, its fields are not shown

### ISSUE THREAD

**Issue by giovanni-ciccia** [directus/directus#14851]
### Describe the Bug

I have a Test collection with a Many to One relation with a collection called Related Collection. The Test collection also has 20 other "dummy" input fields. The Related Collection has three input fields. I am trying to filter the Test collection by the value of "field 1" in its related collection. However, when I search for Related Collection in the filter search bar, I don't see the arrow that lets me select any of its fields.

### To Reproduce

[directus_bug_repro.webm](https://user-images.githubusercontent.com/95232949/182905358-89f09427-5e50-40e1-95b4-1801632385ab.webm)

### Errors Shown

No errors

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 14.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
This might be because of the current filter logic performed by the search in `<v-field-list>`:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/components/v-field-list/v-field-list.vue#L89-L101

is being passed to `useFieldTree` composable:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/components/v-field-list/v-field-list.vue#L59

but the filter only applies to the current fields in the current collection, without any children or related collection fields:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/composables/use-field-tree.ts#L55-L63

so it may need to be filtered upstream in `<v-field-list>` instead, sort of like how the filter logic for search in `<v-select>`:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/components/v-select/v-select.vue#L294-L314
