### ISSUE TITLE
Interface Options in Conditions not working properly

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#14875]
### Describe the Bug

1. When creating a Button Links field and adding a condition to it, the Interface Options allows us to create new links for that condition:

    ![Bildschirmfoto 2022-08-05 um 14 37 30](https://user-images.githubusercontent.com/46492597/183078702-3832dc09-7fe5-4a22-b64c-769ef0c51e40.png)

2. Clicking on that Create New button, the interface loads a wrong notice instead of a URL-Input:

    ![Bildschirmfoto 2022-08-05 um 14 37 39](https://user-images.githubusercontent.com/46492597/183078785-7b525e22-3973-41e3-9225-536e3242653b.png)

### To Reproduce

see above

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

N/A

### What database are you using?

N/A

### What browser are you using?

N/A

### How are you deploying Directus?

N/A

**Comment by azrikahar** [comment]
I believe this is more so something to do with Interface Options itself (as `collection` prop is null), rather than specific to button conditions. Similar to what was found in https://github.com/directus/directus/discussions/10612#discussioncomment-1845360.

Example Interface Options for M2O field:

![chrome_y3ymUnYxHT](https://user-images.githubusercontent.com/42867097/183361094-51295584-cd07-422f-a5f8-80e344b36e7c.png)
