### ISSUE TITLE
Can't download own file

### ISSUE THREAD

**Issue by nervusdm** [directus/directus#14870]
### Describe the Bug

As a admin (full access), I can't download a file I uploaded.
Even If I refresh the page in a collection.

### To Reproduce

Create a collection, add a file field.
Upload a random file to the collection in this field.
Try Download it.
![download-error](https://user-images.githubusercontent.com/4217180/183042514-063bdddd-ef58-4a03-a18c-f1d190a56622.gif)

### Errors Shown

403

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

6.4.16

### What database are you using?

mysql

### What browser are you using?

edge

### How are you deploying Directus?

localy

**Comment by nervusdm** [comment]
I can download it from the files system.
But not from the collection files system.

**Comment by JonathanSchndr** [comment]
I think it's because the link within the collection is missing the ?download parameter. I can create a PR.

**Comment by nervusdm** [comment]
> I think it's because the link within the collection is missing the ?download parameter. I can create a PR.

Thanks for the answer.
I believe it's not about this, maybe I am wrong , if so, sorry.

If I try to open the link  (copy and past ) I have a json error: (

{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}

 I am admin.

**Comment by JonathanSchndr** [comment]
> If I try to open the link (copy and past ) I have a json error: (

No, the error is already correct, because you do not pass the tokens when calling the URL.

**Comment by nervusdm** [comment]
You mean if I add ?access_token=MYTOKENPRIVATE ?
For now the only workaround I have is allow read file from public in role configuration

**Comment by JonathanSchndr** [comment]
> You mean if I add ?access_token=MYTOKENPRIVATE ? For now the only workaround I have is allow read file from public in role configuration

Short explanation: There were 2 errors in total. In the backend the ?download parameter was not attached to the asset URL and the token was missing. This is corrected in the PR above. Your mistake now was that you thought that you can open the URL directly in the browser to call the file via the API. But this is only possible if the rights are set to public, because otherwise you have to pass a token like with all other API actions. Here you pass the JWT token or a static token. Of course you still have to do this to access the image via the API as long as it is not public. ( sorry *long explanation :D )

**Comment by michael-scheurer** [comment]
To sum up, the working solution is

`<your-domain>/assets/<file-id>?download&access_token=<token>`
