### ISSUE TITLE
Allow duplicate items in M2M and M2A interfaces

### ISSUE THREAD

**Issue by Le4Q** [directus/directus#14938]
### Describe the Bug

It is not possible to add the same item multiple times in M2M and M2A interfaces. It was possible before the relational interfaces rework 9.9.0 for M2A interfaces.

### To Reproduce

1. Create an M2M or M2A interface in collection A relating to collection B. 
2. Enable adding existing items. 
3. Create an item of collection A. 
4. Create an item of collection B and add it to the relational field of A.
5. In the relational interface, choose "Add existing".
6. The item of collection B that was already added is filtered out from the list to add existing items.

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

14.15.1

### What database are you using?

MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Just for context (based on what I understood from the convo on Discord), I believe this is meant as a potential enhancement to add an interface option to make it possible to select duplicate items, since currently it will always filter out the current item by default via `_nin`:

https://github.com/directus/directus/blob/fb79224d7af1b0b2df290529a22f4200110d0d11/app/src/interfaces/list-m2m/list-m2m.vue#L296-L302

**Comment by rijkvanzanten** [comment]
This should be implemented as a new feature on the interfaces: "Allow Duplicates" 👍🏻

**Comment by azrikahar** [comment]
Closing as this has been resolved by #14987.
