### ISSUE TITLE
Can't import (to postgres) exported (from sqlite) CSV

### ISSUE THREAD

**Issue by abenz1267** [directus/directus#14997]
### Describe the Bug

Can't import an exported CSV file.

### To Reproduce

Export data via Directus' export function from sqlite. Try to import it into a fresh postgres database.

### Errors Shown

"This file's data structure doesn't match the collection."

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

lts

### What database are you using?

postgres11, sqlite

### What browser are you using?

chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
> To Reproduce
> Export data via Directus' export function from sqlite. Try to import it into a fresh postgres database.

What collection are you exporting/importing from/to? If it's not a system collection, does the fresh postgres database have the same schema for said collection before importing? If it's a custom collection, would you mind sharing a schema snapshot? Can you share the CSV file used?

> Errors Shown
> "This file's data structure doesn't match the collection."

Understandably this is what's shown in the browser or app, but is there some detailed/verbose error logs shown in the _terminal_?

**Comment by abenz1267** [comment]
Hi,

sadly the console didn't give me any more information, BUT....

i played around a bit, checked out the exported CSV.... tried importing via PSQL's COPY....

turns out: it couldn't be imported because of a missing data in a related collection. So i had to import that first.

Is it not possible to create a complete dump from sqlite to postgres? Do i really have to export and import every collection manually?

Regards

**Comment by azrikahar** [comment]
> turns out: it couldn't be imported because of a missing data in a related collection. So i had to import that first.

Ah that makes sense. I believe this is exactly the same as #13286 now.

> Is it not possible to create a complete dump from sqlite to postgres? Do i really have to export and import every collection manually?

There isn't a complete "import/export"-like dump feature currently, but I do understand that'd be very helpful. Feel free to share your thoughts on this in #14763 as well.

> I also noticed that sometimes the export dialog doesn't always include all available fields. Sometimes IDs are missing..sometimes other fields. Even simple string fields at times.

That might be related to #14572 🤔 but the export fields does, or at least should, follow the current fields/columns shown in the current table. If you think #14572 is different, feel free to open a new issue with a minimal reproduction steps since sometimes it can be difficult to replicate a particular bug without narrowing it down first 👍
