### ISSUE TITLE
Display Template in the Collection Setup of related collection not working in content items page

### ISSUE THREAD

**Issue by NigmaX** [directus/directus#14995]
### Describe the Bug

defining a display template under the collection setup won't show the wanted value under the display of the default collection

### To Reproduce

- create 2 collections (a, b)
- define a display template for the collection "a"
- create an m2o relation from "b" to "a"
- create an item on the collection "b" and populate it with the collection "a"

expected:
under the content list collection "a" will show the Display template that was set up under collection setup

actual: 
under the content list collection "a" will show the "id" (primary key) and not the "Display template"

### Errors Shown

-

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
This is likely due to the tabular layout using `<render-display>` which depends on the display used by said field:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/layouts/tabular/tabular.vue#L28-L41

rather than the "expected" `<render-template>` used when viewing elsewhere like M2O interface:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/interfaces/select-dropdown-m2o/select-dropdown-m2o.vue#L22-L26

Though it feels like supporting this use case may not be truly 80/20 on the table layout as this would mean multiple columns onto the _same_ related collection _without_ displays configured would then show the same display template, rather than the individual field values? @rijkvanzanten thoughts on this?

**Comment by rijkvanzanten** [comment]
The individual columns on the tabular layout are single displays that can be configured. From what I can tell, everything is working as expected. The M2O field holds a single primary key, so that's what's displayed by default when no display is configured for the field (raw value). You can configure the _Related Values_ display on the M2O field to have it render nested relational fields based on a/the display template 👍🏻
