### ISSUE TITLE
When updating an entry in O2M, only the modified values are shown before saving

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15120]
### Describe the Bug

In an item with an O2M field, we normally see the related items with the chosen fields.
If we modify one (or more) fields of the related item and click on Save, before saving the parent item,
among the chosen fields. we only see the modified fields.

_May have some connections with #13537 which is different_

### To Reproduce

1. Parent collection with O2M to Child collection with 2 or more fields.
2. Choose 2 or more fields of the Child collection that are to be seen on the Parent item
3. Add some Child items to the Parent item. Save the Parent item.
4. Open the Parent item, click on one of the Child item
5. Modify one or more, but not all the fields that are going to be seen on the Parent item. Save the Child item<br/><br/> => **Only the modified fields are visible** <=<br/><br/>
7. Save the Parent item
8. Reopen; the modifications of the Child item appear now as expected within all the fields that  are seen on the Parent item

### Errors Shown

At stage 5, not all the expected fields that are to be seen on the Parent item do appear: only the modified one(s)

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment]
I was sure there was already another ticket of this too but cannot find it atm.

**Comment by rijkvanzanten** [comment]
@br41nslug feels similar to https://github.com/directus/directus/issues/8030

**Comment by azrikahar** [comment]
I assume the "chosen" fields here meant the fields used for the interface's display template? I was able to replicate it on the latest version:

(where `B1 | Description 1` becomes `B1 edit | --`, hence the description became missing)

https://user-images.githubusercontent.com/42867097/186169437-96752b33-17d3-4359-a361-92d14c4c43c7.mp4

But it also seems like the PR #15221 does resolve this, hence I've linked it as such. Do let me know if the issue is actually something else:

https://user-images.githubusercontent.com/42867097/186169424-a4e5d176-e9ad-40ac-9f24-186dbd450caa.mp4

**Comment by Pachat** [comment]
Here is an animation with the problem:

1. Before editing, the O2M record is `Simpson  202-555-0194`
2. It is edited, and `email@company.com` is added
3. After saving the editing, only `email@company.com` is seen
4. After saving the parent item, then, and only then, the whole O2M is seen `Simpson  202-555-0194 email@company.com`

![When updating an entry in O2M, only the modified values are shown before saving #15120](https://user-images.githubusercontent.com/13746133/186189580-ebf64f1e-8170-43fd-b4ff-0a864addbf1e.gif)
