### ISSUE TITLE
Relationship fields don't display in table view interface

### ISSUE THREAD

**Issue by u12206050** [directus/directus#15154]
### Describe the Bug

Seems like the PR was changed during the course of its life time since relationship values don't display. :)

PR coming in now.

### To Reproduce

Use the table view on a o2m interface. Add a column choosing a field on one of the relationships. It should show like this `topic -> name` for example.

Got to an item and view the table, notice the values don't display.

### What version of Directus are you using?

9.16.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally & GCP

**Comment by azrikahar** [comment]
Interesting! It was actually a direct refactor of your original code `value: field` to `value: field.field` in https://github.com/directus/directus/pull/12820/commits/733499683941ef79eab014a71d91b7b8ac3271dd#diff-fda8466b5a0ceaaab1d9164198b2994b0a1afd9e9dc19c2ad05231f10f510cc3R343 since the destructuring was crashing the app 😄

**Comment by samspi** [comment]
Any update on this?
