### ISSUE TITLE
Unable to upload .docx files (API 1.1 or web interface)

### ISSUE THREAD

**Issue by stevepatter** [directus/directus#1520]
The type field in directus_files is too short for .docx files. These files report as 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' (72 characters) but the type field is only 50 characters and cause database-insertion errors due to the field length

Directus master, commit hash 2890e9d473a8cd9bb99a9782265b29f28627718b 
Ubuntu, Apache with PHP 5.6

Tested both through the API createFile & by uploading through the web-admin frontend.

Suggested resolution: alter the directus_files table for a longer 'type' field. May as well use 100 characters to allow padding & remain as a round number.

**Comment by benhaynes** [comment]
Interesting. This will also cause issues in the GUI since we sometimes show this as the file-type (when in reality we'd want to see `docx`). @WellingGuzman any thoughts on how to resolve this? Obviously we can increase the length of that column, but should we try to parse/simplify that document type of leave it as its default?

**Comment by WellingGuzman** [comment]
@benhaynes I talked to @stevepatter and the problem here (not tested) it's that the `type` column only allows 50 characters, but the mime type for docx is 71 characters. After reading the RFC, mime types allow up to 255 characters. 

To get this fixed, we will have to set the length to 255 to play it safe

**Comment by benhaynes** [comment]
Perfect. Let's push this change to 6.4. We can also hotfix it to 6.3.x if needed... but 6.4 should be released within a week or so.

**Comment by WellingGuzman** [comment]
Something to notice is that the error is only thrown by mysql when strict mode is enabled, otherwise mysql will automatically truncate the string to fit 50 characters.
