### ISSUE TITLE
Impossible to display field from related table on an imported database

### ISSUE THREAD

**Issue by MickaelNoselProximum** [directus/directus#15235]
### Describe the Bug

I installed directus on an already existing project with an already existing database. Then when i have wanted to configure a list of elements link with another table and try to display the name from the other table it does not work on the list if I choose "Related value" and a column. It only work if i let the default configuration who display the id.
![list](https://user-images.githubusercontent.com/82378763/186368945-713d9f4a-44f7-4d7b-b4ee-6187bc5a4358.jpg)

### To Reproduce

- Having an already existing database with at least two table linked
- Install directus
- Go to Settings
- Go to Data Model
- Choose a elements with for example a Many To One relation
- Click on the relation field link to the other table
- Click on "Display"
- Choose "Related value"
- In the "Display Template" input fill with the name of the other table you want to display in the list
![display](https://user-images.githubusercontent.com/82378763/186368834-6ee0a0f8-0cb2-48a3-8f0d-8ba3053e1db3.jpg)
- Click on "Content" on the main menu
- Choose the table you just configure
- You can see now the list with your external field fill with "--" and not the value you wanted to have
![list](https://user-images.githubusercontent.com/82378763/186368906-2a218a40-e296-4f88-a9ac-afae8c36991c.jpg)

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Kubernetes cluster on GCP

**Comment by br41nslug** [comment]
I was able to reproduce this on a fresh database as well.

**Comment by rijkvanzanten** [comment]
Mind sharing a minimal Postgres database dump where this is happening? I tried setting up two new tables in Postgres directly with a foreign key constraint between the two, and things seem to operate as expected on my end.

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the given information, so I'll this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by MickaelNoselProximum** [comment]
Like i said the table needs to be created before directus (or outside directus). This is a serious problem.

Here is a minimal postgres. database dump : 
`CREATE TABLE public.community (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    domain character varying(255) DEFAULT ''::character varying NOT NULL,
);`

`CREATE TABLE public.community_configuration (
    community_id integer NOT NULL,
    primary_color character varying(255) DEFAULT NULL::character varying,
    secondary_color character varying(255) DEFAULT NULL::character varying,
    logo character varying(255) DEFAULT NULL::character varying,
);

ALTER TABLE ONLY public.community_configuration
    ADD CONSTRAINT community_configuration_pkey PRIMARY KEY (community_id);

ALTER TABLE ONLY public.community_configuration
    ADD CONSTRAINT fk_c50d3abafda7b0bf FOREIGN KEY (community_id) REFERENCES public.community(id);`

**Comment by azrikahar** [comment]
> I tried setting up two new tables in Postgres directly with a foreign key constraint between the two

> Like i said the table needs to be created before directus (or outside directus).

@MickaelNoselProximum Judging from the words "directly" and "foreign key constraint between the two", I believe it was in fact before and outside of Directus!

That being said, I do notice the minimal postres db dump you shared to be a bit odd, with how `community_configuration` doesn't have it's own autoincrement primary key, as well as `community` itself doesn't have primary key, so running your last ALTER TABLE statement causes error. I assume this is an unintentional incomplete copy/paste.

I've went ahead and use the following slightly modified statements instead:

```sql

CREATE TABLE public.community (
    id serial primary key,
    name character varying(255) NOT NULL,
    domain character varying(255) DEFAULT ''::character varying NOT NULL
);

CREATE TABLE public.community_configuration (
    id serial primary key,
    community_id integer NOT NULL,
    primary_color character varying(255) DEFAULT NULL::character varying,
    secondary_color character varying(255) DEFAULT NULL::character varying,
    logo character varying(255) DEFAULT NULL::character varying
);

ALTER TABLE ONLY public.community_configuration
    ADD CONSTRAINT fk_c50d3abafda7b0bf FOREIGN KEY (community_id) REFERENCES public.community(id);
```

I've then done the following general steps to attempt to reproduce your issue:

1. Run the sql statements above to create `community` and `community_configuration` tables in a new Postgres database.
2. Bootstrap the database with `npx directus bootstrap`.
3. Go to Settings -> Data Model, and see that `community` and `community_configuration` are marked as database-only.
4. Click on `community` to configure it as a collection, then click on all fields to configure them.
5. Click on `community_configuration` to configure it as a collection, then click on all fields to configure them. For `community_id`, make sure to use select "name" as the Display Template in Display tab during field configuration.
6. Create an item in Community collection.
7. Create an item in Community Configuration collection, and select the previously created Community item in Community ID m2o field.
8. Go back to the Community Configuration table layout view, see that it is shown as "Community A" (the name of the newly created Community) instead of the numeric ID only.

Some of the steps like configuring other fields may be omitted, but I've done them just for demo purposes.

However I can't seem to reproduce this. Here is a quick screen capture from Step 3 onwards (didn't show the first 2 steps for brevity):

https://user-images.githubusercontent.com/42867097/187125243-4c5c270b-8b8b-4320-9262-a73c90d35d0d.mp4

**Comment by MickaelNoselProximum** [comment]
It is not id serial primary key but a sequence created to have the auto increment value for the id. The database was created thanks to symfony entities.

**Comment by MickaelNoselProximum** [comment]
The reason was that i did not have an id with auto increment in the community_configuration table. This is weird but fine if someone fall into that, this is the solution ;)
