### ISSUE TITLE
SQLite default value sets wrongly Toggle false as false, not 0 when created via endpoint extension

### ISSUE THREAD

**Issue by gubarez** [directus/directus#15264]
### Describe the Bug

You could see a screenshot of the DB values. I believe, the proper values must be 0 or 1. Note, in the screenshot, the 0 value was in the UI afterwards.
![image](https://user-images.githubusercontent.com/925134/186646464-8295a0cb-7579-4c2f-9523-5dff9dcbf195.png)

Field configuration (as Toggle).  
![image](https://user-images.githubusercontent.com/925134/186646713-1bbc1d31-5df2-40db-92f8-b62d575578b8.png)

**Note, I haven't tried with default value true, but I gues it would behave the same way.**

I am not sure whether it is related, but sometimes I have the by default disabled Nullable checkbox being enabled without user intervation and app restart. (Tripple checked)

### To Reproduce

Create a Toggle (boolean) field and set Default Value, make the field not required. Then add a record via endpoint extension without setting a value of the Toggle field.

```
export default {
    id: 'demo',
    handler: async (router, { services, exceptions, getSchema }) => {              
        const schema = await getSchema()
        const { ItemsService } = services
        const callsService = new ItemsService('calls', { schema })
        await callsService.upsertOne({
                title: 'Test record',
                //toggle field not set
        })
    }
}

```

### Errors Shown

no error messages

### What version of Directus are you using?

16.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

SQLite 3.38.5

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by licitdev** [comment]
Replicated the issue on SQLite and not in PG.
The default value inserts as `1` when field is newly created.
After editing the field and toggling the non-nullable state, the default value becomes a `true` or `false` string instead of a numeric value of `1` or `0`.

Tested with following, added a route to prevent crash on load due to missing collection.

```js
module.exports = {
	id: 'demo',
	handler: async (router, { services, getSchema }) => {
		router.get('/', async (req, res) => {
			const schema = await getSchema();
			const { ItemsService } = services;
			const callsService = new ItemsService('calls', { schema })
        		const callID = await callsService.upsertOne({
                		title: 'Test record',
                		//toggle field not set
		        })
			res.send(`Inserted: ${callID}`);
		});
	},
};

```

**Comment by azrikahar** [comment]
> Replicated the issue on SQLite and not in PG.
The default value inserts as `1` when field is newly created.
After editing the field and toggling the non-nullable state, the default value becomes a `true` or `false` string instead of a numeric value of `1` or `0`.

This sounds exactly like the findings here: https://github.com/directus/directus/issues/14356#issuecomment-1179914039, where this'll only happen upon updating said field on SQLite. 👍

Let's close this in favor of tracking this same bug in #14356.
