### ISSUE TITLE
Impossible to display field from related table on an imported database

### ISSUE THREAD

**Issue by MickaelNoselProximum** [directus/directus#15274]
### Describe the Bug

I installed directus on an already existing project with an already existing database. Then when i have wanted to configure a list of elements link with another table and try to display the name from the other table it does not work on the list if I choose "Related value" and a column. It only work if i let the default configuration who display the id.
![list](https://user-images.githubusercontent.com/82378763/186368945-713d9f4a-44f7-4d7b-b4ee-6187bc5a4358.jpg)

### To Reproduce

Here is a minimal postgres. database dump : 

```sql
CREATE TABLE public.community (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    domain character varying(255) DEFAULT ''::character varying NOT NULL
);

CREATE TABLE public.community_configuration (
    community_id integer NOT NULL,
    primary_color character varying(255) DEFAULT NULL::character varying,
    secondary_color character varying(255) DEFAULT NULL::character varying,
    logo character varying(255) DEFAULT NULL::character varying
);

ALTER TABLE ONLY public.community_configuration
    ADD CONSTRAINT community_configuration_pkey PRIMARY KEY (community_id);

ALTER TABLE ONLY public.community_configuration
    ADD CONSTRAINT fk_c50d3abafda7b0bf FOREIGN KEY (community_id) REFERENCES public.community(id);
```

- Having an already existing database with at least two table linked
- Install directus
- Go to Settings
- Go to Data Model
- Choose a elements with for example a Many To One relation
- Click on the relation field link to the other table
- Click on "Display"
- Choose "Related value"
- In the "Display Template" input fill with the name of the other table you want to display in the list
![display](https://user-images.githubusercontent.com/82378763/186368834-6ee0a0f8-0cb2-48a3-8f0d-8ba3053e1db3.jpg)
- Click on "Content" on the main menu
- Choose the table you just configure
- You can see now the list with your external field fill with "--" and not the value you wanted to have
![list](https://user-images.githubusercontent.com/82378763/186368906-2a218a40-e296-4f88-a9ac-afae8c36991c.jpg)

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Kubernetes cluster on GCP

**Comment by gkibria** [comment]
Hi, I have similar issues regarding relationship on existing database tables. After some research, I found that there is a system table "directus_relations" that is not automatically populated on existing tables. When I manually populate the relations in that table, it works.
![Screenshot 2022-08-26 at 13 39 41](https://user-images.githubusercontent.com/7963363/186896158-bf41c5a4-01e7-48fd-82f1-31ffe688a9b7.png)
The above screenshot, I configured m2o relationship between drug_brand and drug_generic tables. I think directus is yet to support auto magic relationship on existing tables.
Thanks

**Comment by azrikahar** [comment]
@MickaelNoselProximum Let's keep the discussion in the same issue #15235 instead of opening a new duplicate one 🙂 I have shared my attempt at reproducing this issue over here: https://github.com/directus/directus/issues/15235#issuecomment-1229770896 as well.

Understandably you may have opted to open a new duplicate issue because you have yet to receive a reply in that thread. However, triaging the myriad of issues/PRs/discussions does take time, thus responses may not be as immediate every now and then. Hope that's understandable 👍

---

@gkibria This does sound similar to OP's case, but I wasn't able to reproduce this as seen here: https://github.com/directus/directus/issues/15235#issuecomment-1229770896. If you can share a minimal and working dump of the 2 tables with the foreign key constraint used, that'd be very helpful!
