### ISSUE TITLE
Conditions wouldn't allow to aggregate into relation collection fields 

### ISSUE THREAD

**Issue by NigmaX** [directus/directus#15300]
### Describe the Bug

when trying to apply a condition to a field based on a relation collection field value, there is no dropdown arrow to select the fields.

<img width="830" alt="Screen Shot 2022-08-29 at 7 58 52" src="https://user-images.githubusercontent.com/8597752/187126402-eb558dbe-2725-4c31-a3c0-a76fc76d7550.png">

### To Reproduce

crate collection named collection_test_a
crate collection named collection_test_b
create in collection_test_b field name type

create in collection_test_a field named test_b (m2m with the collection_test_b)
on the junction collection that was created create a field named showOnTypeA
try to put a condition on it referring to the type field on collection_test_b 

expected:
there should be a dropdown showing collection_test_b fields

actual:
no dropdown shown and it selects the id by default

### Errors Shown

none

### What version of Directus are you using?

latest

### What version of Node.js are you using?

latest

### What database are you using?

mysql

### What browser are you using?

chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment]
This was an intentional change in PR #14818, as seen in this comment here: https://github.com/directus/directus/pull/14818#pullrequestreview-1060822769, because conditions with relational fields doesn't work properly at the moment (specifically when the relational field only contains the related primary key).

Hence the PR disables relational collection fields for validations & conditions temporarily, before their respective issues (#11775 and #8228) gets fixed. 

You can subscribe to #8228 specifically for conditions with relational fields 👍
