### ISSUE TITLE
Special flags not set when configuring db-only fields

### ISSUE THREAD

**Issue by gisostallenberg** [directus/directus#15335]
### Describe the Bug

The properties specified in the OAS of an **item** are not always cast to the type in the API response.

Snippet of OAS:
```
"active": {
    "nullable": true,
    "type": "boolean"
}
```

Actual
```
{"data":[{"id":1,"active":1}]}
```

Expected
```
{"data":[{"id":1,"active":true}]}
```

### To Reproduce

N/A

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

N/A

### What database are you using?

N/A

### What browser are you using?

N/A

### How are you deploying Directus?

N/A

**Comment by br41nslug** [comment]
Would you mind answering the following questions:
- **What database are you using?**
- **How are you deploying Directus?**

As this could be database dependent

**Comment by rijkvanzanten** [comment]
I haven't been able to reproduce this based on the given information, so I'll this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Comment by gisostallenberg** [comment]
Using mysql and running directus as a docker container.

I'm not saying it should return a boolean from the API per se. I mean the OAS is from the same environment. So if the API for an item is going to return an integer because of the database used, the OAS should say that items property return type will be an integer, right?

**Comment by rijkvanzanten** [comment]
What version of MySQL are you using? Was this field configured through Directus or directly in the database/

**Comment by gisostallenberg** [comment]
So now there's two issues:
* When creating a toggle field from an existing db column the casting is not set
* When a fields _interface_ is boolean the OAS types it as boolean, although when no cast is set the API is going to return an integer

**Comment by azrikahar** [comment]
> I found out that in that case the 'special' column will not be set to 'cast-boolean', while it will be set to 'cast-boolean' when creating a toggle through directus.

Nice catch 👍 Can confirm this is the case for `special` column (I indicated which toggle is created via app or db in their name):

![Antares_g9weHxwghy](https://user-images.githubusercontent.com/42867097/189585906-3de2bfdd-823d-4923-a328-537af7c4817d.png)

(interface _should_ be null since we didn't "pick" it like how the field creation flow does)

I believe it's because when we create fields via the app, it does set `field.meta.special` according to the type:

https://github.com/directus/directus/blob/5f3f44a38667a3ae111043e45d9cbf8a98ab0a1b/app/src/modules/settings/routes/data-model/field-detail/store/alterations/standard.ts#L14-L32

However when we configure a db-only field, it will only pass an empty `field.meta` object to update (or upsert in this case) the new field:

https://github.com/directus/directus/blob/5f3f44a38667a3ae111043e45d9cbf8a98ab0a1b/app/src/modules/settings/routes/data-model/fields/components/field-select.vue#L311-L313
