### ISSUE TITLE
github login not usable in login to project page

### ISSUE THREAD

**Issue by cnschu** [directus/directus#15389]
### Describe the Bug

If you use the "github login" to create an account at https://directus.cloud/, it is not possible to use this account to login to any project page. any project page should also provide a "github login".

### To Reproduce

1) go to https://directus.cloud/login
2) click "login with gitHub"
3) authenticate via github
4) logout from directus
5) go to a project page (like https://hrrmmfg8.directus.app/)
6) there is no option to use the "github login", so it is impossible to login with the account created in step 1 - 3

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

https://directus.cloud/

### What database are you using?

https://directus.cloud/

### What browser are you using?

Crome

### How are you deploying Directus?

https://directus.cloud/

**Comment by azrikahar** [comment]
Hi @cnschu! Similar to #15388, this sounds like a cloud specific issue so I'll pass this along to our cloud team as they will be more suited to look into this matter 👍

For future inquiries or issues pertaining to Directus Cloud projects, do kindly reach out through the Live Chat in our Cloud Dashboard as that's the best channel to get assistance with your Cloud projects 🙂

**Comment by cnschu** [comment]
Ok.
Can you please elaborate on the matter (why is it an installation specific problem?)
I trust your judgment on that, but a little more information would be nice. So i can understand what is the error made by the cloud team that resulted in this error. So that i can avoid making the same mistake with my own installation of the software.

**Comment by azrikahar** [comment]
> Ok. Can you please elaborate on the matter (why is it an installation specific problem?) I trust your judgment on that, but a little more information would be nice. So i can understand what is the error made by the cloud team that resulted in this error. So that i can avoid making the same mistake with my own installation of the software.

It is primarily because there are other elements at play here, such as the Cloud Dashboard & the cloud infrastructure as a whole, so this particular scenario isn't technically isolated to Directus itself (in other words, the Directus cloud projects). This prompts the need to forward this to the cloud team for further clarifications/investigations 👍

Just to clarify, when opening an issue, there is also the following notice in the form:

> For issues specific to Directus Cloud projects, please reach out through the Live Chat in our Cloud Dashboard.

for reasons such as this issue and to reduce potential ambiguity 👍 Understandably some bugs with the Directus App/API can still very much possibly be in core (this repo), and when that is confirmed/investigated to be the case, they will definitely be moved back into here as a ticket.

---

That being said, to elaborate on the matter after receiving clarification from the cloud team, this is actually working as intended. The GitHub login logs you in to the Cloud Dashboard, but isn't being used to login users into individual Directus instances/projects. If there is any docs/descriptions that brought about this confusion, do let us know so that we can try to describe it clearer. Single Sign-On (SSO) into your Directus projects is currently only available in Enterprise Cloud as listed in the pricing page: https://directus.io/pricing. Hope that helps!
