### ISSUE TITLE
Empty create/edit drawer form for O2M/treeview relations

### ISSUE THREAD

**Issue by icalvin102** [directus/directus#15407]
### Describe the Bug

Creating or editing treeview items is broken in the newest version of directus (v9.17.1)

Clicking the edit icon on existing items or clicking `Create New` to create a new item opens a empty edit form without any form controls.

https://user-images.githubusercontent.com/40042006/188514686-054cecf7-8f5f-4d24-986a-e5a853c34923.mp4

### To Reproduce

- Create new data model (name: `trees`)
- Add string field (name: `title`)
- Add treeview field (name: `children`, collection: `trees`, foreign_key: `parent`)
- Goto `Collections` > `Trees`
- Create new Tree
  - Click `Create New` on `Children` field

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

SQLite

### What browser are you using?

Brave,Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
This seems to be caused by #14605, as the `<v-form>` was moved into the `<template v-if="junctionField">` level and since there's no junction field for tree view relation, the form is never rendered.

Example of reverting the position of `<v-form>` back out from the template to confirm the regression in #14605:

https://user-images.githubusercontent.com/42867097/188550970-ca3f0009-4404-4805-a2b9-01186755c1d7.mp4
