### ISSUE TITLE
Empty data at second min/max aggregation request

### ISSUE THREAD

**Issue by lubrst** [directus/directus#15415]
### Describe the Bug

There is a collection `test` with the auto-generated timestamp field `date_created` and some items.

If I perform this GET request: `/api/items/test?aggregate={"max": ["date_created"]}`, I get this response:

```json
{
    "data": [
        {
            "max": {
                "date_created": "2022-09-06T07:13:48.747Z"
            }
        }
    ]
}
```

I perform the same request multiple times after the first request, I get this response:

```json
{
    "data": [
        {
            "max": {
                "date_created": {}
            }
        }
    ]
}
````

It seems like a problem with the cache (I use redis 7.0.4) and timestamps/dates with min/max aggregation.
If I disable the cache, I get the expected data for all requests.

### To Reproduce

Make sure to enable caching via `CACHE_ENABLED=true` first.

1.  Create a new collection with a timestamp field.
2.  Add an item to the collection.
3.  Perform GET request: `/api/items/collection_name?aggregate={"max": ["timestamp_field"]}`
4.  Perform the same request again.

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome, Edge, Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Can confirm it's related to caching, even just with memory cache:

https://user-images.githubusercontent.com/42867097/189049094-215a0a98-197f-447a-975b-cc48cb3accbc.mp4

I believe it's due to the compress util added in #14855, where `Date` which is an object, is passing this condition:

https://github.com/directus/directus/blob/4d465764a19c6ca7482239f94dc7b27e10bd9484/packages/shared/src/utils/compress.ts#L54-L61

Hence dates/times are being compressed into an empty object `{}`.

I tried to patch it with the following code _before_ the `typeof part === 'object'` condition, where it checks whether it's a valid date via date-fns' `isValid()`, and uses the same piece of code as `typeof part === 'string'` to encode the date as an iso string:

```js
                // the original array check
		if (Array.isArray(part)) {
			// ...
		}
		
		// new check for date/times
		if (typeof part === 'object' && isValid(part)) {
			const value = encode((part as Date).toISOString());

			if (strings.has(value)) {
				return {
					type: Types.STRING,
					index: strings.get(value)!,
				};
			}

			const index = strings.size;

			strings.set(value, index);

			return {
				type: Types.STRING,
				index,
			};
		}
		
		// the original object check
		if (typeof part === 'object') {
		    // ...
		}
```

and it _seemed_ to work:

https://user-images.githubusercontent.com/42867097/189053131-956f52f4-e2f3-48fd-bf9b-a7bd6884d315.mp4

but not 100% sure if there's a cleaner approach. cc @rijkvanzanten

**Comment by rijkvanzanten** [comment]
@azrikahar We should serialize the date as a "regular json timestamp" (which uses iso8601/rfc3339 if not mistaken) 👍🏻
