### ISSUE TITLE
Translation string performance

### ISSUE THREAD

**Issue by bcartier** [directus/directus#15501]
### Describe the Bug

In projects with many translation strings, there's a UI blocking delay every time the Directus app loads in the browser (logging in, opening a Collection Item in a new tab, etc. The delay is caused when parsing the strings, not the network API request to retrieve the translation string values. 

I think the translation strings should be aggressively cached, and not re-requested or parsed every time Directus is opened a tab/window. 

 

### To Reproduce

1. Create many translation strings (like localized values for a large checkbox tree, for example)
2. Observe the impact on performance waterfall in browser dev tools

### Errors Shown

None

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

16.17

### What database are you using?

MySQL

### What browser are you using?

Chrome, Safari on macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
Related, though not the same: https://github.com/directus/directus/discussions/15503

**Comment by rijkvanzanten** [comment]
@br41nslug I think we can be smarter about this, and only download / parse the translations applicable to the current configured language rather than all. That already cuts _at least_ 50% of the data that's processed. We do have to re-fetch and parse on language changes in that case. 

Especially hopeful we can maybe use this as a reason to seriously R&D https://github.com/directus/directus/discussions/7277 as well. It'd be especially useful if we would be able to download only the translations for the correct language with something like `"json(translations.language)": { "_eq": "nl-NL" }"`

**Comment by rijkvanzanten** [comment]
Thanks for the additional insight @bcartier! We're currently aiming to solve this by making sure we only load in the translations for the language of the current user through a new feature that allows filtering inside of JSON objects (https://github.com/directus/directus/pull/15889). That should already clear up a lot of this by reducing the amount of data that's needed to be parsed. That being said, having displays individually parse it is definitely not supposed to happen. @azrikahar mind taking a look at that?

**Comment by azrikahar** [comment]
> That being said, having displays individually parse it is definitely not supposed to happen. @azrikahar mind taking a look at that?

I believe this is due to the translate usage in render-display:

https://github.com/directus/directus/blob/b99e8f02d4812c70ef79501899aad3a3c35059da/app/src/views/private/components/render-display.vue#L7

Hence each label/chip is running said function. Using translate in labels display started in #7858 as a fix, which was then moved to render-display for boolean displays in #13861. But a more efficient fix would likely be to translate the field options right at the beginning within the Fields store when they are hydrated if possible. Will look into it further on that front 👍

**Comment by rijkvanzanten** [comment]
Linear: [ENG-193](https://linear.app/directus/issue/ENG-193/translation-string-performance)
