### ISSUE TITLE
Remove Webhooks

### ISSUE THREAD

**Issue by Nitwel** [directus/directus#15553]
We should remove Webhooks from the app & api in v10 as they are currently implemented twice with flows.

**Comment by Nitwel** [comment]
This issue can also be fixed when removing Webhooks. #11679

**Comment by piotr-cz** [comment]
Is it possible to modify the response with flows?
From reading the [Custom Operations](https://docs.directus.io/extensions/operations.html) docs it doesn't look like it is, unlike when using hooks.

I'm particularly interested in adding custom header to all responses.

**Comment by rijkvanzanten** [comment]
@piotr-cz This issue is referring to Webhooks, not the Hooks extensions 👍🏻

**Comment by piotr-cz** [comment]
@rijkvanzanten Great, thank you!

**Comment by rijkvanzanten** [comment]
Linear: [ENG-190](https://linear.app/directus/issue/ENG-190/remove-webhooks)

**Comment by Attacler** [comment]
@Nitwel might i ask why?
For my POV webhooks are to let another party notice that something has been changed.
Flows are for internal automation (might also add a webhook call to another party) but would require a little more extra work.

I am in favor of this but some people might already be using them because they are easier to setup in comparison with a flow.

**Comment by rijkvanzanten** [comment]
@Attacler Flows does everything webhooks does and more, the amount of configuration is only marginally different, so there isn't really a point for us to try to maintain two different bits of logic that achieve the same goal 🙂

**Comment by alexchopin** [comment]
This feature is deprecated so let's do a soft remove by checking if the project have webhooks:
- If not? Disable the webhooks module.
- If yes? Display a banner that link to the flow/webhooks documentation
