### ISSUE TITLE
Getting assets return permission error

### ISSUE THREAD

**Issue by ali-shabani** [directus/directus#15619]
### Describe the Bug

Hi,
I configured my s3 compatible file driver with the below configuration:
```
STORAGE_ARVAN_ACL="public-read"
```
I can accept that my files are publicly available and can access them with a public URL from my storage.
But when I'm using the `assets` API, it gives me the below error:
Providing the static token even gave me this error too.
```JSON
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
```
I'm calling the API with this structure:
```
http://0.0.0.0:8055/assets/<file-id>
```

### To Reproduce

- create a new app
- set the storage environment variable for s3-compatible storage
- add `STORAGE_ARVAN_ACL="public-read"` to the environment
- upload some sample file
- try to reach the file with this route `<base_url>/assets/<file-id>`

### Errors Shown

```
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.17

### What database are you using?

postgres

### What browser are you using?

chrome

### How are you deploying Directus?

locally

**Comment by ali-shabani** [comment]
> * Are the files present in S3 after uploading?

Yes, absolutely. I think 4 files with the same image will be uploaded with different aspects in my storage.

> * Are you uploading via the app, or via the API like a script of sort?

I'm using the app. I can see my file with the same generated UUID in my storage. And the permission in my storage is public.
Images will be correctly loaded in the app, I mean I can see them.
And the storage property of the uploaded image in the app panel is my s3 storage name.

> * (More relevant if you are not using the app) Are you generating your own UUID when uploading the files? If yes, are they UUID v4 compliant? A quick confirmation could be looking at the first number of the 3rd group being the number 4, eg. 
`xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx`.

generated uuid is: `a09d2014-02ee-4685-959e-7510ce064971`
and here is the uploaded image:
`https://buynow-test.s3.ir-thr-at1.arvanstorage.com/a09d2014-02ee-4685-959e-7510ce064971.jpeg`

**Comment by azrikahar** [comment]
> Images will be correctly loaded in the app, I mean I can see them.

Every other info you have shared doesn't seem out of the ordinary to me, but this does seem odd.

The app should request the same `/assets` URL to display the images. Would you mind checking the devtools network tab to see are the image being loaded from the assets url? And can you try loading that same URL (possibly also try removing the access token since you said it is public) and see does it load? 

It'll also be helpful if you can share the exact URL used in the app to show the image, and the exact URL you are using which returns permissions error, so that we can try to draw the comparison easier 👍

**Comment by ali-shabani** [comment]
Actually, it doesn't seem odd to me. Cause inside the app, all the requested images are streaming to the app. (I want to be clear that by using the `app` word, I mean the admin panel)

it is something like this: `Request URL: data:image/jpeg;base64,/9j/2wB....`
I think the admin panel uses the `getStream` method of `s3` storage to load the images inside the app.
![image](https://user-images.githubusercontent.com/12711392/190986938-bef45153-fc7f-44a1-b3c9-de33313ed9c1.png)


By the way, there is an option in the app where you can download the image. And an ‍‍`access_token` attached to its query parameter.
![image](https://user-images.githubusercontent.com/12711392/190988232-a707f4d7-b0d0-4615-91ea-f4fc88c3e5b7.png)


For example:
`http://127.0.0.1:4201/assets/7e929b53-7515-473b-8164-e6dc8eb11402?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9....`
And it works seamlessly.
If I remove the access_token part from the URL, I will give the error I mentioned in my previous comment. And even If I generate a static token from the admin panel, I get the same error.

**Comment by azrikahar** [comment]
> Actually, it doesn't seem odd to me. Cause inside the app, all the requested images are streaming to the app. (I want to be clear that by using the `app` word, I mean the admin panel)
> 
> it is something like this: `Request URL: data:image/jpeg;base64,/9j/2wB....` 

I believe should still be a GET request before this 🤔 since the app specifically makes said GET request over here:

https://github.com/directus/directus/blob/54cd2d47da982a011d1b49ff6ddc474ea4607973/app/src/components/v-image.vue#L50-L55

before it was then set as base64 value for as the src:

https://github.com/directus/directus/blob/54cd2d47da982a011d1b49ff6ddc474ea4607973/app/src/components/v-image.vue#L76

We can see the initial API request to `/assets` in my example before the `Request URL: data:image/jpeg;base64,/9j/2wB....` that you were mentioning:

https://user-images.githubusercontent.com/42867097/190989603-fa6d2b40-1ed6-4f52-8772-870ffce193ca.mp4

---

That being said, I think the actual issue here is although you had set `STORAGE_ARVAN_ACL="public-read"`, the `directus_files` Read permission for the Public role is still being restricted! Can you try granting read permission to the public role for `directus_files`? 🙂

Example steps to grant read permission:

https://user-images.githubusercontent.com/42867097/190989928-4b9295f4-bdd7-4850-834d-1e58396bca57.mp4

**Comment by ali-shabani** [comment]
I appreciate your help. That was my mistake. I completely forgot the role & permissions tab. First, I gave it the proper access, but my files were private in my storage. Then I reset my database and forgot to get the access back.

**Comment by azrikahar** [comment]
No worries, it also flew under my radar! Glad we got to the bottom of this 👍 Marking this as resolved.
