### ISSUE TITLE
WYSIWYG editor add only one image

### ISSUE THREAD

**Issue by JonathanKerwin** [directus/directus#1570]
## Version Info
  - Directus version and branch: 6.3.9
  - PHP version: 7.0.18
  - MySQL version: MariaDB 10.1.22
  - Web server: Apache 2.4.25
  - OS name and version: Windows server 2012

## Expected Behavior
Add a undefined number of images during edit

## Actual Behavior
Add only one image by edit

## Steps to Reproduce
 1. Create new item at any table with a WYSIWYG component(sql type: Text).
 2. Add one image via WYSIWYG.
 3. Click the WYSIWYG add imagem button again.

## Also
The way to add more than one image is save de changes, and then edit the same item again and add another image, meaning that if I want 3 images and need to save and edit 3 times.

**Comment by WellingGuzman** [comment]
Hey @JonathanKerwin thanks for reporting this, but we have some issues working with the current WYSIWYG, so we are getting rid of it for a new one.

@rijkvanzanten do you think we could bring the WYSIWYG from 6.4 to 6.3?

**Comment by rijkvanzanten** [comment]
Yeah, I think that should be doable 🙂

**Comment by benhaynes** [comment]
After testing this same process in `6.4`, everything seems to be working as expected (add multiple images without saving in between). Since we are releasing `6.4` in a few hours we will only be hotfixing previous versions if it's a critical/easy update.

Upgrading to `6.4` will resolve this issue in the new WYSIWYG editor.
