### ISSUE TITLE
v switch not working on custom module

### ISSUE THREAD

**Issue by joeltargett** [directus/directus#15719]
### Describe the Bug

After one of the recent updates, v-switches no longer appear to be working on custom modules. Were they removed on purpose? I've converted my switches to v-checkbox, which seems to be a decent solution.

### To Reproduce

Here is an example of a basic component demoing a v-checkbox and a v-switch.

```vue
<template>
    <div style="padding:20px;">
        <v-checkbox label="Test Checkbox" v-model="result" />
        <hr/>
        <v-switch label="Test Switch" v-model="result" />
    </div>
</template>
<script>
export default {
  data() {
    return {
      result: true,
    }
  }
}    
</script>
```

The checkbox is showing fine, but the switch is missing.

### Errors Shown

There are no errors in the console. The v-switch is not displayed in the browser. When viewing the HTML source, the v-switch remains non-rendered.

![image](https://user-images.githubusercontent.com/4231643/191873297-04cb67c8-8135-4ef9-b335-5c52cb78bbe8.png)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

MariaDB

### What browser are you using?

Chrome 106

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
Seems like it was indeed removed in #15094, presumably since it was no longer used in the app, particularly since the Boolean interface (which uses v-checkbox) is functionally the same. cc @Nitwel in case I'm mistaken 😄 Perhaps we'll need to remove the `v-switch` wiki if that's the case.

In the meantime (or going forward), if you'd like to still be able to use `v-switch`, you can refer to the previous `v-switch` code here: https://github.com/directus/directus/blob/f5befa5bc5c53f20750bf70b68d91a1f8a1d77cb/app/src/components/v-switch.vue, and create a custom interface using it 👍

Hope that helps to clear things up!

**Comment by joeltargett** [comment]
Thanks for the response!

**Comment by Nitwel** [comment]
Good guess Azri! Rijk and I agreed that we are not using the component anywhere so we might aswell remove it to clean everything a bit up.

**Comment by azrikahar** [comment]
> Good guess Azri! Rijk and I agreed that we are not using the component anywhere so we might aswell remove it to clean everything a bit up.

Makes sense! Thanks for confirming 🙌
