### ISSUE TITLE
Field validations not working with M2O relations

### ISSUE THREAD

**Issue by leonardodipace** [directus/directus#15734]
### Describe the Bug

I have a `donations` collection and one of its fields is a M2O relation to the `donors` collection.
When I try to set up field validations, I'm not able to add a filter based on the sub-fields of donor as shown below.
The same applies to `association` and `receipt` which are M2O relations as well

![untitled](https://user-images.githubusercontent.com/63299726/192103620-ffaeb0ae-69fb-476e-96de-2a557fc7c178.png)

### To Reproduce

1. Create a `donations` collection
2. Create a `donors` collection
3. Create a `donor` field in the `donations` collection and set it up as an M2O relation to the `donors` collection
4. Try to set up field validations on the Roles and permissions page

### Errors Shown

No errors shown

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

MySQL 15.1

### What browser are you using?

Firefox 105.0.1

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment]
This was an intentional change in PR #14818, because validations with relational fields doesn't work properly at the moment (specifically when the relational field only contains the related primary key),.

the linked PR purposely "hides"/disables relational collection fields for validations in the mean time to prevent confusion when it doesn't work, before #11775 gets fixed. You can subscribe to #11775 for further updates 👍

**Comment by NilsBaumgartner1994** [comment]
Thanks
