### ISSUE TITLE
User interface only translated but not localized

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1574]
## Version Info
  - Directus version and branch: version/6.4 / e98001a7f3c3365d119401eb017480f0a6eb185e 
  - PHP version: 7.1.5
  - MySQL version: 5.7
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Offical docker image of Directus

## Expected Behavior
Directus allows the user to change the user interface to German. In that case not only the interface is translated but also localized. For example the time should be displayed in the 24-format instead of am/pm format.
The calendar view for example is only partial translated, I guess because of the missing localization.

## Actual Behavior
The user interface should be translated to German and localized according to what europeans expect :)

## Steps to Reproduce
 1. Change the language to german in your profile
 2. Browser a table which has a date field and switch to the calendar view

## Logs or Screenshots
![locale](https://user-images.githubusercontent.com/1575445/27125952-406134f4-50f6-11e7-9ae4-aecba7a8318b.png)

**Comment by WellingGuzman** [comment]
Thanks @wittwerch, we need help to translate it to some languages.

Any help is welcome.

**Comment by wittwerch** [comment]
I'm not talking about translations, that is fine. It's about the locale used in the frontend. It looks like it is currently hardcoded to english?
https://github.com/directus/directus/blob/master/app/main.js#L37

Changing the locale is important because date and time is formatted really different depending on your country/language. Checkout https://momentjs.com/ and the "Multiple Locale Support" section.

In the screenshot above the user interface is changed to German, but still the date/times are formatted in the english locale (11:22am for example should be 11:22 in german because we use 24h format).

**Comment by benhaynes** [comment]
Hey @wittwerch – I believe what Welling was saying is that we are pretty swamped with updates/fixes for the upcoming release of 6.4. So for issues like this (especially if they need to be resolved soon) we would be looking for contributors to help out if possible – otherwise it may take a while for us to get to them.

Obviously a simple translation isn't enough, someone would need to get into the codebase and make adjustments at a deeper level to localize date formatting (in a global/standardized way). 

Being free and open-source, we have very limited resources, so any help from the community is greatly appreciated! Also, for changes like this, it might be best for a developer native to the language formats to make the change – since our team may not be as familiar with the intricacies. I've marked this ticket as `Help Wanted`, so hopefully we'll spark some interest and get a PR soon!

**Comment by benhaynes** [comment]
@WellingGuzman – let's resolve these three front-end dates and look for any others. Most of our dates/times are contextual (3 days ago) or within interfaces (which should already have a way to change display formatting, right @rijkvanzanten?).

I can only think of this Calendar Listing View that shows actual dates/times... so let's localize them into the correct format based on the `current_user.locale`.

**Comment by rijkvanzanten** [comment]
It would be nice if we had a global flag somewhere where we can read out the preferred formatting and format the interfaces based on that. Having settings for each individual interface seems like a bit much.

**Comment by wittwerch** [comment]
I think you only need to include the https://momentjs.com/ and set the locale. 

@rijkvanzanten there are some pre-defined formats in moment.js which could be used.
```
moment().format('L');
```
for english (US) =>  /07/25/2017
for german (Switzerland) => 25.07.2017

**Comment by benhaynes** [comment]
I agree – no interfaces preferences (for now). Let's focus on having the user's locale determine the formatting.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/directus/commit/003eac4d77ddf11c08e759cff72a6669fee4f3c1
