### ISSUE TITLE
Setting up with SQL Server - trustServerCertificate

### ISSUE THREAD

**Issue by keskinonur** [directus/directus#15881]
### Describe the Bug

Dear all, 
If you have to install or upgrade directus with SQL Server, even you select encrypt option true, in many cases you have to set trustServerCertificate option too. Right now CLI tool does not ask anything and stops with an error.

### To Reproduce

A SQL Server with encrypted connection with self sign server certificate.

`npm init directus-project example-project`

OR

`npx directus init `

### Errors Shown

[ESOCKET] Failed to connect to x.x.x.x:1433 - self signed certificate

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.1

### What database are you using?

SQL Server 15.0.4236.7

### What browser are you using?

Firefox, Chrome, Safari

### How are you deploying Directus?

Local

**Comment by sudOnur** [comment]
I manage to overcome this issue by **adding 2 lines**;

First go edit your directus CLI, which is at [project_folder]/node_modules/directus/dist/cli/utils/**create-db-connections.js**
You will see something like these lines;


```
if (client === 'mssql') {
   const { options__encrypt } = credentials;
   connection['options'] = {
   encrypt: options__encrypt,
   trustServerCertificate: options__encrypt, // <-- ADD THIS LINE
 };
}
```

Now you can init your setup without any issue. And in order to run the actual app, you have to add the following line to your **.env**

```
DB_OPTIONS__ENCRYPT="true"
DB_OPTIONS__trustServerCertificate="true" # <-- ADD THIS LINE
```

I hope these settings will implemented in short time.
🍻

**Comment by rijkvanzanten** [comment]
Linear: [ENG-168](https://linear.app/directus/issue/ENG-168/setting-up-with-sql-server-trustservercertificate)

**Comment by lutticoelho** [comment]
Is there a pull request open for this? Because I'm facing this same problem in version 10.4 and at the main branch [this is not implemented](https://github.com/directus/directus/blob/9d75fa22be71773809c57250fe48cd6bf20dbb56/api/src/cli/utils/create-db-connection.ts#L47)

I wasn't able to find a PR about this. Can I open one?

**Comment by br41nslug** [comment]
> Is there a pull request open for this?

There is not, you can check this in the right side bar of the issue 😄 

> Can I open one?

This is an open triaged issue so you're welcome to give it a shot.
https://docs.directus.io/contributing/pull-request-process.html#pull-request-process

**Comment by lutticoelho** [comment]
I just realize that this is not necessary. According to another issue, directus can handle this already [Directus converts the DB env vars to a camelCased object which is passed on to knex.](https://github.com/directus/directus/issues/7002#issuecomment-887571022) so it is possible to do `DB_OPTIONS__TRUST_SERVER_CERTIFICATE=true`.

I tryed this and it works

**Comment by br41nslug** [comment]
In that case i'll be closing this issue as configuring this is already supported 😄 using the ```DB_OPTIONS__TRUST_SERVER_CERTIFICATE=true``` variable.
