### ISSUE TITLE
Missing Interface Fallback

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#1590]
We need to fall back to the default for missing interface IDs (checkbox -> toggle) based on the datatype. Also, we should display a notification:

`You are missing the interface: "checkbox"`

**Comment by WellingGuzman** [comment]
This will throw lots of interfaces warning if there's a lot missing.

Probably we should alert once per app instantiate? and flag any interface that has been warning until the page is refreshed again?

I will close this as the fallback works, otherwise we will continue discussing how this warning should be treated.
