### ISSUE TITLE
Bug in the translation progress bar

### ISSUE THREAD

**Issue by Juanjo-GEx** [directus/directus#15901]
### Describe the Bug

In the content page, when we use the translation field, the progress of the field translation is displayed erroneously.

### To Reproduce

If we access the translation of a content, the translation progress bar is displayed correctly:

![correct](https://user-images.githubusercontent.com/110392472/194327462-fcfdbbb3-43f3-4183-be57-f05284d41fdd.png)

However, on the main page, when we click on the information icon, the progress bar shows the information in the wrong way:

![bug](https://user-images.githubusercontent.com/110392472/194327805-541d24f0-4c1d-42a8-8ccc-10c874831939.png)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

SQLite 

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
This seems to be the same as the first bug reported in #9358, but I can confirm this is present in current version `9.18.1`.

As https://github.com/directus/directus/issues/9358#issuecomment-958671498 mentioned, it's due to the fields currently using the display template fields as the total percentage, instead of all fields. @Nitwel I believe you did originally use this fields fix in this commit: https://github.com/directus/directus/pull/9421/commits/2a205ff908cc671557bca98db703fd2d32c64ab8, but it seems like it wasn't included in the final form of that PR 🤔 could it have been an oversight of the follow up changes to your PR that "reverted" your changes unintentionally?

**Comment by Nitwel** [comment]
Possibly an oversight of me or a merge conflict gone wrong. 🤔

**Comment by dammafra** [comment]
Still present in v9.23

**Comment by rijkvanzanten** [comment]
> Still present in v9.23

Please open a new issue 👍

**Comment by paescuj** [comment]
> > Still present in v9.23
> 
> Please open a new issue 👍

Yes, please do so. You might be affected by a different issue because we've successfully tested the fix 👍

**Comment by dammafra** [comment]
> > > Still present in v9.23
> > 
> > 
> > Please open a new issue 👍
> 
> Yes, please do so. You might be affected by a different issue because we've successfully tested the fix 👍

I've found this open issue also #17196

**Comment by rijkvanzanten** [comment]
If that issue describes your problem, then no further action is needed. It's an open issue, so a known problem 👍🏻
