### ISSUE TITLE
Flows: Bug on Manual Trigger or Delete Data Operation

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#16065]
### Describe the Bug

Manual trigger lets me delete item once, then I need to hard refresh.

https://user-images.githubusercontent.com/62306630/196822334-42519ce6-71a2-4bd0-864e-0f7a0c790f81.mp4

### To Reproduce

See video

### Errors Shown

None

### What version of Directus are you using?

Cloud

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

chrome

### How are you deploying Directus?

cloud

**Comment by azrikahar** [comment]
I think it's because the selection isn't being cleared, so when you're performing the manual trigger the 2nd time, it's sending 2 IDs. However since the Delete Data operation is only targeting the first key using `$trigger.body.keys[0]`, it's not actually deleting the 2nd key. Definitely a bug!

In the mean time, using `$trigger.body.keys` should work, and it would also technically be the recommended approach for manual triggers in general (the ID(s) are always sent as an array, even when there's only 1 item selected, or if we're in the Item Page) 👍
