### ISSUE TITLE
Upgrade from 9.18.1 to 9.19.2 with error UNKNOWN 9 after login with `zh-CN` locale

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#16151]
### Describe the Bug

My existing DirectUs version is 9.18.1. When I upgraded to 9.19.1 or 9.19.2 I got an error "UNKNOWN 9" after I login to the DirectUs admin portal. The API functionality is working fine, just that the admin portal UI will have the error no matter which page I try to access.

Later I found that the issue is due to the admin user default language. My admin account default language is set to Simplify Chinese before the upgrade. After I manually change the default language back to english via the API, the admin portal UI work fine. I also try to use the admin portal UI to change back the default language to Simplify Chinese, it is also working fine. However, I tried to logout from the admin portal with the default language remain as Simplify Chinese, the UNKNOWN 9 error will happened again when I re-login.

### To Reproduce

- From existing version of 9.18.1, change the admin user default language to Simplify Chinese.
- Upgrade to 9.19.1 or 9.19.2
- After upgraded, start the directus and try login to the admin portal.
- UNKNOWN 9 error will displayed after login

### Errors Shown

UNKNOWN 9

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.18.0

### What database are you using?

MySQL 8.0.30 (MySQL Community Server - GPL)

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Production build doesn't show any console/devtools errors, but development build does show this:

![chrome_614RCgXo0o](https://user-images.githubusercontent.com/42867097/197691729-c84fc7fa-775c-4c8a-9cae-13a23ce0b4fe.png)

This is due to a typo with `zh-CN`'s `operation_variables_note` translation (there are multiple wrong `{{'}`, where it should be `{'{'}` instead). It has been fixed in #16122 (not merged or released yet), specifically this line here: https://github.com/directus/directus/pull/16122/files#diff-4f013a23849fcfc095e756e051b826871a1c6ddd0a77a8ca984dd35964b05fb6R2068

**Comment by leosin** [comment]
+1
