### ISSUE TITLE
Reordering a m2m field goes wrong - creates multiple new records

### ISSUE THREAD

**Issue by martijnvanderlaan** [directus/directus#16206]
### Describe the Bug

When we reorder a m2m field, the steps are not sorted, but a lot of extra fields are added. This is a video of the issue: 

https://user-images.githubusercontent.com/53000769/198304254-0b36074f-ea1d-470d-ad61-7b898c2f6dbd.mov

Does anyone else also experiences this? I haven't set up the backed myself, so I have no clue what to ask. If someone can help that would be great :)

### To Reproduce

Create a m2m relationship and reorder the list.

### Errors Shown

No related errors in console 

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

?

### What database are you using?

?

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment]
It seems like you're on a rather dated version. This should be fixed by #13574 on `9.12.2`, along with one or two slightly more recent fixes on top of it such as #15221 on `9.18.0`, so the recommended resolution would be to update your Directus instance. 🙂

As noted in the start of the bug report form, it is strongly recommended to ensure we are using [the latest version of Directus](https://github.com/directus/directus/releases) to make sure it is a bug that is present in the latest version 👍
