### ISSUE TITLE
Directus admin panel kicking me out

### ISSUE THREAD

**Issue by mahsamirzapour** [directus/directus#16205]
### Describe the Bug

Hi, the directus admin panel kicking me out after a minute and I don't know why????

### To Reproduce

Hi, the directus admin panel kicking me out after a minute and I don't know why????

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.18.0

### What database are you using?

MySql

### What browser are you using?

Google Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
I believe this is the same issue as #16188, and there is an open PR #16199 aimed to fix this, so let's consolidate this issue over there 👍 The root cause is the refresh API call is mistakenly failing due to Authorization header and the App interpreted it as session expired and redirected users back out to the landing page.
