### ISSUE TITLE
Allow line breaks in a comment

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1621]
## Version Info
  - Directus version and branch: 61e0e0268f646e5879c48296b80625cc7fe3a10b
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Docker 

## Expected Behavior
As a user I can enter a longer comment and structure it with link breaks for readability.

## Actual Behavior
As a user I can't enter a line break and instead accidentally submit the comment to early.
Maybe a small submit button would be nice, so that this doesn't happen plus it would free up the enter button for line breaks.

**Comment by wittwerch** [comment]
Looking at the code I found out that you can press "Shift-Enter" to add a comment. However for most non-technical persons (marketing people) we should change that to enter and and add a button to submit.

**Comment by benhaynes** [comment]
There is text in the comment input saying "Press enter to submit" – we could add a checkbox here so that users can toggle this functionality between:

- [x] Press enter to submit **(Shift-Enter: new line)**
- [ ] Press Enter to submit **(Shift-Enter: submits)**

**Comment by wittwerch** [comment]
My experience from other systems and user behaviour is, that everybody will accidentally hit enter and submit a comment to early. In combination with comments being immutable, this will lead to frustration.
Why not add a submit button?

**Comment by benhaynes** [comment]
This is true – mostly the lack of a button was for visual simplicity, but that should not impede functionality. Since comments aren't editable we could switch this to a button.

Alternatively, and perhaps this is more useful, would be to have the comments _not_ be immutable. A pencil (edit) icon on the current user's comments would allow editing – which would be a great feature to add and partially solves the above learning curve issue.

**Comment by benhaynes** [comment]
I should have referenced it here, but I have finished the style and functionality of the comment submit button. This should be all set now on `master`!

**Comment by wittwerch** [comment]
Awesome, thanks!
