### ISSUE TITLE
Unable to add users to admin role via the role's page

### ISSUE THREAD

**Issue by dmitrygribenchuk** [directus/directus#16556]
### Describe the Bug

Hello. Have a problem with adding admin to admin list. But I try to add, not remove

{
  "message": "You can't remove the last admin user from the admin role.",
  "extensions": {
    "code": "UNPROCESSABLE_ENTITY"
  }
}

![image](https://user-images.githubusercontent.com/15670247/203025923-95c1cd3f-8631-407b-9c6f-31ad096452c4.png)
### To Reproduce

1) log in via SSO (user)
2) Logout, log in via admin
3) Add user to admin list

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgres

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
I can confirm the same error when adding the user via the Admin role's "User in Role" field. Out of curiosity, would you mind trying to assign the admin role by going into the user's page instead? Here's a quick example of what I've tested:

https://user-images.githubusercontent.com/42867097/203026337-4fdcfcdd-bcc6-4739-a00d-46bca1bd999d.mp4

**Comment by dmitrygribenchuk** [comment]
@azrikahar, thanks, successfully added to admins from user list

**Comment by mdoudkin** [comment]
Had a similar issue but when trying to delete a user. The bug is in the `services/roles.js:RolesService.checkForOtherAdminUsers` method

I have an impression the users count is calculated wrong, which brings the code to conclusion there are no users left after the action is performed

this is the part from which the counting starts
`userKeys = users.update.map((user) => user.id).filter((id) => id);`

in my case, the `update` part of the request data is an empty array, because I am trying to delete a user, so the "other admin users" count is considered a zero

Hope that helps

**Comment by rijkvanzanten** [comment]
Linear: [ENG-132](https://linear.app/directus/issue/ENG-132/unable-to-add-users-to-admin-role-via-the-roles-page)
