### ISSUE TITLE
Missing Thumbnail size field in settings page

### ISSUE THREAD

**Issue by martinfojtik** [directus/directus#1668]
## Version Info
  - Directus version and branch: 6.4
  - PHP version: 7.1
  - MySQL version: 5.7
  - Web server: Apache
  - OS name and version: Windows 10

## Expected Behavior
It should be possible change thumbnail size through settings page

**Comment by benhaynes** [comment]
Assuming you are talking about `directus_settings.thumbnail_size`, I don't think we'll be changing this. That size (`200`) is the system thumbnail, and shouldn't really change. We *may* keep the quality option since that can be adjusted to alter the filesize on certain systems.

The main reason this is isn't a priority is because we have a full-featured thumbnail system in the works which should be complete/released in about 2 months. It will allow for more options/sizes and be dynamic.

Thank you for reporting this though, I'm happy to discuss further if you have questions!
