### ISSUE TITLE
Administrator is missing permission to view collections created via snapshot

### ISSUE THREAD

**Issue by danielband** [directus/directus#16728]
### Describe the Bug

There is an funny glitch after applying a snapshot in the collections UI. The administrator is able to view the new collections itself, but does not have the permissions to view the rows inside the collections. Instead an error message appears.

This can be solved by giving an other role temporary admin permissions and removing the admin permissions from the admin role. After saving, give the admin his permissions back and remove the permission from the temporary role. Or I guess by exporting the permissions from the first directus instance via API and importing them in the second..

### To Reproduce

1. Take a schema snapshot of one Directus instance
2. Apply that snapshot to another (the schema of instance 2 should contain collections before applying)
3. Login as admin user in instance 2 
4. Go to collections
5. Click on the newly created collection
6. There should be an error stating: You don´t have permissions to access this

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14.5

### What browser are you using?

Firefox

### How are you deploying Directus?

bare metal

**Comment by azrikahar** [comment]
This sounds like a schema cache issue at a glance. Would you mind trying to set `CACHE_SCHEMA` to false on instance 2 before applying the snapshot? Ref: https://docs.directus.io/self-hosted/config-options.html#cache (note that `CACHE_SCHEMA` will still be true _even if_ `CACHE_ENABLED` is set to false, which is you will need to explicitly set configure `CACHE_SCHEMA`)

At the same time, can you share what cache store are you using in instance 2 (memory, redis, or memcache)?

It would also be very helpful if you can also test this on the latest version (9.21.2 as of now) as requested in the bug report template 👍

**Comment by danielband** [comment]
@azrikahar Starting directus with CACHE_SCHEMA=false did solve the issue in 9.17.4 and 9.21.2. I am using in memory cache.

**Comment by azrikahar** [comment]
Thanks for confirming! Are you running multiple instances of "instance 2"? (as in pm2 or Kubernetes, where "instance 2" in your description as multiple instances by itself, unrelated to "instance 1")

That would indeed cause such issue, as memory cache only works when it's a single node. Here's a snippet of a mention of this in the docs' Cache section: https://docs.directus.io/self-hosted/config-options.html#cache

> When running Directus load balanced, you'll need to use a shared cache storage (like [Redis](https://docs.directus.io/self-hosted/config-options.html#redis-2) or [Memcache](https://docs.directus.io/self-hosted/config-options.html#memcache-2)) or else disable all caching.

Additional elaboration in a similar question a while ago: https://github.com/directus/directus/issues/11916#issuecomment-1058288034

Closing this for now since it should be a cache configuration issue/question similar to #11916.
