### ISSUE TITLE
Filtering and Search in Layout Kanban does not work

### ISSUE THREAD

**Issue by pitstampfli** [directus/directus#16754]
### Describe the Bug

Search and the setting of filters has no effekt, if the Layout is set to Kanban.

Check the Collection "Task" or "Invoice"

### To Reproduce

Check the Collection "Task" or "Invoice"

### Errors Shown

Check the Collection "Task" or "Invoice"

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

Postgress

### What browser are you using?

Chrome

### How are you deploying Directus?

Hosted by Directus

**Comment by azrikahar** [comment]
Thanks for opening this issue! Coincidentally this is already being tracked in a separate issue internally (as it is currently a cloud exclusive extension), and since it's not exactly "actionable" in the context of this repo, I'll close this as a duplicate (even if the other issue is technically private).

**Comment by pitstampfli** [comment]
Thanks
Can you tell me what is the progress or the fixdate for this internal bug?
