### ISSUE TITLE
directus isn't compatible with node v13.14.0

### ISSUE THREAD

**Issue by benweng** [directus/directus#16764]
### Describe the Bug

Directus is required at Node 12.20 or later。but it isn't compatible with node v13.14.0。

### To Reproduce

![1](https://user-images.githubusercontent.com/10015855/206636588-ca9fd14e-ef52-4e08-b172-6f3a562aa6a9.jpg)

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

13.14.0

### What database are you using?

sqlite3  5.1.2

### What browser are you using?

chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Since version `9.19.0` with the dependency updates in #16052, `pino` was updated from `6.13.3` → `8.6.1`. However pino [`7.0.0`](https://github.com/pinojs/pino/releases/tag/v7.0.0) onwards included the [`on-exit-leak-free`](https://github.com/mcollina/on-exit-leak-free) package which requires [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) and [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) that are only available on Node v14+.

Additionally, the `rollup` package was updated in the same PR, where rollup v3 now requires Node `14.18.0` to run. More context: https://github.com/directus/directus/discussions/16382#discussioncomment-4098832

As Node 12 has reached end-of-life status 7 months ago: https://github.com/nodejs/Release#end-of-life-releases (Node 13 is earlier than that), I'd recommend upgrading to Node `14.18.0` or above going forward. 

Keeping this issue up to ensure this requirement is reflected in the README and the docs.

**Comment by benweng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by benweng** [comment]
> Since version `9.19.0` with the dependency updates in #16052, `pino` was updated from `6.13.3` → `8.6.1`. However pino [`7.0.0`](https://github.com/pinojs/pino/releases/tag/v7.0.0) onwards included the [`on-exit-leak-free`](https://github.com/mcollina/on-exit-leak-free) package which requires [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) and [`FinalizationRegistry`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) that are only available on Node v14+.
> 
> Additionally, the `rollup` package was updated in the same PR, where rollup v3 now requires Node `14.18.0` to run. More context: [#16382 (comment)](https://github.com/directus/directus/discussions/16382#discussioncomment-4098832)
> 
> As Node 12 has reached end-of-life status 7 months ago: https://github.com/nodejs/Release#end-of-life-releases (Node 13 is earlier than that), I'd recommend upgrading to Node `14.18.0` or above going forward.
> 
> Keeping this issue up to ensure this requirement is reflected in the README and the docs.

That means I can install version 9.18.1 to solve this problem！right ？

**Comment by azrikahar** [comment]
Yes I believe `9.18.1` should work in the meantime, unless there's other dependency updates or Node version incompatibilities that I'm not aware of 👍

**Comment by benweng** [comment]
> Yes I believe `9.18.1` should work in the meantime, unless there's other dependency updates or Node version incompatibilities that I'm not aware of 👍

Thank you very much. I'll try it first and ask again if I have any questions！

**Comment by benweng** [comment]
> Yes I believe `9.18.1` should work in the meantime, unless there's other dependency updates or Node version incompatibilities that I'm not aware of 👍

But there is another problem. How do I install it? The default is to install the latest version！

**Comment by azrikahar** [comment]
Instead of using the `directus-project` CLI (assuming you are describing this), you will likely need to follow the manual installation instructions: https://docs.directus.io/self-hosted/installation/manual.html. For step 2, replace `npm install directus` with `npm install --save-exact directus@9.18.1` to pin the version.

**Comment by benweng** [comment]
> Thank you very much

Thank you very much！it work!

**Comment by rijkvanzanten** [comment]
For what it's worth, Directus requires the latest LTS version of NodeJS (https://docs.directus.io/self-hosted/installation/cli.html#_1-confirm-minimum-requirements). The readme on this repo was outdated, which #16774 aims to fix 👍🏻

**Comment by rhclayto** [comment]
> Instead of using the `directus-project` CLI (assuming you are describing this), you will likely need to follow the manual installation instructions: https://docs.directus.io/self-hosted/installation/manual.html. For step 2, replace `npm install directus` with `npm install --save-exact directus@9.18.1` to pin the version.

Just a note: the link to the manual installation page in the docs is now a 404. Is this updated somewhere else?

**Comment by benweng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rijkvanzanten** [comment]
> > Instead of using the `directus-project` CLI (assuming you are describing this), you will likely need to follow the manual installation instructions: https://docs.directus.io/self-hosted/installation/manual.html. For step 2, replace `npm install directus` with `npm install --save-exact directus@9.18.1` to pin the version.
> 
> Just a note: the link to the manual installation page in the docs is now a 404. Is this updated somewhere else?

This is the up-to-date self-host guide 👍🏻  https://docs.directus.io/self-hosted/quickstart.html
