### ISSUE TITLE
A user who has no right to delete an O2M or M2O foreignkey should not see the X

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16823]
### Describe the Bug

A user who hos no right to delete an O2M field sees the X at the end of the line

### To Reproduce

Create a collection with an O2M field.
No Access to delete for the O2M collection
Show O2M items in the parent collection

### Errors Shown

You see the X to delete the item at the bottom of every line.
Click on it
Save the main item
=> 
```
{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}
```
The X should not be seen at first.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by br41nslug** [comment]
The delete permissions are not applicable here as "removing a related item from an o2m" is not a delete action but an edit to the foreignkey of the relation. If the edit permissions are fully disabled then the cross does get removed but this does not happen for partial field permissions that do not include the foreignkey.

**Comment by rijkvanzanten** [comment]
Linear: [ENG-107](https://linear.app/directus/issue/ENG-107/a-user-who-hos-no-right-to-edit-an-o2m-or-m2o-foreignkey-should-not)

**Comment by azrikahar** [comment]
As @br41nslug mentioned, delete permission aren't applicable here, as it should be edit permission what's controlling whether the `X` appears. However, I also can't seem to reproduce this with edit permissions on `9.22.1`:

https://user-images.githubusercontent.com/42867097/209629987-e9fc72df-b7a0-4f38-b487-52d525a3a23d.mp4

so I'm closing this for now.

> but this does not happen for partial field permissions that do not include the foreignkey.

@br41nslug is what I tested from the 25 seconds mark the same as what you were describing? Just want to be sure I'm understanding it correctly 👍 Will re-open this if this bug is actually still present.

**Comment by br41nslug** [comment]
@azrikahar This issue comes up when the foreignKey is excluded from the edit field permissions.
![image](https://user-images.githubusercontent.com/9389634/209641023-eaeb0521-7b11-4c5c-bc27-c49fd94718bb.png)
![image](https://user-images.githubusercontent.com/9389634/209641063-eee63e21-9297-426b-8f39-2b52116dc0ee.png)

Causing the O2M interface to think the relation is editable while it is not:
![image](https://user-images.githubusercontent.com/9389634/209641264-6dfe5893-9612-43a8-9dbc-f3a217d191da.png)

**Comment by Nitwel** [comment]
I don't think it is feasable for us to go infinitely deep in checking for permissions. #16373 Will already improve permission checking quite a bit on relational interfaces so I would go ahead and say that #16373 will fix this issue even though technically, we are not checking for field, item and validation level permissions. 

That being said, the api will respond with the proper information if you don't have full access to something.
