### ISSUE TITLE
Unable to install Directus

### ISSUE THREAD

**Issue by denno020** [directus/directus#1686]
## Version Info
  - Directus version and branch: 45357c7bd491687a87777784e4e06c335dfefa6f
  - PHP version: 5.6.25
  - MySQL version: 5.7.14
  - Web server: Apache 2.4.23
  - OS name and version: Windows 10

## Expected Behavior
Directus would proceed with installing, and (I assume) show me some configuration options

## Actual Behavior
Navigating to the index page (in root directory), it correctly detects that I haven't yet installed the software, so it proceeds with doing that, however it stops with a Fatal Error
`Fatal error: Class 'Directus\Bootstrap' not found in {directory}\directus\api\core\Directus\Exception\ExceptionHandler.php on line 95`. Full stack trace can be seen in the screenshot below

## Steps to Reproduce
 1. Checkout repository
 2. Run `composer install`
 3. Attempt to run the software by navigating to the root `directus` directory

## Logs or Screenshots
Excuse the fact that the text is highlighted, the contrast between the text colour and white background was really poor, so highlighting the text like this made it much easier to read
![directus_error_2](https://user-images.githubusercontent.com/2059313/28164268-db09c90c-680d-11e7-8b94-14b7d6b8dc67.png)
![directus_error](https://user-images.githubusercontent.com/2059313/28164229-9785bf06-680d-11e7-9d8d-7489cb6d3971.jpg)

**Comment by WellingGuzman** [comment]
Hey @denno020,

I do not have a Windows machine now to test this, but on mac and linux it's working, so I assume it may be something related to windows.

If you go to `directus/api/core/Directus` directory isn't there a `Bootstrap.php` file?

**Comment by denno020** [comment]
Yep the Bootstrap file definitely exists.. Damn Windows, always making things difficult

**Comment by WellingGuzman** [comment]
I'm trying to get a windows virtual machine to test this. I'm guessing this must be a windows + composer issue that we aren't manage to figure it out, because we all having MacOS or Ubuntu machines.

I will get back to you as soon as I get my hands on a Windows machine.

In the meantime, If you find what's causing this we would love any help, no pressure.

**Comment by denno020** [comment]
So this isn't going to be helpful at all, but it seems to be working now.. I have been working from home all day and hadn't had time to look into this issue until now. I navigated to the directory, and I saw the correct set up form! I was able to go all through way through the set up process (well until I got to creating a database, where I reached an error due to MySQL Strict mode).

I have been installed/uninstalling things on my computer all day (to do with work); docker and virtualbox being the only two, I think.. One of those must have changed some configuration on my machine that has now fixed the issue!

I'm sorry I can't provide more details on the exact fix

**Comment by benhaynes** [comment]
That's OK – the intermittent bugs are the worst, but hopefully this was properly fixed by a commit or it was just some strange caching issue. We are still working on getting a Windows machine setup for testing – but will close this in the meantime since it's resolved.

Please reopen this ticket if it happens again or new information arises. Thank you!
