### ISSUE TITLE
Relations not available in Conditions of translation collections

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#16880]
### Describe the Bug

Create a translation for any collection, when you add fields in the new translation collection and want to have a condition for a field, the relation to the parent collection is not available to configure the condition.

![image](https://user-images.githubusercontent.com/15796397/209073955-e6c59038-905c-42d8-b848-f5ffbf6ebd32.png)

### To Reproduce

Add translation to a collection and add a field. Try to set up a condition to react on the parent collection.

### What version of Directus are you using?

9.21.0 & 9.21.2

### What version of Node.js are you using?

v14.19.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

linux vps & 9.21.2 was tested in directus cloud

**Comment by azrikahar** [comment]
(Disclosure: This is technically the same use case as #15300, so the following response is copied from a previous answer over there)

---

>  the relation to the parent collection is not available to configure the condition.

This was an intentional change in PR #14818, as seen in this comment here: https://github.com/directus/directus/pull/14818#pullrequestreview-1060822769, because conditions with relational fields doesn't work properly at the moment (specifically when the relational field only contains the related primary key).

Hence the PR disables relational collection fields for validations & conditions temporarily, before their respective issues (#11775 and #8228) gets fixed. 

You can subscribe to #8228 specifically for conditions with relational fields 👍
