### ISSUE TITLE
while PATCH: wrong number of digits and critical rounding problem.

### ISSUE THREAD

**Issue by AmmonStretz** [directus/directus#16929]
### Describe the Bug

I wanted to change a float (longitude) value with a patch

But the saved value just has only 5 chars after the decimal point. (88,12346)
Is there a way to chage that? By hand I can insert more decimal places.

And then I found out that with changing the 88.1234567... to a _888_.1234**5**67...
the rounding is strange. It returns 888.1234**7**
From 5 to 7

### To Reproduce

PATCH` /items/location/6?access_token=....... HTTP/1.1
Host: .....
Content-Type: application/json
Content-Length: 44

{
	"longitude": "88.123456789123456789"
}

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

v16.14.2

### What database are you using?

mySQL

### What browser are you using?

Chrome, Firefox, ...

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
> But the saved value just has only 5 chars after the decimal point. (88,12346)
Is there a way to chage that? By hand I can insert more decimal places.

The "only 5 chars after decimal point" is likely because by default, float and decimal has default precision of 10 and scale of 5:

https://user-images.githubusercontent.com/42867097/209620641-4beceb6d-bd5e-4b33-8ca3-d126a912ea47.mp4

As described in MySQL's docs for [floating-point types](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html) and [fixed-point types](https://dev.mysql.com/doc/refman/8.0/en/fixed-point-types.html), precision would indicate how many digits in total, and scale is how many digits following the decimal point.

With the default precision of 10 and scale of 5, this would mean the range for that field will be from `-99999.99999` to `99999.99999`.

If you would like to insert more decimal places, make sure to modify precision and scale accordingly 👍

> And then I found out that with changing the 88.1234567... to a 888.1234567...
the rounding is strange. It returns 888.12347
From 5 to 7

This should be partly related to the default 10 digit + 5 decimal place as described above. 

That being said, I also believe rounding oddities should be expected for float, as it is only an approximate value, unlike decimal that is an exact value. Here's a quick example showcase between decimal and float, and we can see float tends to round numbers even when it's not what typically expected:

https://user-images.githubusercontent.com/42867097/209621636-b7f63a53-aadc-403f-a37d-63aa4fcb52d0.mp4

Though this is more of a database factor rather than Directus itself.

> What version of Directus are you using?
9.0.0

Would you mind specifying the exact version, such as the current latest `9.22.1`? Unless you are indeed on the old `9.0.0` version, in which case it is recommended to try it on the latest version before filing any bug reports.

> What database are you using?
mySQL

Would you mind sharing what MySQL version is this? As there can be a number of differences between 5.7 and 8.0 even if they're both MySQL.

---

Moving this to discussion for now as I believe it's more of a precision/scale config for float/decimal fields rather than a bug 👍
