### ISSUE TITLE
DigitalOcean one-click install not opening up

### ISSUE THREAD

**Issue by crewnew-git** [directus/directus#16923]
### Describe the Bug

I followed these instructions in the Directus documentation https://v8.docs.directus.io/installation/do-one-click.html but the URL https://marketplace.digitalocean.com/apps/directus-1 gives an error: https://i.imgur.com/A5Yxorz.png and also couldn't find by using the search term "directus" in the marketplace.

### To Reproduce

Just try to find the installer.

### What version of Directus are you using?

Want the latest

### What version of Node.js are you using?

Latest

### What database are you using?

Whatever the installer installs

### What browser are you using?

Chrome

### How are you deploying Directus?

One-click

**Comment by azrikahar** [comment]
> I followed these instructions in the Directus documentation https://v8.docs.directus.io/installation/do-one-click.html 

That is an older docs for Directus v8 which has been deprecated. It is recommended to use v9 (or v10 in the future) going forward 👍

> but the URL https://marketplace.digitalocean.com/apps/directus-1 gives an error: https://i.imgur.com/A5Yxorz.png and also couldn't find by using the search term "directus" in the marketplace.

I'm not 100% sure myself, but I believe the one-click install was removed to prevent confusions such as https://github.com/directus/directus/discussions/16382#discussioncomment-4171582, because that one-click install is no longer maintained.

Highly recommend to use the [official Directus docker image](https://hub.docker.com/r/directus/directus) via DigitalOcean's App Platform instead as mentioned in the discussion linked above.
