### ISSUE TITLE
When clicking on menu items (collections), data does not get loaded by default

### ISSUE THREAD

**Issue by philipdalen** [directus/directus#17011]
### Describe the Bug

When clicking on the different collection on the menu, the items does not get loaded as expected, a page refresh is required. Please see attached video.

https://user-images.githubusercontent.com/12196246/210501884-a1ae0852-e816-4ead-8198-f74909dac096.mp4

### To Reproduce

- The problem was introduced in v9.22.0, I confirmed this by downgrading each version until the bug was not present anymore.
- Make sure you are on v9.22.0 or above
- Use any local Directus environment with with sqlLite for example, the bug is also present in when using PostgreSQL
- Create some collections with some items in it.
- Click though the menu with the different collections.
- Notice that the items does not get loaded by default.

### Errors Shown

There a no errors shown, I have however noticed from the network tab that the data does get returned to the browser, which makes me suspect that it must be a frontend issue.

### What version of Directus are you using?

0.22.0 or above

### What version of Node.js are you using?

18.12.1

### What database are you using?

SQLLite 5.1.4 or PostgreSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Paas (https://railway.app)

**Comment by u12206050** [comment]
I have the same issue, seems to be a layout issue. Since it is also happening in presets.
Might it be due to the loading waiting on both count and items to finish fetching?

![Screen Recording 2023-01-04 at 08 34 01](https://user-images.githubusercontent.com/6641242/210505795-fe59e00b-b7e6-416b-9523-84b4298c8880.gif)

At the end of this recording you see layout works first time, but not when navigating back to another item. It works again after selecting another layout and then reselecting table layout.

**Comment by azrikahar** [comment]
Should be the same issue as #16883 👍
