### ISSUE TITLE
There is no total count for pagination view when list items by api

### ISSUE THREAD

**Issue by jacobzeng** [directus/directus#1720]
# Version Info

- Directus version and branch: 6.4 master on commit 228bc94
- PHP version: 7.0.18
- MySQL version: 5.7.19
- Web server: Apache
- OS name and version: Ubuntu 16.04
## Expected Behavior

I need a attribute of meta to show the total count of current query, not the total of table.

## Actual Behavior
For example, the query api like /domain/api/1.1/tables/fang_todo/rows?filters[content][contains]=abc,the result as following:

{"meta":{"table":"fang_todo","type":"collection","total":10,"total_entries":54},"data":[...]}

the total is just the length of data, the total_entries is count of total records of the table, but i need another attribute for count the query total result is 14, then i can display the result in pagination view

**Comment by benhaynes** [comment]
Hey @jacobzeng – could you explain this a bit more?

`total_entries` is the total number of items for the whole table, no filters
`total` is the count of items returned by the request

What is the attribute you are looking for? when you talk about `10` vs `14`... is `10` limited or capped by pagination? If you could explain that difference we can look into this.

**Comment by benhaynes** [comment]
If I am correct, and you are sending a request with a `LIMIT` (or Pagination) and want the total results returned without the limit... I don't know if this is something we will implement. 

I realize it could be quite useful in some situations, but since Directus passes through these as actual SQL commands (including the limit), we would have to either change the core Directus logic (don't pass through SQL) or double the command (with and without the LIMIT):

1. Core Codebase Change
Instead of passing through the SQL command, SELECT all results *without* the LIMIT (to get the un-paginated count) and then _manually_ offset the full-dataset to return. This is one query, but it would require a larger overhaul of how we access data.

2. Double Query
We can either run the same query twice (with and without the LIMIT) or we can create a custom SELECT using the command in the StackOverflow post below. This direction is not as performant, and it specific to MySQL (bad, because we're abstracted to start supporting Postgres and MS-SQL).

https://stackoverflow.com/questions/12887266/get-total-number-of-rows-when-using-limit

I would recommend doing the "double request" within your app for now – then at least you can select specific places to have queries take a bit longer. Either way, happy to discuss further, but I'm going to close the ticket in the meantime. If you really feel that this is a good feature to add (despite the performance hit) then please submit it to our FeatHub:

http://feathub.com/directus/directus

**Comment by jacobzeng** [comment]
> If I am correct, and you are sending a request with a LIMIT (or Pagination) and want the total results returned without the limit... I don't know if this is something we will implement.

Yes, you are right, it's what i want, the attribute will help me to know how to display the page index without get total result.

BTW, thanks for your response.

**Comment by magbeat** [comment]
@jacobzeng I have openned a feature request at https://feathub.com/directus/directus/+118

**Comment by abhilashak** [comment]
This is really important in implementing the pagination to show not only the 'count of total filtered records', but also creating the last page of the pagination. 
Last page url is:
Offset: Integer part of (total / limit)
            Integer part of (total / limit = say 12.5 ) = 12 
Limit: say 20
Here I don't have 'total' for now to create the logic for the last pagination link !!
Correct me If I am wrong.
