### ISSUE TITLE
Docs mention "FLOWS_EXEC_ALLOWED_ENV" for flow configuration

### ISSUE THREAD

**Issue by janericwinkelmann** [directus/directus#17263]
### Describe the Bug

If I try to access some environment variables inside a flow with the `$env` injection, it doesn't work. The object is empty. The docs state that all env variables that should be exposed should be declared in another env variable called `FLOWS_EXEC_ALLOWED_ENV`. It seems as if this variable is not consumed.

In order to send emails correctly with a flow that contains links to the Directus instance, it is necessary to access the `PUBLIC_URL` for example. I can't get this working.

Maybe I am doing something wrong or this feature is not implemented yet?

### To Reproduce

1. Create a new directus instance
2. add the environment variable `FLOWS_EXEC_ALLOWED_ENV` inside the .env file
3. Create a flow and try to access the `$env` variable
4. Log the result and you will see it's empty.

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

19

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

local and docker

**Comment by paescuj** [comment]
Hey, thanks for your report!
The name of the variable was wrong in the documentation (https://docs.directus.io/configuration/flows.html).
It's supposed to be `FLOWS_ENV_ALLOW_LIST` instead of `FLOWS_EXEC_ALLOWED_ENV`, see also https://docs.directus.io/self-hosted/config-options.html#flows.
This has just been corrected!
