### ISSUE TITLE
Flow trigger handles key differently for Create & Update

### ISSUE THREAD

**Issue by mcqua007** [directus/directus#17356]
### Describe the Bug

When following this [Directus Auto Generate Slugs Tutorial](https://www.youtube.com/watch?v=Z4ua6CH45L4). They use `$trigger.key` in order to update the slug field with the new slugified data. The issue is this works for `create` but the key is coming back undefined for `update`. If I use `$trigger.keys[0]` this works for `update`, but is `undefined` when trigger by `create`. I am not sure if this is an issue with the tutorial or a bug in the flow. It would be nice if you could use `$trigger.key` for both as shown in the video. I see in the logs that for update  keys is returned as an array and for create it is not. So maybe this is an issue with the tutorial.

## Flow Logs For Update & Create
<img width="855" alt="Screenshot 2023-01-31 at 11 43 03 AM" src="https://user-images.githubusercontent.com/17321059/215865995-f5d2181a-f0c3-4220-b77c-a53533065707.png">

<img width="854" alt="Screenshot 2023-01-31 at 11 42 34 AM" src="https://user-images.githubusercontent.com/17321059/215866008-af1a5296-9efe-45b9-bbaa-af29599ca407.png">

### To Reproduce

Follow the official tutorial listed above or just create a trigger flow with a scope of items.create & items.update. And console log out trigger.key and trigger.keys[0]. Ten go to the collection and update & create some test data.

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

chrome

### How are you deploying Directus?

Directus Cloud

**Comment by bryantgillespie** [comment]
Good find @mcqua007! Indeed it is an issue with the tutorial. I'll make sure we get that updated so we don't confuse anyone moving forward.

But I also don't think there's a single *best* solution – it all depends on your specific needs. There's many ways you could approach this.

**If you want to update the slug on both items.create and items.update**, then you could do something like this inside the Run Script operation...

``` js
module.exports = async function (data) {
	const text = data.$trigger.payload.title

	let key
	if (data.$trigger.event.includes('items.update')) {
		key = data.$trigger.keys[0]
	} else if (data.$trigger.event.includes('items.create')) {
		key = data.$trigger.key
	}

	const slug = text
		.toLowerCase()
		.trim()
		.replace(/[^\w\s-]/g, '')
		.replace(/[\s_-]+/g, '-')
		.replace(/^-+|-+$/g, '')

	return {
		key,
		slug
	}
}

```

So you return the key and the slug inside an object. And then you would pull the id from the Run Script operation instead of the Trigger.


<img width="922" alt="ScreenShot 2023-01-31 at 17 33 39@2x" src="https://user-images.githubusercontent.com/23302570/215899583-fb554076-1a7c-42ad-b175-70d26dff4e5f.png">


Or you might decide you only want to auto-generate slugs on `items.create` / item creation. Then if the title changes, users would manually update the slug so you don't accidentally create a bunch of 404s.

Or you could even go further down that rabbit hole and create a flow that adds items to a `redirects` collection if the slug changes for a published article.

Does this help?

**Comment by mcqua007** [comment]
Oh okay, this is a good way to do it I ended up putting in a conditional via the flow but, this is a lot cleaner and yeah I am only going to use it on create rather than on update but wanted to ask the question in case I need to do something on both update & create. Thanks for the help.

**Comment by bryantgillespie** [comment]
Yep. A condition operation would work fine as well.

It seems like you're all sorted so I'm going to close this one out 👋 .

If you're not already there, check out our Directus Discord community.
https://directus.chat

**Comment by mcqua007** [comment]
Thanks Bryan. I'll check out the discord server that will be helpful as I have tons of questions.
