### ISSUE TITLE
Replace file doesn't remove previously generated thumbnails

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#17477]
### Describe the Bug

Replacing an image with another image doesn't invalidate the other variant images generated through transformation presets.

### To Reproduce

- Upload an image
- Access the asset using transformation keys
- Replace file through admin UI
- Access the same asset using the same transformation keys
- Served file is still the old one

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

Docker

### What database are you using?

PG 14

### What browser are you using?

Edge

### How are you deploying Directus?

Docker

**Comment by emrahnazif** [comment]
Maybe this bug can be considered along side with #13559

**Comment by Nitwel** [comment]
This seems to be caused by `CACHE_TTL` having a default of 30 days which sets the header `Cache-Control: max-age=86400`. You probably have to change the name of the url when you replace it for the time being.
We could introduce versioning to files meaning that each file will have a new version field that only ever gets changed when you replace a file. That way you can add a query parameter to the request that busts the cache when the file got replaced. Thoughts @rijkvanzanten?

**Comment by rijkvanzanten** [comment]
The /assets endpoint already allows any arbitrary text behind the UUID, so you could do this as-is 👍🏻

**Comment by DanielBiegler** [comment]
Tested on v10.6.2 as container in production:

Curious how Firefox apparently **does** receive the new image but refuses to replace it:

![image](https://github.com/directus/directus/assets/14810858/f46e5849-b29d-4dc0-9ab8-8ddbc5b1134f)

**Comment by DanielBiegler** [comment]
So after a little bit of research I found a couple of approaches we could take here but first, let's specify exactly whats happening.

1. Currently we actually _do_ remove all generated transformations when replacing a file (v10.6.2)
2. We do serve the new file as per my screenshot [here](https://github.com/directus/directus/issues/17477#issuecomment-1731096561).

Technically, if

- you provide cache disabling headers for `/assets`
- the browser ignores caching itself
- you use your own cachebusting param with a new value, for example `/assets/<hash>?cachebust=abc123`

the browser **will** see the new resource. Going further along without the mentioned options:

3. The new transformations get persisted once upon request for the new resource
4. Now the browser refuses to replace the cached resource because it's still [fresh](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#fresh_and_stale_based_on_age) defined by us setting the [max-age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#response_directives).
5. max-age seems to have a higher priority than other caching options 

### What we could do

1. Get rid off the max-age header completely and switch to a [conditional request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests) where we can reply with an [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) and or Last-Modified header to either return the resource or reply with body-less and tiny [304 Not Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304)

This'd allow to always get the latest resource but with the cost of an extra request. Probably for most people the following would be best:

2. Use either the ETag and or modified-headers to be able to reply with tiny 304 responses, but make the max-age default from [ASSETS_CACHE_TTL](https://docs.directus.io/self-hosted/config-options.html#assets) **way shorter** than the current default of 30days. This'd allow for good prevention of unnecessary requests and the quick revalidation via the 304 reply where we don't have to transmit the image at all after max-age.

Messing with caches can and will impact every Directus instance so I'd love to be very careful with this.

**Comment by rijkvanzanten** [comment]
That makes sense 👍🏻

**Comment by DanielBiegler** [comment]
Created a discussion for this on #19768
