### ISSUE TITLE
Problem with: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". 

### ISSUE THREAD

**Issue by newathnow** [directus/directus#17765]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I get this in the console and cant login: 

login:48 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-gLoyID1ECZ2GJq21n2O8ZJ/PYCCaU2lnrlmDuPO/YIs='), or a nonce ('nonce-...') is required to enable inline execution.

### To Reproduce

ubuntu 20.04
nginx

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment]
Judging from the console error `login:48`, generally line 48 is just the body end tag:

![](https://user-images.githubusercontent.com/42867097/224378606-f3a68057-3ab2-4800-9e14-cb624fe0c8c3.png)

However I can only assume you are using an [Embed Hook](https://docs.directus.io/extensions/hooks.html#embed) to add custom script in your app, in which case I can confirm line 48 would be the injected custom script:

![](https://user-images.githubusercontent.com/42867097/224378942-9375029d-f93a-429c-b5fc-d6d4304ef1fa.png)

and I can indeed see the console error:

![image](https://user-images.githubusercontent.com/42867097/224379032-82794c86-200f-4db5-b803-690195b14a47.png)

However this is only because inlining script that way does indeed violate the `script-src` CSP directive as stated. You can configure CSP via [`CONTENT_SECURITY_POLICY_*` environment variable(s)](https://docs.directus.io/self-hosted/config-options.html#security) as describe in the docs. You may also refer to [this comment in a separate discussion](https://github.com/directus/directus/discussions/15865#discussioncomment-3786705) which hopefully goes further in detail on how to configure it.

---

That being said, I do believe this should not prevent any logins, as seen in my attempt here:

https://user-images.githubusercontent.com/42867097/224380145-2197a73e-9d00-4b2d-bc32-4019c23a801a.mp4

<br />

So I'll proceed to close this issue for now. If you can reproduce this issue _without_ any embed hooks, feel free to give us an update and we'll re-open it after successfully reproducing it 👍

**Comment by newathnow** [comment]
thanks it worked
