### ISSUE TITLE
Foreign keys are set to null when applying schema changes in SQLite

### ISSUE THREAD

**Issue by blaemmle** [directus/directus#17832]
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When using Schema.yaml files to apply data structure changes that remove a not nullable relation, we lose relations to other collections. 
e.g. 

**Collection page**
- image* (directus_file)
- buttons (many-many)

**Collection button**
- name*

When we remove the image by applying a schema change, it will null the relations to buttons in the relation table page_button. It also happens if we do not delete the image field, but allow it to be nullable. 

We use the Directus version 9.23.1 and SQLite3.

Thanks in advance! Please let me know if you need more details.

### To Reproduce

https://gitlab.com/blaemmle/directus-sqlite3-reference-bug

I've tried to create a small Repo with some steps to reproduce the problem. 

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by gkielwasser** [comment]
@azrikahar This issue has been closed but I'm still having an issue that seems to be like this one. I can create another issue if it doesn't seem to be the same problem.
I'm using directus 9.26.0 but I have this issue since I'm using 9.25.x.

**What is happening**:
After my snapshot is applied on my production environnment, some foreign keys are removed. I don't understand why and why only some foreign keys. I'm applying a snapshot from postgreSQL to postgreSQL.

Probably because of those missing keys I have this error happening. The error is about fields where the foreign key has been removed.
```
ERROR: Failed to create relation "explore_filters.primary_label"
ERROR: "collection" is required
err: {
"type": "InvalidPayloadException",
"message": "\"collection\" is required",
"stack":
Error: "collection" is required
at RelationsService.createOne (file:///usr/src/app/node_modules/@directus/api/dist/services/relations.js:113:19)
at file:///usr/src/app/node_modules/@directus/api/dist/utils/apply-diff.js:201:44
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
"status": 400,
"code": "INVALID_PAYLOAD",
"extensions": {}
}
```
