### ISSUE TITLE
Extensions-sdk pnpm (shamefully-hoist) 

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#17948]
### Describe the Bug

When creating an extension via the extension SDK through pnpm and try to import from `@directus/shared/` package the CodeEditor / IDE (at least VsCode) doesn't recognize the shared package. You need to install the dependencies via `pnpm i --shamefully-hoist`. Would be great if this could be optimized or be mentioned in the docs as directus uses pnpm itself and probably a lot of users use it too.

### To Reproduce

- Create an extension with the extensions-sds and pnpm
- run `pnpm i`
- Try to import from the shared package (VsCode won't recognize it and show an error)
- re-install dependencies with `pnpm i --shamefully-hoist` and everything works as expected

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment]
The extensions sdk does not install `@directus/shared` by default. You have to run `pnpm i @directus/shared` to be able to use it.

Also be aware that you can't import from `directus/shared` directly but have to use `directus/shared/[whatever]` in oder to import things from utils or composables and so on.

You where able to access `@directus/shared` when running `pnpm i --shamefully-hoist` because `--shamefully-hoist` installs all subdependencies to the top level and because some other dependency has `@directus/shared` as a subdependency, you where able to access it but that is not the right way to do it and highly discuraged as it can lead to a lot of problems.
