### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by lericol** [directus/directus#17946]
### Describe the Bug

You have table (collection): id (int), params (string)
If you try to find big value in this table (collection) - you catch the error

```json
 {
  "errors": [
    {
      "message": "select \"collection_name\".\"params\", \"collection_name\".\"id\" from \"collection_name\" where ((\"collection_name\".\"id\" = $1) or LOWER(\"collection_name\".\"params\") LIKE $2  order by \"collection_name\".\"id\" asc limit $12 - value \"710406684325\" is out of range for type integer",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

create collection with id (int) and field test (string)
try to find big value in this table (collection) - you catch the error

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
@lericol just to confirm, are you using PostgreSQL as the database?

This seems very much like #15809. It looks to be a rather odd bug. I can confirm it happens in PostgreSQL, but not in MySQL.

### Exact reproduction steps

0. Use PostgreSQL database.
1. Create a new collection `test`.
2. In collection `test`, create a new string field called `name`.
3. Create 3 items in collection `test`, with names `T1`, `T2`, and `T3` respectively.
4. Make a GET request to `/items/test?search=710406684325` with the necessary read permission.
5. (optional) try the hooks extension shared below.

### Findings

It seems like the "issue" precisely happens with this line:

https://github.com/directus/directus/blob/13a720bb639018475a4e7af8774df0e6da76e6f2/api/src/utils/apply-query.ts#L762

as `.where({ "test.id": 710406684325 })` is causing trouble in postgres, but not `.whereRaw('??.?? = ??', ['test', 'id', 710406684325])`. However both works perfectly for MySQL.

What's particularly odd is both syntax actually generates the exact same SQL query, at least from what I've found. Here's a sample hooks extension to further illustrate it:

```js
module.exports = ({ init }, { database: knex }) => {
	init('app.before', async () => {
		const collection = 'test';
		const name = 'id';
		const number = 710406684325;

		const failedQuery = knex.from(collection).where({ [`${collection}.${name}`]: number }); // this is the same object syntax as apply-query.ts line 763
		const successfulQuery = knex.from(collection).whereRaw('??.?? = ??', [collection, name, number]);

		// both generates the exact same query.
		// PostgreSQL: 'select * from "test" where "test"."id" = 710406684325'
		// MySQL: 'select * from `test` where `test`.`id` = 710406684325'
		console.log({ rawFailedQuery: failedQuery.toString() });
		console.log({ rawSuccessfulQuery: successfulQuery.toString() });

		// somehow for failedQuery, `710406684325` is turned into string `"710406684325"` via pg driver
		failedQuery.then((r) => console.log(r)).catch((e) => console.error(e));
		successfulQuery.then((r) => console.log(r)).catch((e) => console.error(e));
	});
};
```

With the information at hand, I can only assume it's something to do with the `pg` driver itself, rather than Knex or Directus. However it may require more research to verify this assumption.

**Comment by lericol** [comment]
> @lericol just to confirm, are you using PostgreSQL as the database?
> 
> This seems very much like #15809. It looks to be a rather odd bug. I can confirm it happens in PostgreSQL, but not in MySQL.
> ### Exact reproduction steps
> 
>     0. Use PostgreSQL database.
> 
>     1. Create a new collection `test`.
> 
>     2. In collection `test`, create a new string field called `name`.
> 
>     3. Create 3 items in collection `test`, with names `T1`, `T2`, and `T3` respectively.
> 
>     4. Make a GET request to `/items/test?search=710406684325` with the necessary read permission.
> 
>     5. (optional) try the hooks extension shared below.
> 
> 
> ### Findings
> 
> It seems like the "issue" precisely happens with this line:
> 
> https://github.com/directus/directus/blob/13a720bb639018475a4e7af8774df0e6da76e6f2/api/src/utils/apply-query.ts#L762
> 
> as `.where({ "test.id": 710406684325 })` is causing trouble in postgres, but not `.whereRaw('??.?? = ??', ['test', 'id', 710406684325])`. However both works perfectly for MySQL.
> 
> What's particularly odd is both syntax actually generates the exact same SQL query, at least from what I've found. Here's a sample hooks extension to further illustrate it:
> 
> ```js
> module.exports = ({ init }, { database: knex }) => {
> 	init('app.before', async () => {
> 		const collection = 'test';
> 		const name = 'id';
> 		const number = 710406684325;
> 
> 		const failedQuery = knex.from(collection).where({ [`${collection}.${name}`]: number }); // this is the same object syntax as apply-query.ts line 763
> 		// using number as the 3rd binding also doesn't work in Postgres, but works in MySQL
> 		// .whereRaw(`??.?? = ?`, [collection, name, number]);
> 		const successfulQuery = knex.from(collection).whereRaw(`??.?? = ${number}`, [collection, name]);
> 
> 		// both generates the exact same query.
> 		// PostgreSQL: 'select * from "test" where "test"."id" = 710406684325'
> 		// MySQL: 'select * from `test` where `test`.`id` = 710406684325'
> 		console.log({ rawFailedQuery: failedQuery.toString() });
> 		console.log({ rawSuccessfulQuery: successfulQuery.toString() });
> 
> 		// somehow for failedQuery, `710406684325` is turned into string `"710406684325"` via pg driver
> 		failedQuery.then((r) => console.log({ failedQuery: r })).catch((e) => console.error(e));
> 		successfulQuery.then((r) => console.log({ successfulQuery: r })).catch((e) => console.error(e));
> 	});
> };
> ```
> 
> Testing with `psql` in the terminal also seems to indicate that the raw SQL query above should work:
> 
>     * Success: raw SQL that is built by Knex
>       ![](https://user-images.githubusercontent.com/42867097/227826057-28f8e1e7-2858-4ff5-b3fd-272ea6358cea.png)
> 
>     * Fail: intentionally add single quotes to make it throw the same error as reported
>       ![](https://user-images.githubusercontent.com/42867097/227826118-ee7db74e-1740-4aa5-a969-cb419f5bc2c8.png)
> 
> 
> With the information at hand, I can only assume it's something to do with the `pg` driver itself, rather than Knex or Directus. However it may require more research to verify this assumption.

Yes, PostgreSQL

**Comment by Zack-Heisnberg** [comment]
After further investigating here are my findings , the way knex is parsing whereRaw and passing it to the PG driver is diffrent

i had a table called currencies , and a int field and i init a connection with the pg library

```
const { Pool } = require('pg')
const connectionString = "postgres://************/postgres"
const pool = new Pool({
  connectionString: connectionString,
})
const collection = 'currencies';
const name = 'sort';
const number = 710406684325;
```


using whereRaw and orWhereRaw  is the equivalent of the following code , it's will ignore the error how ever the results are actually always 0 row unless there is a diffrent orWhereRaw , so it's not really a successfulQuery , more like one that ignore errors. 



```
const successfulQuery = "SELECT * FROM " + collection + " WHERE " + collection + "." + name + " = " + number;
pool.query(successfulQuery, function(err, rows) {
  if(err) throw err
  console.log(rows)
})
```
![image](https://user-images.githubusercontent.com/69718435/227912933-176d2620-5437-4cbe-90be-53ed00033710.png)


in the other hand using where ( orWhere ) is the equivalent of the following code , the code will perform checks internally using the ( libpq library ) , and show the out of range error
```
const failedQuery = "SELECT * FROM " + collection + " WHERE " + collection + "." + name + " = $1";
pool.query(failedQuery, [number], function(err, rows) {
  if(err) throw err
  console.log(rows)
  pool.end()
})
```
![image](https://user-images.githubusercontent.com/69718435/227912123-d75d6ef4-2d88-4708-8f19-05dd0bca2f09.png)


so using  this.orWhereRaw instead of this.orWhere will be the solution

**Comment by Fusseldieb** [comment]
Would be nice to see a fix for this
