### ISSUE TITLE
M2O field doesn't allow `directus_collections` to be selected

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#18054]
### Describe the Bug

I'm trying to create a `m2o` fields to the `directus_collections` table, which results in the following:

- `directus_collections` doesn't show up in `System` dropdown menu
- If i manually enter the `directus_collections` table name in the `Related Collection` field, foreign key gets recognized and also automatically populated, but then, in content creation, the relation shows an empty set

![image](https://user-images.githubusercontent.com/3661363/229984049-9b77a511-5811-4545-8b57-ce5a6b06ca0a.png)

![image](https://user-images.githubusercontent.com/3661363/229984221-27ba1d15-6540-418b-a3b3-82fb2aeffa74.png)

![image](https://user-images.githubusercontent.com/3661363/229984329-100164dd-63d5-4c8c-b692-bef64524b8ee.png)

### To Reproduce

Create a `m2o`  fields to be related to `directus_collections` table

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment]
This is currently intentional because `directus_collections` is one of the system collections that does not 100% work the same as other typical collections, as noted in:

https://github.com/directus/directus/blob/f1b48cb81db03986ed19f9d5c198e56981a7aaa8/app/src/constants.ts#L27-L39

Another relevant answer that elaborates more on what are the "differences": https://github.com/directus/directus/discussions/14362#discussioncomment-3121079

Depending on what you're looking to achieve, feel free to open a new discussion in the category of your choice 👍

**Comment by darioguarascio** [comment]
Thanks @azrikahar
