### ISSUE TITLE
Configuration to disable upgrade checks

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1837]
**For security issues, please email support@getdirectus.com directly.**

Directus makes a HTTP call to https://directus.io/check-version to check for new versions. It should be possible to disable that call in the configuration.php, much like as for the feedback.

## Version Info
  - Directus version and branch: 6.4

**Comment by benhaynes** [comment]
Hey @wittwerch – first let me give a little background on this:

* For security reasons, it is important to stay up to date with the newest versions of any software. Still, developers should be able to choose if and when they upgrade.
* The other *extremely* important reason for this check is that it gives us a very basic (and anonymous) sense of Directus usage. Being a free and open-source project, we need a way to gauge how many people are actually using Directus. If that number gets too low, we would need to reduce our development/support. Our goal is to build a world-class framework that can benefit an increasing number of people – so we need to keep our costs/staff commensurate to the usage. Believe me, Directus is free... but not cheap.
* That said, you can always adapt Directus remove this. We're trying to find a balance here – if it's too easy to remove then we have no insight into Directus – too difficult is annoying too. We're happy to discuss this on Slack – hopefully we can find a direction that most people are comfortable with.

Second, we're really trying to keep our issues/requests organized. Since this is technically a feature request, it should be logged at FeatHub so that our community can vote on it:

https://feathub.com/directus/directus

**Comment by wittwerch** [comment]
Hi Ben

Thanks for your detailed feedback. I understand why you want these basic metrics, but in larger corporate environments software that phones home is a no-go. However since it's open source we will simply remove that call and maintain that in our fork, otherwise we won't pass security.

Sorry for not posting on FeatHub, forgot about it. I'm used to have that on Github too..

Best 
Christian

**Comment by benhaynes** [comment]
Yeah, it was a tough decision to add this, but it's necessary for now. In the future we'll try to make it easier to disable – but for now a fork should do.
