### ISSUE TITLE
Bad token 

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1854]
## Version Info
  - Directus version and branch: build
  - PHP version: 5.6
  - MySQL version: 5
  - Web server: apache
  - OS name and version: linux 

## Expected Behavior
401 with a json error or a meaningfull error

## Actual Behavior
401 Unexpected Y

## Steps to Reproduce
 1. request a token
 2. add the token as a bearer on Authorization header
 3. remove the last char token to make it invalid

```
GET /api/1.1/tables/comments HTTP/1.1
Host: localhost:8081
Authorization: Bearer UuF5yrtp6W597bClHDZA9uni7bKW9W
Cache-Control: no-cache
```

**Comment by rijkvanzanten** [comment]
Hey @cgarnier! Thanks for the heads up.

For reference, the same happens for the other ways of passing the access_token (f.e. the param)

**Comment by WellingGuzman** [comment]
Now that I'm thinking about this, this has been working like this for long time, don't know if we should keep it that way, to prevent current user for broken results. Expecting the string instead of the JSON.
---

This definitely will be part of our new API Version. Should we call it a bug (API 1.1) or feature request for the new API version?

**Comment by benhaynes** [comment]
If it changes the response then we DON'T update the previous versions. Let's fix this (and everything else) and release it under 2.0

**Comment by WellingGuzman** [comment]
This will be include in API 2, we are not going to update this for API 1.x.
