### ISSUE TITLE
Saving row with translations interface fails

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1872]
## Version Info
  - Directus version and branch: [develop latest](https://github.com/directus/directus/commit/9d3263c89cabc7bbba64433ccdd195725ae81c2c)
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: Apache (MAMP Pro)
  - OS name and version: macOS High Sierra v10.13.1 Beta (17B25c)

## Expected Behavior
Clicking the save button of a table with a translations interface included saves the item.

## Actual Behavior
The server returns an error
```
Server Error
Undefined index: id
```

This might be due to the fact that the `languages` table uses a custom text-based primary key named `code` instead of `id`

## Steps to Reproduce
 1. Setup a translations interface by following the [Medium article on the subject](https://medium.com/directus/multilingual-content-setup-in-directus-i18n-4f243f72e554)
 2. Create a new item and save

## Additional info
[schema-dump.sql.zip](https://github.com/directus/directus/files/1368756/schema-dump.sql.zip)

**Comment by WellingGuzman** [comment]
It wasn't related to the table using a text-based primary key, but due to our simple caching implementation on the tables/columns objects.

When you fetch for one column from a table before fetching all, you will always get the first one.

Already fixed by https://github.com/directus/directus/commit/ff9cb1fbe8e96edf9ea28d791072b8fc6f1e9686
