### ISSUE TITLE
Emoji inside Markdown resulting in error with MySQL 5.7

### ISSUE THREAD

**Issue by afonsolopez** [directus/directus#18768]
### Describe the Bug

I'm not able to save a Markdown text on MySQL 5 if a use a emoji on it.

This text input:
### Another one ☝️

Result in this error:
```
{
  "message": "update `post` set `text` = '### Another one ☝️', `date_updated` = '2023-05-29 12:35:59.044' where `id` in ('8') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\\xE2\\x98\\x9D\\xEF\\xB8\\x8F' for column 'text' at row 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

### To Reproduce

Im using a fresh install of Directus docker and default MySQL 5.7 setup.

Everything else is working fine, as expected.

FYI:
I also tried setting envs like `DB_CHARSET="utf8mb4_unicode_ci"` and `DB_CHARSET="utf8mb4"`

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by u12206050** [comment]
Does Directus/Knex even support Mysql 5.7?

**Comment by jaads** [comment]
> Does Directus/Knex even support Mysql 5.7?

Knex runs integration tests only against the latest version of databases, so I'd say they don't support it actively. Directus also runs some test against MySQL 5. However emojis are probably not part of those tests.

**Comment by rijkvanzanten** [comment]
This is most definitely because the column is using the wrong collation in MySQL. Make sure that the actual column is configured to use the `utf8mb4` character set (rather than on the connection level, which is what the env var controls.

> Does Directus/Knex even support Mysql 5.7?

We're trying to match whatever the active LTS version is of the third party service. From what I can tell, 5.7 is technically still under LTS by Oracle until October 2023, so we'll match that! That does mean that starting this October, we'll stop supporting MySQL 5.7 as well 👍🏻 https://endoflife.date is a great resource for that information.
