### ISSUE TITLE
integer input field, auto incremented field cannot be null

### ISSUE THREAD

**Issue by co2nunes** [directus/directus#18784]
### Describe the Bug

I am trying to create an order number such as a primary key, and I set all field UI options the same as the "id" primary key but it returns the value cannot be null even though I when trying not allowing or not NULL values.

### To Reproduce

create an integer input field with a different name of the id primary key
set the settings the same as the id

returns: value cannot be null.

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
Do you by any chance already have data in that collection? If so then you cannot set a new field to be not-null without default because the column will be created with the value NULL for each existing record.

Happy to re-open when more information becomes available

**Comment by co2nunes** [comment]
No I don't have any data in the collection.

**Comment by br41nslug** [comment]
Interesting, then can you elaborate on how exactly you are configuring this field and where you're seeing this error?
If you're seeing this while trying to save a record then are you setting a value for this field? Because the primary is both `hidden` and `not null` by default causing a save null if you copied those settings.

**Comment by co2nunes** [comment]
I tried to create a "secondary" key for tracking order numbers just like a primary key but with a prefix.
The settings exactly the same except for the field name.

**Comment by br41nslug** [comment]
> I tried to create a "secondary" key for tracking order numbers just like a primary key but with a prefix. The settings exactly the same except for the field name. I can provide a screenshots if you want.

Exactly the same won't work (for the reasons i tried explaining in my last message). Because you cannot set "auto increment" outside of primary keys (with Directus) you're left with a "hidden" + "required" + "unique" field expecting a value you are unable to fill using the App.

**Comment by co2nunes** [comment]
How would you suggest me create an automatic order number field within Directus? I would like it to be auto-incremented and perhaps have a prefix.

**Comment by br41nslug** [comment]
If you were to add 2 auto increments you'd have 2 identical fields. It sound like you want to fill a new field with `prefix + ID` which you definitely can do using flows or hooks.
I personally however would not actually save that to the database because if it's deterministically built from a static prefix and the ID then you can always rebuild using only the ID 🤔

**Comment by co2nunes** [comment]
Thanks for your input. Will do this on Flow's Run script Operator.
