### ISSUE TITLE
Bad http code for /api/1.1/tables/

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#1883]
## Version Info
  - Directus version and branch: build
  - PHP version: 7
  - MySQL version: 5 
  - Web server: apache 
  - OS name and version: ubuntu 

## Expected Behavior
Trying to resolve a missing table should result a 404

## Actual Behavior
/api/1.1/tables/missing-table => 200 with a json 404 error
/api/1.1/tables/missing-table/rows => 403 with a json forbiden error

## Steps to Reproduce
 1. GET /api/1.1/tables/missing-table
GET /api/1.1/tables/missing-table/rows

**Comment by WellingGuzman** [comment]
This has been fixed already on `develop` branch and it returns `422 Unprocessable Entity`, but this doesn't seem as a proper error, as the actual problem is that's not found rather that can be processable.

Fixed by https://github.com/directus/directus/commit/1e03c01ab0c2c5f23662627dabff035b22f6b462
