### ISSUE TITLE
Markdown Field - Toolbar not visible when too much text included

### ISSUE THREAD

**Issue by wfriedman89** [directus/directus#18869]
### Describe the Bug

When using a markdown field, if the text becomes too much, you can get to a point where you can't see the toolbar while editing lines of text at the bottom of the field
![Screenshot 2023-06-13 at 12 09 59 AM](https://github.com/directus/directus/assets/109602228/6e3625ac-c9ab-4858-ac08-504f953cc554)

### To Reproduce

1. Add a markdown field to a collection
2. Add an item in that collection
3. In the item, add lots of text to the markdown field
4. You can scroll on the field/page enough and get to a point where you can be editing text in the markdown field but you cannot see the toolbar

### Directus Version

v10.2.1

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
Same here both Firefox and Chrome seem to handle this just fine. There is a point where the text area becomes larger than the screen you're watching on "hiding" the toolbar above the fold. However i dont think that is something trivially solvable and will amount to a new feature instead of a bug if that is what you meant.
