### ISSUE TITLE
Repeater field has no validation via API

### ISSUE THREAD

**Issue by maxsteinwand** [directus/directus#19163]
### Describe the Bug

When creating a repeater field and adding fields that are required the validation works in the Directus app but not via the API. The JSON is not validated at all and you can leave fields empty or remove them completely. You can also add random fields/values to the JSON.

The names used below are examples.

### To Reproduce

1. Create Repeater Field 'settings'
2. Create Field 'key' and mark as required
3. Create Field 'value' and mark as required
4. Add a pair via Interface (working as expected, if no value entered you can't create/update an item)
5. Update the repeater field via the API with a Patch HTTP Request

You can leave out the required fields or set a value that shouldn't be possible.
```
 "settings": [
        {
          "key": "",
          "value": null
        },
        {
          "value": ""
        }]
```

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
This is technically working as intended, JSON field content is not validated 😬 Repeaters are stored as JSON field which are not validated at the API layer because it is just a string. The required checkbox you mention is an App only feature when it comes to repeaters (or virtual fields).

If you require API validation on your fields please do use actual database fields.

Feel free to open a feature request for enhanced JSON support or improvements to the Repeater interface.
