### ISSUE TITLE
Block Editor - Latest content is not always saved

### ISSUE THREAD

**Issue by a-fazal** [directus/directus#19234]
### Describe the Bug

When I type or make changes to a block editor/editorJS field, the changes sometimes do not always save. This usually happens if I'm typing fast or adding blocks fast and then right after I press save but sometimes it can happen randomly. I expect that it should save the latest changes always though...

See in this video how inside the quote I last typed "oktest" and saved but only "ok" got saved

https://github.com/directus/directus/assets/19141713/84347124-f6b9-4a44-a345-2c1ec99713e4

I think this is happening because Directus does some async comparison between the old blocks and the new blocks to see if they have changed, and then emit the change value, but if this check doesnt finish before the next value is emitted it may still save with the previous value. Or also related to the debouncing. But I think the save button click should capture the latest changes regardless.

### To Reproduce

1. Enter some content in a block editor field
2. Save
3. Notice that the last changes werent actually saved*
*Might have to repeat steps 1-2 repeatedly to get 3 to happen, usually fast typing/changes causes it to trigger more

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
I tried the suggested steps and re-did them a bunch of times but cannot reproduce this. :frowning_face: 

![image](https://github.com/directus/directus/assets/14810858/3bea2518-3b1c-4728-82fc-33b7905b0130)

Can you share a lil' more info about your setup? "It just works" for me.

**Comment by a-fazal** [comment]
@DanielBiegler Can you try with more content and different blocks and see if theres an issue? Adding a new list and then changing a text in a paragraph, then save.

**Comment by rasco** [comment]
we have actually also encountered this problem before.
pressing save too quickly right after entering or copy-pasting text sometimes does not save the new changes in that field.

**Comment by DanielBiegler** [comment]
I now copied large amounts of generated _Lorem Ipsum_ text and simply cannot reproduce this. Works as intended on v10.5.2

@rasco or @a-fazal have you maybe found a reproducible way? Have you upgraded to v10.5 - did that help?

**Comment by DanielBiegler** [comment]
I managed to reproduce this via a new Docker instance using tag 10.5.2 and sqlite as the DB! See here:

[Screencast from 08.08.2023 16:09:31.webm](https://github.com/directus/directus/assets/14810858/3065cb91-47b3-414e-a9fa-35498d67da8a)

**Comment by DanielBiegler** [comment]
Dear reader: This seems to be caused by the delayed calling of `onChange` because editorjs does debouncing/batching of events instead of firing for every keystroke, see:

https://github.com/codex-team/editor.js/blob/b39996616c33de90bb82e3d7a009c865cf2b0f0c/types/configs/editor-config.d.ts#L91-L96

We use this to emit our own `input` event to change the state, hence the "quickly input changes" dont get reflected!

**Comment by MarioLiebisch** [comment]
Not sure if this is related, but spent quite some time trying to figure out why my blockquote alignment isn't properly applied. Turns out the changes aren't saved.

To reproduce my case (latest Docker image, but experiencing this since adding the block editor weeks ago):

* Create a text block and add some text.
* Create a blockquote block and add some text.
* Create another text block and add some text.
* Save and reopen the editor. Everything is as expected.
* Now change the text alignment for the blockquote. Don't change anything else.
* Save the changes and reopen the editor. The alignment change didn't save.
* Now change the text alignment for the blockquote once more, but also type a few extra characters anywhere.
* Save the changes and reopen the editor. The alignment saved properly.
