### ISSUE TITLE
Batch edit, set status bug

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1924]
## Version Info
  - Directus version and branch: develop
  - PHP version: 7.0
  - MySQL version: 5.7

## Actual Behavior
When batch edit, set status to active, were deleting items. **Bug only if column `status` settings is visible.** 

## Steps to Reproduce
 1. Make `status` column visible (**This issue, is only played if the column is visible**)

![default](https://user-images.githubusercontent.com/4669992/32043970-e8d0ba62-ba44-11e7-91d4-b56032949d38.png)

 2. Batch edit items, set active and save 
 
![default](https://user-images.githubusercontent.com/4669992/32044047-25096c7c-ba45-11e7-92e2-0e2b4acec8b8.png)

see `post` values

![default](https://user-images.githubusercontent.com/4669992/32044138-5d26d14e-ba45-11e7-8b50-630a0bea74dc.png)

**Comment by WellingGuzman** [comment]
Thanks for reporting this @dsivokhin, there's a bug (as you reported) with batch, and we will be working on it this week, we will try to get this done the as soon as possible.

**Comment by danhipke** [comment]
I'll take a look at this one.

**Comment by WellingGuzman** [comment]
Thanks @danhipke, we appreciate your contributions.

**Comment by danhipke** [comment]
@WellingGuzman Opened a PR for this issue. 

The jquery serializeArray function was serializing the input of type="hidden" for the status field as an empty string, causing it to be concatenated with the draft/published status flag from the radio buttons. This created instances where the edit view data had status set to "1," or "2,", because it thought status was a multivalued field and was joining the actual value and an empty string by a comma. Switching the input a type of "radio" and hiding it via styling fixes the issue, so that only one "status" value gets serialized.

**Comment by WellingGuzman** [comment]
This issue has been fixed by 57f2bd3

Thanks for your contribution @danhipke
