### ISSUE TITLE
@directus/sdk File upload

### ISSUE THREAD

**Issue by kuzyk** [directus/directus#19255]
### Describe the Bug

Sending files with latest version of sdk throws server exception
<img width="1336" alt="image" src="https://github.com/directus/directus/assets/941542/86efe387-7f00-4fe6-a8ea-d40e301afdcd">

that happening because of 
Content-Type: multipart/form-data
it should be empty

and there is not way to unset it (with empty Content-Type its value will be set to application/json https://github.com/directus/directus/blob/main/sdk/src/utils/request.ts#L30)

### To Reproduce

```js
const client = createDirectus(domain)
    .with(
        rest(),
    )
    .with(authentication("json"));

client.setToken(token);

const file = ... File;

const form = new FormData();

form.set("file", file, file.name);

const item = await client.request(uploadFiles(form));
```

### Directus Version

v10.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
That FormData looks to be invalid https://docs.directus.io/reference/files.html#upload-a-file

**Comment by paescuj** [comment]
The issue is valid, it's indeed not working.
We shouldn't set the `Content-Type` header explicitly as it's missing the [`boundary`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#directives) property. By simply dropping the header we allow the `fetch` implementation to automatically and correctly set it.

This means we need to figure out a way to "unset" the `Content-Type` header:

https://github.com/directus/directus/blob/9a675880aba1ce6b1e916de9fde712ba9acf2b6b/sdk/src/rest/commands/create/files.ts#L29

https://github.com/directus/directus/blob/9a675880aba1ce6b1e916de9fde712ba9acf2b6b/sdk/src/rest/composable.ts#L19-L23

https://github.com/directus/directus/blob/9a675880aba1ce6b1e916de9fde712ba9acf2b6b/sdk/src/utils/request.ts#L29-L32

---

Another thing I noticed is that parsing the response fails when the "create" permission is granted without the "read" permission as it will be empty:

> Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

https://github.com/directus/directus/blob/9a675880aba1ce6b1e916de9fde712ba9acf2b6b/sdk/src/utils/request.ts#L38-L41

---

Example `vite` project for testing:
```js
import { createDirectus } from '@directus/sdk';
import { rest, uploadFiles } from '@directus/sdk/rest';

const client = createDirectus('http://localhost:8055').with(rest());

document.querySelector('#app').innerHTML = `
  <form>
    <label for="file">File</label>
    <input id="file" name="file" type="file" />
    <button>Upload</button>
  </form>
`;

const form = document.querySelector('form');
form.addEventListener('submit', handleSubmit);

async function handleSubmit(event) {
  event.preventDefault();

  await client.request(uploadFiles(new FormData(event.target)));
  event.target.reset();
}
```
