### ISSUE TITLE
directus:extension ignores "path" parameter and doesn't load extension

### ISSUE THREAD

**Issue by Joonel** [directus/directus#19263]
### Describe the Bug

I created an extension using [this doc](https://docs.directus.io/extensions/creating-extensions.html), then ran `npx directus link ...` to create a symbolic link, afterwards started Directus and got an error:
```
[12:28:48.027] WARN: Couldn't bundle App extensions
[12:28:48.028] WARN: Could not resolve "./extensions/interfaces/directus-extension-custom-tinymce/index.js" from "virtual:entry"
    err: {
      "type": "Error",
      "message": "Could not resolve \"./extensions/interfaces/directus-extension-custom-tinymce/index.js\" from \"\u0000virtual:entry\"",
      "stack":
          RollupError: Could not resolve "./extensions/interfaces/directus-extension-custom-tinymce/index.js" from "virtual:entry"
       ...
```
While simply coping `index.js` from `dist`  folder to `/extensions/interfaces/extension-name/` folder works, Directus ignores the extension's `path` parameter in the `package.json` that says (as I understood) where the actual `index.js` is located.

![image](https://github.com/directus/directus/assets/69682842/48dbce81-587d-4d82-b9b0-d6c62c6c323c)

### To Reproduce

Create a new extension, build it, link it and start Directus.

### Directus Version

10.5.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment]
The `path` variable is used to determine where to build the extension `index.js` during build it has no further functionality for deployment (only bundle extensions do).
It doesnt look like you've correctly `npm linked` the package.
Instead of trying to untangle that the easiest way to test your extension locally is to use the `path` setting and point that to your extension folder like so:
```
"directus:extension": {
  "path": "/path/to/extensions/interfaces/directus-extension-custom-tinymce/index.js"
}
```
