### ISSUE TITLE
Block editor default value injected when editing existing records.

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#19428]
### Describe the Bug

When setting a default value on a block editor field, every time the form is opened in the Directus Studio App, the default value is injected again. This does not delete existing content.

### To Reproduce

Create a block editor field.
Add a default value.
Create a record and notice the default value
Save the record
Open the record again
Notice that the default value has been added in again.

Demo Recoding:

https://github.com/directus/directus/assets/21194068/56d52a8d-561f-46a1-9572-5b088ccafc59

### Directus Version

10.5.2

### Hosting Strategy

Directus Cloud

**Comment by Nitwel** [comment]
What is the exact value that you are using as the default value? I'm having trouble reproducing this.

**Comment by Nitwel** [comment]
Was able to reproduce this on postges. MariaDB seems to have an entirely different problem with saving default values as proper json.

**Comment by Nitwel** [comment]
This seems to be a but in Editor.js, see https://github.com/codex-team/editor.js/issues/2439

**Comment by hanneskuettner** [comment]
This seems to be fixed in some of the last Editor.js versions (they touched the `render` method a few times in the last 2 minor versions), at least it is not showing up in v10.10.7 of Directus anymore.


https://github.com/directus/directus/assets/4376726/c1ddd519-046f-434f-8425-ed7ae20c7350

Closing this for now, happy to reopen if this surfaces again.
