### ISSUE TITLE
Using numbers on left hand side of filter of condition throws ValidationError

### ISSUE THREAD

**Issue by danielband** [directus/directus#19478]
### Describe the Bug

In one of my flows I implemented a condition with the following filter
```
{
  "filter": {
    "$trigger": {
      "shop": {
        "_neq": 2
      }
    }
  }
}
```

The trigger is another flow with input
```
{
  "shop": 2
  "course": 6
}
```

The condition operation throws
```
[
  {
    "name": "ValidationError",
    "message": "\"$trigger.shop\" contains an invalid value",
    "stack": "ValidationError: \"$trigger.shop\" contains an invalid value"
  }
]
```

Accessing $trigger.shop in the console operation expectedly logs 2.

### To Reproduce

1. Create a flow with json user input params.
2. Create a condition operation with filter on a number input field of **$trigger**
3. Let it fail

Using a filter with string the left other operation variable actually works e.g. this input would work:
```
{
  "shop": "2"
  "course": 6
}
```

My workaround is to convert the shop field into a string. Thanks to javascript that works, but its hacky and retarded.
```
module.exports = async function(data) {
	return {shop: `data.$trigger.shop`, course: data.$trigger.course};
}
```

This operation used to work in directus 9.21.2. Seems like you guys made a bunches of changes to types?

Somehow flows are quite broken atm :(

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
Hi there! Thank you for the clear reproduction steps, I reproduced this and can confirm. It fails on `2` but works on `"2"`.

**Comment by DanielBiegler** [comment]
So I retraced the data flow because I expected the field to be converted to a string at some point but it all checks out so far...

We go into the operation and try to `schema.validate` it

https://github.com/directus/directus/blob/54763aa7400efe5279315a905e8e1f4aed81ccc5/packages/utils/shared/validate-payload.ts#L56-L64

`payloadWithFunctions` holds our data and is indeed a number but `schema.validate` fails.

Stepping into how the `schema` gets generated in `generateJoi` confirms that both `compareValue` and `numericValue` both are indeed numbers! (used typeof to confirm) - Can also confirm that Line 130 gets called:

https://github.com/directus/directus/blob/54763aa7400efe5279315a905e8e1f4aed81ccc5/packages/utils/shared/generate-joi.ts#L121-L132

Currently not sure if its related but the `getAnySchema().not(compareValue, numericValue)` results in the type any?:

```json
{
  type: 'any',
  '$_root': {
    _types: Set(12) {
      ...
```

Will have to check out how the joi schema thing works /shrug

**Comment by DanielBiegler** [comment]
Wait a minute, I think I misunderstood you yesterday. Everything is working correctly.

There are 4 states we could be in:

| Filter | Value |
|--------|--------|
| `_neq: 2` | 2 | 
| `_neq: 2` | "2" |
| `_neq: "2"` | 2 | 
| `_neq: "2"` | "2" | 

And it works as expected for these cases, because the equality checks for types too. If you would like to check for both possibilites you could use the "is not one of" Operator, see here: https://docs.directus.io/reference/filter-rules.html#filter-operators

`_nin: [ 2, "2" ]` which will work as you expected, failing for both possibilites.

**Comment by dband** [comment]
Uff, I feel a bit ashamed right now. Negations can be a brain fuck sometimes. I am so sorry.
 
Thank you a lot!
