### ISSUE TITLE
Add /server/time to get server current time

### ISSUE THREAD

**Issue by loongmxbt** [directus/directus#19484]
### Describe the Improvement

In https://docs.directus.io/reference/system/server.html, we have /ping, /info, /health, etc. I think add a /server/time or some better routes is useful for server to client side cross check, which is useful in many scenarios.

**Comment by rijkvanzanten** [comment]
Do you have an example of how / when this would be used?

**Comment by br41nslug** [comment]
I have used such features for syncing clients in the past, implemented through extensions
```ts
// ./extensions/endpoints/server-time/index.cjs
module.exports = function defineEndpoint(router) {
	router.get('/', (_req, res) => res.json({ serverTime: Date.now() }));
}
```

**Comment by u12206050** [comment]
Yeh funnily enough I just added a custom endpoint this past week for exactly this. Although I would add I return the ISO Timestamp, but I guess epoch time might be fine as well.

We use it to sync our frontend clients, since we have some count downs etc before registration opens, and some of them are either ahead or behind our server time. Using a simple NTP protocol using the time we get from the server to sync.
