### ISSUE TITLE
External images not loading in default WYSIWYG editor due to CSP error

### ISSUE THREAD

**Issue by eaglexer** [directus/directus#19585]
### Describe the Bug

When I try to copy content that contains external images, the images are not displayed in the editor and I see an error in the console for each image.

`Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".`

<img width="1673" alt="CleanShot 2023-09-04 at 13 21 39" src="https://github.com/directus/directus/assets/9868992/b373a290-e1d3-4ea0-bab0-d3c181164b9b">

![CleanShot 2023-09-04 at 16 47 28](https://github.com/directus/directus/assets/9868992/564947ea-7e2a-4814-a7e4-0d65cadf0524)

When adding an external image through the editor, it is loaded locally and then displayed.

Can you please tell me what should I check first? Maybe it's worth changing something in the directus configuration or in nginx, cloudflare? Is the problem possible in tinyMCE itself?

Unfortunately, in trying to find a solution to this problem, I found nothing. I hope you can help solve this problem and thank you for your great work. Of all the cms that we tested, yours is the most flexible, fast and easy to use!

### To Reproduce

Copy any article with external images and paste it to standard WYSIWYG editor

- Ubuntu 22.04.3 LTS
- Cleavr Server management tool
- Directus 10.6.0
- Cloudflare

### Directus Version

v10.6.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
If you want to explicitly customize your content security policies you can do so via environment variables. See the config docs under [the security section](https://docs.directus.io/self-hosted/config-options.html#security).

Please see the section about [nesting](https://docs.directus.io/self-hosted/config-options.html#type-casting-and-nesting) too since you'll need this. The env variable will be converted into a configuration object for helmetjs.
