### ISSUE TITLE
How to modify admin interface

### ISSUE THREAD

**Issue by neocafe** [directus/directus#1960]
Hi, 
I was wondering if there is any way to use a custom interface on the admin panel for particular usergroup.

For example, I want to display a custom interface when a client of mine login to the CMS but for me as an admin / manager I can use the current default interface.

Any help will be appreciated
Thanks,
Sreejith

**Comment by benhaynes** [comment]
Hello – as of now there is now way to show different interfaces to different users/groups within Core. However, you could simply _extend_ your custom interface to check the current user's group/permission and show a different interface based on the value.

I've never tried that, but it seems like an interesting approach! If you decide to give it a go let us know how it turns out! If that doesn't work you can always submit a feature request: https://request.getdirectus.com/
