### ISSUE TITLE
GraphQL API Service has slow performance with large schema's.

### ISSUE THREAD

**Issue by dp1194** [directus/directus#19664]
### Describe the Bug

We've been using Directus for around 10 months now and we've recently run into some performance degradation on the GraphQL API. Our problem was 2 fold and half the issue had to do with our infrastructure which we resolved. This highlighted another issue though and allowed us to pinpoint where it was.

To investigate, we logged out console.time around the [GraphQL service](https://github.com/directus/directus/blob/main/api/src/services/graphql/index.ts#L105) within Directus and had the following results. We did this by modifying the JS files in `node_modules`.

```
--reduceSchemas: 199.016ms
--getReadableTypes: 1.369s
--getWritableTypes: 18.583ms
--readableCollections: 7.5ms
--updateCollections: 0.944ms
--buildSchema: 805.566ms
-getSchema: 2.424s
-validate: 116.788ms
-execute: 138.236ms
initService: 2.681s
```

The above results are on the infrastructure that had issues but helps to highlight where the issue is. Here are results on new infrastructure which was a lot better but you can still see a bottleneck.

```
--buildSchema: 258.314ms  
--getReadableTypes: 226.154  
--reduceSchemas: 67.201ms 
-getSchema: 568.241ms
-validate: 58.549ms  
-execute: 311.355ms 
```

So the [getSchema](https://github.com/directus/directus/blob/main/api/src/services/graphql/index.ts#L127) function call is taking a considerably long time to complete, understandably though with a fairly large schema. It is very CPU intensive.

So, should this function be called for every GraphQL request or should it rather be cached? In our case, I think that the composed schema should be cached and not rebuilt for every request.

I'd be happy to help out with a PR for this as we'd feel a lot better having those extra cpu cycles available. Would like to get your take on it first.

### To Reproduce

To reproduce this you need a fairly large schema. I can't provide our schema unfortunately but hopefully this will be useful.

`select count(collection) from directus_collections `
`305`

`select count(id) from directus_fields`
`2575`

So we have a total of 305 collections and 2575 fields across all collections.

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by davidpurkiss** [comment]
Awesome! I see this ready. Thanks for picking up! 🙌

**Comment by dp1194** [comment]
Awesome! I see this is ready. Thanks for picking up 🙌

**Comment by DanielBiegler** [comment]
I created a "big" sqlite database for testing purposes so that someone can pick this up without needing to generate everything themselves. The following DB has:

- 500 collections
- 20 fields per collection (e.g. 10000 total)
- 20 items per collection (e.g. 10000 total)

Version: current Main 10.7.0

[directus_v10-7-0__500_collections_10k_fields.zip](https://github.com/directus/directus/files/13179640/directus_v10-7-0__500_collections_10k_fields.zip)


(Note: Wrapped it in a ZIP due to GitHub complaining!)

**Comment by azrikahar** [comment]
> I think that the composed schema should be cached

After looking into this, unfortunately I'm not sure if this is easily achievable, at least from my understanding.

when using the default `cache.set`, the GraphQL schema's functions such as resolvers will be lost due to the underlying `JSONB.stringify` in keyv: https://github.com/jaredwray/keyv/blob/726b26991d9d53ec30a4797a2c5fedd63cd66a6a/packages/keyv/src/index.ts#L283-L284

which serializes the value before they are cached: https://github.com/jaredwray/keyv/blob/726b26991d9d53ec30a4797a2c5fedd63cd66a6a/packages/keyv/src/index.ts#L111-L112

As for when using our own `setCacheValue` wrapper which uses the `compress` util (inspired by jsonpack), it will also error because functions aren't really a supported type either:

https://github.com/directus/directus/blob/a11fb2b59dd9fff973f0ee24a51608600172a457/packages/utils/shared/compress.ts#L26-L188

---

That being said, it seems like the 2 most expensive calls _within_ `getSchema` are actually these 2:

https://github.com/directus/directus/blob/a11fb2b59dd9fff973f0ee24a51608600172a457/api/src/services/graphql/index.ts#L204-L206

as it'll go through all collections to create the `ReadCollectionTypes` used for queries and the rest for mutations.

With that in mind, one potential alternative approach I've also attempted to improve the performance was sort of skipping the mutations generation logic for queries, since we're not using those mutations when making a simple query, and altough that does help to reduce the time taken by around 30-40% from my tests, one flaw of "skipping generation of mutations for GraphQL queries" is it shouldn't be skipped for introspection queries. I'm not sure if there's a standard way to distinguish general queries vs introspection queries, but in hindsight this train of thought might not be a good solution to begin with.

@rijkvanzanten any thoughts on how should we approach this?

**Comment by rijkvanzanten** [comment]
@azrikahar Is there any way for graphl-compose to generate out the schema to a static representation and cache that? 🤔 If not, caching on the readable/writable type makes the most sense to me 👍🏻

**Comment by rijkvanzanten** [comment]
Next to slow performance, this can also cause memory issues if the schema is really big
