### ISSUE TITLE
Linking issue with foreign keys

### ISSUE THREAD

**Issue by neocafe** [directus/directus#1967]
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version:  7.1.11
  - Web server: Apache
  - OS name and version: Windows 10 

## Expected Behavior
I'm not so sure if this is either a feature request or a bug, what I was looking for is something like this: I have two tables: category & subcategory. Table subcategory has a column named category_id that links category to subcategory.

Now, when first I choose from a category I need subcategory values to be listed only based on the category I have chosen.

## Actual Behavior
No linking, will list all the fields within

**Comment by WellingGuzman** [comment]
This is a feature request @neocafe. We have talked about this, I don't know where we got in term of design this. @rijkvanzanten @benhaynes?

**Comment by benhaynes** [comment]
Correct. This "conditional fields" option has been discussed for quite a while. In order to add it into our workstream we need to get it to the top of https://request.getdirectus.com/

Then we'll want to discuss the best way to standardize this type of field. In the meantime, you could always create a custom Interface that updates based on the value of a previous field. If that works well then maybe we can add it to the Core codebase.

I'll close this for now since new features should go to the request tool. Thanks @neocafe!
