### ISSUE TITLE
Roles with App Access can view all Users when custom fields chosen

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#19693]
### Describe the Bug

When **App Access** is enabled for a role the following minimum permissions are applied by default:

```json
{
  "id": {
    "_eq": "$CURRENT_USER"
  }
}
```

Once I select fields to add permissions and save, the rule no longer applies and now I can view all users info.

### To Reproduce

- On a Role with **App Access** enabled
- Change access for the role to **App Access Minimum**
- Notice the Custom Permissions for Directus Users mentions App Access will have minimum permissions applied, limiting results to the current user
- Make an authenticated request to `/users` and you will only see yourself (correct behavior)
  - _You can do this by visiting the Users module in Directus (assuming there are multiple users)_
- Change the Custom Permissions for Directus Users to allow specific fields only, and save
- Make an authenticated request to `/users` and you will see basic info for all users
  - _You can do this by visiting the Users module in Directus (assuming there are multiple users)_

Video Demo
https://github.com/directus/directus/assets/73146636/1ad60dc0-3984-42bc-a02d-dd25da1a56fc

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
Hi there! :)

Those are _**minimum**_ permissions. An app user can at **_minimum_**, see themselves. You gave them more permissions afterwards, which you can constrain back using the filter.

**Comment by ched-dev** [comment]
The message says:

> The following minimum permissions are automatically applied when
"App Access" is enabled. You can grant additional permissions if
needed, but you cannot reduce permissions below this level.
> 
> ```
> {
>  "id": {
>    "_eq": "$CURRENT_USER"
>  }
> }
> ```

This implies these minimum permissions will be applied because I have **App Access** checked. That is not the case though.

I think it should either always apply the minimum requirement or somehow mention "unless you manually change permissions".

**Comment by rijkvanzanten** [comment]
> This implies these minimum permissions will be applied because I have App Access checked. That is not the case though.

Is it not? It will always be applied in an _or_ with whatever permissions you've configured beyond the minimally required ones. "Minimum" in this context refers to "minimally required to be able to use the application" 🤔 

Just to confirm @ched-dev, what did you set the _Permissions_ rules to when doing this test? Did you leave it blank? I'm wondering if the sneaky bug here actually might be that you've accidentally ended up with Permissions `_or: [app-minimal, {}]` where that empty object will allow anything (cc @DanielBiegler)

**Comment by ched-dev** [comment]
I added permissions for a few fields, then it loses it's App Access minimum. Here's a video of the whole setup: https://github.com/directus/directus/assets/73146636/1ad60dc0-3984-42bc-a02d-dd25da1a56fc

![Screen Shot 2023-09-16 at 1 49 11 PM](https://github.com/directus/directus/assets/73146636/601e3e9c-a6ae-4b02-b0af-21794ca9221c)
![Screen Shot 2023-09-16 at 1 49 43 PM](https://github.com/directus/directus/assets/73146636/e0cc6706-8113-4f17-80eb-45d5f4c4f2c9)

**Comment by ched-dev** [comment]
I do believe it's because it uses an `_or` but I think it should always be an `_and`, right? That's what the message implies because it says _you cannot reduce permissions below this level_.

**Comment by DanielBiegler** [comment]
> I think it should always be an _and, right?

No, I dont think so. Under that logic then every user will only ever be able to see their own user and noone else. Item permissions are for constraining, you don't grant more access there. Remember _and & _or are logical operators and are to be interpreted differently than normal spoken language. With an _and you would only allow someone to read an item IF the id matches the current user AND other matching constraints, which means you can only ever read your current user. If you tried to read a different user the first constraint would fail always because it cant match your ID, i.e. you see nothing but yourself.

> That's what the message implies because it says you cannot reduce permissions below this level.

But you are not reducing permissions, you are increasing permissions by supplying field permissions. They are all forbidden by default and you can only allow them. You are not reducing.

1. Setting `Field Permissions` is for _increasing_ permissions. They are all off by default.
2. Setting `Item Permissions` is for _reducing_ permissions. There are no rules by default.

This means: If you allow someone to read the field `example` they can read all `example` fields of all items of this collection. Then you can constrain it back down with a rule that says

```{ "id": { "_eq": "abc123" } }```

Now they can see only `example` fields of items with the id `abc123`.

Maybe [the docs](https://docs.directus.io/user-guide/user-management/users-roles-permissions.html#how-it-works-in-directus) might help too.

**Comment by ched-dev** [comment]
Thanks for the detailed description @DanielBiegler
