### ISSUE TITLE
WYSIWYG field filter issues by UTF-8 items

### ISSUE THREAD

**Issue by er1z** [directus/directus#19777]
### Describe the Bug

TinyMCE is converting some language-specific chars to entities what makes search impossible. Check `to reproduce`.

I guess it's caused by this: https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@encoding/

### To Reproduce

1. Create a WYSIWYG field
2. Create a record with something UTF-ish, like `stół z powyłamywanymi nogami`, save
3. Use global search against this field, `st` will show the item, but `stół` = nope

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment]
What database are you using? And if applicable, what collation/charset does that database use? According to the link you sent, that TinyMCE option should be disabled by default. Are you seeing the html entities returned from the API?

I'm wondering if this is actually related to the database `%LIKE%` query as discussed in https://github.com/directus/directus/discussions/19699 rather than how TinyMCE is saving thing s 🤔

**Comment by br41nslug** [comment]
TinyMCE replaces the `ó` with `&oacute;`. You can work around this by using the "raw editor" to save the actual data you want to be saved.

**Comment by rijkvanzanten** [comment]
Ah good one @br41nslug. Looks like the linked option was the wrong one. It's this one instead: https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@entity_encoding/

Can confirm this can be configured by adding

```json
{
  "entity_encoding": "raw"
}
```

to the "Options Override" options of the wysiwyg interface 👍🏻
