### ISSUE TITLE
Check if value exist and add +1 in slug

### ISSUE THREAD

**Issue by RudolfFussek** [directus/directus#1978]
Hey,

I have a problem. When I generate a article and the slug is setting by the title and I have two articles white the same title the slug don't see it?

Exaple:

Title => Hello boys!
Slug => hello-boys

Another Exaple:

Title => Hello boys!
Slug => Hello-boys-1 <= The 1 because it already gives the article with the Slug.

Is there a setting that the slug checks to see if the slug already exists?

Thanks for help!

**Comment by rijkvanzanten** [comment]
Hey @RudolfFussek! 

It is currently not possible to have the slug interface to check for uniqueness, but I really like the idea!

In order to add it into our workstream we need to get it to the top of https://request.getdirectus.com/

In the meantime, you could [create a custom Interface](https://medium.com/directus/how-to-create-a-custom-interface-ba8a4b7e72f4) (a copy of slug) that checks the uniqueness of the value field.

I'll close this for now since new features should go to the request tool. Thanks @RudolfFussek!
