### ISSUE TITLE
Many to one on the same collection preventing deletion

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#19865]
### Describe the Bug

When you create a many-to-one relation to the current collection the relational trigger for "on delete" will be locked to "prevent deletion". This results in being unable to delete any item in this collection that has the relation set (or is being related to if the one to many was configured too).

### To Reproduce

1. Create a recursive many-to-one relation to the same collection.
![firefox_W9A5yD0gzY](https://github.com/directus/directus/assets/9389634/d1c93da3-0506-4d5a-aa0b-2b714a333f49)

2. set up a few records who have this relation filled.
![firefox_Ar3PvDsD6C](https://github.com/directus/directus/assets/9389634/1f6fd97f-efa4-4b31-9ea7-76f234b5a382)

3. try to delete any of these items
![firefox_VY9Jffp9lB](https://github.com/directus/directus/assets/9389634/0e988313-f3cb-47b4-a1bc-03892fd7e894)

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by SvenBudak** [comment]
Thank you for opening this issue! I'm facing exactly the same problem in my app. My feeds have comments, and those comments have replies, which are essentially also comments. As long as there are replies, a feed cannot be deleted. This means if a user in the app wants to delete their own feed, Directus throws an error. This is a significant issue, and because of it, we cannot go live at the moment. GDPR mandates that if a user wants their data to be deleted, it must be genuinely erased. Therefore, we can’t just set the status to unpublished and filter it on the frontend.

I hope this issue can be fixed without too much effort :)

**Comment by SvenBudak** [comment]
These issues sound very similar, just in case this could be helpful: [#11604](https://github.com/directus/directus/issues/11604) https://github.com/directus/directus/issues/11510

**Comment by rijkvanzanten** [comment]
@br41nslug The reason for that is that not all database support recursive relational constraints (notably MS SQL will error out if you try setting that).

I think we should close this in favor of https://github.com/directus/directus/issues/9507, which is all about implementing an app-side flow that will automatically find and help you delete related items that are preventing the deletion of the current item 🙂
