### ISSUE TITLE
Do Design Double-Check

### ISSUE THREAD

**Issue by alexchopin** [directus/directus#19986]

**Comment by benhaynes** [comment]
@DanielBiegler — can we run through a live screenshare to go over the current design... or can you post some images/videos here for me to review? 🙌

**Comment by DanielBiegler** [comment]
@benhaynes Hey! Sure thing, will do so shortly after adding support for theming so you can see everything at once. :+1:

**Comment by DanielBiegler** [comment]
@benhaynes heres a quick summary of how it looks, now with theming support. Note how it didnt prompt the project-setup for the second admin since the first one already filled it out. Shoot me a DM in case you wanna do a 1:1 for the feedback :+1: 

[Screencast from 29.11.2023 12:55:31.webm](https://github.com/directus/directus/assets/14810858/fa40ab52-60db-401d-9cff-ff8ccbbd3ca8)

**Comment by benhaynes** [comment]
Thanks @DanielBiegler! Some feedback below...

* Reduce the paragraph max-width on Welcome (~12-14 words per line, max)
* Use underline for paragraph links (theming can make these colors weird)
* Should we add "Project Descriptor" to the first form?
* Radio button interface should be 3-up (one row)... do we support this as of now?
* In the "Let's setup your project..." (and any other text) we should use em dashes (—) instead of hyphens (-)... also let's confirm if it's "setup" or "set up".
* Should "Appearance" be "Default Appearance"?
* "Receive once-a-month updates" should be "Receive monthly updates"... it should be ON by default, and let's shorten that helper note to two lines (for the normal form width), maybe: "We take privacy very seriously. We never sell or share your information with anyone outside our organization."

**Comment by DanielBiegler** [comment]
@benhaynes 

- [x] Reduce the paragraph max-width on Welcome (~12-14 words per line, max)
- [x] Use underline for paragraph links (theming can make these colors weird)
- [x] In the "Let's setup your project..." (and any other text) we should use em dashes (—) instead of hyphens (-)... also let's confirm if it's "setup" or "set up".

- [ ] Should "Appearance" be "Default Appearance"?

Yes but thats as far as I know not a translatable i18n string yet whereas "Appearance" is, probably best to add full internationalization for the theming-labels as a separate PR from this one and update this PR once we have those.

- [x] Should we add "Project Descriptor" to the first form?

I included that now, which means we have one more half-field room for another field before the question:

![image](https://github.com/directus/directus/assets/14810858/1596958b-b74f-425e-8bd1-0cf3f5de0bfe)

I think configuring the project language would make sense too and it'd fit as a half field. Agreed?

- [ ] Radio button interface should be 3-up (one row)... do we support this as of now?

Yeah I'd love to do that also but its a little tricky! _As of right now_ the grid is directly tied to the length of the radio options per:

https://github.com/directus/directus/blob/99a7d04a135a2efc08f8386d7091e515c1321c28/app/src/interfaces/select-radio/select-radio.vue#L37-L54

I've happened to come upon this behaviour when debugging an issue once with chinese characters; Different languages have different lengths i.e. will look different. For example if we shorten the options to the following words it'll look slightly different:

![image](https://github.com/directus/directus/assets/14810858/495774bb-ae79-4aed-9f93-8b8402e2c642)

This is a tricky tiny detail indeed; No, we currently dont have a way to _properly_ overwrite that behaviour.

- [x] "Receive once-a-month updates" should be "Receive monthly updates"... it should be ON by default, and let's shorten that helper note to two lines (for the normal form width), maybe: "We take privacy very seriously. We never sell or share your information with anyone outside our organization."

Regarding

> it should be ON by default

We cant if we want to adhere to GDPR where only "positive action" is considered consent, for a short summary [I quote](https://cookiefirst.com/gdpr-cookie-banner-dont-use-pre-selected-boxes/):

> In May 2020, the European Data Protection Board (EDPB) published updated guidance on the use of consent under the GDPR. The guidance is clear on the fact that pre-ticked boxes are not a valid way to obtain consent from individuals.
>
> The EDPB states that consent must be given through a “positive action”, such as ticking a box or clicking a button. This means that consent cannot be bundled with other terms and conditions, and must be separate from them. In addition, the EDPB guidance says that consent must be “unambiguous”, which means that it should be clear to individuals what they are consenting to.
>
> The guidance goes on to say that any consent obtained under the old standard of consent will have to be renewed in order to meet the GDPR’s higher standard. This means that organizations will need to reach out to individuals who have already consented and obtain their consent again, this time using a method that complies with the GDPR.

Since we're interested in most likely personally identifiable info (website, email) we'll also need to include details on what gets transmitted and how users can withdraw. I could use your input on this please. :pray: 

We can argue that users can very easily disable transmission via environment variable to opt-out but for example basic cloud users cant set those themselves i.e. cant opt-out which is a big nono for GDPR.

One approach that I think would work for everyone is that we add all necessary info on a dedicated slide at the end with two buttons: "Dont share and Continue" and "Agree and Continue" which will finish the onboarding. Thoughts?

**Comment by benhaynes** [comment]
> I think configuring the project language would make sense too and it'd fit as a half field. Agreed?

This could make sense, but I'm wondering if a "Project Environment" dropdown (Prod, Staging, Dev, etc) might provide more valuable insight. We could also have the URL be full width, and put Descriptor next to Name.

> For example if we shorten the options to the following words it'll look slightly different:

Ahh, I remember that! We should probably just make 3/4 up an option instead of inferring it from the char-length. In any event, for now let's just use these shorter descriptions.

> We can argue that users can very easily disable transmission via environment variable to opt-out but for example basic cloud users cant set those themselves i.e. cant opt-out which is a big nono for GDPR.

What if we based the initial state of that checkbox on the ENV value? I guess that doesn't solve the PRO Cloud issue though, since the ENVs aren't configurable yet.

I like the idea of using two buttons... but don't think it needs to be a dedicated slide, adding this to the last slides CTA should be enough. So a default/primary CTA that says "Agree and Continue" and a subdued CTA that says "Do Not Share and Continue" (where the Skip action was previously). If we used the CTAs, would we still have the checkbox, or does one replace the other? CC @rijkvanzanten @alexchopin

**Comment by rijkvanzanten** [comment]
Design has been reviewed. Considering this issue closed 🙂
