### ISSUE TITLE
SVG Display Issue: Top and Bottom Parts Truncated in Add Item to Collection View

### ISSUE THREAD

**Issue by TiBej** [directus/directus#20035]
### Describe the Bug

In the view to add a item to a collection: When you upload there a svg the top and bottom parts are not shown.

![image](https://github.com/directus/directus/assets/25526512/1a4ff764-504f-4593-b75b-5bb01e1bc489)

In comparison to the full svg:
![complexity 41b7b4b011](https://github.com/directus/directus/assets/25526512/7ddf2dea-536e-4a42-b9f5-4f69e29cf867)

I've uploaded various svg's, some of which I found online. The issue doesn't seem to be the file itself.

### To Reproduce

1. Add a image field to a collection. Select "crop image as needed".
2. Add a entry to the collection and upload a SVG to the image field.

Example SVG's:
[svgs.zip](https://github.com/directus/directus/files/12910013/svgs.zip)

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment]
I dont quite understand your problem. Are you talking about the look of the image preview or the actual file itself? Can you elaborate what you mean exactly? Thanks.

**Comment by rijkvanzanten** [comment]
![CleanShot 2023-10-23 at 11 53 42@2x](https://github.com/directus/directus/assets/9141017/0a1231a7-b144-441f-8755-4f942d69a9ed)

Looks like the additional padding for SVGs is causing this issue with SVGs that are "bigger" (TBD on what that means). The padding there was intended to render SVG logos etc with a bit of padding. We should probably add a "letterbox" option to the interface to make that opt-in, rather than base it on the file type
