### ISSUE TITLE
UX improvement for UUID value in filters

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#20195]
### Describe the Improvement

When filtering by UUID at collection level, the results are the same and the input is very small until the input value is a valid UUID.
This happens because value is only evaluated when a valid input is set:
https://github.com/directus/directus/blob/bc2f3b85ed90f91731944a167c112b28407a7c32/app/src/interfaces/_system/system-filter/input-component.vue#L42-L81

Here's a demonstration:

https://github.com/directus/directus/assets/14039341/8b51af7b-fe91-42fd-8a03-20f6790caccc

So my suggestion is either:
1. show an error saying that input is not a valid UUID
2. do the query on API

In both scenarios the input should enlarge as we type up to a maximum width.
For scenario 2. we need to consider that the validation of this input was added otherwise it would return an issue from database (`123...` is not a valid uuid). That was the motivation for this validation (https://github.com/directus/directus/issues/8696).
So we can try to cast the fields on database. An example on Postgres, `select * from example where id::text ilike '%123%';`

**Comment by alexchopin** [comment]
@DanielBiegler can you add the description of the missing part we would like to implement in the future? Thanks

**Comment by DanielBiegler** [comment]
@alexchopin we added the visual feedback now in #21023 :smile: :+1: 

Generally what I'd like to see in the future is a rework of the `Filter` type and object so that we no longer rely on the position of keys. This is how we identify the filters right now:

```ts
// @see app/src/interfaces/_system/system-filter/utils.ts
export function getNodeName(node: Filter): string {
	if (!node) return '';
	return Object.keys(node)[0];
}
```

Since theres no proper structure to the content, that makes it quite awkward and very error prone to expand on filters currently. If you define a new key in the wrong order the entire filter logic breaks and stops working. They are used in many places so its not as easy to replace it quickly and we have to keep in mind compatability for when people update. We dont want to break every preset/bookmark in every instance :pray: 

Secondly it'd be good if we could identify filters uniquely via some autogenerated `id` so that `<draggable>` can render filters properly. Right now its `v-for` rendering of the filter just uses the index as `key` which leads to vue being unable to detect when it should actually rerender the components and mis-handles state. That means we gotta do awkward state handling inside the `input` element so we dont break the rendering. Changing the look of the filter rows currently is very painful and sometimes even impossible because of the broken rendering. I tried to introduce some new markup for an indicator but due to not rendering correctly the whole filter just breaks and refuses any new input.

Thirdly, after the rework of the `Filter` type we should be able to more easily fix the issue of losing state when changing filtering orders with invalid (i.e. not-applied) values, see the following video:

[Screencast from 10.01.2024 15:37:55.webm](https://github.com/directus/directus/assets/14810858/8b615c00-eef1-4075-85b5-cd7b55e52a75)

Fourthly, this would also enable easier and more robust sharing or exporting of filters from the app, there were some feature requests for that :-)
