### ISSUE TITLE
Get translations

### ISSUE THREAD

**Issue by cgarnier** [directus/directus#2027]
How i m supposed to get only the language i need for an entity?
Is there a way to filter them?

**Comment by rijkvanzanten** [comment]
Hey @cgarnier!

As of right now, there is no way to filter for a specific language. The API will always return all available translations. However, we are working on a new `lang` parameter which does just this! It will be launched in the next major version of the API (2.0) which is in active development as we speak!

**Comment by pedrohh** [comment]
Hello, is there any update regarding this? This was a feature I was looking so I can integrate directus as a content management service in a microservices architecture.

**Comment by pedrohh** [comment]
Ok @rijkvanzanten thanks!

**Comment by schindld** [comment]
Where's the documentation for the lang query parameter? Adding `?lang=fr` to the api calls doesn't change anything for me.

**Comment by azrikahar** [comment]
> Where's the documentation for the lang query parameter? Adding `?lang=fr` to the api calls doesn't change anything for me.

@schindld This thread is 4 years old now, so I believe it's for the previous version 8 (seems to be released here: https://github.com/directus/v8-archive/releases/tag/v2.0.0-rc.1) rather than the current v9. Note that v8 is end-of-life and hasn't been updated in years, so it is strongly advised against using it at this point.

Assuming you are on v9, there is a feature request for this in this discussion #6654. There's also a custom hooks extension by a community member over here which you can try out: https://github.com/directus/directus/discussions/6654#discussioncomment-1613498.

Hope that helps! If you have any further questions, feel free to ask it in [discussions](https://github.com/directus/directus/discussions) in the Q&A category, or alternatively you can also join our [community Discord server](https://directus.chat/). 👍 Locking this thread for now to avoid any further confusions with v9, hope that's understandable.
