### ISSUE TITLE
Sorting behaviour in tables

### ISSUE THREAD

**Issue by ivansf** [directus/directus#2033]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 7
  - MySQL version: RDS Aurora 
  - Web server: Apache
  - OS name and version: Ubuntu Artful 

## Expected Behavior
Be able to sort tables in the admin panel.
Be able to view dates in the table

## Actual Behavior
Sort doesn't seem to be working.
Dates only come up some times when doing command+R refresh. multiple times clicking the column header makes the dates to come up but not sorted.

## Steps to Reproduce
 1. Create a table with title and date_updated system field.
 2. Add some records.
 3. Visit the table in the admin panel, try to sort.

## Schema Dump, Logs, or Screenshots
Database
<img width="413" alt="screen shot 2018-01-25 at 1 46 28 pm" src="https://user-images.githubusercontent.com/50224/35414086-4e245328-01d6-11e8-8106-ff166d874bc1.png">

When initially loaded (command+R)
<img width="910" alt="screen shot 2018-01-25 at 1 46 15 pm" src="https://user-images.githubusercontent.com/50224/35414070-41a37bb0-01d6-11e8-9924-e8ad020e6ad7.png">

after cycling through clicking the date updated header
<img width="841" alt="screen shot 2018-01-25 at 1 46 20 pm" src="https://user-images.githubusercontent.com/50224/35414076-4631c380-01d6-11e8-91de-d173a6a120c5.png">

**Comment by rijkvanzanten** [comment]
Hey @ivansf!

Do you have some more info for us to replicate this issue? I'm particularly interested in the specific version of Directus you're using and how you've installed it (git vs build branch).

If possible, could you provide us with a database dump where this problem is happening? That'll help us out a lot in the debugging process.

Thanks in advance!

**Comment by ivansf** [comment]
I was using the released 6.4.4 then updated to 6.4.5, in both php 5 (locally) and php 7 (staging server). I did switch to git version at some point and the issue still existed. Also created site cache.

This happens with the Interface table that the CMS created, and no sorting is working (slugs, titles, dates). Will update to 6.4.7 and test again.

**Comment by jroxendal** [comment]
For what it's worth we're having the same problem with latest from master. Though we found that the correct sorting is applied, because after a page refresh everything looks good.

**Comment by treechime** [comment]
I'm also having this issue across versions 6.4.6 & 6.4.7 (build download from releases page).

Sorting doesn't seem to update the view, but correct sort is shown on refresh. Drag & drop sort also isn't working for M2M tables, but I don't think that's related.

[Dump20180227.zip](https://github.com/directus/directus/files/1761369/Dump20180227.zip)

**Comment by rijkvanzanten** [comment]
We're rebuilding the complete sorting / view logic of Directus in version 7.0, which is in active development and scheduled for a (beta) release end of Q2. Since that's taking up most of the time of our developers, non system-critical issues will be put on the backburner..  

As always, a PR is to solve this is in 6.x is very welcome!

**Comment by treechime** [comment]
I assume also tied this issue, is that if I try and sort by a M2M column (which doesn't work, but is applied to the database) and then refresh the page, I then get an error says `Server Error Unable to find the column [column_name]` which is correct because that column doesn't actually exist because it's an alias.

I assume this would be handled in the app sorting process that's not working.

**Comment by rijkvanzanten** [comment]
This has been fixed by #2109 thanks to @shevaroller and will be released to the `master` branch soon 👍

**Comment by treechime** [comment]
Hey - just updated to 6.4.9 and this patch kinda breaks functionality for nested tables.

Since I don't actually need my nested tables to be sorted by column as they have draggable sorting, I just added this bit of css to disable the functionality `.related-table th { pointer-events:none; }`

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/27)
