### ISSUE TITLE
"Gap" in Official video and documentation?

### ISSUE THREAD

**Issue by kkar** [directus/directus#2041]
Hello, and thanks for this awesome project. I am new to Directus, so excuse me if i am asking "obvious to resolve" things.

By watching the intro video [here](https://www.youtube.com/watch?v=rLodHE3e7Os) especially the part where the user table is made, i can't understand how that table would be possibly create a real user that would be listed in users menu. I mean, is it even possible to use directus' core user table to store users and assign them to groups, by using a form created with directus?

Thanks again!

**Comment by rijkvanzanten** [comment]
Hey @kkar!

This is admittedly a bit confusing in the video. The `users` group displayed in this video is in fact **different** from the main Directus Users (`directus_users`) table that stores the users that have access to Directus itself.

Creating your own `users` table can be useful if you want to implement an account system that's separate from the Directus auth system but we recommend to use the "native" Directus Users table, since that also gives you the power to manage permissions and use the auth tokens flow.

In conclusion:
> I mean, is it even possible to use directus' core user table to store users and assign them to groups

Yes!
> by using a form created with directus?  

No! The user edit view is _as is_ and can't be modified (as of right now).

_We are working on allowing the admin user to change the fields that are available in the user table from version 7.0 onwards :)_

Hopefully that answers your question. Feel free to [join us over on Slack](https://slack.getdirectus.com) if you have any other questions / recommendations / feedback!

**Comment by kkar** [comment]
@rijkvanzanten thanks! That feature would be super helpful!!!!!
