### ISSUE TITLE
Dropdown value shows instead of the text in table view

### ISSUE THREAD

**Issue by DouweAVROTROS** [directus/directus#20491]
### Describe the Bug

I have a dropdown field with a different text and value as choice.

When I'm on the table view (but also card, kanban etc), I see the raw value and not the text from my choice.
Everywhere else is the text mapping used.

Here are some screenshots to demonstrate:
<img width="827" alt="image" src="https://github.com/directus/directus/assets/99420504/d183ee53-f52a-4acf-9b5c-f137797c738f">
_Dropdown choices_

<img width="175" alt="image" src="https://github.com/directus/directus/assets/99420504/d7a6fe9c-df09-4a8e-9af7-b8487a718969">

_Field choice in my item_

<img width="549" alt="image" src="https://github.com/directus/directus/assets/99420504/fd0d67a1-04b6-495f-a522-fd1735ee41e0">

_Table view_

Notice that even the filter shows the text. But the table itself shows the raw value.

The solution will be a mapping/conversion to the values from the dropdown.

### To Reproduce

Open the table view and select a dropdown field. It shows the raw database value, instead of the mapped value.

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
> When I'm on the table view (but also card, kanban etc), I see the raw value and not the text from my choice.

This is expected behavior, only the `value` is actually saved to the database the `text` is just a visual label managed by the interface in the app only (it does not apply to the API). This may be confusing as the App hides this from you when filtering, just like the dropdown it shows you the text but actually filters against the `value`. If you want to apply labels to the table layout/overview pages you will have to configure the `display` to do so:
![image](https://github.com/directus/directus/assets/9389634/496d2624-f2fe-4948-9b1b-6e78cf0ba358)
![image](https://github.com/directus/directus/assets/9389634/ca464928-2b93-425d-82bd-846437b13238)

**Comment by DouweAVROTROS** [comment]
Oh, that will work. Thank you!
