### ISSUE TITLE
Registry Abstraction: Install extensions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#20539]
- Registry should be an environment variable that defaults to `npm`
- Should be a new endpoint that takes the package name, and optionally a registry (defaults to env var)
- Download tarball from registry, extract to configured extensions folder
- Reload extensions

Ref POC PR https://github.com/directus/directus/pull/19506 for inspiration

**Comment by paescuj** [comment]
I think we should also adding the following items to the list:
- Support authentication for private registries
  - While this might be as simple as advising admins to put the registry / token inside the `.npmrc` file [^1], it think it's worth mentioning because we need to test & document it
- Optionally, a allow/blocklist which enables admin to restrict installation to certain registries

[^1]: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file

**Comment by mahendraHegde** [comment]
@rijkvanzanten i'd like to work on it. after checking [this PR](https://github.com/directus/directus/pull/20207/files), I got 2 questions though

1. what if i'm running directus on k8s with multiple pods, when i install the plugin through this api this will be loaded into one of the pods, unless i restart the rest it wont be loaded correct? or am i missing something.
2. does directus cloud support plugins? from code i understand there is no multi tenancy support.

**Comment by rijkvanzanten** [comment]
@mahendraHegde hit me up on discord! There's a lot of context to these questions that's gonna be easier to discuss there :)

**Comment by mahendraHegde** [comment]
hey @rijkvanzanten  i have raised a PR, plz share your thoughts.

**Comment by rijkvanzanten** [comment]
Centralized registry download endpoint is done. Tracking installing/uninstall of extensions in Directus in https://github.com/directus/directus/issues/20560 🚀
