### ISSUE TITLE
Adding extra Integration and data stubs!

### ISSUE THREAD

**Issue by Sonichigo** [directus/directus#20715]
### Describe the Improvement

Adding integrations test with realistic data stubs, would help to get better test coverage.

**Comment by Sonichigo** [comment]
@jaads can i take this up issue ? 
I can try with bunch of frameworks and make a PR that provides high code coverage and are easy to maintain tests created.

**Comment by paescuj** [comment]
Hey, thanks for opening the issue!

We need more information before we can approve this request.
On the one hand, that is to ensure we end up with a solution which brings a real advantage over the current state and can be maintained over the long-term from our side. 
On the other hand, to prevent you from spending time on something we cannot incorporate.

> realistic data stubs
- How would that look like? Would that be static or dynamic data stubs? How would you generate the data and how/where would you integrate that in our application?

  _Note: We currently have [Blackbox Tests](https://github.com/directus/directus/tree/main/tests/blackbox) in place, which are tailored to the versatile form in which our application processes data (different data types, relationships, etc.)._

> high code coverage
- Would that be related to the data stubs you mentioned or is that a separate additional solution?
- How can you ensure it to be high(er)?
  
  _Note: While we're not actively tracking code coverage at the moment, we can manually verify it (e.g. when adding new test), using Vitest's coverage feature._

- Are you planning to introduce new framework(s)?
 
  _Note: We currently use Vitest for both, Unit Tests as well as Blackbox Tests. If it does not bring a clear advantage, we prefer not to introduce any further frameworks in order to keep it maintainable for us._

**Comment by Sonichigo** [comment]
> How would that look like? Would that be static or dynamic data stubs? How would you generate the data and how/where would you integrate that into our application?
> 
> Note: We currently have [Blackbox Tests](https://github.com/directus/directus/tree/main/tests/blackbox) in place, which are tailored to the versatile form in which our application processes data (different data types, relationships, etc.).

The data stubs are created by recording the network calls from the application. 

Let's say the user hits the API, and Directus then queries the database, keploy would record the entire flow and then save the input as a test case and the outgoing database or API calls as stubs (in YAML format). Keploy can then spin up a proxy over the recorded stubs or run the entire flow as tests without needing the database or other dependencies to be provisioned. 

This can reduce flakiness and make these tests fast to run. 

Example of a recorded Postgres stub - https://github.com/keploy/samples-go/blob/3f4fe462114c23340e11addc18b8c56c85dd1230/echo-sql/keploy/test-set-0/mocks.yaml#L94

Example of an HTTP stub recorded - https://github.com/nutanix-cloud-native/prism-go-client/blob/e26318d0c57ed027824234588e60df65c34cc4f0/karbon/mocks/TestKarbonCreateClusterRegistrationWithNoUUID.yaml#L2 

> Would that be related to the data stubs you mentioned or is that a separate additional solution?

If you use keploy to generate the test flows (which also included the stubs) and run them, the code paths covered by these flows can be added to the existing test coverage. 


> How can you ensure it to be high(er)?

Since the tests are generated by recording the network interactions when the core flows of Directus are performed, I assume that we can quickly hit high coverage. If it's going to be higher depends on if we cover flows that are already not covered.

> Are you planning to introduce new framework(s)?

Not really. Keploy is more like a test scenario recorder and replayer which generates test and stubs files and doesn't require any (generally) code changes. I have not used Vitest (I'll try to integrate with it) but have been using keploy with jest.

**Comment by Sonichigo** [comment]
Can i take it up @paescuj ?

**Comment by jaads** [comment]
Sounds like an interesting approach but it would require a proper evaluation first before we take action on this and it seems  we don't have the resources to do so at the moment.

CC @rijkvanzanten

**Comment by rijkvanzanten** [comment]
@jaads Maybe down the line for more specific uses like individual database drivers, but for now: e2e coverage is great to have, but the cost of implementation far outweighs the coverage benefit we get from it at present time. The first focus should be to get the unit test coverage up. I'll close this for now 👍🏻

**Comment by Sonichigo** [comment]
@rijkvanzanten sure that make sense! just nudging to this :- https://github.com/directus/directus/issues/20715#issuecomment-1855508038

Since i think there some information/context may have been missed!

**Comment by rijkvanzanten** [comment]
Nudge successful! Keploy looks very promising, but I still believe it's something we should look into once we've taken care of the low-hanging fruit first 🙂 That being said, not having to manually maintain a bunch of JS based IO tests in an e2e folder sounds very promising.
