### ISSUE TITLE
WYSIWYG FULL doesn't save any data on M2O relationship

### ISSUE THREAD

**Issue by iKonrad** [directus/directus#2078]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch: 6.4.5/6.4.7
  - PHP version: 7
  - MySQL version: latest
  - Web server: Apache
  - OS name and version: Ubuntu 16

## Expected Behavior
Wysiwyg Full field to save the content correctly

## Actual Behavior
Wysiwyg doesn't save any content for M2O relationship items

## Steps to Reproduce
1. Create a 'pages' table with a title 
2. Create a 'sections' table with WYSIWYG FULL field and an M2O relationship to pages
3. Add O2M relationship in 'page' table to 'sections' with 'Add new' and 'Choose existing' buttons enabled
4. Go to pages and click on the plus icon to create a new item
5. Click on add new in the sections field, add some text and click save
6. Watch the content of the section in the list disappearing

I'll post a video of this as soon as I can

**Comment by rijkvanzanten** [comment]
Hey @iKonrad! Thanks for the heads up. If possible, could you share an SQL dump of your schema so others can reproduce this immediately? The core team is working full time on the next major version (7.0), so if anyone feels inclined to take a swing at this, PRs are very welcome 😄

**Comment by rijkvanzanten** [comment]
This is a duplicate of #1567

**Comment by kieranwhite1994** [comment]
Hi,
Looking into this issue I believe I have located the issue and applied a fix to my local copy of Directus and seems to be working fine.

This issue is caused by the delay in the debounce function used for the `saveEditorContents` function inside `/wysiwyg_full/interface.js`. As the `saveEditorContents` function has a delay on it of 500, the function is executed after the contents of the page is changed e.g. the textarea of the WYSIWYG is no longer present on the page therefore the `content` is blank and the value is lost.
