### ISSUE TITLE
updateFile API does not upload file

### ISSUE THREAD

**Issue by moeomer** [directus/directus#2085]
## Version Info
Directus Build 6.4.3
File adapter: S3

## Expected Behavior
Using updateFile API, one can replace a file using base64 data that is then uploaded using the file adapter.

## Current Behavior
updateFile succeeds, albeit only updating file metadata (e.g. tags) and not uploading the file

## Steps to reproduce
1. Call updateFile with base64 data

**Comment by rijkvanzanten** [comment]
@WellingGuzman Could you confirm is this is still the case in the next major version of the API? Thanks 🙂

**Comment by AteoMarcel** [comment]
@ rijkvanzanten what major version do you mean exactly is there an update (coming) which is not yet on directus.io? In Api 1.1 (on directus.io) when I try to update a file with a put request I get no error, but instead of updating the file a new (defunct) file is uploaded. 

I try it with a Put request to ".../api/1.1/files/67" (67 is the file id of the file I want to update).
I tried it both with binary data and with base64 string (which is used in the creation).

I tried it both with  "id" added to the header and without it in both cases there was the same behaviour.

**Comment by rijkvanzanten** [comment]
@AteoMarcel We're working on the next major version of the application (7.0) and api (2.0). Seeing a lot of stuff got rebuild in that upcoming version, I would like to verify if we got it fixed there already or if this issue got migrated over 🙂

**Comment by AteoMarcel** [comment]
@rijkvanzanten ah ok thank you for the clarification! 
So before the version 2.0 goes live, is there any possibility to update a file (via a put (or post) request)? 
Or the possibility to delete a file via a http request?

Sorry if this question is not 100% related, to the issue, but it is something I kinda need to do now.

**Comment by benhaynes** [comment]
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/37)
