### ISSUE TITLE
User fields layout breaks when adding custom field

### ISSUE THREAD

**Issue by PhilBookst** [directus/directus#20894]
### Describe the Bug

When creating an extra field in directus_users collection, the layout of the fields breaks as shown in the images below

![image](https://github.com/directus/directus/assets/68562883/7c3888b2-a729-44c8-ad44-cf1aca3cc1a9)
![image](https://github.com/directus/directus/assets/68562883/e1565c1f-12cc-4803-a69b-d1aad360bf4e)

### To Reproduce

Create a custom field in the directus_users collection and visit a users profile

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment]
Just tried it and can reproduce it! See:

![image](https://github.com/directus/directus/assets/14810858/984c3d7c-397d-4a68-a45a-07c8aac076bd)

Thanks for reporting this!

**Comment by DanielBiegler** [comment]
## Update

This is because of the `meta.sort` property on the field object.

`first_name` has `meta.sort == 1` and if you add new fields they get initialized to also start from `1` which leads to this "collision" 

Contrary on the data model view we check for the `meta.system` field to separate the non-editable fields from the user supplied ones. Thats why they appear at the bottom there. Theres different methods on how we could fix this. Gonna take a look.
