### ISSUE TITLE
Splitting Config from Self-Hosted Section

### ISSUE THREAD

**Issue by phazonoverload** [directus/directus#21061]
### Describe the Improvement

The config (env vars) docs page and SSO page do not make it clear that configuration of environment variables is available on self-hosted AND enterprise cloud projects. This clarification has been requested by @wfriedman89 to make it clear to readers that it may apply to them.

**Comment by paescuj** [comment]
To that fact, I'd love if we can restructure it so that the "Config Options" and "Single Sign-On (SSO)" pages aren't bound to the "Self-Hosted" section anymore. (Also, technically "Single Sign-On (SSO)" is kinda a sub-page of "Config Options")

Not sure if there's enough space for another root section in the menu, but with that we would have a dedicated place where we could easily add other config examples similar to "SSO", e.g. for "Storage".

**Comment by phazonoverload** [comment]
I would be up for exploring this as an approach. We are gearing up for a large restructure of the docs, and I think having a separate configuration section would be a good idea

**Comment by phazonoverload** [comment]
Starting to flesh this out. I'm thinking:

## Self Hosted

- Quickstart
- Docker Guide
- CLI
- Upgrades & Migrations
- Deployment Guides (front page to various blog posts)

## Configuration

- Introduction (the preamble before the tables of variables)
- General, Server (also contains admin account, telemetery, limits & optimizations, PM2)
- Database
  - Examples as per #20610 
- File Storage & Assets
  - Examples
- Email (with some vendor examples)
- Authentication & SSO
  - Examples
- Extensions
- Realtime
- Flows
- Caching & Multi-Container (caching, redis, messenger, synchronization)
- Security - I'm thinking this is where #21006 could live? 
- CORS
- Rate Limiting

Are there any more groupings we should make? I don't want this to be a huge section, but don't want to obscure where content is.

**Comment by phazonoverload** [comment]
New docs handle this
