### ISSUE TITLE
[SERVICE_UNAVAILABLE] Service "files" is unavailable. Couldn't save file

### ISSUE THREAD

**Issue by JeremyMAQUAIRE** [directus/directus#21148]
![error](https://github.com/directus/directus/assets/134293073/ceb390d7-2788-489b-994e-a160d5e4ca5c)
![error](https://github.com/directus/directus/assets/134293073/894755c2-3d80-4819-b90c-9567055aba3f)
![logs](https://github.com/directus/directus/assets/134293073/a6c19de5-44d0-4a56-9bf8-3974a949e383)
### Describe the Bug

I have error 503 when I want to download a file on directus

### To Reproduce

just download a file the file part of directus

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
The file doesn't exist on the filesystem (anymore).
I assume this happens because the container has been restarted since the initial creation and the `/directus/uploads` directory inside the container isn't persisted.
See https://docs.directus.io/self-hosted/docker-guide.html#persistence for how you can do so.

I'm closing this issue for now, but we can reopen if it turns out to be a different problem.

**Comment by Roman991** [comment]
In my case the problem was that the owner of the folder `/local/directus/` was `root`
and it was inherited in docker's environment, but directus uses `node` as user, which has not root permissions
I had to change the owner of the host folder to a non root user and it fixed

`sudo chown -R user:user /host_directory_directus`

![image](https://github.com/directus/directus/assets/10634244/01943228-da60-4abc-8114-b0497939b315)

U can check if the owner of `uploads` folder (inside docker) is node:node

**Comment by wenig** [comment]
Thanks @Roman991, that works!

**Comment by fedeandri** [comment]
Same problem just happened to me, @mkdirnow solution fixed it, thanks!

**Comment by STY1997** [comment]
> ```
> docker exec -u root <directus-container-id> chown -R node:node /directus/database /directus/extensions /directus/uploads
> ```

Hero
