### ISSUE TITLE
Null Values for number types when sorting in the app

### ISSUE THREAD

**Issue by JugaadiTek** [directus/directus#21459]
#### When sorting Integer Input fields Null Values should be treated the same as 0 for any analytics,data crunching or accounting purposes.

Pushing them to the top, can be frustrating if you are sorting metrics.

Example, tracking post/page/video views, accross different platforms on a unified table, nulls are expected if the content didnt release to all platforms, and the viewcounts are relational data.

![image](https://github.com/directus/directus/assets/106853815/6404bb37-fd99-45c0-a63c-c4d6d433ec06)

#### Confirmed Null goes to top on non relational data as well
`BigInt`, `Int`, `Float`, `Decimal`

![sorttest](https://github.com/directus/directus/assets/106853815/468f280a-9eef-4025-8a19-f33f5bb19fb1)

**Why This Matters:** In accounting Null could be used for cancelled transactions, so setting Nullable to false might not be an option.
In Content Production Null could represent platforms where content didn't release.

**Displays Tested:** `No Selection`, `Raw Value`, `Formatted Value`, `Formatted Value Auto Format`, `Formatted Value Labels`, `File Size`, `Labels`, `Rating`, `Rating Simple`
![sortdisplay2](https://github.com/directus/directus/assets/106853815/54cb50b5-f7e1-46ba-b974-6169d303df9d)

**Directus:** `10.9.2`
**Database:** `Postgres`
**Host:** `Railway`

**Comment by br41nslug** [comment]
I believe there has been discussion around this before and the current behavior is the result of that. I recommend filtering out the `null` values before sorting then they wont be an issue either way.

I am closing this issue since this is not an improvement that can be directly implemented without discussing the alternatives/advantages/drawbacks. Instead please feel free to open a [feature request](https://github.com/directus/directus/discussions/categories/feature-requests) to see this discussed and potentially implemented
