### ISSUE TITLE
When there is paging on a M2A it will remove sorting.

### ISSUE THREAD

**Issue by VincentKempers** [directus/directus#21532]
### Describe the Bug

When you use the Builder (M2A). and you have more than (the specified items per page) it will add a new page of items. 
Unfortunately it loses sorting and set the content back at when it's added. 

When adding items and you can sort as much as you want. Upon saving and the pagination kicks in it will remove the sorting.

### To Reproduce

To reproduce this you add a builder (M2A) to a collection and go to the page and add as much items as possible and set a sorting.
When done check if your sorting still works. 
If you have less than let's say default 15 change it to 10 and you'll see your sorting is gone.

### Video

https://github.com/directus/directus/assets/14160793/9945e58a-0510-43ad-8721-b744392b22f1

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
After talking to @br41nslug, it seems like it was intentionally not supported, as there currently is no support for sorting across pages and potential edge cases arise once the sort field is touched by the user manually.

We could enable sorting within a page with the note and the docs that things might break if the sort field is touched manually. Sorting across pages would require (probably, a lot) more work and a proper feature discussion, to consider the UX and implications of dropping an item from page 1 to page 1000 and having to update sort field of the 1000s of items inbetween.

**Comment by paescuj** [comment]
Related thread: https://github.com/directus/directus/discussions/12818

**Comment by hanneskuettner** [comment]
Reading through the proposed solutions especially the comment from Rijk https://github.com/directus/directus/discussions/12818#discussioncomment-4769412 I think I will take this PR as an excuse to add a info notice for the user that sorting is disabled, because of the page size. Additionally I could add a selection to the pagination that allows for selecting (and maybe even entering) a page size on the fly on order to reenable sorting.

Open questions:
- Should there be an option to set it manually, if so, should there be a limit we are imposing so that non-technical user can't DOS themselves by setting 1,000,000 as their desired page size?

**Comment by br41nslug** [comment]
> Should there be an option to set it manually, if so, should there be a limit we are imposing so that non-technical user can't DOS themselves by setting 1,000,000 as their desired page size?

I think say this should not be a free to fill field, I'd expect a limited pagination dropdown same as for collection pagination. Perhaps even less options since that select goes up to 1000 but i dont think the relational interface was built with a thousand items in mind so maybe just to a max of 100.
