### ISSUE TITLE
Not working with authentik (after upgrade)

### ISSUE THREAD

**Issue by aoor9** [directus/directus#21531]
### Describe the Bug

Has anyone recently experienced an authentik login issue? I have this config...

```
AUTH_PROVIDERS: "authentik"
AUTH_AUTHENTIK_SCOPE: "openid email profile"
AUTH_AUTHENTIK_DRIVER: "openid"
AUTH_AUTHENTIK_CLIENT_ID: ${AUTH_ID}
AUTH_AUTHENTIK_CLIENT_SECRET: ${AUTH_SECRET}
AUTH_AUTHENTIK_IDENTIFIER_KEY: "email"
AUTH_AUTHENTIK_ISSUER_URL: "https://authentik.example.com/application/o/slug/.well-known/openid-configuration"
AUTH_AUTHENTIK_REQUIRE_VERIFIED_EMAIL: true
AUTH_AUTHENTIK_ALLOW_PUBLIC_REGISTRATION: true
```

and this worked with v2023.10 . But when I upgraded authentik to v2024.2, it returned `SERVICE_UNAVAILABLE`. I realized the `offline_access` was required, so I set it on [both parts](https://goauthentik.io/docs/providers/oauth2/#authorization_code) `AUTH_AUTHENTIK_SCOPE: "openid offline_access email profile"`, but now it returns `INVALID CREDENTIALS`.

### To Reproduce

- Upgrade authentik to **v2024.2**

### Directus Version

v10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by jamesatjaminit** [comment]
I ran into exactly the same issue. My issue was related to the `offline_access` parameter as you mentioned. 
Authentik requires `prompt=consent` in the requesting OpenID body when the `offline_access` scope is used, as per the [OpenID Connect spec](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess), otherwise the `consent_required: The Authorization Server requires End-User consent` error is returned.

I fixed it in my config my adding to my config:

```yaml
AUTH_AUTHENTIK_PARAMS: "{\"prompt\":\"consent\"}"
```

**Comment by aoor9** [comment]
@jamesatjaminit I actually solved my problem before your reply. Anyway I tested your suggestion on another instance with the same problem, and it didn't work at all.

Keeping the docker compose config I updated, all I had to do is set user's `auth_data` key to null.
