### ISSUE TITLE
Login not working on built-in PHP server

### ISSUE THREAD

**Issue by khromov** [directus/directus#2168]
## Version Info
  - Directus version and branch (Or commit hash): `develop`
  - PHP version: `PHP 7.1.14 (cli) (built: Feb  2 2018 08:41:46) ( NTS )`
  - MySQL version: MySQL 5.6
  - Web server: (Ex. Apache, nginx or IIS?) PHP built-in
  - OS name and version: OSX

## Expected Behavior

Logging in works after installation

## Actual Behavior

Login not working with `/api/1.1/auth/login - No such file or directory` due to missing mod_rewrite.

## Steps to Reproduce
 1. Start local server `php -S localhost:8080`
 2. Visit and install Directus - http://localhost:8080
 3. Attempt to login

## Schema Dump, Logs, or Screenshots

N/A

**Comment by rijkvanzanten** [comment]
Hey @khromov!

Directus requires the use of some sort of rewriting engine to operate properly. Seeing that the endpoints are generated based on the user schema, there is no way for the platform to include all possible endpoints in just PHP. You will have to run a webserver alongside PHP that rewrites all paths to `/api/api.php`.

You could try implementing some sort of router script yourself (http://php.net/manual/en/features.commandline.webserver.php) if you want to run Directus solely with PHPs built in server. Otherwise, you'll have to run it locally with something like WAMP/MAMP, or a local Apache / Nginx / Caddy installation.
