### ISSUE TITLE
Directus Cloud - Session expiring every 15 minutes

### ISSUE THREAD

**Issue by JackMullinkosson** [directus/directus#21693]
### Describe the Bug

Every 15 minutes I get logged out of Directus Cloud with the message: "Session expired". I am not self hosting or using any custom functionality. I just set up a Directus cloud account yesterday and have started creating my content model. I'd like to increase the session expiration time so I don't get logged out in the middle of my work and end up losing progress. Don't see any way to do that currently in settings. I went to the user configurations and saw I could generate a token, which I did, but that didn't affect anything. 

### To Reproduce

1. Set up a directus cloud account
2. Login as admin and wait 15 minutes

### Directus Version

v10.9.2

### Hosting Strategy

Directus Cloud

**Comment by rijkvanzanten** [comment]
Heya! It sounds like this issue might be specific to cloud rather than a bug in the core software, so I'll close this issue on our public software issue tracker. 

I highly recommend reaching out to support@directus.io for any and all questions, concerns, and issues you're having about/with Directus Cloud. Thanks!

**Comment by mschem-esa** [comment]
Same issue, sure other people are experiencing it to. 
Hopefully there's a better way, than scores of people messaging support about it separately?
