### ISSUE TITLE
CSV import always omits first column

### ISSUE THREAD

**Issue by pierremonico** [directus/directus#21727]
### Describe the Bug

When I create a new collection, and then import a CSV file, the first column of the CSV file is always ignored. 

I tried several things like:
- Renaming the column/field
- Changing the column/field data type
- Moving the column around (which is when I realized the first one always gets ignored)

### To Reproduce

Create a collection with fields: `always_ignored,data_type,uniclass_code,level_of_information`
Import [sample.csv](https://github.com/directus/directus/files/14514294/sample.csv)

This is the sample file:
<img width="609" alt="image" src="https://github.com/directus/directus/assets/10991626/6048cc0f-c525-4b4d-b222-ea3c980035d9">
After import, it results in:
<img width="850" alt="image" src="https://github.com/directus/directus/assets/10991626/0b678b90-bf8a-4e23-96f4-21edd98f9065">

If I swap the columns, i.e. put `data_type` first in the CSV, then that's the one ignored. I am probably missing something obvious (i.e. it's expecting an `ID` column), but I can't figure out what it is nor find anything useful in the docs.

Thanks. 

### Directus Version

v10.10.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Zewb** [comment]
I've seen this exact error. With some testing, it seems like you can get it to work with smaller batches of data if using quotes on the first column's data. Like "this","will","work" most of the time, but with larger blocks of data I was getting an error. :/ In the end the easiest way for me to import the data was to add a column I didn't need, make it the first column, then add the data, and then delete the temporary column. 

For added context, I have been using Excel to make the CSV files since the original data is in excel workbooks. But Excel does not support "" as a default option with their csv exports.
