### ISSUE TITLE
EXTENSIONS_AUTO_RELOAD not working on version 10.10.1

### ISSUE THREAD

**Issue by emahuni** [directus/directus#21745]
### Describe the Bug

Since I upgraded my self-hosted setup from v10.9.3 to v10.10.1, moved an extension from extensions/modules/attend to extensions/attend as indicated in the migration; EXTENSIONS_AUTO_RELOAD is no longer working. 

Everything is working well, as in, the extension itself is registering and appearing in extensions and working as intended. However, if I make any changes to the extension and build, nothing happens. I believe that the watcher is still trying to watch the old extension dir structure; I have not confirmed this.

### To Reproduce

1. Create a self-hosted setup.
2. Set `EXTENSIONS_AUTO_RELOAD=true` in `.env` file.
3. Create an extension in extensions dir. 
4. Build the extension
5. Run the project using `directus start`
6. The server should be watching for changes.
7. Test the extension to confirm that it is working as expected
8. Make changes to the extension and build

The server doesn't reload the buiilt extensions.

### Directus Version

v10.10.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by olivermack** [comment]
I'm having the same issue. It appeared in `10.10.0` and persists in `10.10.1`. I always have to restart the server manually in order to see the effects of my changes inside my extension(s).

**Comment by ymc-sise** [comment]
Same for me, but on 10.9.3, MacOs Sonoma. The watcher (running in the container) builds the new dist file in the docker container when changing the vue file on the host, but the hot reloading will not trigger, using new extension way. But somehow it worked for me before.

**Comment by fanadin** [comment]
until this bug is fixed you can just update your package.json for example change the version number and hit save, this will autoreload the extension

**Comment by olivermack** [comment]
I'm not sure if this makes sense but I'm still facing issues that could possibly related to this:

In my setup I have sort of the following monorepo project structure where the directus installation lives next to my custom extension(s):

```
* project-root/
** directus-app/
** directus-extension-1/
** directus-extension-2/
```

When starting directus via `directus start` inside `directus-app/` it obviously recognizes the extensions because it registers their entries into the `directus_extensions` table.

However, when I perform a change inside of one of my extensions I see that the watcher of `directus-extension build -w --no-minify` does a rebuild and the running directus-app also does some sort of re-init but my changes are not applied properly... I need to restart the directus-app manually to "apply" my changes.

I don't know what's wrong to be honest. I've also tried to use the `directus-extension link` cmd which had some sort of effect (as I think) but ultimately registered my extensions twice - once as `local` and once as `module`.

I'm pretty sure this setup worked properly before upgrading to `10.10.*`. 

@rijkvanzanten do you have any suggestion what I could try to figure out what's wrong?

Thanks!

**Comment by Zehir** [comment]
@olivermack I'm facing the same issue. I'm also in a monorepo where I have Directus in the `store` package and 2 extensions: `store-extension` and `oauth-pop-up`.

I'm not sure if it was working before, but I think it was. (around 80% sure).

Until we have a fix or a better workaround, this is what I did:
I use a `directus_dev.cjs` script to start the watchers for the extensions and to start Directus.

```js
#!/usr/bin/env node

const concurrently = require('concurrently')

concurrently([
  {
    command: 'pnpm start',
    name: 'directus',
    prefixColor: '#f39c12',
  },
  {
    command: 'pnpm --dir ../store-extension run dev',
    name: 'extensions',
    prefixColor: '#3498db',
  },
  {
    command: 'pnpm --dir ../oauth-pop-up run dev',
    name: 'oauth-pop-up',
    prefixColor: '#2ecc71',
  },
  {
    command: 'node scripts/propagate_watcher.cjs',
    name: 'watcher',
    prefixColor: '#34495e',
  },
])
```

The `dev` commands are the default one `directus-extension build -w --no-minify`.
The `pnpm start` start directus with a custom script to load multiple env file. More details [here](https://github.com/deconz-community/ddf-tools/blob/ef399b5a557ee0fdc241c79b493cc9a340c430fd/packages/store/package.json#L47-L48) and [here](https://github.com/deconz-community/ddf-tools/blob/ef399b5a557ee0fdc241c79b493cc9a340c430fd/packages/store/scripts/load_env.cjs).

And then the `propagate_watcher.cjs` script watches for changes in the dist of each extension and trigger the `package.json` file of the main package like suggested [above](https://github.com/directus/directus/issues/21745#issuecomment-1986321344).

```js
#!/usr/bin/env node

const { exec } = require('node:child_process')
const watch = require('node-watch')

const filePath = '../store/package.json'

const extensions = [
  'store-extension',
  'oauth-pop-up',
]

watch(extensions.map(extension => [
    `../${extension}/dist/`,
]).flat(), {
  recursive: true,
}, (evt, name) => {
  exec(`touch ${filePath}`, (error) => {
    if (error) {
      console.error(`Error executing command: ${error}`)
      return
    }

    extensions.filter(extension => name.includes(extension)).forEach((extension) => {
      console.log(`Extension ${extension} changed.`)
    })
  })
})
```

I know it's not a pretty solution but it works.
