### ISSUE TITLE
Conditions based on language code do not work in translations.

### ISSUE THREAD

**Issue by Valdri** [directus/directus#21819]
### Describe the Bug

Conditions based on language code do not work in translations.

### To Reproduce

1. Create a new data model
2. add translations field
3. inside translations create a new field 
4. set conditions to that field and set rule: Language Code Equals: de, select: Hidden on Detail

### Directus Version

v10.10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Very similar problem to #15604. 
Since we don't preemptively fill translations with any content (not even with language codes), there is no data for the validation to go off on. 

We might want to consider populating all languages with at least the language code and accounting for it in the saving of translation relational items that have not been touched by the user.
