### ISSUE TITLE
Extensions: Changing name of an `entry` on a `bundle`  it's not reflected

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21942]
### Describe the Bug

While working with a `bundle` extension, I have tried to change the name of an `endpoint`.
I have done this by change the name of the `entry` in the `package.json`.
As result I was expecting to access the custom endpoint with the new name, but it was only accessible using the old name.

### To Reproduce

- Create a folder
- Run `npx create-directus-extension@latest` and choose bundle
- Enter newly created folder
- Run `npm run add` and choose `endpoint` with name "lorem"
- Access `/lorem` and you should see "Hello, World!"
- Copy files to extensions folder
- Edit `package.json` and change name "lorem" to "ipsum"
- Restart Directus
- Access `/ipsum` and it will send 404. Access `/lorem` and you should see "Hello, World!"

### Directus Version

10.10.4 (main)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by Ventinc** [comment]
Hello, I had a similar problem an hour ago, I think it's because of all the things that has been changed in extension loader and the database for marketplace. I could create an endpoint extension in my bundle extension but it was never added to the list of enabled extension. The only solution I had was to delete everything in the directus_extensions table and then stop and restart directus to reload all extensions

**Comment by joselcvarela** [comment]
Yes, it looks like once the extensions/entries are added to database, they are not being updated again 🤔
