### ISSUE TITLE
[SDK] Set correct type for filesize

### ISSUE THREAD

**Issue by davidsandoz** [directus/directus#21957]
### Describe the Improvement

In the SDK, the `DirectusFile` type has its `filesize` attribute set to be `string | undefined`.
https://github.com/directus/directus/blob/main/sdk/src/schema/file.ts#L22

Based on what the API returns, and on the `filesize` type of the `File` type, it should rather be `number`.
https://github.com/directus/directus/blob/main/packages/types/src/files.ts#L16

**Comment by br41nslug** [comment]
The `filesize` is typed as string because its actual database type is `big integer` which exceeds the size of numbers `Number` can store.

https://github.com/directus/directus/blob/main/api/src/database/migrations/20210626A-change-filesize-bigint.ts#L12
![image](https://github.com/directus/directus/assets/9389634/d7f52e8b-d7cc-4e46-b968-4ac67d83120a)

The type you linked there seems to be outdated.

**Comment by davidsandoz** [comment]
@br41nslug Thanks for your explanations!

As I was still getting an actual `number` in the API response for the `filesize`, I thought it was because I was not using the latest version of Directus. I just updated to v10.10.4, and I was surprised to see that I'm still getting a `number`. I am using it for a public website, so you can even see for yourself: https://cms.tchoukball.ch/files/b17a7965-a567-45da-91fc-2aa2162264aa/

Do you have any idea how this could be?

The DB is on MariaDB v10.6
