### ISSUE TITLE
Return whole object before deleting it in flows

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#21960]
### Describe the Improvement

When using action "On delete" in flows return whole object before deleting it, it opens many other possibilities, in context to reacting to object deletion.

**Comment by br41nslug** [comment]
This will come at a significant performance hit especially when doing bulk deletes. Since the platform does not track whether anything is actually listening for the events we would have to always do an extra database call fetching this data even if there are no flows/hooks listening to it.

For this reason you should read the wanted data of the to be deleted item in the specific flow/hook that needs it.

Since this would be more than a tiny tweak to implement please make a [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) for this 😄
