### ISSUE TITLE
Allow subscriptions to work with custom events

### ISSUE THREAD

**Issue by emahuni** [directus/directus#21998]
### Describe the Improvement

I was trying to subscribe to a custom event that was going to be emitted by an extension eg:

```js
emitter.emitAction('custom', { payload: 'hello world' });
```

then in a the app, a module would sbuscribe to it as

```js
const { subscription } = await client.subscribe({
    event: 'custom',
    query: { /* ...any params or query for the custom sub */ },
  });
```

Then each time the extension emits the event, that works the same way subscriptions work. The syntax maybe different according how you may want it to work.

**Comment by br41nslug** [comment]
The extensions `emitter` cannot emit events to be used by flows or websockets as it is isolated to extensions only.

In order to emit custom events you'll have to use the `WebSocketService` in an extension to send or broadcast a message and listen for those on the client using `onMessage` (subscribe only works for the known events it is registered to https://docs.directus.io/extensions/hooks.html#available-events)

**Comment by br41nslug** [comment]
In that case please go through the proper [feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) process for new features as this is not a "tiny tweak" that can be implemented without extra discussion/considerations.
