### ISSUE TITLE
Directus_users create permission does not apply correctly. Create button remains active on custom permissions

### ISSUE THREAD

**Issue by scharez** [directus/directus#21997]
### Describe the Bug

In the directus_users permissions, I configured field validation to allow only a specific user to create a specific user with role. However, the create button on the user page remains visible. When I change the permissions to **no access**, the button becomes disabled. Despite trying conditions that are 100% true and 100% false, the button remains active when I apply custom permissions.

### To Reproduce

Create a role with a user assigned, modify the directus_users permission to permit creation, but with a specific condition.

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
This is expected behavior: The validation rules needs to run against a "to-be-created" item, in order to validate it. We cannot run the check before an item is about to be created, since there's nothing to check against.
The validation rules will become visible once you try to save the new item, and will prevent creation if the rules are not met.
