### ISSUE TITLE
What happened to the webapp-example repo?

### ISSUE THREAD

**Issue by katokalen** [directus/directus#2209]
This link worked a couple weeks ago, has this repo been renamed or moved?

https://github.com/directus/webapp-example

I'm now seeing a github 404 error when I try to access.

Looking to reference this example for a client project so would appreciate the info on what happened to it.

**Comment by benhaynes** [comment]
Hey @katokalen – since v7 was released a few days ago and is a significant departure from v6, we've decided to clean up our GitHub organization a bit. Over the next few weeks we'll be removing legacy repositories so that our users aren't confused between the two versions.

I'll add the final zip of that repo here in case anyone needs access to it:

## WebApp Example Site (for Directus v6.x)
[webapp-example-master.zip](https://github.com/directus/directus/files/2480641/webapp-example-master.zip)

**Comment by katokalen** [comment]
Great, thank you!
