### ISSUE TITLE
Impossible to retrieve the v6 documentation for hooks and v7 docker image

### ISSUE THREAD

**Issue by dario30186** [directus/directus#2212]
Hello,
I'm using v6 version for directus with a docker compose. I wanted to update to v7 but the image does not exist. So I am obliged to use v6 if I want to stay with docker.
I'm trying to get hooks work but I cannot find hook which are in the documentation. 
For exemple, in your official doc here: [Documentation](https://docs.directus.io/extensions/hooks.html#action-hooks-list) there is field.update hook. But it doesn't work for v6 apparently.
Why do you not provide documentation based on version ? If you do I am sorry but I couldn't find it.

I need a hook to be called for each update, insert, delete done on some tables. Any suggestions ?

Thank you in advance

**Comment by benhaynes** [comment]
Hi @dario30186 – let me try to answer your questions:

**Docker in v7** – Instead of a dedicated repo, Docker is now [included in the main repos](https://github.com/directus/directus/blob/build-v7/docker-compose.yml) for version 7. 

**Docs** – Since we're a small team and have a LOT of things going on with this release, some things are a bit messy at the moment. We do have [v6 docs](https://github.com/directus/docs) and [v7 docs](https://github.com/directus/docs-v7), but they are not clearly delineated. Once we have the initial issues of v7 resolved we will be "sunsetting" our core support/repos for v6 and moving full-steam ahead for v7. Once that happens all docs will clearly point to v7 and we'll add notes to new features (eg `Works in v7.0.12+`). Please bear with us while we get things organized.

**Hoooks** – You can find the [v6 Docs on Hooks here](https://github.com/directus/docs/blob/f4a0a7294fd3c21d98cda3ee3266e7d6a9770a34/developer-guide/hooks.md) including all of the hooks you're looking for.

**Comment by dario30186** [comment]
Thank you very much for your answer!
Just a question: in your docker-compose there are only 2 services, php-apache and mysql. How can I deploy the directus code ?

**Comment by benhaynes** [comment]
That would be a questions for @rijkvanzanten  😬

**Comment by dario30186** [comment]
@benhaynes one more question for you :D
in the documentation v6 for hooks there is action table.update.
If I write this in configuration.php I have no errors:
`        'table.update' => function ($table, $data) {
            $client = new \GuzzleHttp\Client([
              'base_uri' => 'http://example.com'
            ]);
                               $response = $client->request('POST', 'https://gitlab.com/api/v4/projects/XXX/trigger/pipeline', [
                        'form_params' => [
                            'token' => 'XXXXX',
                            'variables[TRIGGERED_BY]' => 'DIRECTUSDEV',
                            'ref' => 'dev'
                        ]
                    ]);

        }`

BUT if I write this I get some errors in directus website (Server error, but any log in log file)
`                           'table.update' => function ($table, $data) {
            $client = new \GuzzleHttp\Client([
              'base_uri' => 'http://example.com'
            ]);
            switch ($table) {
                case "pages":
                case "hp_sections":
                case "carousel":
                case "pagesHpSections":
                case "pagesImages":
                    echo "going to build code in gitlab";
                    $response = $client->request('POST', 'https://gitlab.com/api/v4/projects/XX/trigger/pipeline', [
                        'form_params' => [
                            'token' => 'XXXXX',
                            'variables[TRIGGERED_BY]' => 'DIRECTUSDEV',
                            'ref' => 'dev'
                        ]
                    ]);
                    break;
                default:
                    echo "not going to build code in gitlab";
            }

        }`

any suggesitons?

**Comment by benhaynes** [comment]
Hey @dario30186 – you'd need to open this in a new ticket so we can assign it to a developer. This would be an API question:

https://github.com/directus/api/issues/new?template=Bug_report.md
