### ISSUE TITLE
IP Whitelist Restriction not working

### ISSUE THREAD

**Issue by shoaibjdev** [directus/directus#2216]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus version and branch (Or commit hash): git clone -b build-v7 https://github.com/directus/directus.git
  - PHP version: 7.2.11
  - MySQL version: 5.5.60 MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) Apache/2.4.6
  - OS name and version: CentOS 7

## Expected Behavior
When adding an IP to the list of **IP Whitelist** under a new Role, any user in that role should be able to login only from that specific host IP which is in Whitelist. From any other host IP it should deny access.

## Actual Behavior
User is able to login from any host in the network, seems like whitelist is not working at all.

## Steps to Reproduce
 1. git clone -b build-v7 https://github.com/directus/directus.git
 2. configure Apache 
 3. Launch the app & click Install providing DB details next

**Comment by benhaynes** [comment]
@rijkvanzanten – does the App honor the IP whitelist or does it send the server's IP to the API? If the latter, how can we reliably respect this restriction in the App?

@WellingGuzman – can you confirm that the IP Whitelist is working as expected for the API directly?

**Comment by rijkvanzanten** [comment]
@benhaynes The application can't do anything here. The app can't read the the IP address of the user.

**Comment by benhaynes** [comment]
So I guess this IP whitelist will have to be noted (in the Docs) as an API feature only. Some other alternatives:

1. Add a server-side file to the App that can access this info to enforce IP whitelist. This is a heavy-handed solution to a smaller problem, but could be a good "option" to have.
2. Instead of adding the actual code, we could describe what the code needs to accomplish in the Docs. Then devs can add support for this feature by adding a file to the App themselves. Then we could manually add this to `directus.app` too.
3. Make this work for the combined build only... or if App/API are on the same server. This seems like a good progressive enhancement for those that use a single server.

Thoughts? Any other options?

**Comment by shoaibjdev** [comment]
@benhaynes @rijkvanzanten - I don't agree we can't get IP address of the user. Check the Activity Log, there we are getting exact ip addresses of the user's machine. Below screenshots for Activity Log from my network for two different user's login from two different machines:
[Imgur](https://i.imgur.com/VrxLySQ.png)
[Imgur](https://i.imgur.com/cIQ0QN8.png)

Also note I'm on **v7.0.2** with App and API hosted on different servers.

Now coming to actual issue, it's the code for whitelisting which is not working at all. Even if we go with the theory that server's IP address is being returned when am trying to login, it should not allow me to login as in the whitelist I have added a specific IP address from which i'm not loging, so it should deny me not allow.

**Example:**
App is deployed on a machine in my network with IP **192.168.99.1**

In whitelist section for the Role I have entered IP **192.168.99.2** - This means I should only be able to login from machine with IP **192.168.99.2** in the network

Now, I try login from a machine in my network with IP **192.168.99.3** - I'm able to login succesfully

Which proves that the code for whitelist is not working at all, assuming it's getting server's IP address instead of actual user's IP. So when I try to login from machine 192.168.99.3, App code is getting server IP address which is 192.168.99.1, which should not allow me to login as I have entered in the whitelist only IP 192.168.99.2

Kindly review the code for Whitelist as in my opinion there is no challenge with getting user's IP here.

**Comment by rijkvanzanten** [comment]
@shoaibjdev the activity log is generated by the API and has nothing to do with the app specifically, which is why it's able to show the IP address.

I'm still pretty sure you can't read someone's IP address in the browsers client side JavaScript, please let me know if you have resources that prove other wise. 

@benhaynes the API can block incoming requests based on IP, which also means it can block the application from accessing the API (which is the feature we're looking for). What I'm referring to is the fact that we can't block things in the app itself based on IP, as we don't have access to it before someone logged in (at which point the api returns it).

**Comment by benhaynes** [comment]
This has been moved to: https://github.com/directus/app/issues/1042

We'll be reserving this issues area for build bugs only.
