### ISSUE TITLE
Create Data Operation Allows Improper Creation Structure for M2O

### ISSUE THREAD

**Issue by JackMullinkosson** [directus/directus#22212]
### Describe the Bug

When creating an item with a M2O relation in flows, the proper way to set the relation is with the one item's ID. However, in directus flows, setting the entire object as the relation will still work. The problem with that is, once there are more than 100 relations present, using this update structure will seemingly randomly cause other relations to become unrelated. This ends up being a confusing bug to troubleshoot.

To resolve, directus flows should throw an error when improper update structure is used.

I first thought that this bug was caused by a query limit, which is why I made this [post](https://github.com/directus/directus/discussions/22179), but after a discord discussion I realized it was a flow which was importing new data which was causing the issue, and when changing the update structure as described above, the bug went away.

### To Reproduce

Create a many to one relation, such as "reservations" related to a "club". In Directus flows use a get operation, called "get_club" to get the club, and then create a new reservation setting the club like this: {"club": "get_club"}. Although the correct way to create this would be: {"club": "get_club.id"}, the first way still works and will only cause problems for the user later on down the line. 

### Directus Version

10.10.5

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment]
I dont think this is "proper" vs "improper". I expect you are using the "basic" relational format which has drawbacks like you're describing. I would recommend using the "detailed" relational format same as the app.

https://docs.directus.io/reference/introduction.html#one-to-many-many-to-many

Happy to re-open if thats not the cause.

**Comment by JackMullinkosson** [comment]
@br41nslug I'm not using the API I'm using directus flows

**Comment by br41nslug** [comment]
Both Flows and the API use the same services which use the same query object and logic.

**Comment by JackMullinkosson** [comment]
@br41nslug so how would you use the 'detailed' query logic in the case I'm describing inside directus flow?

**Comment by br41nslug** [comment]
For that you will have to update the issue description first. You say m2o and more than a 100 relations which is not possible since m2o is a relation to a single item, did you mean an o2m?
If you did explicitly mean m2o then the amount of relations is irrelevant as thats always 1 and did you mean to use template string here? because `{"club": "get_club.id"}` and `{"club": "get_club"}` both just store a plain string.

**Comment by JackMullinkosson** [comment]
It is M2O - the field "club" on the reservation is a M2O - many reservations related to a single club. There are more than 100 reservations related to that single club. Yes that was a syntax error above, not supposed to be a plain string. I have corrected it.

**Comment by br41nslug** [comment]
Alright then the o2m/m2m relational structure doesnt apply ofc (different relations) and that makes more sense. 

> To resolve, directus flows should throw an error when improper update structure is used.

This is still however not something Directus can validate for you since it may be intentional to send an object (if you're creating a new related item for example).

Obvious programmatic errors will still error the flow of course (like accessing non-existent properties and fields) but Directus cannot tell your intentions with the when it is technically correct but may not be logically correct for what you want to achieve.

**Comment by JackMullinkosson** [comment]
If the only case where you'd want to send an object is when creating a new item, then directus could check if the object being passed already exists, and throw an error in that case.

I'm not sure what you mean by programmatic errors would error the flow - it still works in relating the object even though it's improper structure. It doesn't create a new object.

**Comment by br41nslug** [comment]
> If the only case where you'd want to send an object is when creating a new item

Not the only case it was just an example you can also do updates that way.

> I'm not sure what you mean by programmatic errors would error the flow

Thats why i gave examples (like accessing non-existent properties and fields)

> it still works in relating the object even though it's improper structure

Sounds like its doing an update as expected nothing improper about that.

**Comment by JackMullinkosson** [comment]
The bug I discovered is that if you relate an item using the whole object vs. just the ID, in cases where there are more than 100 relations, it causes other relations to become unrelated. This is true whether you are doing an update or just relating an existing item as is. So there is no use case where users should be allowed to relate an existing item using an object. You should only be able to do that when creating a new item that you also want to be related.

**Comment by br41nslug** [comment]
That is likely happening because if you do that using an object you are updating the related item and if that related item has the reverse O2M relation included in it with only 100 items in it... Then you are effectively overwriting the values in your O2M relation with an array of 100 items using the previously shared "basic" mode which assumes that the provided items are *all* the items you want in that relation nullifying the others.

So we have come full circle, it was the issue i originally mentioned updating the o2m relation in "basic"/"detail", but less intentional or direct than i expected, it has some extra steps but you are updating the o2m field in "basic" format via a relation instead of directly.

Making sure you're not sending an object is one way to prevent this or to make sure the o2m field is not present in the object would do the trick aswell.

**Comment by JackMullinkosson** [comment]
I see.. so the reverse O2M relation would only include 100 items because of the default query limit. Now everything makes sense. I agree that it's not a logical error.

**Comment by br41nslug** [comment]
Exactly, that 100 limit is enforced on the read which is then passed to the update, and since a read without relational fields is a list of IDs that would behave like the "basic" relational logic if used in an update/create 1 on 1.
