### ISSUE TITLE
The file-image interface doesn't allow to disable the option to choose from library

### ISSUE THREAD

**Issue by luistar15** [directus/directus#22215]
### Describe the Bug

[Similar to this petition](https://github.com/directus/directus/discussions/8999), but in my case I need to disable the option to choose from the library.

![image](https://github.com/directus/directus/assets/1296095/777b457d-2717-49ba-b272-ca3d14193ebc)

There is an option `"enableSelect": false` for other interfaces, so It could be similar.

### To Reproduce

Try to disable the option to choose from the library in a file-image interface.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
You cannot disable "select from library" because that would be disabling the selecting of images completely, and to achieve that you can also set the field to read-only or hidden in the app.

the other options are "selecting from the library" with extra steps:
- upload to the file library and select the uploaded file.
- import from url to the file library and select the uploaded file.
