### ISSUE TITLE
504 Gateway Time-out after adding fields to a detail group

### ISSUE THREAD

**Issue by Karthik-Pydishetty** [directus/directus#22312]
### Describe the Bug

"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n"

Whenever i am adding fileds to a detail group  after I add tehm this error would pop up and then after I press dissmiss all the fields I have added are than removed

### To Reproduce

try adding fields to a detail group

### Directus Version

v10.x.x

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
In the current Directus v10.10.7 I'm unable to reproduce this problem. Can you please share more details on your setup, is this a local installation (I would assume not, since the error message smells like nginx), what fields are you adding to the detail group specifically, can you see which request errors out (in the Browser Console), etc. Anything really, that helps us reproduce the error, because it does not seem like this occurs under normal circumstances.

**Comment by br41nslug** [comment]
As hannes mentioned "gateway timeout" is not an error thrown by Directus but rather some other piece of software in your stack. Most likely nginx or a similar proxy server.
