### ISSUE TITLE
Custom Condition Check if exists and hide field on detail hides the field as soon as I start typing on creation

### ISSUE THREAD

**Issue by bonface221** [directus/directus#22395]
### Describe the Bug

Here is the issue I have a slug field which I only want to be visible on creation.
So this is what I have done,  I have created a custom condition on the field itself and I'm checking if the field is null then hide the field on detail. 
![image](https://github.com/directus/directus/assets/98006412/3ebeabca-0139-4761-abbd-a74b82263a26)

So here is the issue When I'm creating a new record the slug field is shown as it should but as soon as I start typing the custom condition is validating and then the field is disappearing. 

Now is this the best behaviour or I'm missing something

### To Reproduce

Create any collection with a slug field and then add a custom condition like this one 
![image](https://github.com/directus/directus/assets/98006412/02234806-d9dd-48e5-8e2d-a8422d4a646f)
and then create a new record and start typing on the slug field and see it disappear 

### Directus Version

v10.10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment]
So what exactly is the issue here? If you have a condition saying "hide the field if not `null`" and then you start typing in it... well then it is no longer `null` and will get hidden.

From the description this condition is doing exactly what you've configured.

**Comment by hanneskuettner** [comment]
This behavior is expected, since the conditions are dynamic and evaluated on the current item values. Otherwise dynamically modifying interfaces based on the current edits would not be possible.

Since you require the slug to be set on creation you can probably get away by using an `AND` group in your condition and check if the primary key is not `null` in addition to the slug value, since that is an indicator that it is a new item.
