### ISSUE TITLE
GraphQL Schema is missing! 

### ISSUE THREAD

**Issue by paula-mamdouh** [directus/directus#22442]
### Describe the Bug

When I try to access /graphql for schema introspection, I receive this response:

```
curl 'https://estemarat.elmenya.com/graphql' -H 'Content-Type: application/json' -H 'Accept: application/json' --compressed  --data-binary '{"query":"{\n\t__schema{\n queryType {\n fields{\n name\n }\n }\n }\n}"}'

{"data":{"__schema":{"queryType":{"fields":[{"name":"_empty"}]}}}}
``` 

The same behavior happens when I try to send queries using Postman (it retrieves an empty schema), or when I try to use playgrounds.

Strangely enough, when I call `https://estemarat.elmenya.com/fields`, it returns the REST schema successfully. I'm also able to use the REST API, but I'm not able to perform any queries using GraphQL.

I've tested on versions 10.10.5 and 10.11.0.

I have these environment variables in my project:

```
GRAPHQL="true"
GRAPHQL_PLAYGROUND="true"
GRAPHQL_INTROSPECTION="true"
WEBSOCKETS_GRAPHQL_AUTH="public"
```

### To Reproduce

- Self-deploy a new Directus instance
- Add new data models
- Try to use /graphql

### Directus Version

10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Heya, it looks like you're missing the authentication token in your curl `/graphql` request. With proper authentication (and permissions) the introspection should return the expected results. If you want to have it run without authentication you need to give your public role read access to `directus_fields` and the collections your interested in.

That your `/fields` REST query returns the expected fields might be, since I presume you're navigating to it in your browser? If so, your Directus app session token is automatically transmitted, taking care of the authentication for you. You can give it a try and request it with curl and you should see a 403 - Forbidden.
