### ISSUE TITLE
AUTH_LDAP_DEFAULT_ROLE_ID overwrites assigned role on every login

### ISSUE THREAD

**Issue by JSDA123** [directus/directus#22546]
### Describe the Bug

When using LDAP authentication, the assigned user role is always overwritten upon login with the role ID set with AUTH_LDAP_DEFAULT_ROLE_ID. As a result, the LDAP users's role always resets to the AUTH_LDAP_DEFAULT_ROLE_ID value, overwriting any changes. This occurs even when AUTH_LDAP_DEFAULT_ROLE_ID is null,  leaving the LDAP user with no role at all.

Expected behaviour:  AUTH_LDAP_DEFAULT_ROLE_ID should set the initial role on creation of a new user, and not overwrite the role on subsequent logins.

### To Reproduce

Configure LDAP and configure AUTH_LDAP_DEFAULT_ROLE_ID to equal the Administrators role. Login as the LDAP user and note the account is created with the Administrator role. Log out and log back in as default Directus admin, change or remove the group membership of the LDAP user.  Log out and log back in as LDAP user, and note the role has reverted to the value set in AUTH_LDAP_DEFAULT_ROLE_ID.

### Directus Version

10.11.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by aidenfoxx** [comment]
As specified in the docs, this should only be true if a `GROUP_DN` config is specified (in point [3]) https://docs.directus.io/self-hosted/config-options.html#ldap-ldap.

If you don't wish to sync roles on login, simply remove that config option and things should work as expected. I believe the behavior was done this way so that if a users role is removed in active directory, when they re-authenticate they will be forced back into a default role.

**Comment by JSDA123** [comment]
I can confirm, thank you.  That's sensible behaviour if using GROUP_DN, and could be useful in my case as well.

I'm closing this 'bug' report. Thank you
