### ISSUE TITLE
How can I  change timezone to asia/beijing

### ISSUE THREAD

**Issue by kroawen** [directus/directus#2270]
I get items/books  
{
"created_on": "2018-12-24 04:32:27",
}
created time is not a current time

**Comment by kroawen** [comment]
thanks @shealavington.
I Changed timezone in my profile page and api.config  to Asia/shanghai or Asia/beijing . Only /admin page it worked, 
![22222](https://user-images.githubusercontent.com/6927999/50461406-22dcb480-09b9-11e9-9d9e-be9af234a35d.jpg).  
But api result did not work. api result print New York time not Asia/beijing  time
![1111](https://user-images.githubusercontent.com/6927999/50461474-97afee80-09b9-11e9-84dc-d57c7866a741.jpg)

**Comment by WellingGuzman** [comment]
All datetime fields are saved as is, unless it's a system collection or ISO format.

@kroawen What's the `type` of the `publisher_date` field?

**Comment by kroawen** [comment]
@WellingGuzman  field publisher_date I chose type Date Time from options

**Comment by WellingGuzman** [comment]
@kroawen I think the interface localized options is for how the datetime will be displayed in the app based on the user locale, not on how the api will return the datetime.

You will always get the datetime you save without timezone. If you use ISO format, the date will translate to UTC and save it, but will return the datetime back as the format shown in your image above.

localization and timezone are different thing.

You will always get the time in UTC. can you share the schema you are using? because if `publisher_date` is a core interface (`datetime_created`) it should've return the datetime in ISO format.

**Comment by kroawen** [comment]
@WellingGuzman , I run SELECT * from information_schema.columns WHERE column_name = 'publisher_date' :
![33333](https://user-images.githubusercontent.com/6927999/50469569-fb511080-09e7-11e9-9a20-d8105bfb59b3.jpg)
![555555](https://user-images.githubusercontent.com/6927999/50469570-fd1ad400-09e7-11e9-952c-62b9d621f4bf.jpg)

**Comment by benhaynes** [comment]
Hey @kroawen , Welling is looking for the field info found within `directus_fields` for `publisher_date`
