### ISSUE TITLE
Live Demo not working

### ISSUE THREAD

**Issue by TobiasDax** [directus/directus#2280]
# Bug Report

## Steps to Reproduce

1. Go to 'https://directus.app/#/login'
2. Enter Credentials 'admin@example.com + password'
3. Click Login

## Expected Behavior
Login should work

## Actual Behavior
"Unknown Error, Try again later"

## Technical Details

- Device: [MacBook Pro 2017]
- OS: [MacOS 10.14.2]
- Chrome

**Comment by rijkvanzanten** [comment]
Thanks for the heads up! It's working again now.

**Comment by fibigerg** [comment]
Not working for me now. Assuming password is 'password', result is 'Wrong username and/or password'. Thanks

**Comment by shealavington** [comment]
Yep, I was trying to login too, someone changed the password, however the demo gets reset every hour, so it's up and running again now I believe.

**Comment by rijkvanzanten** [comment]
@shealavington should we reset the demo more often? 🤔

Maybe hide the password field completely?

**Comment by shealavington** [comment]
I mean, theres potentially a few solutions:
- Lock down the fields. This would instead give an error like "This is a demo, you can't change that information here"
- Have a 'before hook' that intercepts a password or email change, and just sets it back to default, completely ignoring user entry for those fields.
- Remove password field for demo
- Reset more often
- Add more demo accounts, admin1, admin2
- Add a flag in the API config for putting the API into demo mode this could disable all input fields?

The hook one might be nice, this way the user sees it all working but due to being a demo the change is never actually made, though as a demo it might look broken.

**Comment by marufmax** [comment]
Live demo is not working again. This is what  I am getting on Console.

![image](https://user-images.githubusercontent.com/7222229/69616999-bc956180-1061-11ea-866b-0cf1ac5fab7c.png)

**Comment by benhaynes** [comment]
We're working on it now... it's been down for a week while we reconfigure the servers to work with the new v8 structure. Should be up today. @marufmax
