### ISSUE TITLE
How to upgrade Directus from previous versions ?

### ISSUE THREAD

**Issue by jameswill** [directus/directus#2296]
Hi,

I wanted to upgrade my directus to latest version i.e 7.0.16 from previous version.

Is there any upgrade guide I can refer ?

**Comment by shealavington** [comment]
Hopefully this helps https://docs.directus.io/guides/upgrading.html

**Comment by jameswill** [comment]
Hi,

Thank you for the guide.

I have installed Directus 7.0.15 on share hosting environment and git upgrade is not possible there.

I have tried with Admin Settings -> Update Database, which only updates database and not files. 

Also in Admin Setting -> Coming soon section it displays version as 7.0.15 only. How will user come to know that the version is updated or not ?

![directus](https://user-images.githubusercontent.com/6368036/52336058-ea091400-2a29-11e9-80fc-5c8907275343.png)

**Comment by benhaynes** [comment]
Hey @jameswill — I've added steps for manually upgrading here:

https://docs.directus.io/guides/upgrading.html#manually-upgrading-ftp-installs

Hope that helps!

**Comment by shealavington** [comment]
In response to the last post by James: Perhaps what I'm about to say was the intended use of that area anyway, however it could potentially make a `GET` request to the GitHub API to fetch a list of releases to see if the version being used is out of date, then proceed to inform the user there's an updated version, and list all changes since the release the current version is running. (I would see a change-log for 7.0.12, 7.0.13, 7.0.14... etc.)

Endpoint: https://api.github.com/repos/directus/directus/releases

**Comment by benhaynes** [comment]
I like that! Looks like it doesn't need an API token, so this seems like a good way to showcase up-to-date versions.

@rijkvanzanten @shealavington — should we open up a new feature request for this?

**Comment by rijkvanzanten** [comment]
Sounds good to me!
