### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by tipcircle** [directus/directus#2297]
# Feature Request
Mostly just questions.

My apologies is this isn't the proper place to post. 

I've been looking at the demo and it looks awesome! I've also been reading the docs, but can't find the answers.

So...
Can users register themselves and be added to a certain role?

After they register and log in, can they be presented with pre-defined collections called "collection 1" "collection 2" or something like that?

Is there a group option to allow groups with all members having a predefined role?

Is there an option to allow collections to be cloned but not created?

If not, is there an option to allow users to create only certain types of pre-defined collections?

Can there be a limit to the number of collections they create based on their role?

Can users be set to only see/edit collections/entries they have created themselves or as a group they belong to? This is where a group option would be cool.

Can entries in a collection be scheduled to be published at a future date?

Can entries in a collection be scheduled to auto delete?

Can the comments/activity sidebar be removed?

Thanks!

## What problem does this feature solve?
Streamlined creation of users and collections. 

## How do you think this should be implemented?
I don't know if any of them are yet

## Would you be willing to work on this?
Yes

**Comment by benhaynes** [comment]
Thanks for this, @tipcircle — some great ideas in there.

Since GitHub is our primary source of issue tracking and feature requests, we do need to keep this a bit more organized. Each feature request should be created as its own ticket so it can be individually voted on by the community, specific comments can be left regarding each, and we can close them when one is completed. Also, any questions should be asked on our [Slack](https://slack.getdirectus.com) or StackOverflow. Lastly, if you don't see something in the Docs, give GitHub a search... many of these questions are in here already. :)

That said, I will respond to these here and then close this issue. If you have time, I'd love to see some of these added as individual tickets!

* User Registration — https://github.com/directus/app/issues/788
* That ticket has them assigned to a group, which can have any permissions you want
* Collections are extremely complex, having an option to duplicate them would be too problematic. In addition to basic settings, each collection has fields, interface options, and relationships. Some of those can't easily be duplicated (eg: relationships). We do have Field Duplication though... which is much easier and helps solve your problem.
* Only admins can create collections, and admins have all permissions. **Do you mean duplicate/create items?** (database records) Items can be duplicated with "[save as copy](https://docs.directus.io/guides/user-guide.html#saving)".
* You can control what ITEMS a user can create with permissions.
* You can not limit how many items a user can create... just if they can create or not.
* You can set users to only see items created by users of their role.
* You can publish items in the future by setting a date field and only fetching/displaying `publish_date > NOW`
* I think you can disable the comments, @rijkvanzanten ?
