### ISSUE TITLE
SDK contains side effects that prevent tree shaking, resulting in a large bundle

### ISSUE THREAD

**Issue by fabian-hiller** [directus/directus#23138]
### Describe the Improvement

The SDK claims to be modular and lightweight, but this is not true due to the side effects of `@directus/system-data`. The bundle size of `export { createDirectus } from '@directus/sdk';` is 7.47 kB (gzip). This is almost the entire size of the `@directus/system-data` dependency due to side effects that prevent tree shaking. `@directus/system-data` is not used at all and is unnecessary when using `createDirectus`.

> Without `@directus/system-data` the bundle size of `createDirectus` is 187 B (gzip).

Reproduction: https://bundlejs.com/?q=%40directus%2Fsdk&treeshake=%5B%7B+createDirectus+%7D%5D

**Comment by fabian-hiller** [comment]
If I am not mistaken, the SDK only uses `isSystemCollection` from `@directus/system-data`. Maybe it is easier to just add a simple array or function directly to the SDK to remove the dependency.

**Comment by rijkvanzanten** [comment]
It's built right now to use the `collections.yaml` from system-data as the source of truth for what system collections exist, which is then reused across multiple packages within Directus. That being said, it does mean we're pulling in that whole yaml file in a static build most of which we don't need in the SDK. A separate function with a hardcoded const array would be a quick fix for this, but we'd risk the SDK diverging from the rest of the platform if and when we're changing the system collections. Ideally there's a solution in between where we can statically include just the collection names for that function rather than the whole yaml file to reduce the bundle size across the board.

**Comment by fabian-hiller** [comment]
I am happy with any solution that keeps the bundle size to a minimum. I plan to use Directus heavily over the next few months and will be happy to provide feedback and contribute if I can find the time.
