### ISSUE TITLE
Password Reset missing domain name

### ISSUE THREAD

**Issue by jerrylovee2** [directus/directus#23292]
### Describe the Bug

When attempting to reset an admin password in Directus, the system sends a password reset email. However, the reset link provided in the email is missing the domain name, resulting in an invalid URL that cannot be used to reset the password.

the link is - 
file:///admin/reset-password?token

### To Reproduce

1. Request a password reset for an admin account in Directus.
2. Check the email received for the password reset link.
3. Observe that the link provided is missing the domain name.

### Directus Version

v9.2.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Directus v9.2 is ancient at this point in time and we're not actively supporting old versions anymore. Especially since I am quite sure this problem has been resolved in the last 3 years since it was released. I encourage you to upgrade to the most recent version (v11) of Directus and see if the problem still persists.
