### ISSUE TITLE
image: directus/directus:latest does not install latest (v11.0.1)

### ISSUE THREAD

**Issue by Pachat** [directus/directus#23317]
### Describe the Bug

As of today, latest is v11.0.1
so image: `directus/directus:latest` over a v11.0.0 should install v11.0..1
But in fact stays at v11.0.0

### To Reproduce

On a v11.0.0 restart docker with docker-compose.yml containing
`image: directus/directus:latest`
Restart => No change applied
Now modify
`image: directus/directus:11.0.1`
Restart => Change applied

Then modify
`image: directus/directus:latest`
Restart => Goes back to v11.0.0

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis:15-master

**Comment by hanneskuettner** [comment]
This might be due to caching in Docker. Docker will not pull the `latest` tag anew if it already is available on your system. It is generally discouraged to use the `latest` tag, for this and other reasons. See https://vsupalov.com/docker-latest-tag/ for more details on why the `latest` tag should be avoided. Just stick with an explicitly chosen version and you will be fine!
