### ISSUE TITLE
Validation Fields

### ISSUE THREAD

**Issue by phongXEM** [directus/directus#23633]
### Describe the Bug

I have colection with field check_box_1 and check_box_2 type boolen
<img width="849" alt="Screenshot at Sep 11 16-17-29" src="https://github.com/user-attachments/assets/c43fc8bd-ebac-4a6f-915f-bf0a1dd2fa5d">
set validation field check_box_1 
<img width="847" alt="Screenshot at Sep 11 16-19-15" src="https://github.com/user-attachments/assets/edbf2706-bddc-4515-b329-dec67a364a5d">
Mean is check_box_1 = false or check_box_1 = true , then check_box_2 must be false
But when i edit check_box_1 = true and check_box_2 = true, there is no validation at all
<img width="1048" alt="Screenshot at Sep 11 16-24-16" src="https://github.com/user-attachments/assets/81ee4e91-4db1-4dee-ab59-9cd768bb768b">

### To Reproduce

need help in this case

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment]
Validation on field level can only include the respective field itself.
To validate multiple fields together, you can configure validation via Policies:
<table><tr><td>
<img width="800" src="https://github.com/user-attachments/assets/f8eb65f1-eb4f-4bcb-8a67-07f93f4c1f2a">
</td></tr>
<tr><td>
Settings → Access Policies
</td></tr>
</table>

However, assuming you want the restriction to apply on item updates and not just item creation, you need to set-up a Flow instead, so that existing values are also taken into account during validation (e.g. if `check_box_1` has been set to true on first edit and now `check_box_2` is set to true as well).

Here's a simple example Flow that validates updated items:
<table><tr><td>
<img width="800" src="https://github.com/user-attachments/assets/710576b7-857a-4160-8403-02ff8f6a40ac">
</td></tr>
<tr><td>
<img width="600" src="https://github.com/user-attachments/assets/b8979a1c-cc41-46c2-80cd-b48236a32700">
</td></tr>
</table>

Please join our Discord server and ask for help there if you have any additional questions, as Issues on GitHub are reserved for discussing feature requests and bugs, see https://docs.directus.io/contributing/community.html#online-community. Thank you!

**Comment by phongXEM** [comment]
When throw new Error, Directus show message in role administrator and user is different
<img width="821" alt="Screenshot at Sep 13 14-18-58" src="https://github.com/user-attachments/assets/21137eb9-8000-44e9-95f3-bb1257872344">
Role Administor
<img width="885" alt="Screenshot at Sep 13 14-17-15" src="https://github.com/user-attachments/assets/431cb89c-cb86-4f6a-87fc-ca82bbd85ee6">
Role User( add all permission collection test). I want role user show message like administrator
<img width="1022" alt="Screenshot at Sep 13 14-17-34" src="https://github.com/user-attachments/assets/c23e72c3-8027-4408-9c69-ff0df7de456d">
