### ISSUE TITLE
Base singleton with common fields

### ISSUE THREAD

**Issue by omzy83** [directus/directus#2369]
Suppose I want to build a brochure website which includes: **home, about, services, service details, contact**.

Each of these pages will have different fields, for example the contact page will have a field to enter Google Maps embed code. However every page has some common fields such as: **h1 title, meta title, meta description, banner image**.

I know I can create a "single" collection type (singleton) for each page, however the only issue with this is that I would have to create the common fields repeatedly for each page. Also suppose later on I wanted to add a new common field, such as **h2 title**, I would have to add this manually to each page.

Is there a way to have a singleton which extends a “base” singleton, which contains all of the common fields and then allows me add some page specific fields?

**Comment by benhaynes** [comment]
Hmm, this seems like a very specific request... so not sure it passes our 80/20 rule. I personally don't think it would be that much additional effort to add that field to all 5 collections, but there are other options:

You could have all the "base" (specific) fields in the actual collection, and then have all of the shared fields be relational from a different collection. You can do this now with a `o2m` field, but then the shared fields would be edited in a modal (you would also want [this one](https://github.com/directus/app/issues/1464) so you can limit it to ONE item). To get all of this "inline" you would need to wait for [this one](https://github.com/directus/app/issues/1205#issuecomment-476266730).

I'll close this one since we should focus on those other two tickets... and then this functionality will be supported.
