### ISSUE TITLE
Improve Flows schema readability on dark mode

### ISSUE THREAD

**Issue by Pachat** [directus/directus#23764]
### Describe the Improvement

In dark mode, it's almost impossible to see the stream. Could you improve?

![image](https://github.com/user-attachments/assets/a108712a-ab5e-4cce-b61b-fbde0e6625eb)

**Comment by Pachat** [comment]
Same for buttons.

We see 
![image](https://github.com/user-attachments/assets/7129f64c-3bfe-4552-9327-2a0c6fb7e5dc)
instead of
![image](https://github.com/user-attachments/assets/9199f1f7-f8c2-45d5-b53d-1ffaa4e6bd03)

**Comment by elaminm2003** [comment]
I would like to work on this issue. can you please assign it to me

**Comment by kdj309** [comment]
Hi @Pachat can I work on this issue

**Comment by Pachat** [comment]
Sure. Just ask Rijk to let you.

**Comment by kdj309** [comment]
Hi @rijkvanzanten can I take this task

**Comment by hanneskuettner** [comment]
This seems to be very much an issue with the project color that you chose for your project, since that influences the primary color. This will not only be a problem with flows, but with every use of the primary color in the dark theme. Your best bet is to customize the `primary` color of the dark theme in the settings. I personally would not consider this to be a problem of Directus, as this very much is a problem of the customization that was performed.
