### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by triplecasquette** [directus/directus#23831]
### Describe the Improvement

Since the last update, I've noticed that some French translations are missing, whereas they were present in the old version.

Please let me know where I can add the translations. I'd be happy to help

Here is an example of where it disappear

![Capture d’écran 2024-10-09 à 19 11 07](https://github.com/user-attachments/assets/798c1a60-0997-47ed-a4e1-6f0b504fb5c5)

**Comment by hanneskuettner** [comment]
Heya! Thank you for making us aware of this, when you say last update, was that an update from v10 to v11?

Generally you can contribute translations over on Crowding and they will automatically be included in the next version that is released: https://crowdin.com/project/directus and for French specifically https://crowdin.com/project/directus/fr

I'll be closing this here, since there is nothing we can do in this repo and the translations always are a moving target. But  that being said, thank you for making us aware and please be so kind to help us translate this project.
