### ISSUE TITLE
Creating an item with a relation inside it requires required fields of nested relation

### ISSUE THREAD

**Issue by BorisKamp** [directus/directus#23868]
### Describe the Bug

I am using Directus `11.1.0` with Docker.

Making a query to create an item like this:
```gql
mutation Create_orders_item($data: create_orders_input!) {
    create_orders_item(data: $data) {
        id
        status
        date_created
        payment_intent_id
        payment_date
        form_move_to_ce {
            id
        }
    }
}
```

With the following `$data`:
```json
{
    "data": {
        "form_move_to_ce": {
            "id": "8e7eb549-a07a-418f-be62-3dd56cfb7c03"
        }
    }
}
```

fails if I leave out the `product` (one to many relation on the `form_move_to_ce`) in the `form_move_to_ce` data map.
I get the following error:
`Variable "$data" got invalid value { id: "8e7eb549-a07a-418f-be62-3dd56cfb7c03" } at "data.form_move_to_ce"; Field "product" of required type "Int!" was not provided.`

but that does not make sense. I want to create an order and establish a relation to `form_move_to_ce` with `id` `8e7eb549-a07a-418f-be62-3dd56cfb7c03`, then why does it expect the product? The product is a non-nullable relation on the `form_move_to_ce`.

### To Reproduce

see above

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres 16

**Comment by br41nslug** [comment]
Considering that `form_move_to_ce` is an one-to-many relation you're missing the array since o2m's can have multiple values. In your current setup it is trying to create a new product with the provided information and errorring as expected since you mentioned "product" is a required/non-nullable value.

(alternatively the same will happen if this UUID does not already exist)

```
{
    "data": {
        "form_move_to_ce": [{
            "id": "8e7eb549-a07a-418f-be62-3dd56cfb7c03"
        }]
    }
}
```

Closing this issue for now but happy to re-open if needed 😄
