### ISSUE TITLE
New collection does not appear under Persmissions in Access Policies

### ISSUE THREAD

**Issue by amy1hwang** [directus/directus#23882]
### Describe the Bug

After creating a new collection, the new collection does not appear in the permission list.

<img width="675" alt="Screenshot 2024-10-18 at 11 41 53 AM" src="https://github.com/user-attachments/assets/301eee57-744f-468e-8ab6-e69d0bb55910">
<img width="898" alt="Screenshot 2024-10-18 at 11 42 06 AM" src="https://github.com/user-attachments/assets/7fa8377d-d0c5-4743-8ba8-9c6a01fd9022">

### To Reproduce

1. Create a new collection.
2. Check Access Policies to see if the collection appears

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
Heya, you need to click the "Add Collection" button under the collection list on the policy page.

![CleanShot 2024-10-19 at 12 08 24@2x](https://github.com/user-attachments/assets/18dc269c-086e-467c-87c3-50b05c98b75c)

I'm closing this since I assume it is "just" a UX problem, but we are investigating if we can improve the experience / prominence of the button.
