### ISSUE TITLE
Request fields should be optional with status Draft

### ISSUE THREAD

**Issue by joezak11** [directus/directus#23950]
### Describe the Improvement

I think it would be more reasonable to make required fields be only on published and make it optional on draft so data can be partially saved and completed afterwards then published.

**Comment by hanneskuettner** [comment]
This can already be achieved by utilizing field conditions, that only make a field required if the status is "published".

![CleanShot 2024-10-31 at 13 42 57@2x](https://github.com/user-attachments/assets/c4c00cfa-c80f-4fa1-9aa0-b1bd2a302ffc)

I'm going to close this to, as it can already be achieved right now.

**Comment by joezak11** [comment]
Yes, I realize this can be achieved, I mean the default behavior in my opinion should be to make the fields optional when the status is Draft. It makes more sense to me, but maybe there would other use cases that would differ. I'm not sure.

**Comment by hanneskuettner** [comment]
>  I mean the default behavior in my opinion should be to make the fields optional when the status is Draft.

Since the status field (and states in it) is fully user definable the "when is it okay for fields to not be required" question becomes very opinionated very quickly. 

If you feel like there should be a way to configure an "official" draft status for an item, similar to how the archived status works that has some implicit behavior, please open a feature request in the discussions, as that is more than a small improvement request.
