### ISSUE TITLE
api create collection error

### ISSUE THREAD

**Issue by anhtu812** [directus/directus#23980]
### Describe the Bug

`curl http://0.0.0.0:8055/collections -H 'Authorization: Bearer uTNcEbGQtjxnUvYes6VNrevGMMwGnaoB' -d '{"collection":"API_config_tool","meta":{"icon":null}}'`

return error:
`{"errors":[{"message":"Invalid payload. \"collection\" is required.","extensions":{"reason":"\"collection\" is required","code":"INVALID_PAYLOAD"}}]}`

### To Reproduce

curl http://0.0.0.0:8055/collections -H 'Authorization: Bearer uTNcEbGQtjxnUvYes6VNrevGMMwGnaoB' -d '{"collection":"API_config_tool","meta":{"icon":null}}'

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment]
You need to set the `Content-Type` header when sending data with curl, otherwise the data is encoded as form data which is not supported by the endpoint.

`-H "Content-Type: application/json"`, see https://stackoverflow.com/a/7173011/6444752

I'm closing as it seems to be a usage problem and not in Directus itself.
