### ISSUE TITLE
Directus Files

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#2410]
Directus Files is a little special. It's the only collection that will receive `multipart/form-data`, it's the only collection that has a field where the input is different from the output (`data`), and it's the only collection (right now) where we actively need a separate field to present the data (`preview`).

The current flow in the application of creating a new file is as follows:

* User clicks `+`
* A modal comes up with a drop zone
* User drops file
* File gets uploaded with the multipart/form-data enctype in a field called `data`
* The user gets send to the item detail page for files
* The preview interface reads the value that's returned by the API in `data` and renders the file preview
* The user can edit the other data of a file

This is all a bit cumbersome. The main issue here is the fact that the `data` has a totally different input (`multipart/form-data` binary string for the file) than the output (JSON object representing the file data).

Ideally, the user can hit `+` and get send to the regular create item page (eg `/files/+`) where the file can be dropped, and all the other meta fields can be entered. Only when the user hits save, everything gets saved up to the API. This will allow files to operate like any other collection in places like modals for relationships too. The main issue here still is that only the directus_files collection should POST in the alternate enctype (form-data vs JSON).

I think the application has most things in place in order to make this happen. I do have a couple of questions for @directus/api-team though:

* Does the API support POSTing in `multipart/form-data` for multiple fields at the same time? eg `data`, `filename`, `description`, etc
* Can we add a `file` field type for `data` that supports (and validates) INPUT as a string (file content) and OUTPUTs as JSON (like we have right now)

Once those two things are confirmed, I believe we should be able to create a custom interface that will render a file drop-zone when there's no value, and the file preview when there _is_ a value. This will also allow us to get rid of the ALIAS `preview` field, that currently (kinda hacky) reads from the `data` key on the same page.

**Comment by cdwmhcc** [comment]
That would be great!!!

**Comment by philleepflorence** [comment]
@rijkvanzanten ... Are you sending the raw file data or the base64 string data, along with the other fields?

**Comment by rijkvanzanten** [comment]
> Are you sending the raw file data or the base64 string data, along with the other fields?

Right now I send the file data in multipart/form-data as raw file data. The other fields aren't send at all. Once the file is uploaded, the user is navigated to the edit page for the newly uploaded files. Changing values from there is business as usual: saving as JSON

**Comment by philleepflorence** [comment]
Ah okay, I got you, would it be too much to convert to base64 within Dropzone, then send JSON of data and other columns after the user enters the title, caption, et al?
Either way, the method you deem most efficient would be the way to go.

**Comment by rijkvanzanten** [comment]
> would it be too much to convert to base64 within Dropzone

Yeah, cause it has to read the whole file contents into JS memory, and base64 encoding will [increase the size of a file by ~33%](https://stackoverflow.com/a/4715499/4859211). This will implode for most browsers with files > 20MB

**Comment by philleepflorence** [comment]
Makes sense!!!
If you still want to send the file data along with title, et al:
https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

**Comment by rijkvanzanten** [comment]
Yes! That's what I want to do 🙂. We need to make sure the API supports that though

**Comment by philleepflorence** [comment]
If it does not, it is a simple function to add to index.php to accept.
I have it included in the v6.x of Directus: 
`$input = file_get_contents('php://input');` and `mb_parse_str()`

**Comment by janbiasi** [comment]
> Makes sense!!!
If you still want to send the file data along with title, et al:
https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

> Yes! That's what I want to do 🙂. We need to make sure the API supports that though

And we also need to think about that the main implementation on the server is different to the one in the browser (regarding adjustments in the SDK) because Node does not support `FormData` natively and you need to use a framework for that (as we had in the previous issue with the header fields).

cc @rijkvanzanten & @philleepflorence

**Comment by philleepflorence** [comment]
Directus API should be in PHP currently, right? 
Unless I am missing something.
This implementation is from the Browser App (VueJS) to Directus API (PHP).
Correct me if I am wrong @rijkvanzanten .

**Comment by janbiasi** [comment]
The App uses the `@directus/sdk-js` internally for the requests so if we change a behaviour there we must ensure that the SDK still works on Browser and NodeJS - that's why I've mentioned the input above @philleepflorence. So we can't just ignore the NodeJS side which doesn't support FormData, instead look also for a solution there :) 

cc @rijkvanzanten

**Comment by philleepflorence** [comment]
I can confirm my ExpressJS, NuxtJS and NextJS Applications pass on the POST (FORM DATA) from the front end (Vue/React/jQuery) to the Directus API - communication is Node API to Directus API.
I know I had to add the `$input = file_get_contents('php://input');` as Directus (v6.x) did not see the full `$_REQUEST` object.
I have never really used the JS SDK that much for specific security reasons.

But if there will be issues with the JS SDK, then I am open to learning more.

**Comment by rijkvanzanten** [comment]
The problem @janbiasi is referring to @philleepflorence is the fact that the SDK uses `new FormData` under the hood, which is natively supported in browsers, but not in Node.JS. We have to verify that the SDK works in Node (or react native for that matter).

**Comment by philleepflorence** [comment]
Okay, maybe I am confusing the topic @rijkvanzanten ... 

I thought you were referring to the Directus App File Interface processing the file and form data in the browser then submitting the data to the Directus API File Collection Endpoint for processing and saving.

If that is the case, there is no problem since you control the environment of the App and API.

However, if you are submitting the data to a NodeJS server for processing or saving, that is a different case entirely and you would need a package like: https://www.npmjs.com/package/form-data as of Node 8x.

That was why I said it is a blocking process and would hang if you have a large form or file data to read and process.

But if the Node or Express Server is merely a server middleware, then your method would work as well,  as I can confirm it does currently on v6.x.

**Comment by janbiasi** [comment]
And that's the issue, we need to add more different builds which are splicing the `form-data` package out etc. so that it won't be included in the bundle. I already did a test lately in a poc to replace axios with fetch. You'll also end up writing tests for your builded/compiled files because you never know if something works in the end-user environment or not.

cc @philleepflorence, @rijkvanzanten

**Comment by hemratna** [comment]
> * Does the API support POSTing in `multipart/form-data` for multiple fields at the same time? eg `data`, `filename`, `description`, etc
> * Can we add a `file` field type for `data` that supports (and validates) INPUT as a string (file content) and OUTPUTs as JSON (like we have right now)
> 

Yes, Both are possible, I need to make some changes in API. Let me know the timeline. So I can start working on it.

**Comment by rijkvanzanten** [comment]
What changes @hemratna? It would be nice to get everything in there over the course of the next couple weeks. It's no rush, but it would be nice to get this cleaned up sooner rather than later

**Comment by rijkvanzanten** [comment]
The file detail and file upload flow have been redesigned and optimized over on github.com/directus/app-next/ and can be tested in the alpha release
