### ISSUE TITLE
Non-Admin Users Unable to Create Collections Despite Having Full Permissions

### ISSUE THREAD

**Issue by sshan33** [directus/directus#24175]
### Describe the Bug

I have encountered an issue where non-admin users are unable to create collections in Directus, even though they have been explicitly granted full permissions (Create, Read, Update, Delete) on directus_collections and directus_fields. Changes to permissions are saved and confirmed, but non-admin users still receive a permission denial when trying to create collections. This issue persists even after clearing cache and restarting the Directus service.

### To Reproduce

1、Permission Configuration

Create a new role or use an existing non-admin role.
Navigate to Settings > User Roles & Access Policies.
Select the role and grant full permissions (Create, Read, Update, Delete) on directus_collections, directus_fields, directus_settings, and all other System Collections.
2、Attempt to Create Collection

Log in with a user assigned to the modified role.
The 'Settings' option and 'Data Model' are not visible or accessible in the user interface.
Despite having the necessary permissions, the user encounters a "Permission Denied" error when attempting to create a collection via the API with the correct Authorization Bearer token.

### Directus Version

 v11.1.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

 PostgreSQL 16

**Comment by hanneskuettner** [comment]
Heya!

This is due to collections being a special case, where the creation and updates are restricted to admin users only, see https://github.com/directus/directus/blob/48a0ae33c99839003bc3474c6ac23823345d1849/api/src/services/collections.ts#L58-L60

As this is an intentional limitation I will close this issue.

You can circumvent this limitation by for example creating your own flow operation, endpoint or hook that interoperates with the `CollectionsService` with "service level" accountability, ie. passing `accountability: null`. You will have to do you own permissions checking then, as the consequences might be bad if you don't.

@phazonoverload this might be something that should be explicitly documented in both the API docs and the user guide, as this is something that deviates from expectation.
