### ISSUE TITLE
WYSIWYG Advanced is missing in v8-rc1

### ISSUE THREAD

**Issue by gianniskarmas** [directus/directus#2465]
WYSIWYG Advanced has been removed and brakes front end.
Had to change the directus field types in the database as to make it work.

The new editor is so much better but uses Times New Roman as the default font and hearts my eyes :)

Also, Hooks are amazing and thank you for the addition but replaced Database update button that I hoped was going to fix the WYSIWYG Advanced changes.

**Comment by rijkvanzanten** [comment]
@bjgajjar lets add that on the migrations list 

@benhaynes times doesn't sound correct to me, can we verify that the serif font is loaded correctly?

@gianniskarmas The api automatically runs the migrations, so that button doesn't do anything :)

**Comment by benhaynes** [comment]
The font in the new `wysiwyg` is _Merriweather_, not _Times New Roman_ (though both are serifs). This was intentional as serif fonts are much better for legibility in long-form writing (like a blog post). That said, I did add an interface option on `textarea` that allows you to choose between serif/sans... so we'll add that here too. The problem is that the `wysiwyg` loads the iframe styling through a vue computed prop... so I'll need @rijkvanzanten to help figure that out. 😉
