### ISSUE TITLE
State of WYSIWYG interface

### ISSUE THREAD

**Issue by adamkobor** [directus/directus#2613]
Hey there, 
I have a question about the WYSIWYG interface, because it's kind of unclear what happened to it in the past, and what could happen to it in the future :) There are closed issues where TipTap has been mentioned, and theoretically it has been introduced in v8 RC1 as well (I'm not sure about this, because we didn't use Directus when v8 came out). 
Right now the editor behind this interface is TinyMCE, but we want to replace it in our project (probably with TipTap), however if it would be replaced anyway, we can wait for it, and spare the extra work on our side :)

Could you please clarify the situation? 🙏

**Comment by gyulavoros** [comment]
To chime in, I think what Directus is lacking a bit right now, is support for technical writing. Tech writing potentially involves editing lots of code snippets and math formulas.

The Markdown Interface widget makes it difficult to embed media/images. The WSYWIG Interface widget makes it difficult to work with code snippets.

I know it's probably not directly adaptable, but I think Ghost did strike a good balance with their [Koenig editor](https://github.com/TryGhost/Ghost-Admin/tree/master/lib/koenig-editor) in this regards.

Are there any recommendations / best practices for setting up to Directus to power tech blogs?

**Comment by benhaynes** [comment]
Thanks to you both... and here is the authoritative update:

We did have a PR for TipTap, and it was in the Release Candidate. However we did not want to have **two** WYSIWYG editors in the core suite any longer, and TipTap was not feature-rich enough to be the single/only editor. Since TinyMCE is proven (WordPress) and quite feature-rich, we chose that library.

That said, we would like to have a robust ecosystem of extensions, such as many different WYSIWYG and Markdown editors available for easy installation. However we're still working through the "Directus Marketplace" that would serve these... and the exact right modular way to install extensions on the fly. It's important to get this right so we don't have to implement a big breaking change to interface/extension architecture in the next 6-12 months that would render all those interfaces broken.

Also, I 100% agree that a solid markdown interface would be _really_ nice... especially for technical writing. We do have a Markdown editor, so someone could clean that one up a bit, or look into adding a new/netter one. There are two directions here... WYSIWYG Markdown (what we have now... with a side-by-side view), or [the more visual one](https://simplemde.com/). Eventually we should have both... ideally one interface that has an option to choose the style.

All this is happening on a small, open-source team... so it's slow going. We're looking into funding options, but in the meantime, if you'd like to help speed things up, come chat with me on our [Slack Community](https://directus.chat) and we can discuss you joining our official core contributors (working on the marketplace, interfaces, or anything else). 👍

**Comment by adamkobor** [comment]
Hey @benhaynes,
thanks for the clarification, I understand all your concerns :) We will dive into the RC's code and try to integrate a 3rd party solution then.

**Comment by mohsin51** [comment]
Hey @benhaynes,
First of all the tool is **awesome** for being purely open-source and not charging for extra features like strapi,ghost etc.
I just wanted to know is there any way to write a code snippets with highlight.js in between your blog/article etc. 
if not i'd like to dive into code to make it happen just need some direction thanks.

**Comment by rijkvanzanten** [comment]
@mohsin51 Heya! This is a pretty old resolved issue, so not really the best place to discuss this 🙂 

Our current WYWISYG interface has a "codeblock" option you can enable in the toolbar, but it doesn't do any syntax-highlighting-to-HTML magic. Can you open [a feature request](https://github.com/directus/directus/discussions/new) so we can talk about it?

**Comment by mohsin51** [comment]
@rijkvanzanten just added [feature request](https://github.com/directus/directus/discussions/4198).

**Comment by taismassaro** [comment]
hey @rijkvanzanten, sorry to come back to this again, but I'm researching tooling options for a project and I'm also interested in the possibility of using Tiptap. 

we have a very specific use case for the rich text editor (where we want to create our own meaningful/semantic marks instead of just 'bold', 'italic' etc) with a lot of focus on the editors' workflows and UX, and Tiptap is currently the best fit we found for that purpose. but I would still like to leverage all the features of a headless CMS instead of writing it from scratch.

maybe I just missed the documentation for this, but would it be possible for us to swap the out-of-the-box editor with our own custom Tiptap one, like @adamkobor suggested?

**Comment by rijkvanzanten** [comment]
@taismassaro You could make a custom Tiptap extension :) https://docs.directus.io/extensions/interfaces.html
