### ISSUE TITLE
M2M is showing up as O2M why?

### ISSUE THREAD

**Issue by chrisformula** [directus/directus#2679]
Steps to Reproduce

1. Install on Shared Hosting
2. Add a new Collection
3. Add M2M relationship

## Expected Behavior
M2M to work as needed

## Actual Behavior
M2M not available

## Other Context & Screenshots

#
![Settings___Editing_Item__Test](https://user-images.githubusercontent.com/3940594/80025581-2b77c900-84e1-11ea-82a4-122c340ca8c9.png)
# Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Directus Release Version: [8.6.2](url)
  - App Version: [eg: 7.11.0] (include if Directus Release Version <=`190927A`)
  - API Version: [eg: 2.6.0] (include if Directus Release Version <=`190927A`)
- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
> Expected Behavior
>> M2M to work as needed

M2M works as expected 😉 

What's shown in that overview is the Directus _type_ of the field. A Many to Many is nothing more than a one to many that then has another many to one from the junction table

`A -o2m- junction -m2o- B`

This is technically correct. Moving forward (v9+), we're going to show a small description of the interface instead of just it's type, which should also prevent this confusion
