### ISSUE TITLE
WYSIWYG (HTML) Interface appears disabled on non-admin update

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#2907]
From https://github.com/directus/next/issues/817#issuecomment-723058177:

The normal Inputs are working, but the text area/wysiwyg fields are now disabled. (with them enabled in custom permissions).

**Comment by nelolka** [comment]
> @rijkvanzanten if I edit an existing record the style of the WYSIWYG is wrong. It looks like it is `readonly`.

Yes, if you create a new item, the style is right. But if you edit an existing item, the style inside tinymce iframe is wrong (while the style of `iframe` is right). It looks like TinyMCE is simply overriding your styles.
To reproduce the bug **you must not have admin access**.

![image](https://user-images.githubusercontent.com/24505418/104137177-a2bcf800-53a3-11eb-88e0-487d11f96eb3.png)

**Comment by benhaynes** [comment]
Reproduced. If you're editing an item and view field with the WYSIWYG-HTML interface as a non-administrator... it appears disabled:

![Screen Shot 2021-02-10 at 3 57 39 PM](https://user-images.githubusercontent.com/522079/107571297-bc2aad00-6bb8-11eb-9148-0710752cd6b4.png)

Note: When the field is set to `readonly` it is styled as disabled AND does not allow for editing. So that is all correct.

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/directus/directus/issues/3916
