### ISSUE TITLE
Add import/export endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#2927]
The export endpoint allows you to export the output of multiple endpoints at the same time. This effectively allows you to export schema and data of the installation. Subsequently, the import endpoint should be able to intake this data and process it through the regular services, as if they were separate requests.

This allows you to move schema and/or data from/to different Directus installation, like staging to production

**Comment by aiomaster** [comment]
It would be really nice if the schema export would be in a good format for version control systems like git.
I think of usecases where you want to track your schema and develop it in different branches.
It would be really cool to be able to merge them and setup a directus out of the result.

I don't know if it is in scope, but it would be really cool to be able to kind of "migrate" an existing schema to a newer one. Or is it somehow already possible?

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/directus/discussions/4248#discussioncomment-450821

**Comment by zanami** [comment]
@aiomaster I miss this feature very much. Some plain JSON/JS code to control both schema and presentation within admin UI would be really nice.

Strapi has it (a bit complicated, but flexible, I guess) — you can design your collections in UI and then tweak/change/reuse it.
It's very opinionated so does not play well with custom/existing databases, though.

[Keystone](https://www.keystonejs.com/guides/schema), [Payload](https://github.com/payloadcms/custom-website-series/blob/master/collections/Page.ts) - these are simply 'code/config first', so no 'model builder' available, just an example what the exported configs could look like. In Payload config files control both collections/fields (collection tables in Directus) and their behaviour: permissions, appearance in admin UI etc. (i.e. corresponding records in directus_* tables), .

The only 'source of truth' in Directus is the database. You can't easily track changes, find and resolve inconsistencies, test, share or reuse parts of its' schema etc.

Some kind of solution to this would be really useful even for an "App dashboard for managing SQL database content", and Directus is already much more than that.

@rijkvanzanten Please clarify it's out of scope. I found [this comment](https://github.com/directus/v8-archive/issues/31#issuecomment-437647526) from 2018. Anything new since then?

**Comment by rijkvanzanten** [comment]
@zanami Nope, not out of scope at all. As a matter of fact, it's very likely that https://github.com/directus/directus/discussions/3891 will land in the future as an alternative way of managing schema 🙂 

As for that comment you linked, that's exactly what this issue is tracking, so that will be implemented soon

**Comment by adrchen** [comment]
Currently the only way of inputting information is by using the UI? At the moment I cannot "import", say, a XLS file into the database so the information gets loaded into the respective Collection?

**Comment by rijkvanzanten** [comment]
@adrchen Hard no! You can insert it directly into the database, and it'll show up and work with Directus as expected 👍🏻

**Comment by benhaynes** [comment]
Also, you can use the API (or SDK)... which is not UI, and we're actively working on the `/import` endpoint.

**Comment by adrchen** [comment]
Thanks for the reply, @rijkvanzanten & @benhaynes .

Could something like [this](https://justnumbersandthings.com/post/2018-06-12-dbeaver-import-csv/ ) work (I'll also try from my side)?

Also, any chance this is on Directus roadmap? Being able to import information into Collections done directly thru the UI.

**Comment by rijkvanzanten** [comment]
> Could something like this work (I'll also try from my side)?

This exactly should work just fine 🙂 I personally use [TablePlus](https://tableplus.com) to modify my databases, but DBeaver is a perfectly fine tool too 👍🏻 

> Also, any chance this is on Directus roadmap? Being able to import information into Collections done directly thru the UI.

Yes absolutely. We already have the functionality to export to a file, adding a way to "mass import" from those files it the next iteration on that 👍🏻

**Comment by geisterfurz007** [comment]
Quick question: Is it really just possible to straightup dump the database and reimport it (as SQL dump for example) or is there additional data Directus stores on the collections like sorting keys, etc? Thanks for this amazing project, it's hard (not to say impossible) to find anything comparably clean yet extensible!
