### ISSUE TITLE
No records shown when porting data from v8 database

### ISSUE THREAD

**Issue by tuxnese** [directus/directus#3180]
I have copied a table from a v8 database. This time the table has a primary key. I do not get errors, but the table of the records is empty. 
Here is the dump of the database:

[directus_v9_dump_issue_2.sql.zip](https://github.com/directus/directus/files/5591343/directus_v9_dump_issue_2.sql.zip)

**Comment by rijkvanzanten** [comment]
What's the issue here exactly? What do mean by 

> but the table of the records is empty.

??

I just imported your dump, and everything looks correct to me:

![CleanShot 2020-11-27 at 19 24 21](https://user-images.githubusercontent.com/9141017/100490035-28cbfa80-30e6-11eb-9406-7cba088ec22e.png)

(without auth)

![CleanShot 2020-11-27 at 19 24 47](https://user-images.githubusercontent.com/9141017/100490050-384b4380-30e6-11eb-8331-35c1dc7853fc.png)

(with auth)

![CleanShot 2020-11-27 at 19 24 27](https://user-images.githubusercontent.com/9141017/100490036-2cf81800-30e6-11eb-8b24-5d1099b23765.png)
