### ISSUE TITLE
Support collection scope in display templates

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3225]
Similarly to `fields` in the API, we should support the following `:` based syntax in display templates across the app:

```
{{ title }} - {{ sections.item:headings }} 
```

That allows you to setup displays/display templates for `a2o` / `m2a` correctly as well

**Comment by benhaynes** [comment]
Should we close https://github.com/directus/directus/issues/3258 as a duplicate of this? Or are they different? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Different 👍🏻

**Comment by aiomaster** [comment]
It would be nice to be able to select fields from the referenced collections of the Many-to-Any relations to use them in display templates.
The GUI should also support this somehow.

I have a special question and I don't know if it would be addressed by this issue or if I should create a new issue for that.
What if I want to use the same field in every referenced m2a-collection?
For example I have a collection `pages` with a m2a-field called `sections` that references two collections called `teaser_sections` and `main_sections`, both having a field called `title`.
It would be cool to use something like this in my display template for the sections field: `{{ sections.item:*.title }}` so that the exact collection does not matter. It should only have a field called title. If it has not, we could just leave the result empty.

Thanks for the awesome work on directus!

**Comment by benhaynes** [comment]
Does this solve the M2M Display Template issue we were discussing, where we need the junction fields from the related collection? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
No it doesn't. This only applies to m2a relations where you have to choose the fields per collection
