### ISSUE TITLE
List view isn't shown

### ISSUE THREAD

**Issue by TorbenHammes** [directus/directus#3322]
Me again ^^

I have added content in a new instance, but it is not shown in the collection overview. Unfortunately I do not know what the reason is. In other instances it went smoothly. 

Should I install it again?

<img width="857" alt="Bildschirmfoto 2020-12-06 um 01 11 51" src="https://user-images.githubusercontent.com/12980389/101268135-29a50200-3760-11eb-8257-bebf76fca313.png">

---

### Project details
Directus Version: 9.0.0-rc.20
Environment: production
OS: Linux 5.4.0-51-generic
Node: 10.19.0

**Comment by TorbenHammes** [comment]
Maybe that's interesting. I think it's a problem with the database.

<img width="857" alt="Bildschirmfoto 2020-12-06 um 01 29 23" src="https://user-images.githubusercontent.com/12980389/101268392-86a1b780-3762-11eb-9a13-63d166254d35.png">

**Comment by rijkvanzanten** [comment]
@TorbenHammes would you be able to share a DB dump where this is happening?

**Comment by TorbenHammes** [comment]
Of course. I will share it with you on Discord.

**Comment by shlaing** [comment]
@rijkvanzanten @TorbenHammes  any status? I am also happening too.
I got this error when I start using relationships.

**Comment by shlaing** [comment]
@rijkvanzanten Similar Issues -  #2923 #3346

**Comment by TorbenHammes** [comment]
@rijkvanzanten today I've tried it again with RC 21... but the error is the same. Now I changed the database from MySQL to MariaDB and it works.  I think the problem is depending on MySQL... FYI

The other instances are running on MariaDB, too. It works well there.

**Comment by aidanwhiteley** [comment]
Hi, I've been seeing the same intermittent behaviour. While I'm only using MySQL sometimes collections are displayed and sometimes they aren't. I thought the issue might be because I had imported (just) the content tables from a Directus v8 schema into a Directus V9 rc20 install. However, when the problem is occurring the "collection" of users isn't shown to the admin user either.

In both cases (no content elements and no users listed) the browser console message is "TypeError: Cannot read property 'field' of undefined". On clicking through to the corresponding "prettified" code, although the running code is understandably different, the name of the field that is undefined is the same (code snippets below - the one for the content collection first)

            }, [e._v(" " + e._s(e.showingCount) + " ")]) : e._e()])], 1), e.loading || e.itemCount > 0 ? a("v-table", {
                ref: "table",
                staticClass: "table",
                attrs: {
                    "fixed-header": "",
                    "show-select": !e.readonly && void 0 !== e.selection,
                    "show-resize": "",
                    "must-sort": "",
                    sort: e.tableSort,
                    items: e.items,
                    loading: e.loading,
                    headers: e.tableHeaders,
                    "row-height": e.tableRowHeight,
                    "server-sort": e.itemCount === e.limit || e.totalPages > 1,
                    "item-key": e.primaryKeyField.field,     <<====    error on this line
                    "show-manual-sort": null !== e.sortField,
                    "manual-sort-key": e.sortField,
                    "selection-use-keys": ""
                },

               return a("card", {
                    key: t[e.primaryKeyField.field],    <<===== error on this line
                    attrs: {
                        "item-key": e.primaryKeyField.field,
                        crop: "crop" === e.imageFit,
                        icon: e.icon,
                        file: e.imageSource ? t[e.imageSource] : null,
                        item: t,
                        "select-mode": e.selectMode || e._selection && e._selection.length > 0,
                        to: e.getLinkForItem(t),
                        readonly: e.readonly
                    },

In both cases the JSON returned _looked_ Ok to me but I'm just guessing. Examples below

http://localhost:8055/items/component_intros?limit=25&fields[]=website&fields[]=status&fields[]=componentname&fields[]=title&fields[]=introtext&fields[]=detailtext&fields[]=id&page=1&filter=%7B%7D
{"data":[{"website":"aidanwhiteley.com","status":"draft","componentname":"MapsCarouselIntro","title":"The GPS Blog","introtext":"...","id":1}, {more entries}]}

Apologies - if I eventually spot a pattern for when this works and when it doesn't I'll update this issue.

http://localhost:8055/users?limit=25&fields[]=role&sort=id&page=1&filter=%7B%22role%22:%7B%22_eq%22:%22fa3bc1d0-c1b3-4c05-8a5e-21ae9987a07d%22%7D%7D
{"data":[{"role":"fa3bc1d0-c1b3-4c05-8a5e-21ae9987a07d"}]}

**Comment by shlaing** [comment]
![Screenshot 2020-12-10 at 5 46 56 PM](https://user-images.githubusercontent.com/811734/101755341-b4df1880-3b0f-11eb-8051-4d409567ed2c.png)
Error message.

**Comment by h2bear** [comment]
for me its quite similar... likely without no reasonable reason it doenst show any users,files,roles...anymore

System:
```
"directus": "^9.0.0-rc.22",
"mysql": "^2.18.1"
```

DB:
`mysql  Ver 8.0.21-12 for Linux on x86_64 (Percona Server (GPL), Release '12', Revision '7ddfdfe')`

Error on Browser Console:  
`TypeError: e.primaryKeyField is undefined`

Dump:
[dump.sql.zip](https://github.com/directus/directus/files/5674148/dump.sql.zip)

**Comment by shlaing** [comment]
@rijkvanzanten , @h2bear , @aidanwhiteley , @TorbenHammes 
I found something. Primary key was not created when creating a collection/table with MySQL 8.x.x ( not sure on lower ver ).

**with MySQL**
![test-with-MySQL8 x x](https://user-images.githubusercontent.com/811734/101860263-5d40bb80-3ba8-11eb-84db-a4e50dd8facd.gif)

**with MariaDB**
![test-with-MariaDB](https://user-images.githubusercontent.com/811734/101860594-27e89d80-3ba9-11eb-9da1-8b801827b368.gif)

**Comment by ialexs** [comment]
> @rijkvanzanten , @h2bear , @aidanwhiteley , @TorbenHammes
> I found something. Primary key was not showed when creating a collection/table with MySQL 8.x.x ( not sure on lower ver ).

I'm on MySQL 8.0.22,  docker `directus/directus:v9.0.0-rc.22`..

The icon sometimes not showed. But the PK is there in the database (confirmed by looking in to the table structure itself)

Some  collections showed up again in the screen, after toggling the view/hide setting 
(screen shot here: https://discord.com/channels/725371605378924594/725817819882586132/786521604762107904)

.. some are not :( .. I'll try to reset from scratch again, and taking notes on what might be the cause..

**Comment by benhaynes** [comment]
Interesting — could be related, @shlaing ... could also be that knex is having an issue identifying the pk in the table. Either way, it's something that needs to be fixed.

**Comment by rijkvanzanten** [comment]
I know enough people are seeing this so it's definitely a problem, however...... I can't for the life of me reproduce it on my end 😐 

I've tried the MySQL (InnoDB) 8.0.22 + Node 10.19.0, with both provided DB dumps, in development _and_ production, under macOS and Docker 😭 

@ialexs Would you be able to share your _exact_ Docker setup and a DB dump where this problem is happening? That's my best shot at reproducing this now :\

**Comment by JesperJonet** [comment]
Im having the same issue,
Same error refering to the line already mentioned: primaryKeyField
Server version: 8.0.22-0ubuntu0.20.04.3 (Ubuntu)

Something leads me to think the error is related to db collation
Out of curiosity, which collation do you have on your DB/table/fields? 

I have the mysql default utf8mb4_0900_ai_ci

**Comment by kroawen** [comment]
I has updated to rc.26, issue still existed
Version: 9.0.0-rc.26
OS: Linux 3.10.0-1160.6.1.el7.x86_64
Node: 14.15.1
MYSQL: 8.0.22 utf8mb4_0900_ai_ci

`
chunk-vendors.8f64b78c.js:113 TypeError: Cannot read property 'field' of undefined
    at app.04fb7d50.js:1
    at a.Pt [as _l] (chunk-vendors.8f64b78c.js:113)
    at a.i (app.04fb7d50.js:1)
    at chunk-vendors.8f64b78c.js:28
    at be (chunk-vendors.8f64b78c.js:28)
    at a.t.render (chunk-vendors.8f64b78c.js:28)
    at a.e._render (chunk-vendors.8f64b78c.js:113)
    at a.r (chunk-vendors.8f64b78c.js:113)
    at nr.get (chunk-vendors.8f64b78c.js:113)
    at nr.run (chunk-vendors.8f64b78c.js:113)
`

**Comment by kroawen** [comment]
project have updated to rc.26, issue still existed
Version: 9.0.0-rc.26
OS: Linux 3.10.0-1160.6.1.el7.x86_64
Node: 14.15.1
MYSQL: 8.0.22 utf8mb4_0900_ai_ci

`chunk-vendors.8f64b78c.js:113 TypeError: Cannot read property 'field' of undefined at app.04fb7d50.js:1 at a.Pt [as _l] (chunk-vendors.8f64b78c.js:113) at a.i (app.04fb7d50.js:1) at chunk-vendors.8f64b78c.js:28 at be (chunk-vendors.8f64b78c.js:28) at a.t.render (chunk-vendors.8f64b78c.js:28) at a.e._render (chunk-vendors.8f64b78c.js:113) at a.r (chunk-vendors.8f64b78c.js:113) at nr.get (chunk-vendors.8f64b78c.js:113) at nr.run (chunk-vendors.8f64b78c.js:113)`

**Comment by lancehornback** [comment]
FYI I resolved this issue by restarting MySQL.

Issue: Can add collections and items; everything shows up in db but nothing displays at /admin/collections/{collection-name}. Error in console: ...TypeError: undefined is not an object (evaluating 'e.primaryKeyField.field')...

MacOS 11
MySQL 8.0.21
Directus 9.0.0-rc.26

**Comment by khromov** [comment]
I too ran into this problem after trying to add a new admin user. No API endpoints were working, no errors in server JS console, reloading the page was not working and the client console was full of `primaryKeyField` errors. 

It was very disconcerting that the only way to fix it was to restart the database. I understand that Directus 9 is still in RC but this is a very critical issue - how can anyone deploy this when it randomly crashes the backend until reboot?

**Comment by whatwasmyusername** [comment]
I am running mysql v8.0.22-0ubuntu0.20.04.3 with directus ^9.0.0-rc.17 and I am having this same issue.

I took a look at [@directus/schema's mysql dialect](https://github.com/directus/directus/blob/main/packages/schema/src/dialects/mysql.ts) and found the query responsible for looking up the column properties and it looks like it comes down to this:

<pre>select `c`.`TABLE_NAME`, `c`.`COLUMN_NAME`, `c`.`COLUMN_DEFAULT`, `c`.`DATA_TYPE`, `c`.`CHARACTER_MAXIMUM_LENGTH`, `c`.`IS_NULLABLE`, `c`.`COLUMN_KEY`, `c`.`EXTRA`, `c`.`COLLATION_NAME`, `c`.`COLUMN_COMMENT`, `c`.`NUMERIC_PRECISION`, `c`.`NUMERIC_SCALE`, `fk`.`REFERENCED_TABLE_NAME`, `fk`.`REFERENCED_COLUMN_NAME`, `fk`.`CONSTRAINT_NAME`, `rc`.`UPDATE_RULE`, `rc`.`DELETE_RULE`, `rc`.`MATCH_OPTION` 
from `INFORMATION_SCHEMA`.`COLUMNS` as `c` 
left join `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE` as `fk` on `c`.`TABLE_NAME` = `fk`.`TABLE_NAME` and `fk`.`COLUMN_NAME` = `c`.`COLUMN_NAME` and `fk`.`CONSTRAINT_SCHEMA` = `c`.`TABLE_SCHEMA` 
left join `INFORMATION_SCHEMA`.`REFERENTIAL_CONSTRAINTS` as `rc` on `rc`.`TABLE_NAME` = `fk`.`TABLE_NAME` and `rc`.`CONSTRAINT_NAME` = `fk`.`CONSTRAINT_NAME` and `rc`.`CONSTRAINT_SCHEMA` = `fk`.`CONSTRAINT_SCHEMA` 
where `c`.`TABLE_SCHEMA` = 'multi_po_test'</pre>

When I run this query directly in mysql for a table that I'm having trouble with it returns these records (extra columns omitted):
<pre>+--------------+-----------------+------------+
| COLUMN_NAME  | CONSTRAINT_NAME | COLUMN_KEY |
+--------------+-----------------+------------+
| part_number  | PRIMARY         | PRI        |
| status       | NULL            |            |
| sort         | NULL            |            |
| date_created | NULL            |            |
| date_updated | NULL            |            |
| name         | NULL            |            |
| manufacturer | NULL            |            |
| condition    | NULL            |            |
| returnable   | NULL            |            |
| modality     | NULL            |            |
| list_price   | NULL            |            |
| category     | NULL            |            |
| image_url    | NULL            |            |
+--------------+-----------------+------------+</pre>

This what I would expect because the code is looking for CONSTRAINT_NAME = 'PRIMARY' to set the flag passed to the client.

When I look at the data at runtime for this `part_number` column, the `CONSTRAINT_NAME` is coming up as null instead of 'PRIMARY', but the value for `COLUMN_KEY` does have the value 'PRI'.  So, in my case at least, the primary key can be determined correctly using `COLUMN_KEY`.  I have no idea why the query wouldn't be returning the same data when run via knex, but would a workaround for this be to change the mysql driver to check for either case:

<pre>is_primary_key: rawColumn.CONSTRAINT_NAME === 'PRIMARY' || rawColumn.CONSTRAINT_NAME == 'PRI'</pre>

**Comment by metamagpie** [comment]
> I know enough people are seeing this so it's definitely a problem, however...... I can't for the life of me reproduce it on my end 😐
> 
> I've tried the MySQL (InnoDB) 8.0.22 + Node 10.19.0, with both provided DB dumps, in development _and_ production, under macOS and Docker 😭
> 
> @ialexs Would you be able to share your _exact_ Docker setup and a DB dump where this problem is happening? That's my best shot at reproducing this now :\

The issue is quite simple to reproduce. Just create a new directus project using the world database example provided by MySQL and only the City collection will be visible in the admin UI. Thanks!

**Comment by rijkvanzanten** [comment]
@whatwasmyusername Thanks for that insight! I'm.. still not able to reproduce this on my MySQL installations.. but your explanation makes total sense. I'll update that check to include both statements `rawColumn.CONSTRAINT_NAME === 'PRIMARY' || rawColumn.COLUMN_KEY === 'PRI'` (I think you made a typo in saying to check for CONSTRAINT_NAME instead of COLUMN_KEY).

I'm generally just very confused by 

> When I look at the data at runtime for this part_number column, the CONSTRAINT_NAME is coming up as null instead of 'PRIMARY'

Why would it work sometimes, but not others? 🤔 And seemingly only works for some tables, but not others?
