### ISSUE TITLE
nextjs with directus/sdk-js

### ISSUE THREAD

**Issue by jiangyh1024** [directus/directus#3442]
![image](https://user-images.githubusercontent.com/34930870/102463765-8076d980-4086-11eb-81fb-d812bb2d99e5.png)

**Comment by jiangyh1024** [comment]
maybe caused by 
![image](https://user-images.githubusercontent.com/34930870/102464086-e4999d80-4086-11eb-889b-be90ba792434.png)
 ?

**Comment by rijkvanzanten** [comment]
@jiangyh1024 `next` should handle optional chaining [starting with v9.1.7](https://nextjs.org/blog/next-9-1-7). What bundler are you using for your node modules? Make sure it's up to date enough to handle Optional Chaining in JS.

(@nickrum Seems like Next.js is importing from the `module` path instead of the `main` path. Is the `main` export (the CJS one) babel-ed down?)
