### ISSUE TITLE
Users overwrite each others changes if they save the same collection item

### ISSUE THREAD

**Issue by khromov** [directus/directus#3558]
If two users edit the same collection item, the last user to save will always get their changes through, even if another user made changes to the collection first.

Directus should detect on save if the collection item has been edited since it was last loaded into the UI and refuse to save in such case to avoid users accidentally overwriting each others changes.

More preferably, there should be support for real-time collaboration so that multiple users could edit the same collection item simultaneously.

**Comment by rijkvanzanten** [comment]
> If two users edit the same collection item, the last user to save will always get their changes through, even if another user made changes to the collection first.

The app will only submit the changes to the fields that were actually altered. In this case, your reported situation feels like the expected behavior here. If user A is setting title to "Hello", while user B is making it "Hello World", whoever saves last is the one that becomes the saved value.

> Directus should detect on save if the collection item has been edited since it was last loaded into the UI and refuse to save in such case to avoid users accidentally overwriting each others changes.
> More preferably, there should be support for real-time collaboration so that multiple users could edit the same collection item simultaneously.

Good ideas 👍🏻 Feel free [to open a feature request for that](https://github.com/directus/directus/discussions/new)

**Comment by benhaynes** [comment]
I agree with what Rijk said (since we only save the changed fields), but we [will add back in the "Someone else is editing this page" message](https://github.com/directus/directus/issues/2963)... and I like the idea of a "Someone has edited this page since you got here" sort of message too! Worth a Feature Request!
