### ISSUE TITLE
Removing the 'status' field breaks the collection page

### ISSUE THREAD

**Issue by shealavington** [directus/directus#3737]
When removing the status field from a collection:
![image](https://user-images.githubusercontent.com/16869302/104974556-4c2d6a80-59f0-11eb-882d-4f752aa90127.png)

the following is presented on the collection items index:
![image](https://user-images.githubusercontent.com/16869302/104974615-7848eb80-59f0-11eb-947c-172afe54a2dc.png)

The collection should continue to work.

MYSQL, dev directus, chrome

**Comment by benhaynes** [comment]
I assume this is because the Collection's Archive is still set to the column name... if we can confirm that is the case (by clearing that in the DB directly) then it should be an easy fix to simply check/clear that on field delete. We should also add a catch so that if that's missing it simply disables/clears it instead of 500'ing.

**Comment by Nitwel** [comment]
![grafik](https://user-images.githubusercontent.com/22577866/108205726-be938680-7125-11eb-81c1-79d839d79e61.png)
Yes, this seems to be caused by this in the `collections` collection not getting removed when deleting the status field.

**Comment by rijkvanzanten** [comment]
We should clear out the archive stuff and sort_field on field deletion in the API 👍🏻
