### ISSUE TITLE
Related values display should show total count

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#3743]
I used the Directus app to add a O2M field to a collection with a lot of items, and choose to add the corresponding M2O field to the related table.

When visualizing the collection hosting the O2M field, that field indicates "100 items" and it's only possible to scroll through these 100 items, even though there are way more.

Would it be possible to skip that limit, to change its value, or just to indicate that there are indeed more than 100 items ? 

![status](https://user-images.githubusercontent.com/33065839/105030029-782e0780-5a53-11eb-82a9-0a7c3f6e0c58.png)

**Comment by jpetryk** [comment]
I'm no sure if this is related or not, but the "100" limit jumped out at me because it's also the same number of "Directus" collections that seem to be recognized, despite the fact I have way more. As a result, the interface is incorrectly showing collections as "Database Only" even though they are certainly not since they were created through Directus and are part of other M2O, O2M or M2A relationships. The end result is they show up on the  main Collection screen when I have set them to be hidden (see screenshots at below links).

- https://drive.google.com/file/d/1QgV7Glm_bHTeYj5_5pKP44uTbx_kB4jW/view?usp=sharing
- https://drive.google.com/file/d/1lwDu9ArAoE8ifafcWhsL6BX3ThA5eIIB/view?usp=sharing
- https://drive.google.com/file/d/1-3nF0znu7XMp7Sg_APP_SOhvrXSaI6mS/view?usp=sharing

Please let me know if this is the same issue or if I should open a new issue @benhaynes. Thanks!

**Comment by rijkvanzanten** [comment]
@jpetryk That's a different issue caused by a very similar reason: The default limit for the API is 100, so the app has to explicitly state to fetch all items. The fact that it only the first 100 items could be considered a good thing for the inline preview of the o2m (as it would otherwise potentially blow up the browser if it tries fetching 10k+), but for the amount of collections, it should definitely fetch all

**Comment by YannickMol** [comment]
Trying to reproduce, but failing to, see below image. Is it still showing 100 at your end?

![image](https://user-images.githubusercontent.com/13256289/108473959-fd911b80-728e-11eb-8448-6b3ce055f8ec.png)

**Comment by rijkvanzanten** [comment]
@YannickMol I think you've accidentally found a bug in the API 😁 It should still apply the default `100` limit to nested o2m sets

**Comment by rijkvanzanten** [comment]
@YannickMol Mind updating the `related-values` display to use the `total_count` meta to render that label??

**Comment by YannickMol** [comment]
I'll do so tomorrow, no longer behind my PC today 😅

**Comment by rijkvanzanten** [comment]
Vrijmibo!

**Comment by YannickMol** [comment]
> @YannickMol Mind updating the `related-values` display to use the `total_count` meta to render that label?? I'll fix the api limit in the meantime 👍🏻

I had a look but not sure how to do this. The item count is fetched in a very different way than in the cards/tabular view.

**Comment by rijkvanzanten** [comment]
Ah yeah, I thought we could "just" update the fetch to include the meta count, but it doesn't fetch itself in the display (otherwise a page of 100 items would do a 100 fetches 👀)

The next best thing is to show a "100 or more" style when it's the max number (100) I suppose 🤔

**Comment by YannickMol** [comment]
@rijkvanzanten, can you help me with where the number of items is fetched for this? I can't find it.

**Comment by rijkvanzanten** [comment]
@YannickMol it isn't fetched separately. The API returns the o2m items as a nested array of primary keys, and it's "just" the length of that. We can't fetch the real count per o2m item, as that would mean fetching it per row (which causes a massive amount of requests / perf regression). That's why I mentioned this as the possible solution:

> The next best thing is to show a "100 or more" style when it's the max number (100) I suppose, and then fetch the "real" number on click (when we do the fetch for the nested previews) 🤔

**Comment by YannickMol** [comment]
@rijkvanzanten, I believe that currently the "real" number is also fetched by the primary key. So if we set that already to a limit of 100 when fetching the items up to 100, how could I then fetch the "real" number?

https://github.com/directus/directus/blob/ce9a6c8cf6925732134bceaff0b9dfaef831df91/app/src/displays/related-values/related-values.vue#L75-L80

**Comment by rijkvanzanten** [comment]
We can't! That's the problem 👀  

I think the only thing we can do is do "If value.count == 100" show it as "100 or more" (`100+`), and then fetch the "real" count when the dropdown gets opened? (Seeing that's a user interaction, it'll give us the chance to do some async work and requests that we wouldn't be able to do for every row automatically).

**Comment by YannickMol** [comment]
Haha we're on the same page then, so there is a need for a new request function on opening the dropdown 👍

**Comment by YannickMol** [comment]
@rijkvanzanten, I tried, but I can't figure this one out unfortunately, so un-assigning myself, hopefully someone else can get it to work!
