### ISSUE TITLE
Use interfaces for advanced filter inputs

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#3747]
Similar to https://github.com/directus/directus/issues/3731

When using an advancer filter on a field of type `date` or alike, there is no validation of the user input, leading to a server error when the string cannot be casted to a date.

This should be handled from the app ( use the already existing datetime input, or use the native html one ).

**Comment by Nitwel** [comment]
I'm not getting an error here anymore when filtering for a date with the filter value of `equal to AA`.

Having propper inputs here would be really nice but there are some drawbacks that could make this more difficult.
The width of the sidebar is very small so not all inputs would match the width instantly.
Relational fields could also cause some trouble here because we might have to add special interfaces for them too.

**Comment by rijkvanzanten** [comment]
@Oreilles What database vendor is this under?

**Comment by Oreilles** [comment]
PostgreSQL 13

**Comment by Oreilles** [comment]
Would like to get this fixed. Here's a few solutions:
- Use native HTML `date` input for `datetime` fields
- Use the `datetime` interface instead
- Validate the date format with `try { new Date(input) }` client side (in `filter-input.vue` probably)
- Do the validation server side (in `getASTFromQuery` probably) to avoid error when input is sent through the api instead of the app
- A combination of these

**Comment by benhaynes** [comment]
I think we should map an interface to each data type, so there's a way to properly enter data within filters. Any validation on top of this is even better.
