### ISSUE TITLE
Unable to create M2M relationships for directus_users

### ISSUE THREAD

**Issue by gchris** [directus/directus#3790]
Hi all,

first: Nice software ;-)
Now to my issue: I have a user collection say it is named **col1**.
Now I want to have a M2M relationship between **directus_users** and **col1**.

If I configure such a relationship from the side of **directus_users**, then the table name will be:

**directus_users_col1**

This however causes a validation fail at API level, because the API prevents clients from creating tables with names that start with **directus_**.

**Comment by benhaynes** [comment]
Yeah, that makes sense since all `directus_` collections are reserved. That said, you can uncheck the box below the junction so you can manually change that collection name to something allowed. I'll close this issue, since it's not really a problem. If you'd like to open this as a GitHub Discussion, we can track it as a possible enhancement to have Directus offer different junction names. 👍
