### ISSUE TITLE
Batch edit allowed from 2 items, but should be from 1 item selected

### ISSUE THREAD

**Issue by pstuifzand** [directus/directus#3837]
The batch edit starts to be allowed from > 1 selected items, but should be allowed from >= 1 selected items. See line 140.

https://github.com/directus/directus/blob/959872b4990aef230426a7d6a20b122740fdc10d/app/src/modules/collections/routes/collection.vue#L134-L144

**Comment by benhaynes** [comment]
Could you clarify why Batch edit should enable at `>=1` item? What's the benefit of batch editing a single item?

**Comment by pstuifzand** [comment]
Couldn't the same by said for archiving or deleting one item? This is also possible one at a time in the detail view.

Editing one item from the collection layout is just as useful as the other actions. When I'm in the mode of cleaning up the items in the collection, I just want to stay in the collection and adjust some things. All actions are available for one item, except editing. When editing one item is also available this makes the interface more consistent.

It also makes the "mass update" more visible.

**Comment by benhaynes** [comment]
Hmm, now I'm a bit confused. **Edit** is the primary action, and is enabled simply by clicking on the item within the layout view. All other actions are secondary (archive, delete, etc) — and our "batch" edit action (by definition) is a special form UI dedicated to editing multiple items.

> **Batch**: A group of records processed as a single unit

The horizontal real-estate in the header is fairly limited/precious, and I suppose that showing that button earlier doesn't seem to solve any actual issue. If anything, the button tooltip could be updated to specifically say "Batch Edit" to clear up its purple. 

Certainly open to discussing this further, but I'll close this issue as I don't see this as a bug. We can discuss here on this closed ticket, or open up a GitHub Discussion (GitHub disabled converting issues to discussions, otherwise I'd do that!).

As always, I appreciate your thoughts and feedback... we're always excited to polish the platform and make it as intuitive as possible. Quite the balancing act. :)
