### ISSUE TITLE
Switch repeater types from String -> Text -> String, displays "Select a field type" instead of dropdown

### ISSUE THREAD

**Issue by pstuifzand** [directus/directus#3855]
When I create a new column with a JSON / Repeater field, and switch to Text (or other type) and then back to String, I get the "Select a field type" message instead of the Dropdown with options.

Steps:
1. create new table
2. create new Standard field with type JSON
3. set interface to Repeater
4. edit repeater fields
5. set item type to Text (or other type)
6. switch back to String
7. Dropdown is replaced with text "Select a field type", while String is selected.

Environment:
Docker with docker compose, Postgres 12, Firefox (but also Chrome).
Directus Version: 9.0.0-rc.34

**Comment by Nitwel** [comment]
This is caused because v-form checks if the values matches the default value and if so, doesn't update the field.

https://github.com/directus/directus/blob/fbf72b32ac56d7749c45bd3c0c4fb762602f06bc/app/src/components/v-form/form-field.vue#L138-L147

I want to wait until https://github.com/directus/directus/pull/4093 gets merged to avoid unessesary merge conflicts.
