### ISSUE TITLE
Add Image Versioning

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#3862]
The image versioning is not working.

1. The issue and what you expected to happen
    
An image modified, i.e., rotated, the reverted change using the versioning should revert to the original rotation 

2. Exact steps to reproduce this issue:

- Upload an image
- Rotate the image
- Click on `revisions` and revert to the version named `Created`
- The image should be still be rotated

3. Your environment:
- AWS RDS PostgreSQL
- Directus v9.0.0-rc.34

4. Any other relevant information we might need to reproduce this issue
    - The name of the file is reverted if it is changed but no the image rotation, crop, etc

**Comment by A-Floppy-SkizSanz** [comment]
Nice input

**Comment by benhaynes** [comment]
Not really a bug, more of a feature request, as Directus never had this... but I'll leave that for @rijkvanzanten to decide. I agree it would be a great feature to add (in Discussions), shouldn't be too hard either... just need to agree on the ideal storage naming/location.

**Comment by juancarlosjr97** [comment]
Thank you for the reply @benhaynes. I have not tested this on v8, so it is good to know that it would a feature. I would have expected on the versioning to restore also the image previous state.

Probably, could be done using S3 versioning if it is enabled.

**Comment by benhaynes** [comment]
Yeah, it seems intuitive to have files be versioned and it's definitely something we want to add. We can't use anything specific to S3 since all features need to be abstracted away so they are not storage adapter specific (eg: needs to work on local filesystem too). I assume that this will be a new naming convention in the **upload** directory... perhaps with these centralized in a sub-directory to keep things clean.

**Comment by rijkvanzanten** [comment]
Yeah we'd have to store a copy of the file _before_ it was updated, and rename it in a way that lets us identify the revision it goes with 🤔
