### ISSUE TITLE
Image interface doesn't allow editing the image itself

### ISSUE THREAD

**Issue by Jonesus** [directus/directus#3869]
After the changes of commit https://github.com/directus/directus/commit/7bbce08b981c696889e037b406b5d7a9252c1df2 (release candidate 31) the image interface no longer allows users to crop/edit the images in a drawer, instead opening a drawer fields of the underlying file. Not sure if this change was intended, but at least personally I feel it's more important to be able to edit the images than their metadata if the Image interface is used for a collection.

Repro:
1. Create a collection with an image relation
2. Create an item into that collection
3. Upload/pick an image
4. Try to edit the image
5. No image editor here, only file metadata

**Comment by benhaynes** [comment]
We might want to move this to a discussion, instead of an issue. It was intentional, but it would be nice to have both. The problem is that we only have so much real-estate to work with and only 4 buttons really fit well (with the current design). 

Trying to say which of the two features will be used more won't get us anywhere. The thinking with going to the file detail page is that you can edit the image there too... so at least you get both options (though editing is one step further away).
