### ISSUE TITLE
Change revert action to insert changes in page

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3941]
Instead of having a dedicated revert action that goes "back in time", consider field reverts as standalone updates. This allows you to pick and choose fields from past and future states and inject them in the editing workflow.

\+ Add a "save as revision" action to the save button
\+ Add a "field has edits" state on the detail page

**Comment by benhaynes** [comment]
Some ideas:

* Clicking on the Revisions could either push changes directly to the form, or expand with buttons for:
    * "Insert" — Stages all the values into the main form (whatever you have permission to). If you already have unsaved changes in your form, this action would warn you about overwriting that data.
    * "Diff" — Shows the full diff in a drawer (still nice to have compared to the field-level-only diff below.
    * "Preview" — Not sure about this one, but it would be similar to what we have now... but also allow "pushing" individual field values to the parent form (not just the whole thing). Might be useful to keep this in case you're already editing the form and just want to check a previous revision value.
* Add a "Clear Changes" button to the header that only displays when changes are present.
* The Revisions count badge in the sidebar should show a spinner while it's loading. Sometimes it's not there... but only because it's still fetching the revisions async.
* There should be a new "secondary" save button in the dropdown for "Save as Revision" (working title) that only saves the revision, and not the actual parent item. These should be displayed ABOVE the current item in the revisions bar. We also need to ADD that current item, since it's not there now... clicking on this would also reset the revision inserts in the form back to the saved values.
* We should look into adding a popover/alert if the data of an item has changed since you opened it... offering to stay as-is, or refresh the page data.
* Global Changes for Fields
    * Fields or Field Labels should show if they have been updated from the saved value. Some sort of visual indicator, that would then enable...
    * A field-level diff for saved value vs current... this means that after you insert the revision into the form, you could hover over a field (or it could be an option in the field menu) label to see what changed in a popover/tooltip.
