### ISSUE TITLE
Create a Flow for Managing Existing Fields

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#3952]
As of now, when you install Directus over an existing database, or add columns directly in the database, when you go to use them in Directus you click a "manage" button that automatically turns them into their "standard" field equivalent. We need to update this to a "wizard" that allows you to configure existing relational fields properly. As of now, standard fields can not be converted to relational fields, so this is a blocker for some people.

This is technically an enhancement, but since Directus focuses on mirroring the database (including existing ones), this is a very serious issue. That is why it is flagged as a `bug`.

**Comment by raphaeltm** [comment]
Just wanted to chime in and say that I've been racking my brains trying to figure this out, so I'm glad to see it's not just that I'm not getting it. If I understand this ticket correctly, there's currently no way to map relations in an existing database to relational fields in Directus?

**Comment by benhaynes** [comment]
@raphaeltm — correct, you would have to create them in Directus too. We'll be solving this soon, but it's difficult because of database abstraction across different SQL vendors we support.

**Comment by laszlokorte** [comment]
Glad to see this will be fixed. I already considered directus for various projects in the recent years. Great to see the gigantic progress being made! 

Currently this is really a road blocker for me because my projects 200-table database with lot's of foreign keys is sadly not usable as is inside of directus.

Another issue I noted which is related:
If have `parent_id int(10) unsigned NOT NULL` column with a corresponding FK defined. (mysql/mariadb)
I can not even edit the field definition in directus at all because it seems directus does not know about `unsigned` integers and tries to change the column type to just `int` which is prevented by the DB because of the foreign key on the column referencing the parent table's primary key which is unsigned as well.

**Comment by rijkvanzanten** [comment]
@laszlokorte Totally, that'll be added and is tracked in https://github.com/directus/directus/issues/3664 🙂

**Comment by Kematia** [comment]
does this mean this will enable us to write our own "directus reflected" knex migrations/seeds?

**Comment by rijkvanzanten** [comment]
Instead of having a duplicated field setup wizard just for m2o vs standard fields, this'll be closed in favor of https://github.com/directus/directus/issues/3664. By reading the foreign keys directly from the DB, there's no need to manually mark a field as a m2o afterwards!

(This also means that https://github.com/directus/directus/issues/3664 just got high-prio 👍🏻 )

Closed in favor of https://github.com/directus/directus/issues/3664
