### ISSUE TITLE
[M2A] Reopen unsaved new item will generate an duplicated item

### ISSUE THREAD

**Issue by jianliao** [directus/directus#4188]
1. Check the screen recording for detail: 
https://user-images.githubusercontent.com/1207520/108572195-a1e28480-72c6-11eb-8c38-1ffc50856ca0.mp4

2. Detail step:
    a. Create an new item in M2A builder and save
    b. Reopen the new item
    c. Do nothing and just save
    d. A new duplicate item will be generated

3. Version: rc.42

**Comment by jianliao** [comment]
I think the root cause of this issue is at [m2a-builder.vue#L551-L553](https://github.com/directus/directus/blob/055ebcb69b54038ddb0c2acb6d2ff536a17772c2/app/src/interfaces/m2a-builder/m2a-builder.vue#L551-L553). I don't understand why a function named `editExisting` will set relatedPrimaryKey and currentlyEditing fields value as `+` to indicate creating new item.

To fix it, I have to introduce a flag - `unsaved` to editsAsStart.value to tell `stageEdits` callback not to treat it as new item.

I also want to rebuilt the items list sorting strategy.
1. Split the items into two set, one for the saved items which has sortField, the other for items which has no sortField
2. Sort the the saved item by sortField and sort the rest by $index
3. Concat the above sort results

The UI rendered result list will be saved items will always before unsaved items.

**Comment by rijkvanzanten** [comment]
> I don't understand why a function named editExisting will set relatedPrimaryKey and currentlyEditing fields value as + to indicate creating new item.

I think the confusion here comes from the fact that `editExisting` is used to edit an existing _row_ in the m2a, whether or not this item exists in the database. If this item doesn't exist yet in the database, we'll have to treat it as a "new item" in drawer-item, otherwise `drawer-item` will attempt to read the existing item from the API (which doesn't exist yet).

> I also want to rebuilt the items list sorting strategy.
> 1. Split the items into two set, one for the saved items which has sortField, the other for items which has no sortField
> 1. Sort the the saved item by sortField and sort the rest by $index
> 1. Concat the above sort results

That makes sense to me 👍🏻 Lets make sure to set the sortValue for the newly added rows correctly to, otherwise it might get funny on refreshes, as it'll sort by null-null-null, which would have unexpected results
