### ISSUE TITLE
Incorrect date value

### ISSUE THREAD

**Issue by aleksejssaburovs92** [directus/directus#4449]
Create collection, add field date, try to save it.
Popup with error appears:
 alter table `news` add `publish_date` date not null - ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '0000-00-00' for column 'publish_date' at row 1 

Version: v9.0.0-rc.45
Installation and running: CLI (npx)
DB: mysql8

<img width="543" alt="Screenshot 2021-03-09 at 20 10 35" src="https://user-images.githubusercontent.com/12848012/110517623-c4243100-8113-11eb-9aa5-eeb94d28f93f.png">

**Comment by rijkvanzanten** [comment]
Did you enable `NO_ZERO_DATE` in MySQL 8 by chance? IIRC MySQL supports 0000-00-00 as a valid default date, but I believe that mysql setting overrides it

**Comment by aleksejssaburovs92** [comment]
yes, it helped, thank you. But it would be nice, if you add somewhere in documentation point about this.

**Comment by rijkvanzanten** [comment]
Yeah totally. In this case, we could argue the API should've tried to insert `null` instead of `0000-00-00` for the date, so lets treat this as a potential bug we could fix in the API 🙂

**Comment by caiguofeng0209** [comment]
On 목요일, 3월 11, 2021 aleksejssaburovs92 ***@***.***> wrote:



yes, it helped, thank you. But it would be nice, if you add somewhere in documentation point about this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe
.

What is this ? Whoare you ? My email was been hacked !! And dont know what is it ?

**Comment by rijkvanzanten** [comment]
Closing this as it's a MySQL configuration problem
