### ISSUE TITLE
Fields not displayed in correct order 

### ISSUE THREAD

**Issue by mcammaert** [directus/directus#4454]
Using directus 9.0.0-rc.45
DB: PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc, a 758249876 p fbce33f506, 64-bit
Tested in Safari and Chrome on Mac OS X

If a collection contains 10 or more fields, the fields will not appear in the correct order when reordering the fields.
This affects both the data model view and the views for creating and updating collections.
However, the order is correctly stored in the database.

```
select id, collection, field, sort from directus_fields
where collection = 'posts'
order by id 
```

id|collection|field       |sort|...|
--|----------|------------|----|---|
47|posts     |id          |   1|...|
48|posts     |status      |   2|...|
49|posts     |created_by  |   3|...|
50|posts     |date_created|   4|...|
51|posts     |updated_by  |   5|...|
52|posts     |date_updated|   6|...|
53|posts     |title       |   7|...|
54|posts     |tags        |   9|...|
55|posts     |body        |  10|...|
56|posts     |slug        |   8|...|

<img width="951" alt="Schermafbeelding 2021-03-09 om 23 48 41" src="https://user-images.githubusercontent.com/6627/110549258-17a57780-8132-11eb-8b9f-4ffd1d311d25.png">

<img width="954" alt="Schermafbeelding 2021-03-09 om 23 48 23" src="https://user-images.githubusercontent.com/6627/110549249-15431d80-8132-11eb-90ef-b716f0cc8c6f.png">

**Steps to reproduce**

- create new collection
- add 10 or more fields
- reorder the fields

**Comment by rijkvanzanten** [comment]
Noticed something curious in that list above, it seems like it's actually sorted correctly, however, it's sorted by `sort` value as a _string_ instead of a number

Compare your above list sorted by `sort` to the screenshot:

| id  | collection | field        | sort |
| --- | ---------- | ------------ | ---- |
| 47  | posts      | id           | 1    |
| 55  | posts      | body         | 10   |
| 48  | posts      | status       | 2    |
| 49  | posts      | created_by   | 3    |
| 50  | posts      | date_created | 4    |
| 51  | posts      | updated_by   | 5    |
| 52  | posts      | date_updated | 6    |
| 53  | posts      | title        | 7    |
| 56  | posts      | slug         | 8    |
| 54  | posts      | tags         | 9    |
