### ISSUE TITLE
Feature: Define Invite URL in environment variable for flexibility

### ISSUE THREAD

**Issue by Buooy** [directus/directus#4456]
### Problem

Currently, the invite URL is restricted to two formats:

1.  URL passed into the service
2.  env.PUBLIC\_URL concatenated with `/admin/accept-invite`

This creates a problem where if the invite URL is to be set to a non-directus service. e.g. a standalone SPA on a different (sub)domain name,  some custom code has to be written to inject the that URL. This is unwieldy. 

Otherwise, the user is stuck with /admin/accept-invite as a route.

Please refer to the following line

[https://github.com/directus/directus/blob/291643e0b429c8ae4dda59355c50303c433a59bf/api/src/services/users.ts#L89](https://github.com/directus/directus/blob/291643e0b429c8ae4dda59355c50303c433a59bf/api/src/services/users.ts#L89)

### Solution

Introduce a new environment variable called `INVITE_URL`, which allows the user to set an FQDN with a relevant subdirectory e.g. https//subdomain.example.com/invite

The current line

`const inviteURL = url ?? env.PUBLIC_URL + '/admin/accept-invite';`

can be easily modified to 

`const inviteURL = url ?? env.INVITE_URL ?? env.PUBLIC_URL + '/admin/accept-invite';`

This will allow for backward compatibility.

**Comment by rijkvanzanten** [comment]
The problem here is that there's a case to allow for both at the same time. By using a single env-var to override the admin path, you disable inviting into the admin app completely.

For example:

You have an external SPA in which you let users register, so you'd like the invite URL to point to your own SPA in order to have a branded registration flow in your app for app role users.

Meanwhile, you're using Directus as a manager role, and would like to invite a coworker as another manager in the platform. This registration should be handled by the Directus app, and thus go through the "regular" /admin/accept-invite flow.


I think the preferred solution from my end is to have to have a specified allow list for custom URLs in the environment variables, similar to reset password 👍🏻
