### ISSUE TITLE
files.create hook fires before the file is written

### ISSUE THREAD

**Issue by dmtkpv** [directus/directus#4728]
### Hook:
```javascript
const path = require('path');
const fs = require('fs')

module.exports = function ({ exceptions }) {

    return {

        'files.create' ({ payload }) {

            // 1. filename_disk is missing
            const record = payload[0];
            console.log(record.filename_disk) // undefined


            // 2. file does not exist
            const filename_disk = record.id + '.' + path.extname(record.filename_download);
            const exists = fs.existsSync(path.join(__dirname, '../../../uploads', filename_disk));
            console.log(exists) // false

        }
    };
};
```
### Environment:
- Directus 9.0.0-rc.51
- MySQL 5.7

**Comment by rijkvanzanten** [comment]
This is expected behavior currently. The file record in `directus_files` is created _before_ the actual file is uploaded to the storage adapter and then updated once the file is done processing with additional information. (In order to generate a UUID and check permissions for it during creation. 

I think the best way forward here is to prevent it from firing `files.create` and `files.update` during the upload step in favor of having a single new `files.upload` hook
