### ISSUE TITLE
App keeps getting slower as more frontend extensions are used

### ISSUE THREAD

**Issue by sabinehoi** [directus/directus#4834]
When having many frontend extensions, it takes a real toll on the app's initial load time. And the more extensions you have, the longer it will take to load the app - at a much faster pace than if you were just developing the same vue app 'natively'.

I have about ~12 extensions (interfaces, layouts, and modules), and because the app frontend has to make `/extensions/[type]/[name]/index.js` requests for each of my extensions, it takes over 5s for the app to load, with caching on (time from seeing the white loading screen to seeing the app - about 12s without cache - and 1s without extensions).

Some workarounds I can think of:

- Reduce overhead of multiple requests by making it so all the extensions can be returned all at once with just 1 request from the API (eg. squeeze them into a single json, should be okay since you do always need them all anyway.)
- Look into making rollup build multiple extensions into 1 file
- Harder to do: load the extensions as they are needed (eg. hot-load module extension when user navigates there, or specific interfaces depending on viewed form) - not sure if possible wiht your current setup tbh
- Show some loading screen in the very initial phases of loading the app to make it less frustrating (currently it is just a white blank screen, with the window title "Loading...")
- More aggressive cache (eg. set a max age?)

With the advent of the marketplace I can easily see people having dozens of extensions loaded, so I think this is worth investigating :)

**Comment by fballan93** [comment]
I know this is off topic but i would really appreciate it if you can share an example of a module or a layout. the documentation is lacking extensively in this regards

**Comment by Nitwel** [comment]
I think what could help there and would be really easy to do is to load all custom extensions at the same time which would reduce the time to the extension that loads the longest. Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
> Harder to do: load the extensions as they are needed (eg. hot-load module extension when user navigates there, or specific interfaces depending on viewed form) - not sure if possible wiht your current setup tbh

We used to do this in v8 actually, but it was a pretty bad experience, as the page would jump all over the place while the individual pieces where being loaded. That being said, there must be a happy medium where we load some things blocking, while others async.

Generally speaking, based on what we've seen in previous versions, it's preferable to load most things up front, and then have a smooth user experience after that. I think this is a big improvement in that regard:

> Show some loading screen in the very initial phases of loading the app to make it less frustrating (currently it is just a white blank screen, with the window title "Loading...")

**Comment by benhaynes** [comment]
I agree. In an ideal world, we load the required/keystone pieces/extensions on load, and then async the others directly after, but before they are specifically requested.

**Comment by WoLfulus** [comment]
*Overengineering warning*

I did something a while ago (not related to Directus) that would "solve" this, but it would require Directus app to become an application (manifest.json). Basically I was prototyping an app that renders responsive images from templates (js css and html), and since I wanted people to be able to publish new templates, I wanted to publish them as zip files instead to cut down storage and bandwidth cost.

In this case I did solve this by using request interceptors. The app would download the zip file from the server with literally all the assets (containing the whole file structure that would otherwise be requested individually by the browser), and I forced a response in the interceptor with the contents I got from that zip file.

I imagine this would work nicely for the whole bundle of extensions, downloading them all at once, in a single connection/request and compressed. It would take more cpu time because of compression but that's nothing compared to the amount of roundtrips needed for hundreds of individual files.

Just a thought :shrugs:

**Comment by nickrum** [comment]
Another approach would be to use a bundler like Rollup to bundle all extensions on startup of the API server. Compression could then be handled by the http server. This would also make it easy to support "native" typescript extensions (I think someone mentioned this on Discord).
