### ISSUE TITLE
Can't add multiple records in O2M field

### ISSUE THREAD

**Issue by hubalt** [directus/directus#4836]
Steps to reproduce (anything not mentioned was left as default):
- create data model "articles"
- create data model "tags", create field "tagname" (string + requires value), interface = text input, display = raw value
- create "tags" field in "articles" as one-to-many (articles.id->tags.id), interface = one to many, display = related values
- create item in "articles", for the "tags" field select "Create New" and enter "tag1" as tagname, select "Create New" again and enter "tag2" as tagname. Now both "tag1" and "tag2" show up under the tags field. Save item.
- select the recently created article and only "tag2" is present under the "tags" field. Also, only "tag2" is present in the "tags" collection.

Expected behavior:
Created article should have both "tag1" and "tag2" in its tags field.

---

### Project details
Directus Version: 9.0.0-rc.53
Environment: production
OS: Linux 5.4.0-62-generic
Node: 14.15.4

**Comment by hubalt** [comment]
btw I deployed this via the Digital Ocean marketplace so I guess postgres is being used.
>  PostgreSQL 12.5 (Ubuntu 12.5-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

**Comment by rijkvanzanten** [comment]
There's two things here that draw my attention:

1) This is most likely intended to be a many-to-many instead of a one-to-many (otherwise you'd only be able to assign a tag to a single article at a time)
2) In `articles.id->tags.id`, you wouldn't want to save the article's ID _on top of_ the tag's ID. You'd want to save `articles.id` in a new field, like `articles.id->tags.articles_id` 

Try setting this up as a many to many. You can rely on the automatically added fields:

<img width="626" alt="CleanShot 2021-04-05 at 16 50 54@2x" src="https://user-images.githubusercontent.com/9141017/113625795-6100be00-962f-11eb-95e9-df70e428032c.png">

**Comment by rijkvanzanten** [comment]
If that's still giving you troubles, we can reopen and investigate :)

**Comment by hubalt** [comment]
@rijkvanzanten thanks for your patience! Due to my lack of SQL knowledge, I thought O2M was implemented as a foreign key array but apparently that isn't a thing. M2M worked as expected when I last tried; will stick to that. Thanks again.
