### ISSUE TITLE
datainsert 

### ISSUE THREAD

**Issue by champak-chopda** [directus/directus#4875]
whenever insert data in directus at that time data do not  insert in to my database

**Comment by Nitwel** [comment]
You have to give a bit more insight on how your setup looks like. What version of Directus, which DB, how did you configure it, any errors? 😉

**Comment by champak-chopda** [comment]
is there any web-hook to get data from directus to phpmyadmin

**Comment by benhaynes** [comment]
phpmyadmin mirrors the database. Directus mirrors the database. It sounds like you're configuration is wrong, because anything entered via Directus would be in the database and phpmyadmin (and vice versa).

Please provide more information about your configuration if you'd like us to help troubleshoot.

**Comment by champak-chopda** [comment]
how to know which version used directus?

**Comment by benhaynes** [comment]
Nav sidebar of settings page.

**Comment by champak-chopda** [comment]
ok after

**Comment by champak-chopda** [comment]
directus versaion use:8.6.2
mysql for our databse version use:5.7.33
phpmyadmin version:7.2.24
