### ISSUE TITLE
LocalStorage auth_token, auth_refresh_token, and auth_expires are not removed on expiration

### ISSUE THREAD

**Issue by finly** [directus/directus#4883]
1) The issue and what you expected to happen
- In old SDK, those 3 tokens are removed when we leave the browser for the period time of ACCESS_TOKEN_TTL set in the Directus API. But in this new SDK, those tokens still persist in localstorage even with refresh. I always get `Token expired` error because my app still trying sending the old token to the API url. I need to manually remove them to fix it. Only, manual `await directus.auth.logout()` clears the tokens.

My current workaround is to always run the `directus.auth.refresh` along with the first time set in the login option.

2) Exact steps to reproduce this issue
- Update Directus to the latest v9.0.0-rc.54
- Replace @directus/sdk-js to @directus/sdk
- Rewrite the auth method as described here: https://docs.directus.io/reference/sdk/#auth
- I am using mode: 'json' and LocalStorage
- Set the API ACCESS_TOKEN_TTL to 1 minute so I can see the issue faster

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.54
    Which DBMS are you using: MariaDB
    Which deployment are you using: npx
    What browser are you using: Chrome 89

**Comment by joeinnes** [comment]
Confirm I am also seeing this bug in RC 57. 

This can be a fairly big issue as the `Authorization` header is set with the `refresh_token` even when trying to log in. This means that even with correct credentials, it's impossible to log in without manually clearing the local storage.

I'm not sure whether it would be best to open a separate issue for this, it doesn't make sense to reject a log in (with user credentials) because a `refresh_token` has expired.

**Comment by rijkvanzanten** [comment]
> I'm not sure whether it would be best to open a separate issue for this, it doesn't make sense to reject a log in (with user credentials) because an access_token has expired.

This sounds like a good improvement in the API indeed @joeinnes. Wanna open a PR for that?

**Comment by joeinnes** [comment]
The more I think about it, the more I think that maybe it *does* make sense for the server to reject a request with an invalid or expired token, and it should be the client's responsibility not to send a request with a bad token (I think this goes hand in hand with #4979).

If this should be implemented in the API, there are a few design questions to answer:

1. Should it just be a few whitelisted routes which don't check tokens (eg: login, logout, register, reset password,...?)
2. If we're not forcing clients to send 'valid' requests to all endpoints, what behaviour should other resources have? Should we replace error throwing all together by just handling requests with bad tokens as though they were sent without a token?

**Comment by rijkvanzanten** [comment]
> Should it just be a few whitelisted routes which don't check tokens (eg: login, logout, register, reset password,...?)

I would think so, yes

> If we're not forcing clients to send 'valid' requests to all endpoints, what behaviour should other resources have? Should we replace error throwing all together by just handling requests with bad tokens as though they were sent without a token?

That.. last bit feels very tricky to me. It'll be impossible to know whether or not it's a token problem, or an authentication problem. It would also mean that we'd have to add a separate route that'll tell you whether or not a token is valid 🤔

**Comment by BartCRMstrategen** [comment]
I have the similair issue with:
@directus/sdk 9.0.0-rc.59
And directus 9.0.0-rc.59

Basicly the tokens do not refresh and when you press f5 and try to login, you have to clear your application cache first before you can sign in again.

Code:
import { Directus } from "@directus/sdk";

const host = "Directus_host_here";

const directus = new Directus(host);

Code that i try to run to check if a user is signed in:
await directus.users.me.read();
If it throws an error, the user is not signed in, otherwise he is.
After this happend, the user can try to login but cannot login unless he clears his cookies
Also, the tokens are not refreshing after 15m, while this should happen
