### ISSUE TITLE
displaying the M2O, O2M, and M2M layout when on ( View Only ) mode dimensions are not proper 

### ISSUE THREAD

**Issue by fballan93** [directus/directus#4915]
The Layout default dimensions are very small when you give a user a view only access while it should have the normal default view layout 

**How it look like for a user with admin or all access**

![image](https://user-images.githubusercontent.com/9093101/114077083-1641a900-98b0-11eb-9792-f1b1c92fec0e.png)

**how it look for a user with view only access** 

<img width="901" alt="CleanShot 2021-04-08 at 21 15 16@2x" src="https://user-images.githubusercontent.com/9093101/114077216-396c5880-98b0-11eb-8886-9d55af928ba6.png">

my environment:
    directus v9.0.0-rc.55
    DBMS : (MySQL 8)
    deployment mode : npx
    Browser : Chrome and Edge

**Comment by benhaynes** [comment]
This will be closed by the following since we'll be switching to a Display Template title for these relational items. @rijkvanzanten wants to wait on this PR and add pagination... but maybe we can consider doing part of this early to solve these issues.

PR: https://github.com/directus/directus/pull/4093
Issue: https://github.com/directus/directus/issues/3647

**Comment by rijkvanzanten** [comment]
Closed in favor of #3647
