### ISSUE TITLE
String Length limitation doubles for collection model update

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#5236]
Every time i make som update to the collection model does the length double from the original value which is a bit troublesome when you try to limit the length of the string ;) This isn't just a visual bug either as it changes how much you can type in the collection item aswell. :/ 

2) 
- Create a new collection 
- Add a string field with a limitation of e.g 24 characters
- Save the field
- Note: At this point can you see that the value saved was 48 not 24
- Change the Note to whatever (e.g "TODO")
- Save
- Now it is 96

![image](https://user-images.githubusercontent.com/2140448/115957541-58e7c000-a503-11eb-8778-78faa3f1b286.png)

3)
Directus 9.0.0-rc.60 (A completely fresh install)
Microsoft SQL server
Npx
Chrome version: 90.0.4430.85

4) 
A db dump can be provided if necessary :)

**Comment by rijkvanzanten** [comment]
Weird!

**Comment by rijkvanzanten** [comment]
Ahhh Knex defaults to `nvarchar` in MS SQL for `string` types. `nvarchar` saves every character in 2 bytes instead of 1, `max_length` in SQL returns the maximum available bytes which in turn means that `max_length` is returned as double the actual available characters in the API, making the app default to the "previous" (wrong) value of 2* the actual character length

**Comment by TheAzack9** [comment]
Ooof, that did not sound fun to debug 😅 Odd interaction 🤔
