### ISSUE TITLE
Empty "field" for RECORD_NOT_UNIQUE

### ISSUE THREAD

**Issue by iksent** [directus/directus#5330]
1) Trying to create new article: `/items/article/?access_token=123...`

```
{
  "status": "draft",
  "translations": [
    {
      "languages_code": "ru-RU",
      "title": "Test article",
      "slug": "test-slug" <<<<<< This field should be unique
    }
  ]
}
```

2) Response:

```
{
    "errors": [
        {
            "message": "Field has to be unique.",
            "extensions": {
                "code": "RECORD_NOT_UNIQUE",
                "collection": "article_translations_slug_unique",
                "field": null, <<<<<<<<< Field is empty
                "invalid": "test-slug"
            }
        }
    ]
}
```

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Linux 5.4.0-66-generic
Node: 10.19.0

**Comment by rijkvanzanten** [comment]
What database is this on @iksent ?

**Comment by rijkvanzanten** [comment]
Based on previous issues, I believe you're on MariaDB / MySQL. Due to the way the error messages are structured in MySQL, it's impossible to extract the offending field name. We do a sort of best effort by relying on the key name, but only if it matches Knex's structure:

https://github.com/directus/directus/blob/a4e2c499e8ba47fd50dc1c8f5e1064aeb89dbd71/api/src/exceptions/database/dialects/mysql.ts#L51-L60

I'd love to hear your thoughts on how to improve this, as this is a bit of a technical roadblock for MySQL specifically

**Comment by iksent** [comment]
Oh, why this was not auto-added from a directus' bug report...

Server version: 10.5.9-MariaDB-1:10.5.9

**Comment by rijkvanzanten** [comment]
Cause we don't have an accurate way to pull that information for every database driver (yet) 🥲
