### ISSUE TITLE
Add default display template for directus_files

### ISSUE THREAD

**Issue by sebj54** [directus/directus#5364]
Hi there,

I just updated to RC61, but it seems to have broken the multiple files display: pictures are not shown.

![image](https://user-images.githubusercontent.com/5880435/116548493-94fc9580-a8f4-11eb-9558-b0c30b5bf711.png)

When I edit the field, option "Image" is not shown either in "interface" and in "display". This option is shown for single file fields, but not for multiple files fields.

Single file field (sorry I'm French! :grin:):

![image](https://user-images.githubusercontent.com/5880435/116548856-18b68200-a8f5-11eb-8e47-6156e75beeb9.png)

![image](https://user-images.githubusercontent.com/5880435/116548903-24a24400-a8f5-11eb-9762-af057ba87801.png)

Multiple files field:

![image](https://user-images.githubusercontent.com/5880435/116548981-3ab00480-a8f5-11eb-9db2-1f35253eaf56.png)

![image](https://user-images.githubusercontent.com/5880435/116549011-44d20300-a8f5-11eb-8c91-93100f936e8b.png)

Let me now if I can help by testing something :)

**Comment by domdus0** [comment]
For the multiple files field -> Interface - you need to click on the option (Many to Many) which allows you to configure the display template.

Choose the fields, seperate them if you want with <blank_space> or e.g. " - " (see image)
![image](https://user-images.githubusercontent.com/73621574/116551872-a8116480-a8f8-11eb-8dc8-d4c94c36d2bd.png)

This:
![image](https://user-images.githubusercontent.com/73621574/116552594-7f3d9f00-a8f9-11eb-9f9e-dac7a31805bc.png)

Results in: 
![image](https://user-images.githubusercontent.com/73621574/116552700-9a101380-a8f9-11eb-994c-242aae904985.png)

**Comment by sebj54** [comment]
Thanks for the information! 

I didn't know it would display the thumbail like this, it's very good to know. 

I was not sure but I thought it has changed in the latest versions, it seems I was wrong!

**Comment by ViniciusGrippe** [comment]
Hi! Enjoying this topic I want to ask about the field Multiple Files. Since of rc.61 the button to Add file turns to Create New, this make me preclude Add new File, the popup open is a form with inputs, before the popup was a Drag&Drop File, like the photos:

Multiple files on rc.59:
![](https://i.imgur.com/4Y8Te30.png)

When I click in "Add New" 
![](https://i.imgur.com/mBXAIB3.png)

Multiple files on rc.61:
![](https://i.imgur.com/J8K7UFr.png)

When I click in "Create New" (Criar Novo)
![](https://i.imgur.com/NGs3Sww.png)

Somebody knows if this is a bug? or change the way of use this field?

**Comment by domdus0** [comment]
Hi,

yes that seems to be a new bug which has been noticed here,: (introduced by rc.60) 
https://github.com/directus/directus/issues/5246
