### ISSUE TITLE
Support custom JWTs as static token

### ISSUE THREAD

**Issue by Adri-Glez** [directus/directus#5598]
1) I try to access to oas especification (/server/specs/oas?access_token=XXX...) but I retrieve a invalid credentials error:
{"errors":[{"message":"Invalid user credentials.","extensions":{"code":"INVALID_CREDENTIALS"}}]}
I tried with admin user and also I created a new user with custom role I am using the latest version V9
I lost a lot of time without finding that the error was because of the token length.

2) How reproduce the error:
2.1)Create a user o change a Existing user and define a token with a long value like: 
eydfdsget65wv6556bDFHFGDHewrv.seatcweWER.sdfsfsadfsdw4534dsdr3fvxcbvcbtt.w35vdfg4ddfgwre435weDSGGFDGDFWEdssgdsgdsDHFG.5324512sdfsdfdsfsdfsaffsa_sdfw3333MP93_9983333 
 
2.2)Access to the api with the token:
/server/specs/oas?access_token=eydfdsget65wv6556bDFHFGDHewrv.seatcweWER.sdfsfsadfsdw4534dsdr3fvxcbvcbtt.w35vdfg4ddfgwre435weDSGGFDGDFWEdssgdsgdsDHFG.5324512sdfsdfdsfsdfsaffsa_sdfw3333MP93_9983333

2.3) you get a invalid credentials error: 
 {"errors":[{"message":"Invalid user credentials.","extensions":{"code":"INVALID_CREDENTIALS"}}]}

3) Your environment:
    Directus v9.0.0-rc.62
    DBMS : MySQL 8
    Docker deployment.
    Browser: Chrome 90

4) Solutions:
    a) Validate le token length when create/update a User
    b) Allow longest tokens accesing by the api: ?access_token=XXX...
    c) Showing a more accurate error when using a long token. It could be: {"errors":[{"message":"access token too long","extensions":{"code":"TOKEN_LONG"}}]}

**Comment by rijkvanzanten** [comment]
@B-Esmaili This sounds unrelated to the original issue 🤔 

I can't say anything about external tutorials from an unknown source, especially not if it's related to another software stack completely..

**Comment by B-Esmaili** [comment]
@rijkvanzanten  Could you please tell me which part of my comment is off-topic? Why you hide my comment rather than answering it? Is this the way you wanna support your product?

**Comment by rijkvanzanten** [comment]
> Could you please tell me which part of my comment is off-topic?

The whole thing! The original issue here is about Directus not supporting a custom JWT under the Token field of Users, and you ask about the oAuth flow using NextJS, which is unrelated to me.

> Why you hide my comment rather than answering it?

I'm hiding it, because it's not related to the original issue, so will cause confusion for people finding the issue.

I did answer it though. My answer was: I don't know. You're asking if you can apply the information from a tutorial about Strapi on a third party blog to something in Directus. I don't know anything about the internal workings of Strapi nor this blog you shared.

> Is this the way you wanna support your product?

I answer questions, fix bugs, and release new features all for free. Triaging issues, and maintaining a clear overview of the history of comments and information in issues is a big part of that. Is that how I want to support Directus? Absolutely yes.
