### ISSUE TITLE
Filtering Fields or Collections in GraphQL

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#5627]
rc64, postgres, docker.

I am writing some internal staging tool and ran into this issue. I want to have a query that gives me all fields for a collection. To my surprise, directus_fields (fields in the system endpoint), doesn't support filter, sort, limit etc (collection doesn't either).
I discovered the query `fields_in_collection`, but I can't get that to work either, neither prefixed with directus, not without it, nor with my own collections I can get it to return any results:

```
{
  fields_in_collection(collection: "directus_files") {
    field
    meta {interface}
  }
}

{
  "data": {
    "fields_in_collection": {
      "field": null,
      "meta": null
    }
  }
}
```
Its really strange, as its the same result for whatever string I enter, existing collection or not.

"collections_by_name" works, with the directus prefix, as I would expect, but that doesn't give me the fields.

what is the reason that I can't use normal filters on these two models? and am I using the fields_in_collection query wrong?

**Comment by rijkvanzanten** [comment]
`fields_in_collection` should work as expected. That being said, not being able to filter on collections/fields/relations is a known limitation at this time.

> what is the reason that I can't use normal filters on these two models?

The reason is that we rely on SQL queries to do the filtering, but half the data in those models doesn't come from regular rows in the database, so they can't be filtered on using the regular filtering setup used elsewhere. We're working on a "filter an existing array of json object using the regular query structure" method to apply after the fact on these results, but until that's a thing, there's no filtering for collections/fields/relations 👍🏻

**Comment by MiniDigger** [comment]
Ah I see, thanks for that. The fields in collection query is prolly good enough for most usecases anyways.

**Comment by azrikahar** [comment]
> directus.fields.[readAll](https://github.com/directus/directus/blob/1ef17c2ed29f05959d887c6dc624b01662c771f0/api/src/services/fields.ts#L70)('foo') from the js sdk returns all fields in the db, non just those of `foo`
> 
> @rijkvanzanten

@wc-matteo  I believe there is a misunderstanding here. `readAll` does not accept any arguments (so `'foo'` is technically ignored in your current example) as it does read all fields within the db. Link to source code as reference: https://github.com/directus/sdk/blob/c9ef0a0f5b1f25e51547f77239e3b3311d9f681c/src/handlers/fields.ts#L30-L33

`readMany('foo')` (which does accept a collection name as it's argument) should be what you are looking for. Link to source code as reference: https://github.com/directus/sdk/blob/c9ef0a0f5b1f25e51547f77239e3b3311d9f681c/src/handlers/fields.ts#L24-L28
