### ISSUE TITLE
Advanced Filter - Filtering related collection boolean value doesn't work

### ISSUE THREAD

**Issue by crhampton1** [directus/directus#5638]
I have a collection that uses a boolean value in a related collection. When I try to do an advanced filter from the app on the parent collection, the item shows up regardless of whether my filter is looking for true or false in the child collection. 

See images below:

![Screen Shot 2021-05-12 at 1 26 46 PM](https://user-images.githubusercontent.com/1928925/118018401-b82c3980-b325-11eb-9ac6-8059c32069eb.png)

![Screen Shot 2021-05-12 at 1 27 17 PM](https://user-images.githubusercontent.com/1928925/118018449-cc703680-b325-11eb-9d8b-b3e3b9a3aa4c.png)

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 4.4.0
Node: 12.22.1

**Comment by MortenHofft** [comment]
Hello - I just installed from npm. It looks great. Thank you.

I can uncheck a boolean filter, but it has no effect. I'm on 9.0.0-rc.80

**Comment by MortenHofft** [comment]
Turns out is has an effect, but only in some cases. I assume that adding a boolean filter that isn't checked counts as not setting it and hence include everything? But it is really valuable to be able to search for FALSE values.

<img width="1168" alt="Screenshot 2021-06-23 at 14 23 30" src="https://user-images.githubusercontent.com/6759267/123095882-d14cfd80-d42e-11eb-8ce9-7b3d7d046172.png">
<img width="1182" alt="Screenshot 2021-06-23 at 14 23 39" src="https://user-images.githubusercontent.com/6759267/123095894-d3af5780-d42e-11eb-854e-b5a26db833ba.png">

**Comment by benhaynes** [comment]
Hmm, `_eq` untoggled should definitely filter out enabled booleans, right @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Yes. I'm assuming it's currently toggling between `null || false` / `true`
