### ISSUE TITLE
Access token not being appended to images uploaded to WYSIWYG field

### ISSUE THREAD

**Issue by dayvista** [directus/directus#5920]
# What's going wrong:

Uploading an image in the WYSIWYG field results in a broken link.

When opening the broken image in a new tab, I get this error:

```
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}
```

I expected the image to appear in the WYSIWYG field instead of a broken image link symbol.

The image is uploading properly, it's just the link that is broken. I know this because I can take the access token from the URL of another image and paste it at the end of the WYSIWYG image's URL.

**It appears that the access token is not being properly appended to images uploaded through the WYSIWYG editor.**

Image uploads work everywhere else in Directus, including updating the project logo, in dedicated Image fields, etc. I tested `local` and `s3` storage options and the issue occurs with both.

## Reproducing the issue:

Attempt to upload an image in a WYSIWYG text field.

To at least access the image, right click a working image in Directus and `open image in new tab`. Find the query string in the URL that begins with `?access_token=`. Copy that entire string. Go back to the broken image in the WYSIWYG editor and `open image in new tab`. Paste the copied query string at the end of the URL and press enter. The image will load.

## Environment:

- Directus v9.0.0-rc.69
- Postgres 12
- Docker
 - Chrome 90.0.4430.212

## Other variables:

- I'm using S3 buckets through both Wasabi and DigitalOcean.

**Comment by dayvista** [comment]
![cms1](https://user-images.githubusercontent.com/58375683/119897828-3b40b880-befe-11eb-8fff-8d06d2ccd331.png)

----

![cms2](https://user-images.githubusercontent.com/58375683/119897835-3f6cd600-befe-11eb-87c3-605f123cf55c.png)

----

![cms3](https://user-images.githubusercontent.com/58375683/119897846-4267c680-befe-11eb-8289-aca11ab0d1fb.png)

----

![cms4](https://user-images.githubusercontent.com/58375683/119897860-45fb4d80-befe-11eb-9a28-0e8cb179e816.png)

**Comment by dayvista** [comment]
![cms1](https://user-images.githubusercontent.com/58375683/119897948-60352b80-befe-11eb-981c-03434467b866.png)

----

![cms2](https://user-images.githubusercontent.com/58375683/119897955-63301c00-befe-11eb-9f50-d5525ec18a09.png)

----

![cms4](https://user-images.githubusercontent.com/58375683/119897962-66c3a300-befe-11eb-8861-60db7103f2e8.png)

**Comment by dayvista** [comment]
![cms1](https://user-images.githubusercontent.com/58375683/119898062-878bf880-befe-11eb-9825-6fd2d8644f32.png)

----

![cms2](https://user-images.githubusercontent.com/58375683/119898067-8a86e900-befe-11eb-9861-3ebe78869489.png)

----

![cms4](https://user-images.githubusercontent.com/58375683/119898075-8ce94300-befe-11eb-9077-600e7de41ccb.png)

**Comment by rijkvanzanten** [comment]
This is a known limitation in TinyMCE. I haven't been able to add a token to the <img> in the HTML without it being saved to the database as well 😵‍💫. If you actually want to save the HTML with a token included, you can use the Token interface option

**Comment by rijkvanzanten** [comment]
I think the next best thing would be to inject if with your local users token at all times, and then strip it out/add it back in right after/before staging the change 🤔

**Comment by AKockWorth** [comment]
Having the access token stripped (in a hook?) seems like a good idea. I just checked and the access token does not get updated if the field settings get updated. It'd be very easy to make a bit of a mess as a content editor if static tokens need to be reset, or if an image uploaded through one WYSIWYG field is re-used in a different WYSIWYG field and it takes the access token along with it. I saw that the static token was added to the interface setting quite deliberately, but I have an idea of a different way of managing permissions for images uploaded through the WYSIWYG editor.

Would it be possible to, in the interface settings, specify either a tag or a folder that must be used for all images either uploaded OR re-used in the relevant field? This way we can use the role permissions mechanism to decide who gets to see the asset (e.g. `{ "folder": { "_eq": "some-uuid" } }`). For the average content editor it would be too much to ask for them to manage the permissions, so if they re-use an image from the asset library, it would be best if Directus could force/assure that that file/image also complies with the WYSIWYG interface setting. In that case, adding a tag would be best, because you can easily add a tag to a file, while a file can only be in one folder at a time. I just tested it, and the permissions can indeed be controlled through tags `{ "tags": { "_contains": "some-tag-label" } }`

**Comment by egeozcan** [comment]
could the admin UI automatically append the current access token to all asset links? it could be just 2 lines of js, or a service worker if one wants to implement it properly

people using directus as a data source can append it on access and/or use a proxy, rewriting the url
