### ISSUE TITLE
computed field formula seen as default value

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6083]
and this causes errors in directus in case the computed data type does not match the formula data type

I should have time to give it a go myself tomorrow. I would just remove computed formulas from being seen as default values

---
```
mssql 2016 / v9.0.0-rc.73
```

**Comment by wc-matteo** [comment]
btw are sql computed field supposed to show up in directus?

**Comment by rijkvanzanten** [comment]
> btw are sql computed fields supposed to show up in directus?

No, similar to Views, those aren't officially supported (yet).

The question now becomes: 
Is it easy (enough) to officially support these "virtual" / computed fields as readonly, or should we just hide them away for the time being until we can support them 🤔

**Comment by wc-matteo** [comment]
good question .-.

I'll think about it and do some research and come back with my findings

**Comment by rijkvanzanten** [comment]
Seems like the database abstraction layer we rely on (`knex`) currently doesn't support creating generated columns cross vendor, so it might be a little more in-depth than we'd hoped it to be.. (same goes for views by the way ;_; )

**Comment by wc-matteo** [comment]
couldn't directus support computed columns without the option to create them? One big tings directus has I think is its ability to operate on an existing schema. Would there be issues with migrations?

**Comment by rijkvanzanten** [comment]
We theoretically could, yeah, though I'd rather do it "properly" and officially support views / generated columns "both ways" 🤔

**Comment by Oreilles** [comment]
Computed columns are just like other columns, they're just readonly so marking them as that should be enough. (I have several in my collections and they work just fine, I just made them readonly manually ).

I choosed to use the `default_value` field to store the computed column `generation_expression` in `knex-schema-inspector` because a computed columns cannot have a default value, and because both should only handled by the database, not inserted by directus.

**Comment by rijkvanzanten** [comment]
> I choosed to use the default_value field to store the computed column generation_expression in knex-schema-inspector because a computed column cannot have a default value, and because both should be handled by the database, not inserted by directus.

Should we make that more explicit? Sounds like we might want to add `generation_expression` as a dedicated field there, to avoid any and all confusion around what we're looking at 🤔

**Comment by Oreilles** [comment]
> > I choosed to use the default_value field to store the computed column generation_expression in knex-schema-inspector because a computed column cannot have a default value, and because both should be handled by the database, not inserted by directus.
> 
> Should we make that more explicit? Sounds like we might want to add `generation_expression` as a dedicated field there, to avoid any and all confusion around what we're looking at 🤔

From the database pov they behave the same and are mutually exclusive, so I think known that it `is_generated` is enough - but surely there's no harm in making it more explicit -  we'd just have to handle it properly in the application :)

**Comment by rijkvanzanten** [comment]
Fair enough!

**Comment by wc-matteo** [comment]
this issue happens specifcally when using the computed field in a relationship (m2o here). The computed field respresents a fk. It all works but when I open an item of the collection this error pops up:

```json
{
  "errors": [
    {
      "message": "select top (@p0) [Test].[Name], [Test].[Id] from [Test] where [Test].[Id] = @p1 order by [Test].[Id] asc - Conversion failed when converting the nvarchar value '[dbo].[my_column_computed_expression]()' to data type int.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
}
```

`@p1` should be the fk while Test.Id is the pk. @p1 should have the value of the computed expression, not the computed expression itself

**Comment by wc-matteo** [comment]
> Should we make that more explicit? Sounds like we might want to add generation_expression as a dedicated field there, to avoid any and all confusion around what we're looking at 🤔

probably this dedicated field should be read-only as well since, at least for mssql, you can't edit the formula from directus

**Comment by Oreilles** [comment]
> > Should we make that more explicit? Sounds like we might want to add generation_expression as a dedicated field there, to avoid any and all confusion around what we're looking at 🤔
> 
> probably this dedicated field should be read-only as well since, at least for mssql, you can't edit the formula from directus

Oh that's another thing, as opposed to default values, generated expressions cannot be modified for any vendors to my knowledge.

**Comment by wc-matteo** [comment]
Another error, again using the computed as fk (m2o). It tries to insert a value into the computed column.

```json{
  "message": "insert into [Test] ([Foo]) values (@p0) - The column \"Foo\" cannot be modified because it is either a computed column or is the result of a UNION operator.",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

I think it's really worth it to support computed columns in directus and shouldn't be _that_ hard. I'll see what I can do

**Comment by wc-matteo** [comment]
> the errors I mention happen specifically when using the computed field in a relationship (m2o here). The computed field respresents a fk. It all works but when I open an item of the collection this error pops up (hiding the field makes the error go away)

in v86 hiding the field doesn't prevent the error anymore. So every time someone opens the affected collections, they receive an error dialog. Any ideas? @rijkvanzanten 

The error is:

``` Conversion failed when converting the nvarchar value '[dbo].[my_column_computed_expression]()' to data type int.```

basically it's trying to covert the computed column formula **name** into the column value. Like it would do if it was a default column value.

**Comment by rijkvanzanten** [comment]
Odd, afaik it's using the `generation_expression` as returned by MS SQL:

https://github.com/knex/knex-schema-inspector/blob/77b0ae749c8bfcadb1c177c9e5b819815ae02da8/lib/dialects/mssql.ts#L35-L37

**Comment by wc-matteo** [comment]
yes, but `rawColumn.generation_expression` is the result of the expression or the expression itself? Cause it seems like it's the latter

**Comment by rijkvanzanten** [comment]
@Oreilles, thoughts on the above?

**Comment by Oreilles** [comment]
`rawColumn.generation_expression` absolutely is the expression itself.

Concerning the error:

    Conversion failed when converting the nvarchar value '[dbo].[my_column_computed_expression]()' to data type int.

I've said it before, but the app should not send the `default_value` (whether it is a default value or a generation expression) to the database as a value, because it can contains SQL expression that must be evaluated - and aren't values.

The problem with supporting generation expression is exactly the same as supporting default values: They both can use functions or references to other columns, but we cannot let end-users use them like that (within the application) because that would mean sending unescaped input to the database. If we wanted to safely support fully-fledged default values / generation expression, we'd need the api to accept some kind of AST that could translate to SQL.

**Comment by wc-matteo** [comment]
@rijkvanzanten do you think it's a complex endeavor to make the app not send the `default_value` (whether it is a default value or a generation expression) to the database as a value, as @Oreilles is saying?

Right now I'm stuck with rc.85 because of this.

**Comment by rijkvanzanten** [comment]
We can't just remove support for default values across the board if that's what you're saying, no..

As for the security implications of the default value including statements submitted by the user, the data model operations are only accessible to `admin` users, so that might not be a problem we have to over-complicate 🤔

**Comment by wc-matteo** [comment]
what about not using the generation expression as a value, tho? It really doesn't make sense to treat the expression as a value. Like for example treating `'[dbo].[my_column_computed_expression_that_returns_an_int]()'` like it were an actual `int`

**Comment by rijkvanzanten** [comment]
Yeah, makes sense. 

The bigger issue here is supporting views/computed columns across the board. Without having a way to properly read/write these settings, it's fairly difficult to start tweaking things in Directus itself to handle it better. A starting point would be to update the `knex-schema-inspector` package to be more explicit about columns that are generated versus columns that are "regular" so we can at least ignore those columns for the time being in Directus while we figure out what else needs to change in order to properly support generated columns (one obvious one would be to force them to be readonly at all time, a second would be to never allow a value to be submitted to a generated column). Then we need to fork/update knex in order to be able to configure generation expressions cross database vendor, and figure out if/how to abstract away (commonly?) used expression functions in the database itself to make sure we can safely allow people to configure/export/restore those settings in a database agnostic way.

**Comment by Oreilles** [comment]
> A starting point would be to update the knex-schema-inspector package to be more explicit about columns that are generated versus columns that are "regular"

In `knex-schema-inspector`, generated columns has the `is_generated` property set to `true`. But the problem does not boils down to knowing wether the columns are generated or not, but to the fact that default values, just like generation expressions, can contain SQL expression, and those cannot be used as values inside the application when creating a new item.

The only solution is to stop using the database' default value when creating new items and let the database handle it.

**Comment by wc-matteo** [comment]
that ^ sounds very logical and reasonable. Is there a reason why directus inserts the default value itself and it doesn't let the db do it?

**Comment by Oreilles** [comment]
> that ^ sounds very logical and reasonable. Is there a reason why directus itself inserts the default value and it doesn't let the db do it?

I suppose it is so that end users can actually see that there actually is a default value, otherwise, they would only see it after the item was created.

A solution could be to return one `default_value_raw` and one `default_value` from `knex-schema-inspector`, the latter being `null` if `default_value_raw` is not of the form `'value'::type`.

Depending on the interface, we could then choose to display one or the other, preferably as a placeholder.

**Comment by rijkvanzanten** [comment]
> that ^ sounds very logical and reasonable. Is there a reason why directus itself inserts the default value/generation expression and it doesn't let the db do it?

I don't think Directus actually does that for every field. I believe the problem only shows up when you use an interface that uses that default value to preview the value, which is then either altered by the user slightly, or staged as an edited value for some other reason. (That's also why making the field readonly/hidden seems to help).

> A solution to the problem could be to return one default_value_raw and one default_value from knex-schema-inspector, the latter being null if default_value_raw is not of the form 'value'::type.

That makes sense to me, we could also add a "default value is generated" flags so we can differentiate in the app. (That way, an interface could show a placeholder with "Generated on save" instead of nothing)

**Comment by wc-matteo** [comment]
thanks a lot guys! I updated to the latest version (rc.92) and all seems to be working well!
