### ISSUE TITLE
Edit code doesn't save unless you also click the WYSIWYG

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#6306]
Steps to reproduce:

- Using a collection with a WYSIWYG field, create a new item
- Don't click the textarea of the WYSIWYG field
- Add content to the field with the code editor
- Save the collection item

The field will save with an empty value. My guess is the code editor is not correctly triggering the change event for the field. I don't believe this was an issue prior to Vue 3 (but I'm not 100%).

Clicking the WYSIWYG textarea after editing the code will cause the field to save correctly.

This may not be a Directus issue per se, but I believe Directus could handle it.

Env:
- Directus rc76
- OracleDB
- Firefox

**Comment by rijkvanzanten** [comment]
I believe this is caused by the code editing doesn't trigger one of these events;

https://github.com/directus/directus/blob/dae9d975572b982426e349e9d7f35fe873a727e1/app/src/interfaces/input-rich-text-html/input-rich-text-html.vue#L7

I just removed `SetContent` from there, as that caused an issue where it would immediately stage a value on first load too.
