### ISSUE TITLE
Bad spacing in Button Links from Alias and Presentation Field (or am i using it wrong?)

### ISSUE THREAD

**Issue by uebmaster** [directus/directus#6358]
1) The issue and what you expected to happen
    when adding multiple buttons they overlap

2) Exact steps to reproduce this issue
    Add a presentation and alias field--->In interface tab select button links---->Add some buttons with a large title and select a icon for every button--->Go to collection's view and look the result.

3) Your environment:
    What version of Directus you are using: 9.0.0-rc.76
    Which DBMS are you using: Postgres 12.7
    Which deployment are you using: npx (ubuntu server 20.04)
    What browser are you using: MS Edge, Chrome, Firefox, Opera, latest versions

4) Any other relevant information we might need to reproduce this issue
    NodeJS 14.17.0

![image](https://user-images.githubusercontent.com/5565506/122455336-e67ae580-cf71-11eb-85ab-5bad809595a0.png)

**Comment by HitomiTenshi** [comment]
I could fix this with a PR.

## Spacing Issue
The spacing issue is because only `margin-left: 8px` is applied to adjacent children.

```css
.action {
  & + & {
    margin-left: 8px;
  }
}
```

This could be solved by using `margin: 4px` on `.action` which would add to 8px for adjacent elements as well as flex wrapped elements below. The only downside of this approach is that you'd have to use a negative 4px margin on the parent element to fix the 4px margin space on the edges, not sure if you are ok with that.

## Bitten Icon
The second issue is because the `.v-icon` combined with `.left` always adds `margin-left: -4px`. Not sure if this makes sense elsewhere, but in this situation it causes the "bitten icon".

```css
.v-icon {
  &.left {
    margin-left: -4px;
  }
}
```

I could overwrite it with `margin-left: unset` to not break other styles.
