### ISSUE TITLE
Database migration between RCs breaks the system

### ISSUE THREAD

**Issue by koziserek** [directus/directus#6476]
After updating to version 80 RC from 61 RC with a command npx directus database migrate:latest the following showed up after login:

```json
{
  "errors": [
    {
      "message": "select directus_relations.id, directus_relations.many_collection, directus_relations.many_field, directus_relations.one_collection, directus_relations.one_field, directus_relations.one_collection_field, directus_relations.one_allowed_collections, directus_relations.junction_field, directus_relations.sort_field, directus_relations.one_deselect_action, directus_relations.many_primary, directus_relations.one_primary from directus_relations order by directus_relations.id asc - SQLITE_ERROR: no such column: directus_relations.many_primary",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

If necessary, I can upload a DB here, as no sensitive data are kept there for now.

Environment:

deployment: npx
DB: SQLite

**Comment by rijkvanzanten** [comment]
Are you actually running Directus rc80 on the updated database? That error looks like it's trying to read the old relationship structure, which was removed 🤔 

> If necessary, I can upload a DB here, as no sensitive data are kept there for now.

Yes please!

**Comment by masterwendu** [comment]
Hello, 
I also have issues with SQLite running on docker:

1. Creating a new docker instance with SQLite is not possible from versions >70 on.
```
directus_test    | 06:05:50 ✨ Initializing bootstrap...
directus_test    | 06:06:15 🚨 Can't connect to the database
directus_test exited with code 1
```
2. Migrating from version < 70 to version > 70 gives following error:
```
directus_test    | 06:00:28 ✨ Initializing bootstrap...
directus_test    | 06:00:28 ✨ Database already initialized, skipping install
directus_test    | 06:00:28 ✨ Running migrations...
directus_test    | ✨ Applying Add Collections Icon Color...
directus_test    | [Error: alter table `directus_collections` add column `color` varchar(255) null - SQLITE_READONLY: attempt to write a readonly database] {
directus_test    |   errno: 8,
directus_test    |   code: 'SQLITE_READONLY'
directus_test    | }
```

Site notice:
Docker image v71 is broken because of missing manifest: `ERROR: manifest for directus/directus:v9.0.0-rc.71 not found: manifest unknown: manifest unknown`

So when I checkout the release notes following commits could have caused the issue:
- https://github.com/directus/directus/commit/22f2e4662f8af81c998154ee08a1d0d628bdb2e3
- https://github.com/directus/directus/commit/77e00b7db49cb35d724dd5d496fd4f65499d58af

**Comment by koziserek** [comment]
The migration succeeded after I removed a table from DB which was not fully configured within directus (just created manually in sqlite). Therefore I consider this was my fault, but future migration scripts might benefit from considering such situations..
