### ISSUE TITLE
Don't treat TINYINT as Boolean

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6665]
### sql
![image](https://user-images.githubusercontent.com/10562635/124555751-be2b2c00-de37-11eb-9ee7-7c7d7b73e8c9.png)

### directus
![image](https://user-images.githubusercontent.com/10562635/124555757-c08d8600-de37-11eb-8638-1fc3fb232e60.png)

### tinyint
https://docs.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-2016

### To Reproduce

create a tinyint field in sql

### What version of Directus are you using?

v9.0.0-rc.82

### What version of Node.js are you using?

n/a

### What database are you using?

mssql 2016

### What browser are you using?

chrome

### What operating system are you using?

win 10

### How are you deploying Directus?

k8s

**Comment by paescuj** [comment]
I think that's on purpose, because that's how most databases store boolean values. See:
https://github.com/directus/directus/blob/46c77f70c8504a62d6fd2270eb3e7e38c96ca54f/api/src/utils/get-local-type.ts#L11

Maybe this could be changed, so only fields declared as "boolean" in directus_fields will actually be treated as boolean.

**Comment by Oreilles** [comment]
SQL server's boolean are stored as `bit` though, not `tinyint`.

**Comment by wc-matteo** [comment]
booleans are bits, `0`-`1`; tinyints are bytes, `0`-`255`

**Comment by paescuj** [comment]
It's a bit of a controversial topic, see e.g.:
* https://www.databasestar.com/sql-boolean-data-type/
* https://stackoverflow.com/questions/3751853/boolean-vs-tinyint1-for-boolean-values-in-mysql
* https://www.bennadel.com/blog/3845-why-i-use-tinyint-columns-instead-of-bit-columns-for-boolean-data-in-a-mysql-application.htm

**Comment by wc-matteo** [comment]
the best would be to treat `tinyint(1)` as boolean and the rest of tinyints as numbers

**Comment by rijkvanzanten** [comment]
[`knex`](https://github.com/knex/knex) seems to rely on `BIT` types as boolean in ms sql as well, so it would make most sense to mirror that in Directus as well. That being said, we'll have to make sure our solution works cross vendor (iirc MySQL has a bit type since 5.0, but I'm not sure if Knex uses that (yet)

**Comment by Oreilles** [comment]
> (iirc MySQL has a bit type since 5.0, but I'm not sure if Knex uses that (yet)

MySQL also has a `boolean` type, which Knex uses - but which is actually is an alias to `tinyint(1)` ( that's how it appears in the database schema ).

**Comment by rijkvanzanten** [comment]
Ah interesting, in that case, we should definitely check for `bit` and `tinyint`, but only if tinyint has length 1, like @wc-matteo suggested 👍🏻
