### ISSUE TITLE
Ability to move directus_files into folders

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#682]
On the files page, currently all files are shown in one large list – ideally I'd like to chat through how difficult it would be to add folders to this view. Basically I imagine there are new records in the *directus_files* that are "folders" instead of files:

**Something like:**
We add a "folder_parent" column to "directus_files" – every folder has this value set to NULL (root) or another folder (nested folder), and all files have it set to the folder that it is contained within.

Thoughts on how difficult this would be @WellingGuzman ?

**Comment by WellingGuzman** [comment]
@benhaynes like you said this is going to be easy to organize just adding a new field to the table, and then we can parse and format our files list into folder with no trouble.

In the front then it would be a bit of more time since we have to handle and specify if the row is directory or a file, or in other word the heavy lifting but at the end it shouldn't not hassle just time consuming.

**Comment by WellingGuzman** [comment]
@benhaynes let's chat about this when it's possible I didn't think this well through, so now I got some questions.

**Comment by benhaynes** [comment]
@WellingGuzman Sounds good. Let's discuss how we want to approach this.

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+12)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
