### ISSUE TITLE
Containers: v prefix dropped

### ISSUE THREAD

**Issue by helge000** [directus/directus#6859]
### Describe the Bug

Since rc.84, the v-prefix was dropped for docker-hub-tags. Please bring it back, brakes automation with me.

### To Reproduce

n/a

### What version of Directus are you using?

9.0.0.rc.84

### What version of Node.js are you using?

n/a

### What database are you using?

n/a

### What browser are you using?

n/a

### What operating system are you using?

n/a

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment]
This is by design. It's pretty uncommon to publish tags to Dockerhub with the `v` prefix in the tag name, so we'll be publishing images without moving forwards. I understand this might require a change in your automation.

Changes and tweaks like these might occur while we're in the RC phase as we're finalizing the exact build and release pipeline. Once the production release of 9.0.0 is out, breaking changes like these won't occur.

Ref https://github.com/directus/directus/pull/6759#issuecomment-881315963

cc @SeanDylanGoff @paescuj
