### ISSUE TITLE
Allow dropping a column from table editing page.

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#729]
Mentioned [here](https://github.com/RNGR/Directus/issues/716#issuecomment-83648122)

**Comment by benhaynes** [comment]
I was against this level of database ALTER within the system since it could have VERY detrimental effects. But positioning things as a database GUI, I feel that at the ADMIN level only you should have the ability to remove columns. But there needs to be a very clear warning, a recommendation to backup the database, and 1-2 confirmations.

**Comment by WellingGuzman** [comment]
Should we close this one and keep an eye #154 ?

**Comment by benhaynes** [comment]
Yeah, we have delete functionality now... we just need to add support for aliases.
