### ISSUE TITLE
Filter Rule on Relational field is not working

### ISSUE THREAD

**Issue by minyangu-bgl** [directus/directus#7423]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have two collections `author` and `article`, I want to hide some fields on the `article` details page if it is linked with some specific `author`. For example, I have a `special_text` field on the article page, and on this field, created a condition rule to hide itself using the relational filtering mentioned from the doc, however things seems not taking effect as the `special_text` still shows on the Body page 

_Ref doc page_:
https://docs.directus.io/reference/filter-rules/#relational

### To Reproduce

1. Create `author` collection with fields: `id`, `name`. Create a single author record with name value `Thor`
2. Create `article` collection with fields: `id`, `status`, `title`, `body`, `special_text` and `author`, where `author` is the Many to One relationship field and links to `author.id` field.
3. on `special_text`, create a new condition and when match choose to hide the field on Detail. 
Rules tried that doesn't work:
Not working if filtering by `author.id`
```
{
    "author": {
        "id": {
            "_eq": 1
        }
    }
}
```
Not working also by filtering `author.name`
```
{
    "author": {
        "id": {
            "name": "Thor"
        }
    }
}
```

So far, only this rule worked which is filtering on the actual value of the relational field, but any sub-fields doesn't seem to be working.
```
{
    "author": {
         "_eq": 1
    }
}
```

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally using docker compose

**Comment by rijkvanzanten** [comment]
Heya! This is the same confusion as https://github.com/directus/directus/discussions/7123.

The relational field, as returned by the API, is just a static ID. Therefore, the conditional fields configuration would be

```json
{
    "author": {
        "_eq": 1
    }
}
```

That being said, as soon as the user makes any alterations to the author itself, it'll be staged as the nested changes, so if you'd want to set a condition on a changed name, you'd use something like

```json
{
    "author": {
        "name": {
            "_eq": "Rijk"
        }
    }
}
```

If you want both, you can combine them with an _or:

```json
{
  "_or": [
    {
      "author": {
        "_eq": 1
      }
    },
    {
      "author": {
        "name": {
          "_eq": "Rijk"
        }
      }
    }
  ]
}
```

**Comment by minyangu-bgl** [comment]
Interesting to know what's the reason to wait for the records alteration to propagate those fields data? Why the initial API fetch cannot return more fields data rather than just ID?

From business user perspective, I'm not sure this is a perfect solution when creating the new collection item.

**Comment by rijkvanzanten** [comment]
> Why the initial API fetch cannot return more fields data rather than just ID?

Because of recursiveness in relational fields. Opening the single parent item could end up fetching up _a lot_ of data 🤔  I'm down to discuss an improved workflow for fetching the initial values for the purposes of conditional fields checking, but for right now, this is working as expected

**Comment by u12206050** [comment]
> Heya! This is the same confusion as #7123.
> 
> The relational field, as returned by the API, is just a static ID. Therefore, the conditional fields configuration would be
> 
> ```json
> {
>     "author": {
>         "_eq": 1
>     }
> }
> ```
> 
> That being said, as soon as the user makes any alterations to the author itself, it'll be staged as the nested changes, so if you'd want to set a condition on a changed name, you'd use something like
> 
> ```json
> {
>     "author": {
>         "name": {
>             "_eq": "Rijk"
>         }
>     }
> }
> ```
> 
> If you want both, you can combine them with an _or:
> 
> ```json
> {
>   "_or": [
>     {
>       "author": {
>         "_eq": 1
>       }
>     },
>     {
>       "author": {
>         "name": {
>           "_eq": "Rijk"
>         }
>       }
>     }
>   ]
> }
> ```

This is not working for me. I have a very similar condition, and even if I change the relation, so that it is altered the condition still doesn't take affect.

I have `attributes` collection with a `type` field on it. 
Within my `formFields` collection which has a m2o relation to `attributes` via `attribute, I have conditions on the interfaces to hide or show depending on what `type` the selected `attribute` is.

This only works if I check directly on the relation eg.
```
{
  "attribute": { "_eq": 2 }
}
```

but not when checking the subfield
```
{
  "attribute": {
    "type": { "_eq": "string" }
  }
}
```

Even when altering the `attribute` to another attribute.

**Comment by rijkvanzanten** [comment]
> but not when checking the subfield

That would make sense in this context, as the staged value for attribute is only the primary key at that point in time. When selecting a different (existing) attribute, the same thing happens. Only the primary key of the other selected attribute is staged.

In order to resolve that, we have to come up with some sort of way where the app fetches the parent item again, correctly following all the paths taken in the condition in order to be able to check the deep values of relational data. However, that doesn't solve it for when the value is _changed_. The app only stages the bare minimum data in order to make the update, so that too would have to have some sort of way to dynamically fetch the deeply nested data of the selected related item in order to be able to do the conditional check on the nested value.

Wanna open a new feature request for that?

**Comment by RaphaelBP** [comment]
same problem.
