### ISSUE TITLE
UI Data type freedom

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus#751]
Reminder to grab data type from ui. 

Example single file is INT instead of ManytoOne.

I'd update this later on.

**Comment by WellingGuzman** [comment]
And I forgot to update this later on, and i forget what I was talking about.

@benhaynes remember any of this?

I will look into it.

**Comment by benhaynes** [comment]
@WellingGuzman Hmm, not sure... but maybe:

When you create a column in Directus you choose a UI... and it creates a column with the correct datatype. I'm not sure how it knows which datatype to choose – but it should use the UI itself.

Since the UI lists the datatypes it works with, we should say that the FIRST datatype in that list is the best/default. So if you create a field with a certain UI it looks at the UI code (`dataTypes: ['TEXT', 'VARCHAR']`) and chooses the first one.

Does that make sense? Do you think that's what it was?

**Comment by WellingGuzman** [comment]
I got it, on `directus_columns` the field `data_type` can be the ui name, but it should actually be the actual field `data_type`, such as `INT` or `VARCHAR`.

**Comment by WellingGuzman** [comment]
Soooo, this is also done, all column stored their data type, except alias should stored `ALIAS`.
