### ISSUE TITLE
with auth.login.before hook login not working

### ISSUE THREAD

**Issue by dschaefer7** [directus/directus#7564]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

after implementing empty auth.login.before hook:

```js
module.exports = function registerHook({services, database}) {
      return {
          auth.login.before: async function (payload, {user}) { 
           }           
      }
}
```

no login in directus working

### To Reproduce

implement empty auth.login.before hook

### What version of Directus are you using?

rc-90

### What version of Node.js are you using?

12 lts

### What database are you using?

mariadb 10.5

### What browser are you using?

chrome

### What operating system are you using?

macosx big sur

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment]
On face value, it seems like the payload was not returned, and since `*.before` handlers are [blocking by nature](https://docs.directus.io/guides/api-hooks/#before), it would appear there wouldn't be any payload to be processed, hence it fails.

However upon inspection, it seems this issue in particular is actually not the root cause, though it did consequently surface another issue where the modified value are just used directly without merging into the original user object. 

I'll try to get a draft PR going which documents what I found & we'll see how it goes.
