### ISSUE TITLE
Save and add new doesn't clear WYSIWYG

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7730]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

WYSIWYG fields are not cleared when "Save and add new" is used.

### To Reproduce

1. "Save and add new" on a collection that has a WYSIWYG
2. See WYSIWYG is not cleared

### What version of Directus are you using?

INTERNAL

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

**Comment by azrikahar** [comment]
This looked like a quick fix on first glance for me... but I was sorely mistaken 😂 After going down the rabbit hole, finally found a solution. It seems like the issue is with the tinymce component used in `app/src/interface/input-rich-text-html/input-rich-text-html.vue` not updating despite the "reset all inputs in the form" logic technically worked flawlessly. Will be creating a PR soon 👍
