### ISSUE TITLE
Behaviour of 'general checkbox' button in M2O interface

### ISSUE THREAD

**Issue by Tummerhore** [directus/directus#7818]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The M2O-Interface shows a checkbox button in the upper left corner. Clicking it always just selects the last element in the list which is likely not the intended behaviour. It makes no difference if an item is already selected (so it shows a minus in the checkbox) or not (so it shows an empty checkbox).
![Unbenannt](https://user-images.githubusercontent.com/45203603/132055677-da1277c1-4375-482b-901d-722d4325c7bb.png)

### To Reproduce

Open a M2O interface and click on the checkbox button in the upper left corner.

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

14.17.5

### What database are you using?

MariaDB and MySQL

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment]
Right now the layouts don't differentiate between "select one" and "select multiple". This means that the tabular layout still has the "select all/none" toggle in the top left. I believe @benhaynes just opened a discussion as well around using radio buttons instead of checkboxes when that's the case. We should add a prop to the layouts to indicate that we're looking to select a single item

**Comment by joselcvarela** [comment]
For reference: #7761
