### ISSUE TITLE
User Tooltips not correctly positioned

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7926]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The user tooltips are showing in the top-left corner of the App... instead of directly next to the user name. Also, ideally, I would like to make it so the username is NOT clickable, but instead, clicking the **tooltip** itself takes you to the user's detail page. This might require some fanciness to allow the cursor to move onto the tooltip.

![Screen Shot 2021-09-08 at 12 41 06 PM](https://user-images.githubusercontent.com/522079/132550468-df669aa4-245d-4b2d-b3b3-f72119fe336e.png)

### To Reproduce

Hover over a user name in the revisions sidebar.

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

INTERNAL

### What database are you using?

INTERNAL

### What browser are you using?

Chrome

### What operating system are you using?

INTERNAL

### How are you deploying Directus?

INTERNAL

**Comment by azrikahar** [comment]
I think it might be better to address this in 3 separate PRs as I can observe 3 key points that can be different in nature despite all belonging in the user tooltip area. They are:

1. > The user tooltips are showing in the top-left corner of the App... instead of directly next to the user name.

    This is the bug sparking the other 2 improvements/changes. The PR for this will be created soon after this comment is posted.

2. > This might require some fanciness to allow the cursor to move onto the tooltip.

    This can also be addressed in a PR as it is still a good quality of life change, even if the tooltip is not clickable yet.

3. >  ideally, I would like to make it so the username is NOT clickable, but instead, clicking the tooltip itself takes you to the user's detail page.

    Currently the tooltip defaults to closing upon being clicked, as seen here (div with `v-menu-content` is the tooltip element):
    
    https://github.com/directus/directus/blob/640368a21b4743689c1df5568eb20ddd564ec8c0/app/src/components/v-menu/v-menu.vue#L39
    
    https://github.com/directus/directus/blob/640368a21b4743689c1df5568eb20ddd564ec8c0/app/src/components/v-menu/v-menu.vue#L237-L241
    
    However, the user tooltip is actually a `user-popover` component that wraps `v-menu` component:
    
    https://github.com/directus/directus/blob/640368a21b4743689c1df5568eb20ddd564ec8c0/app/src/views/private/components/user-popover/user-popover.vue#L2
    
    And since the current `onContentClick` (seems to be) used by any other menu tooltips so that the menu will automatically close when we click on a menu item, and we will also need to be able to pass the "user" data into the `v-menu` to create the user detail router push, this particular feature might need more time to flesh things out.
    
The above are just my thoughts, feel free to advise if there's any issue. Regarding the 3rd point, I'll also try to look into it again once I got the time and see am I drawing the wrong conclusion here.

**Comment by benhaynes** [comment]
Thank you for breaking this all down so clearly!! Really helps to see the process behind the scenes... 👍 

I know @rijkvanzanten will be stoked. 🙂
