### ISSUE TITLE
Save and Stay should insert revision item

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#7930]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

If you choose "save and stay" or use the keyboard shortcut, the page's revisions are not updated... and you have to do a hard refresh to get the new item. If should be injected on save... ideally with a nice slide-in transition. 😉 

### To Reproduce

1. Go to an existing item
2. Click save and stay
3. Watch revisions in info sidebar

### What version of Directus are you using?

RC-92

### What version of Node.js are you using?

Node: 16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DO

**Comment by azrikahar** [comment]
the PR is more of a "mvp" approach to fix this bug first. Once again the logic is already there, just that the function wasn't called properly, so I only had to amend it haha. 

Regarding the ideal approach of adding transition, gave it some thought and it would've been pretty straightforward to append/prepend it to the existing list, but then there's the grouping of date that'll need to be taken into account instead of just pushing it in directly.

With that said, there's also #6303 which will touch upon the revision detail & modifies that part abit, so maybe we can revisit this enhancement after that PR gets merged.
