### ISSUE TITLE
Can't launch Directus locally

### ISSUE THREAD

**Issue by aerdnach** [directus/directus#8107]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi, after local install (https://docs.directus.io/contributing/running-locally/) I'm getting this error via browser when trying to visit http://localhost:3055/

`{"errors":[{"message":"Route /admin doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND","stack":"Error: Route /admin doesn't exist.\n    at notFound (/home/andrea/code/work/directus/api/src/controllers/not-found.ts:22:8)"}}]}`

I get redirect to http://localhost:3055/admin before the error: This is my .env:
```
KEY="directus"
SECRET="directus"
DB_CLIENT="mysql"
DB_HOST="localhost"
DB_PORT=3307
DB_USER="root"
DB_PASSWORD="root"
DB_DATABASE="directus"
ACCESS_TOKEN_TTL="7d"    
REFRESH_TOKEN_TTL="7d"
PORT=3055
PUBLIC_URL="http://localhost:3055/"
```

The strange thing is that I defined a custom api endpoint and it works great. I run Directus with `npm run dev`, but I get the same error if I try `npm run dev -- --scope directus --scope @directus/app`, or if i run the api before the app. Adding a / after admin won't help.

I'm using mysql 8.0.26, and rc 93.

### To Reproduce

Follow the Directus doc guide at https://docs.directus.io/contributing/running-locally/

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

v16.8.0

### What database are you using?

mysql

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
The public url doesn't really change the port, but more so just for url resolution. It is odd that the config you shared doesn't show any `PORT=3055`, but it most likely just proxied from 3055 to `localhost:8055`. Are you sure it's 3055? you can check on the terminal:

![WindowsTerminal_VaQLeVMF2p](https://user-images.githubusercontent.com/42867097/133762718-7c68bac9-b457-4c45-b674-5fda9d1db549.png)

And the reason it wasn't working (/admin) is because 8055/3055 is the API, not the APP. You should use the APP port which should be `8080` by default.

With that said, you can try to do the following:

- add/change these 2 env variables:
  ```shell
  PORT=8055
  PUBLIC_URL="http://localhost:8080"
  ```
- run `npm run dev -- --scope directus --scope @directus/app`
- wait app & api to start up (refer the above screenshot)
- go to `http://localhost:8080` (**not** 8055)
- if you see this, click on the `/admin/admin` link:
 ![chrome_HwWJKKIaDo](https://user-images.githubusercontent.com/42867097/133763378-0aad1e5e-6f76-40f9-96b6-4e0818936762.png)

**Comment by Nitwel** [comment]
Also, make sure to open `http://localhost:8080/admin/` not `http://localhost:8080/admin`.

**Comment by joselcvarela** [comment]
https://docs.directus.io/reference/environment-variables/#environment-variables

As said in the docs, PUBLIC_URL is `URL where your API can be reached on the web`

So if you host your project on the web and have a DNS as `https://my-directus-project.com` so you should define `PUBLIC_URL="https://my-directus-project.com"`. 

This means `PUBLIC_URL` doesn't modify anything.
Just point things to the right place, like relative links, or relative image paths.

**Comment by aerdnach** [comment]
![image](https://user-images.githubusercontent.com/9568794/133803123-6e831600-5445-43ae-8e97-7e5af60d0c5b.png)

@azrikahar @Nitwel I followed your suggestion, but still having problems (see image above). Also @azrikahar you said "add/change these 2 env variables" but in code block i see only one.

Thanks for your help :)

**Comment by rijkvanzanten** [comment]
@aerdnach the build chain for the app is configured to point to 8055 by default here:

https://github.com/directus/directus/blob/62282570a5d9667df007236add8710d4d3ae2ed3/app/vite.config.js#L32

Can you try setting the "API_URL" flag to `'http://localhost:3055/'?

(I always just leave it on the defaults, so haven't really tried this 😁 )

**Comment by fatihky** [comment]
> Also, make sure to open `http://localhost:8080/admin/` not `http://localhost:8080/admin`.

@Nitwel thank you so much for this trick but how about pointing these two endpoints to the same page?

**Comment by rijkvanzanten** [comment]
> but how about pointing these two endpoints to the same page?

That's just a technical limitation of Vite i'm afraid. In production mode, this is already the case 👍🏻
