### ISSUE TITLE
Highlighted links in presets item view's sidebar

### ISSUE THREAD

**Issue by licitdev** [directus/directus#8387]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The links shown in the sidebar are highlighted, but it should only be highlighted when active or hovered.
<img width="274" alt="Screenshot 2021-09-28 at 10 00 34 PM" src="https://user-images.githubusercontent.com/26413686/135102384-b3b391e0-9150-488b-9806-2241f47aa68e.png">

### To Reproduce

Open Settings -> Presets & Bookmarks -> Any preset
Look at the sidebar on the right.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment]
This is actually on purpose @licitdev! Those particular sidebar detail items are specifically to the layout, and not the presets page. The color highlight was used to visually separate them from the "page sections". That being said, I do agree how that feels a little broken seeing the same color is used for hover/active states of other sections.

Thoughts @benhaynes? A middle ground solution could be to use the warning color instead of primary

**Comment by licitdev** [comment]
@rijkvanzanten Ah I see. I saw it as a bug as nothing within the sidebar were active. 
ie: the search, filter etc have nothing selected within.

I am confused with there being a `sidebar` and `sidebar-detail` inside a `sidebar-detail-group`.
<img width="899" alt="Screenshot 2021-09-28 at 10 33 10 PM" src="https://user-images.githubusercontent.com/26413686/135108510-914a97e0-ac78-415c-a676-0db7b138be99.png">

@benhaynes I wonder if a static divider / header will be good. Like a category / grouping for the sidebar. 
Eg: A thick dark gray line as separator when closed but shows a text when opened.

**Comment by rijkvanzanten** [comment]
That's the sidebar slot that's rendered in there in order to allow the layout itself to render markup in that section.

FWIW, we're aiming to replace the ux/ui of this page completely in the (near) future, as settings those options in that sidebar isn't very intuitive to begin with 😁 Until then, we should be able to find a workable middle ground, like using the alternative color

**Comment by licitdev** [comment]
@rijkvanzanten Got it. Haha, I was thinking of something along the lines of header bar. 
Will update the PR now. Thanks!

<img width="277" alt="Screenshot 2021-09-28 at 10 50 36 PM" src="https://user-images.githubusercontent.com/26413686/135111519-88d974b9-42aa-4a73-b969-e826f8da2ce1.png">

<img width="277" alt="Screenshot 2021-09-28 at 10 50 26 PM" src="https://user-images.githubusercontent.com/26413686/135111546-798ca254-03b9-4311-b3ae-b8580f346db8.png">
