### ISSUE TITLE
No package.json when installed in a Kubernetes cluster

### ISSUE THREAD

**Issue by V1210N** [directus/directus#8471]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Installing Directus via its Dockerhub container image on a Kubernetes cluster will cause the image to not have its package.json. 

There are no traces of the Dockerfile's builder steps, which indicate that these might be getting skipped over. There is also no `node_modules` folder.

The absence of `package.json` and `node_modules` leads to extensions being unable to be loaded. 

### To Reproduce

I used a basic setup with a [custom helm chart](https://github.com/V1210N/directus-charts), however, this is likely also reproducible in other chart setups.

1. Install the Directus helm chart.
2. Once the deployment is up and running, SSH into the Directus Pod.
3. Go to the default install directory `/directus` and run `ls`.
4. At this point you'll notice the absence of both `package.json` and `node_modules`.

### What version of Directus are you using?

9.0.0-rc.95

### What version of Node.js are you using?

16.9.1

### What database are you using?

Postgres 12.8

### What browser are you using?

(irrelevant)

### What operating system are you using?

Linux (Directus' Dockerfile)

### How are you deploying Directus?

Kubernetes

**Comment by paescuj** [comment]
The Docker image shouldn't behave differently on Kubernetes, so this must have something to do with your deployment configuration. Looking at the [deployment.yaml](https://github.com/V1210N/directus-charts/blob/1bb70493e8ca43b89551c67816dcdaefaa7618db/templates/deployment.yaml#L42-L44) file, it seems like you're mounting the whole `/directus` folder instead of `/directus/uploads` (see https://docs.directus.io/guides/installation/docker/#persistence).

**Comment by azrikahar** [comment]
This may be another helpful reference: https://github.com/directus-community/helm-chart
