### ISSUE TITLE
Aggregate Functions not working on Datasets with custom permissions

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#8510]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

First - aggregate APIs is really a great enhancement and can be used for many use cases - thanks for that!

Issue: When using aggregate functions on datasets with custom permissions a 403 Forbidden Error is returned

### To Reproduce

Example:
- A Posts Collection with custom permissions, in my case:  only show if published AND only show if publishing date > $NOW
- I am using the following API params to count the different slugs (just a stupid example... also tried other fields)

```
				aggregate: {
					count: 'slug'
				},
				groupBy: 'slug'
```

- I also tried to add the custom filter to the params in the hope that this "works around" the problem:

```
				filter: { _and: [
					{ status: { _eq: 'published'}},
					{ date_published: { _lt: '$NOW'}}
				]},
```

- ... and I tried several other ways... all works fine on datasets where full permissions are available... but if there are custom permissions it fails

### What version of Directus are you using?

9.0.0-rc95

### What version of Node.js are you using?

16.7

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment]
> A Posts Collection with custom permissions, in my case: only show if published AND only show if publishing date > $NOW

Hi, I believe you meant `publishing date < $NOW` (less than) right?

With that said, I can't seem to reproduce this on my end. Can you verify whether my steps are the same as what you were using?

### My reproduction steps

1. Create `Posts` collection with `title`, `status` and `publishing_date` fields (and the create/update default fields)

    ![chrome_USuGtsuI5l](https://user-images.githubusercontent.com/42867097/135790989-6612379e-c9bc-4a84-8f20-45b3ffa0b8a4.png)

    ![chrome_Gt0UMl9hyV](https://user-images.githubusercontent.com/42867097/135791133-a93fec00-bdec-4456-99ce-69f899f3637f.png)

2. Set a custom read permission for Public role on Posts collection:

   ![chrome_9xXk5BCNqd](https://user-images.githubusercontent.com/42867097/135791012-442a7e6b-3698-4855-84da-d3e81e06f57a.png)
 
3. Send GET request to `/items/posts?aggregate[count]=title&groupBy[]=title`:

    ![Insomnia_zrbu1gfXEf](https://user-images.githubusercontent.com/42867097/135791146-a904c868-3f87-410b-a247-78f5c953b851.png)

**Comment by rijkvanzanten** [comment]
> but if there are custom permissions it fails

How does it fail? What errors are you seeing?

**Comment by ernst86913** [comment]
... invested a bit more time in different scenarios:

a) if I remove custom permissions and allow full access to the role it works
b) adding back the custom rules which I described above (status filter, date_published filter) and it still works... I just have the issue now that I can't set $NOW anymore... but this has been raised in a different issue by somebody else already
c) **Deselecting just one of the field permissions results in the ISSUE I described...** would not have expected that one... that's why I just described the filters mentioned above.

ERROR THROWN - 403:
directus: 22:49:59 ✨ request completed GET 403 /items/posts?aggregate=%7B%22count%22:%22title%22%7D&groupBy=title

**Comment by ernst86913** [comment]
... ok... kept playing around... I added the field back now again... and it still throws the issues.

Then I changed the collection back to "ALL ACCESS"...  Now it works again

Now I am not adding any item permissions... just field permissions... and I remove one completely random field which is not required for the query.... and it throws the error again.

When I add this one field back again... (so - all fields are selected again in field permissions) it keeps throwing the error - which is strange.

Only if I click "ALL ACCESS" on the collection it works again.... hmmmm....

**Comment by azrikahar** [comment]
> I just have the issue now that I can't set $NOW anymore... but this has been raised in a different issue by somebody else already

hmm but this shouldn't be the case for rc.95, assuming you meant #8529 (the user raised that issue because he's a contributor running on newer changes that are not released on rc.95). 🤔

> Now I am not adding any item permissions... just field permissions... and I remove one completely random field which is not required for the query.... and it throws the error again.

Yes I can confirm this happens 👍 Great finding. Looks like it might be specifically Field Permissions, not Item Permissions. 

---

## Test case

Removed field permission for `publishing_date`, but as we can see from the follow up screenshots below, the query never used this field yet it still shows permission error.

![chrome_NwuZZIO5in](https://user-images.githubusercontent.com/42867097/135965356-4b10aeda-fe3f-4fc4-a0c6-609c1e99c8ef.png)

### REST API
![chrome_XmwXJL2vh2](https://user-images.githubusercontent.com/42867097/135965066-775ad344-c6a0-4f86-b1d1-581c8140b555.png)

### GraphQL
![Insomnia_BMhpZdqyb0](https://user-images.githubusercontent.com/42867097/135965171-103de631-746c-4572-aec6-69b6cc605fa5.png)

## Investigation

Seems like this is where the issue occurs:

https://github.com/directus/directus/blob/995b8190997abfbf185f2b0e1fc16c380ec26cd1/api/src/services/authorization.ts#L113-L121

- When we deselect any fields (even if it's not in the query as @ernst86913 mentioned), this IF statement kicks in since `allowedFields.includes('*') === false` is true
- Given a query such as `aggregate[count]=id`, 
  - `allowedFields` evaluates as array `['status', 'title', 'id']` 
  - `Object.values(aggregate)` evaluates as array `['id']`
  - `aliasMap` evaluates as string `'id'`
- `Object.keys(aliasMap)` turns it into `'0'`, as that's the key of `'id'`, so `allowedFields.includes(column) === false` is indeed false since it's looking for column `'0'` instead of column `'id'`.

@rijkvanzanten what would be the appropriate fix here? doing `Object.values(aliasMap)` (values instead of keys) does fix it, but it might not be the correct approach. I'm also having trouble unpacking when this `aliasMap` happens 🤔 tried alias fields but doesn't seem to be doing anything, but I might be going about it the wrong way tbh.

**Comment by rijkvanzanten** [comment]
> @rijkvanzanten what would be the appropriate fix here? doing Object.values(aliasMap) (values instead of keys) does fix it, but it might not be the correct approach. I'm also having trouble unpacking when this aliasMap happens 🤔 tried alias fields but doesn't seem to be doing anything, but I might be going about it the wrong way tbh.

This aliasMap check is just to make sure that you have permissions to access every field you're trying to alias. However, like you correctly stated, the order is wrong. In the alias query, it's `[customKey]: field`, instead of `[field]: customKey`, so reversing that keys to values sounds like the right approach to me 👍🏻
