### ISSUE TITLE
Error with mysql installation

### ISSUE THREAD

**Issue by JacquesvanWyk** [directus/directus#8619]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I am on mac and trying to install Directus with mysql. I get the following error

Something went wrong while seeding the database:

[ER_ERROR_ON_RENAME] alter table directus_users add constraint directus_users_role_foreign foreign key (role) references directus_roles (id) - ER_ERROR_ON_RENAME: Error on rename of './directustest/directus_users' to './directustest/#sql-backup-3af-230' (errno: 168 "Unknown (generic) error from engine")

Please try again

### To Reproduce

Fresh installation choosing mysql

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v14.18.0

### What database are you using?

10.6.4-MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally on Valet

**Comment by JacquesvanWyk** [comment]
Hi I just tried rc.96 and still get same error. So I guess it must be something on my system then that is problem?

**Comment by azrikahar** [comment]
> Hi I just tried rc.96 and still get same error. So I guess it must be something on my system then that is problem?

Hmm it's hard to say for sure. How are you setuping up the database? It is MariaDB, not MySQL right? I understand they should have parity to each other, but it'll be helpful to have pinpoint accuracy on the database used so that we can try to replicate this issue on our end.

Slighly off-topic, but not sure does this affect things or not: would you mind elaborating how does the deployment of Directus with Valet works?  I assume it's Laravel Valet right? Granted I definitely have no experience in it, but from what I've briefly looked up, seems like is for PHP but Directus v9 is written in Node.

**Comment by JacquesvanWyk** [comment]
Thanks
