### ISSUE TITLE
Interface display template bug

### ISSUE THREAD

**Issue by dkophelyi** [directus/directus#8872]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I pulled the latest Docker image (v9.0.0-rc.98) and wanted to add display template to an M2M relational field.

![image](https://user-images.githubusercontent.com/59764298/137619991-aba4a4ca-c252-411b-8e80-b9e1119bda16.png)

When I add it and hit save and reopen Edit Field panel, I cannot delete the previously added value by clicking.

And the problem mentioned in #8817 still exists: I can now save the display template, however, the values from Translations field won't show up in any M2M relations.

### To Reproduce

1) Create a collection (let's say Tags), then add a Translation field to it. Add a Term field to the tags_translations table.
2) Create another collection (call this e.g. Posts), create an M2M relational field, and connect Tags to it. Set a corresponding field (e.g. Related Tags). Save the relational field.
3) Go back to the Edit Field panel and click on Interface > Display Template, click the + button, then select Tags ID > Translations > Term. The same thing goes for Display. Hit save.
4) Open the Edit Field panel again and check Interface and Display tabs
5) Try to remove the previously added value. It won't disappear by clicking (just by hitting backspace)

6) Create an Item in Tags, add something to Translations > Term field (to all languages - I have 2). Save the item
7) Create an Item in Posts, go to Tags field, and press Add Existing. Select the freshly added item from the list
8) As you can see, the value will be empty, I cannot see any translation value.

![image](https://user-images.githubusercontent.com/59764298/137620686-fca62053-8c59-49fa-802c-0862ad5975ce.png)

### Errors Shown

No errors have been logged.

### What version of Directus are you using?

v9.0.0-rc.98

### What version of Node.js are you using?

16.11.1

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment]
> When I add it and hit save and reopen Edit Field panel, I cannot delete the previously added value by clicking.

Made a PR #9838 to solve this issue 👍

--- 

As for the relational translations issue, it is due to the render template is trying to do `related_coll.translations.name` instead of `related_coll.translations[index].name`, as translations is an array. For further detail, you can refer to https://github.com/directus/directus/discussions/9559#discussioncomment-1600116 and https://github.com/directus/directus/discussions/9524#discussioncomment-1630959. That being said, it's probably best for us to continue tracking this translations issue over at #9751 as it is more specifically targeting this issue.

In addition, resolving 9560 is also another possible avenue to solve this issue.
