### ISSUE TITLE
Could not unhide a hidden field

### ISSUE THREAD

**Issue by ndaidong** [directus/directus#9023]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

At the model interface, when a field is set to "Hide Field on Detail", there is no way to show it again.

Discussion: #8956 

### To Reproduce

- Create a new model
- Add some fields
- Hide a field on detail

https://www.youtube.com/watch?v=Iz34iMkdr78

### Errors Shown

No

### What version of Directus are you using?

9.0.0-rc.96

### What version of Node.js are you using?

not checked, belong to your docker image

### What database are you using?

postgres 13

### What browser are you using?

Brave, Chrome, Vivaldi, Firefox

### What operating system are you using?

EndeavourOS (GNOME 40.5), Windows 11

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment]
Hello again @ndaidong 
I still cannot reproduce your issue even with the docker-compose you have shared.
But, we have other users complaining about UI issues while using Linux distributions. https://github.com/directus/directus/issues/8820
Is it possible to test this scenario on a Windows or macOS machine?

I am closing this for now, since we were not able to reproduce.
Although if the problem persists on other machines we can investigate a little further but we will need more information in order to replicate this.

**Comment by ndaidong** [comment]
@joselcvarela ok bro, just close this issue to focus on more important features. I will try with Windows when possible and update the result here for you. Thanks.
