### ISSUE TITLE
Error Adding Collection with Collation

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9097]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Getting a collation error when trying to add a collection... with `DB_CHARSET` enabled. This works with that collation env variable commented out, not sure if the type is wrong or what. 🤔 

### To Reproduce

1. Set `DB_CHARSET="utf8_general_ci"`
2. Start in dev mode (latest on `main`)
3. Try to create a collection (just a name)

### Errors Shown

![Screen Shot 2021-10-23 at 10 54 50 AM](https://user-images.githubusercontent.com/522079/138561546-93ae2f5f-2b29-4aac-bc54-ac4ef185fb61.png)

### What version of Directus are you using?

RC.99

### What version of Node.js are you using?

7.20.3

### What database are you using?

MySQL 5.7.26

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Follow up to my previous comment, where this used to work regardless if we were to use `utf8` or `utf8_general_ci`, I suspect this recent change (17 days ago) over at the mysql package is the cause here:

```js
if (charset && !like) sql += ` default character set ${charset}`;
```

https://github.com/knex/knex/blame/ace439d5c76b14ed54d0da5bb38add5090c42cfc/lib/dialects/mysql/schema/mysql-tablecompiler.js#L39

Another form of confirmation is this change affects `create table` statements, at least from my understanding. This is supported by the fact that the error shared in this issue & #9264 both happens during table creation statements. (#9264 failed at "Add Insights" migration, which tries to _create_ `directus_dashboards` & `directus_panels`).

**Comment by cdwmhcc** [comment]
Whether using `utf8`, `utf8_general_ci` or `utf8mb4`, it doesn't work for me.
My database `utf8mb4_general_ci`.

**Comment by rijkvanzanten** [comment]
This was since updated. Also see https://github.com/directus/directus/discussions/11786 for more discussion around charsets.
