### ISSUE TITLE
Translation Display Fixes

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9358]
## 1. It looks like the "percent complete" indicators are not working here. All of these translations have values in all fields, so they should be 100%... like the interface.

![Screen Shot 2021-11-02 at 10 45 35 AM](https://user-images.githubusercontent.com/522079/139870114-f3e55a21-72f4-4862-9b01-e6967715586b.png)

![Screen Shot 2021-11-02 at 10 45 26 AM](https://user-images.githubusercontent.com/522079/139870092-f1580141-2b5b-4b55-981b-7ea3b44edf92.png)

## 2. Clicking on multiple displays stacks them instead of closing previous. Clicking outside will close them properly.

![Screen Shot 2021-11-02 at 10 47 02 AM](https://user-images.githubusercontent.com/522079/139870374-27f8af2a-dc7c-414c-adf8-4063101bce36.png)

**Comment by rijkvanzanten** [comment]
> 2. Clicking on multiple displays stacks them instead of closing previous. Clicking outside will close them properly.

@azrikahar wanna see if we can combine this change with finding a way to standardize the "on focus out" thing you did the other day?

> 3. Clicking anywhere in the display should not open the info popup, it makes it hard to click and enter the item detail. Instead, we should show a right-aligned info icon on hover, and clicking that icon should trigger the popup.

Lets also standardize this across the other displays with hover state / dropdowns (like the related-values)

**Comment by azrikahar** [comment]
## Issue 1

Don't have a solution from me, but an investigation led to here the cause being here:

https://github.com/directus/directus/blob/4c6bcedf520f537a019d5cd447e738da8e13e2db/app/src/displays/translations/index.ts#L99-L101

particularly `getFieldsFromTemplate` which meant we're only retrieving the field(s) displayed for translation, so we're never getting _all_ the fields, resulting in a wrong progress display.

Let's say if I do `const fields = ['*']` as a crude test, everything seems to work now:

Note: first row is fully translated, second row is half translated.

|Before|After|
|---|---|
|![xv8UlZreJf](https://user-images.githubusercontent.com/42867097/140014601-0bd6f031-ff9a-4c71-9859-fcd88a9472f5.gif)|![GrWcp4KqDd](https://user-images.githubusercontent.com/42867097/140014617-c9abaed8-0eef-43ba-9833-df7966b197c4.gif)|

However getting all fields probably was avoided as it can be very large, especially paragraphs, which is understandble. So maybe the logic here needs to somehow be changed to get field keys only.

## Issue 2

> wanna see if we can combine this change with finding a way to standardize the "on focus out" thing you did the other day?

I tried using the directive, but I couldn't make it to work since if I add a parent in the translations display, the outer `<render-display>` has errors (likely because of the v-bind) 🤔

Also just to note the reason why there `.stop` to the click event (personally forgot about this), it's due to table rows having click event as well. removing the `.stop` made the translations display open/close as usual, but triggers the row click in the parent. 

With that said, I was still able to use sort of the same solution over here, with the following change:

```diff
-               <template #activator="{ toggle }">
+               <template #activator="{ activate, deactivate }">
                        <render-template
                                :template="internalTemplate"
                                :item="displayItem"
                                :collection="junctionCollection.collection"
-                               @click.stop="toggle"
+                               tabindex="-1"
+                               @click.stop="activate"
+                               @focusout="deactivate"
                        />
                </template>
```

Result:

![27tcwy3shO](https://user-images.githubusercontent.com/42867097/140014078-be6da842-ce0a-4376-9f39-6e9e8603cb58.gif)

Though we'll likely still need to gravitate to the context menu directive to implement the 3rd issue, info icon here.

**Comment by iksent** [comment]
Is this the same as https://github.com/directus/directus/issues/8811 (Bug №2)?
