### ISSUE TITLE
Divider/Alias setup flow

### ISSUE THREAD

**Issue by benhaynes** [directus/directus#9528]
The divider (and maybe all aliases or presentation types) should not have a "Default Value" or "Required" toggle. That's extra visual noise and might confuse users.

![Screen Shot 2021-11-05 at 10 43 54 AM](https://user-images.githubusercontent.com/522079/140529087-35818f11-5fbb-48c4-b789-f600ee27f95f.png)

**Comment by benhaynes** [comment]
Also, the `key` is not _super useful here (nor the type), but we do have a `title` interface option. I wonder if there's a way to combine these?

Also, small request to move the `title` above the color/icon options. 👍

**Comment by benhaynes** [comment]
I wonder if there's a way to "auto create" a key (eg: `divider-abcd`) for these presentation interfaces that have "Hide Label" enabled. Then we could hide the `key` and `type` (always disabled)... which would only leave the interface options. Sounds cleeeeean!

**Comment by benhaynes** [comment]
I love this!! Wondering if it would feel cleaner to do `divider-1` (dropping the category to keep it shorter, and moving to an auto-increment index). Not sure how possible this is, since we'd need to loop over existing fields to see which number is not taken. Also, then when you reorder these, the numbers might be out of sequence (not an issue unless you're OCD).

I think if we remove the category (eg: `presentation`) and keep 6 characters, we should be good as-is!

Also, we _should_ be able to allow editing the key (in the advanced editor) for presentation-only fields, since there's no data there... but that's a question for the future.

**Comment by rijkvanzanten** [comment]
> I love this!! Wondering if it would feel cleaner to do divider-1 (dropping the category to keep it shorter, and moving to an auto-increment index). Not sure how possible this is, since we'd need to loop over existing fields to see which number is not taken. Also, then when you reorder these, the numbers might be out of sequence (not an issue unless you're OCD).

I think I would actually prefer going with the short hash here for this exact reason. Having `divider-1`, `divider-3` and `divider-2` in that order would kill me.

**Comment by azrikahar** [comment]
> Also, we should be able to allow editing the key (in the advanced editor) for presentation-only fields, since there's no data there... but that's a question for the future.

Is this the expected "editing the key in advanced editor" here? Haven't modified anything since technically it's "hidden" on the new field flow area, but definitely still visible (and editable) in the advanced editor:

![JPBan7o8WM](https://user-images.githubusercontent.com/42867097/141401798-bac50172-b066-4842-879e-672e335e2cb9.gif)

**Comment by benhaynes** [comment]
Ahh, true! Though I don't know if you can edit it **after** the field is created, even through the advanced editor.

**Comment by azrikahar** [comment]
ohh after it's created. Now I understand what the "no data" meant now 👍 

Just tried to give it a shot, was able to apply the same "interfaces with hide label" logic to make the key editable, but unfortunately the API currently will hit an error, especially the "where `field.field`" (field.field being the key in this case) since it can't find itself as we updated the key. Of course this assumes if we don't want to introduce changes in these parts in the API for this added flexibility.

**Comment by benhaynes** [comment]
I think we'll be adding the functionality to be able to edit any field key sometime in the future, so no need to add special logic now. 👍
