### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by faberv** [directus/directus#9576]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello, after upgrading to latest (non RC) version of Directus - **`v9.0.0`** encountered this error: `TypeError: Cannot read properties of undefined (reading 'startsWith')` (see complete error call stack below)

Here are my deps in `package.json`
```json
  "dependencies": {
    "directus": "9.0.0-rc.101",
    "mysql": "^2.18.1"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^21.0.1",
    "@rollup/plugin-node-resolve": "^13.0.6",
    "rollup": "^2.58.3",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-vue": "^6.0.0",
    "vue-template-compiler": "^2.6.14"
  }
```

---

I tried install all dependecies with `pnpm`, `yarn` and `npm` on two Node.js versions: `16.13.0` and `17.0.1` - nothing helped.

Is this a problem on your / my side?

### To Reproduce

1. Install Directus v9.0.0 on Node v.16.13.0 / v.17.0.1
2. Run `npx directus start`

### Errors Shown
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at getLocalType (/node_modules/directus/dist/utils/get-local-type.js:114:18)
    at getDatabaseSchema (/node_modules/directus/dist/utils/get-schema.js:115:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getSchema (/node_modules/directus/dist/utils/get-schema.js:36:22)
    at async registerAuthProviders (/node_modules/directus/dist/auth.js:26:64)
    at async createApp (/node_modules/directus/dist/app.js:92:5)
    at async createServer (/node_modules/directus/dist/server.js:40:38)
    at async Command.startServer (/node_modules/directus/dist/server.js:126:20)
    at async Command.parseAsync (/node_modules/commander/lib/command.js:923:5)
```
### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0 / 17.0.1

### What database are you using?

MySQL 8.0.21

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.4.0-19041-Microsoft (WSL)

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Hi! I've just tested the installation locally (`npm init directus-project <project-name>`) but everything seems to works as expected. 

- > Here are my deps in `package.json`

   I assume this is before the upgrade right? since it's showing rc.101 here.

- > I tried install all dependecies with pnpm, yarn and npm on two Node.js versions: 16.13.0 and 17.0.1 - nothing helped.

   Using npm here should be enough. 🤔 With that said, would you mind detailing what was the exact steps you took to install Directus? 

- Are you using any geometry fields in your current setup?

- Does this error appears right after `npx directus start` or after going somewhere in the Directus admin app? Or perhaps the admin app won't even load since it errors right after you start it?

**Comment by Piteraguayo** [comment]
I have the same problem upgrading from rc.98 to 9.0.0. I have done the previous steps and solved the breaking changes. The problem appears just when doing 
`npx directus start`

The extensions and hooks are loaded without problem.

**Comment by GrefriT** [comment]
Same problem. It consists in the fact that the column has a tinyint unsigned type. There is no such type in localTypeMap, so this leads to an error

**Comment by GrefriT** [comment]
@faberv I submitted PR to fix this #9599

**Comment by gurumark** [comment]
We have a tinyint unsigned  column as well. Changing the column type to char(1) does not help. The server  does not start up after version directus:9.0.0-rc.101.

**Comment by keyofd** [comment]
me too.  Unrecognized types: bigint unsigned, tinyint unsigned, decimal unsigned

**Comment by iherwig** [comment]
We have the same problem with PostgreSQL and geometry columns of type `polygon` and `point`.

These types are contained in [`localTypeMap`](https://github.com/directus/directus/blob/a920041c5b12eab72b5daeb71eaea11129cec8f8/api/src/utils/get-local-type.ts#L7) but explicitly set to `unknown` by the Postgres SchemaInspector [here](https://github.com/directus/directus/blob/a920041c5b12eab72b5daeb71eaea11129cec8f8/packages/schema/src/dialects/postgres.ts#L143). Since `unknown` is not contained in the type map, it resolves to `undefined` which causes the error [here](https://github.com/directus/directus/blob/a920041c5b12eab72b5daeb71eaea11129cec8f8/api/src/utils/get-local-type.ts#L122). 

When I remove the lines in the Postgres SchemaInspector, the application starts without problems.

**Comment by telubeer** [comment]
What version will contain this fix?

**Comment by faberv** [comment]
> What version will contain this fix?

I found it in [`v9.1.0`](https://github.com/directus/directus/releases/tag/v9.1.0) release

**Comment by rijkvanzanten** [comment]
> What version will contain this fix?

You can find that under the pull request that closed this issue (https://github.com/directus/directus/pull/9599) 🙂 

<img width="515" alt="CleanShot 2021-12-24 at 19 28 31@2x" src="https://user-images.githubusercontent.com/9141017/147374862-7ccfcd3f-4b82-4c4a-8903-de9880f77776.png">
