### ISSUE TITLE
[INVALID_PAYLOAD] Collection "Test" doesn't exist

### ISSUE THREAD

**Issue by Pachat** [directus/directus#9617]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

=> It looks like that Directus does not link to the table Test it has just created.

### To Reproduce

1. Create a collection Test
2. Save

### Errors Shown

[INVALID_PAYLOAD] Collection "Test" doesn't exist

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

v14.17.1

### What database are you using?

MariaDB

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by joselcvarela** [comment]
Hello @Pachat 
I've just tested this locally with MariaDB and found no issues.
Have you started a fresh installation and then only create a collection called `Test`? Or have you done something else?

In order to have better help, it is advised to share a [schema snapshot](https://docs.directus.io/reference/cli/#snapshot-the-data-model)

**Comment by Pachat** [comment]
Works perfect on a clean install 9.0.0
I must have mixed something. Sorry for the disturbance.
