### ISSUE TITLE
Same date value displays differently

### ISSUE THREAD

**Issue by u12206050** [directus/directus#9645]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a setup where by I use the date from a previous record and save it in the next record.
In the database I see them both as the same value:
![Screenshot 2021-11-09 at 10 39 21](https://user-images.githubusercontent.com/6641242/140899982-76497d1f-8661-48b7-b424-782c1e884fd8.png)

However in Directus there is an hour difference between what the dates show:
![Screenshot 2021-11-09 at 10 40 00](https://user-images.githubusercontent.com/6641242/140900074-f9d2eb7a-7ca4-4e03-abf5-f062688ffc08.png)

I can confirm that they both are the exact same `datetime` type with nothing else different except the `date_created` is the special directus field for storing the date when the record is created.

My current timezone is indeed +1 UTC and I have tried setting `TZ=UTC` in my env, but that only moved both dates a further hour ahead.

Not sure if this is related to this though: [7383](https://github.com/directus/directus/issues/7383)

### To Reproduce

Create a `DateTime` field on a collection that has a `date_created` field on as well.

Add an action that upon create of that collection you update the item and set your custom `DateTime` field to the same value as the `date_created` field.

Confirm in the database the two values are the same, however when viewing in Directus they are not.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

Locally & GCP

**Comment by azrikahar** [comment]
I believe this is technically not a bug, since `date_created` is actually a `timestamp` instead of `datetime`. Here's a sample where I populate `change_since` (datetime) and `change_since_timestamp` (timestamp) with the value from date_created:

Note: It's UTC+8 in the screenshot shown below

![image](https://user-images.githubusercontent.com/42867097/141048969-549cdae9-bdf0-4a72-9f7c-ecdb2a552c46.png)

Structure in db, notice the distinction of "tz" at end of date_created & change_since_timestamp:

![image](https://user-images.githubusercontent.com/42867097/141049010-5ee56a7b-ea3e-466a-8650-88e5a29f1525.png)

With that said, the data model page does show the two timestamp field as datetime at the moment. Was that by any chance the thing that led the thought of `date_created` being a datetime instead of timestamp? If so, maybe we can clarify it better 🤔 Gif of what I meant:

![7C235SPu8M](https://user-images.githubusercontent.com/42867097/141049394-dac50a38-f1a6-448f-87a5-a5005c075596.gif)

**Comment by u12206050** [comment]
Ah thanks for clearing that up. Yes, it would be good if the types in Directus was a bit more clear. 
In mysql I see now
`datetime = without tz`& `timestamp = with tz`

Will help yes if it was labeled in Directus with `tz`
