### ISSUE TITLE
Make line chart gradient optional

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#9724]
As @jaycammarano correctly pointed out, the gradient in the time-series panel in Insights is scientifically inaccurate. We should add a way to opt-out of the gradient design element for scientific accuracy.

**Comment by benhaynes** [comment]
Let's do:

* Gradient (default)
* Solid
* Disabled

**Comment by azrikahar** [comment]
![chrome_1kwXFjv0Xk](https://user-images.githubusercontent.com/42867097/141333679-4730f720-4b13-434a-b340-5ebe4453f84e.png)

How does these look? I've also added an additional option, "curve type", since I think it is also a pretty common option in terms of line charts. Plus it also makes the options even in number 😄 Also open to opt out of the curve type if it's preferred to keep things minimal at this point in time.

Here's also a short clip showing where the 2 new options currently located at, so perhaps I can get advice on where the 2 options should be put at in terms of hierarchy or importance. Partly added them on top to be closer to Color, but may also make sense to be at the bottom as collection should be the main focus.

**Comment by benhaynes** [comment]
> Plus it also makes the options even in number 😄

Haha, after my own heart! Having those options be unbalanced would have driven me crazy. While we want to avoid too many options, I think this is _perfect_. Really great addition... thanks @azrikahar!!! ❤️

**Comment by rijkvanzanten** [comment]
Also lets move those options to between "Min Value" and "Filter" 👍🏻 They're not mission critical / required for the setup of the panel, and more nice-to-have power-user features 🙂
