### ISSUE TITLE
Chained displaying Display-Template not possible

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#9751]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have the following relationship model, everything o2m:

Parent --> Children --> Translations

On the Children-collection I set a Display Template for Translations to display e.g. their name. (using the Preview Translation feature)
If I now on the Parent-collection set the Display Template of Children to be the Translation property, it won't display anything on the parent.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/9347206/141450729-aea2ba5f-2a75-46d2-9591-2bc02a0faa09.png">

Here's an example on how we have our setup:

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/9347206/141453058-dbf5c261-0128-460d-a479-dfe9ac014b60.png">

However, it seems like this doesn't work and what I see on "Trails" in the "Locations" collection is just empty. (see first image on the right).
I would expect that display templates can be chained and passed through their respective collections.

### To Reproduce

1. Create a parent collection
2. Create a o2m relationship to a child collection
3. Create a translation object on the child collection
4. Try to have the "translation preview" displayed on the parent collection
5. 

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by LevinGermann** [comment]
I started a discussion some days ago here (with some other entities, but same problem): https://github.com/directus/directus/discussions/9524
@christianrr mentioned "Either the display template catches up the display settings of the translations field (however would only work for translations)"

Since there's the Preview Translation feature, I would have expected that in this case the forwarding of the display template would work.

**Comment by rijkvanzanten** [comment]
@LevinGermann I think this is working as expected actually 🤔 

The problem is that you're trying to render a list of things into a single line of text. The translations display can make this work, as you're explicitly telling it what row of the related set to use. In the case of event-location -> translations, you explicitly tell it to only show the row where language = de-DE. 

However, when it comes to trails -> event_locations, there's multiple event locations per trail, where each event location has multiple translations. For these cases, we'd normally recommend using the related-values display on the o2m field on trails. This will render "15 Items", and have a dropdown to preview the actual related items. These rendered previews in the dropdown will then use the translations display configured on the event-locations collection.

I hope that makes sense (and hope that i'm understanding your use case correctly). Happy to keep discussing though 🙂
