### ISSUE TITLE
Migrations can't handle composite primary keys

### ISSUE THREAD

**Issue by Jakob-em** [directus/directus#9779]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When importing a snapshot from a db that contains composite primary keys the import fails.
The error message hints to the creations of multiple single column primary keys and fails for the second column of the composite key (`multiple primary keys for table "..." are not allowed`).

### To Reproduce

- Create a schema with a composite primary key
- Export a snapshot of the schema
- import the snapshot

### Errors Shown

19:35:39 🚨 error alter table "..." add constraint "..._pkey" primary key ("...") - multiple primary keys for table "..." are not allowed

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment]
Composite primary keys aren't supported by Directus, because items can only be fetched, updated and deleted using a single key like this:  `/items/foo/<id>`.
@rijkvanzanten, for that reason I think we should ignore tables with composite primary keys, the same way we ignore table without one. The fix should probably be done in `knex-schema-inspector`, by making sure that composite primary keys - just like composite `unique` keys https://github.com/knex/knex-schema-inspector/pull/80, https://github.com/knex/knex-schema-inspector/pull/79 - don't appear as individually primary... At least, while we find a way to make them work, which probably won't be very soon considering the changes it would require app and api wise.

**Comment by Oreilles** [comment]
Yup, actually same goes for the other vendors! There might still be some changes to be done in `packages/schema` though, since it uses different methods to retrieve the primary keys.

**Comment by rijkvanzanten** [comment]
I believe this is resolved by the changes in https://github.com/directus/directus/pull/9822 and the PRs on knex-schema-inspector. We can reopen if there's still issues after 9.1.0 🙂
