### ISSUE TITLE
Regex table filters as an extension to the blacklist

### ISSUE THREAD

**Issue by chaserelock** [directus/directus#984]
Hey guys - awesome project! I saw that there is a mechanism to blacklist table names by passing in an array of tables not to be read. While this is great, it's not extensible for databases that constantly grow in # of tables that are not necessarily interesting from a dev standpoint (e.g. data specific to 1 user in table_12345). Because our naming however is consistent, a regex filter would allow me to permanently capture that set of tables to ignore going into the future.

**Comment by benhaynes** [comment]
An excellent recommendation. I think that this array might be vestigial, since now Directus takes the opposite approach – only pulling in whitelisted tables. We ran into issues with some installations where temporary tables were created by services that weren't meant to be managed at all. Now you have to add managed tables into directus_tables to pull them into the system.

We will go through and reassess this whitelist/blacklist process to make sure it all makes sense and removes redundancy. Thanks!

**Comment by benhaynes** [comment]
**[Migrated to FeatHub](http://feathub.com/directus/directus/+31)**

Please use the [Directus FeatHub](http://feathub.com/directus/directus) to vote for features or make new request. Accepted feature requests will be added to GitHub Issues.
